### PR TITLE
fix(VRating): add icon aria-label

### LINKED ISSUE #11590: [Bug Report] Issue with Chrome Lighthouse and v-rating - Buttons do not have an accessible name
### Environment
**Vuetify Version:** 2.2.33
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.61
**OS:** Mac OS 10.15.5

### Steps to reproduce
Just use v-rating component, and test your project with Chrome Lighthouse.

### Expected Behavior
Stars - buttons with v-icon class should have aria-label fe. aria-label="rating-star" even if rating is readonly.

### Actual Behavior
Chrome Lighthouse is showing accessibility issue with single rating stars:
Buttons do not have an accessible name.

Failing Elements:
button.v-icon.notranslate.v-icon--link.v-icon--svg.theme--light

<button type="button" tabindex="-1" class="v-icon notranslate v-icon--link v-icon--svg theme--light" style="color:rgba(242,159,5,1);caret-color:rgba(242,159,5,1);">
  

### Reproduction Link
<a href="https://codepen.io/Ogar616/pen/OJMMgvE" target="_blank">https://codepen.io/Ogar616/pen/OJMMgvE</a>

### Other comments
Possible workaround:
Manually add an area-label to buttons with class v-icon like: 

const buttons = document.getElementsByTagName('button');
Array.from(buttons).map((btn) => btn.setAttribute('aria-label', 'rating-star'));

in mounted hook.

Possible fix:
add "aria-label: 'rating-star' " to attributes in:

vuetify/packages/vuetify/src/components/VRating/VRating.ts 
Line 222.

### PR DESCRIPTION
**Pull request by damienrobinson**
## Description

Add aria-label for rating star buttons. Stars - buttons with v-icon class should have aria-label fe. aria-label="rating-star" even if rating is read only.
fixes #11590

## Motivation and Context

Chrome lighthouse accessibility audit fails due to missing aria-labels for rating buttons.
fixes #11590

## How Has This Been Tested?

lighthouse audit in chrome dev tools

## Markup:

<details>

```vue
<template>
<v-rating
      class="d-flex align-center"
      value="4.5"
      background-color="orange lighten-3"
      color="rgba(242,159,5,1)"
      readonly
      half-increments
      round
      dense
     />
</template>
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [x] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Review by KaelWD — COMMENTED** [review]
This isn't useful, it'll just read out "button rating-star" five times.

**Comment by damienrobinson** [comment]
> This isn't useful, it'll just read out "button rating-star" five times.

@KaelWD I have updated the aria-label to `Rating Star ${i + 1}`

**Review by johnleider — DISMISSED** [review]
- The `Rating Star` string needs to go into the locale files
- Documentation needs to be updated
- Formatting onto multiple lines

**Comment by damienrobinson** [comment]
- Added `rating.ariaLabel.icon` to the locale files
- Created an example of setting the `icon-aria-label` prop in the docs
- Formatted the icon attrs onto multiple lines
- Updated presets test snap shots to include updated locales

File: packages/vuetify/src/components/VRating/VRating.ts [hunk 1]
```diff
@@ -219,7 +223,10 @@ export default mixins(
       }
 
       return this.$createElement(VIcon, this.setTextColor(this.getColor(props), {
-        attrs: { tabindex: -1 }, // TODO: Add a11y support
+        attrs: {
+          tabindex: -1,
+          'aria-label': this.$vuetify.lang.t(this.iconAriaLabel, i + 1),
+        }, // TODO: Add a11y support
```
Comment (MajesticPotatoe) [inline packages/vuetify/src/components/VRating/VRating.ts:229]:
```suggestion
        },
```

**Review by MajesticPotatoe — CHANGES_REQUESTED** [review]
- [x] rename `icon-aria-label` -> `icon-label`
- [x] add prop description to api-generator locale

File: packages/vuetify/src/components/VRating/VRating.ts (hunk 1 above)
Comment (damienrobinson) [reply packages/vuetify/src/components/VRating/VRating.ts]: @MajesticPotatoe I have made renamed the prop and added it to api-generator locale

* [x]  rename `icon-aria-label` -> `icon-label`
* [x]  add prop description to api-generator locale

File: packages/docs/src/examples/v-rating/prop-icon-label.vue [hunk 2]
```diff
@@ -0,0 +1,14 @@
+<template>
+  <v-rating
+    v-model="rating"
+    icon-label="custom icon label text"
```
Comment (nekosaur) [inline packages/docs/src/examples/v-rating/prop-icon-label.vue:4]: this example does not make use of `{0}`

File: packages/vuetify/src/locale/en.ts [hunk 3]
```diff
@@ -61,4 +61,9 @@ export default {
       currentPage: 'Current Page, Page {0}',
     },
   },
+  rating: {
+    ariaLabel: {
+      icon: 'Rating Star {0}',
```
Comment (nekosaur) [inline packages/vuetify/src/locale/en.ts:66]: Not sure if `Star` needs to be part of the text. The actual icon could be anything, not necessarily stars. I also think it would be useful to include the max number, something like `Rating x of y`

**Review by nekosaur — CHANGES_REQUESTED** [review]

**Comment by damienrobinson** [comment]
@nekosaur I have removed the text `Star` from the default icon label and added the rating length. The icon label is now `Rating {0} of {1}`.

File: packages/docs/src/examples/v-rating/prop-icon-label.vue (hunk 2 above)
Comment (damienrobinson) [reply packages/docs/src/examples/v-rating/prop-icon-label.vue]: I have added {0} and {1} to the example icon-label to now read `custom icon label text {0} of {1}`.

**Review by nekosaur — DISMISSED** [review]

File: packages/docs/src/pages/en/components/ratings.md [hunk 4]
```diff
@@ -53,6 +53,12 @@ Utilize the same sizing classes available in `v-icon` or provide your own with t
 
 <example file="v-rating/prop-size" />
 
+#### Icon Label
+
+Provide a label to assistive technologies for icons.
+
+<example file="v-rating/icon-label" />
```
Comment (MajesticPotatoe) [inline packages/docs/src/pages/en/components/ratings.md:60]:
```suggestion
<example file="v-rating/prop-icon-label" />
```

**Review by MajesticPotatoe — APPROVED** [review]
👍 
Thank you for your contribution and interest in improving Vuetify! Make sure to join us in the [Discord community](https://community.vuetifyjs.com).
