### PR TITLE
fix(VSlider): disable input tag

### LINKED ISSUE #12620: [Bug Report] Slider Label Click: Sets value to 0
### Environment
**Vuetify Version:** 2.3.17
**Vue Version:** 2.6.12
**Browsers:** Chrome 86.0.4240.193
**OS:** Mac OS 10.15.7

### Steps to reproduce
https://vuetifyjs.com/en/components/sliders/
Click the label of the slider.

### Expected Behavior
Nothing

### Actual Behavior
Sets the slider to 0. This is especially bad, since it also triggers sometimes when users simply scroll/touch past this element with no intention to change the value and leads to unwanted changes.

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/sliders/" target="_blank">https://vuetifyjs.com/en/components/sliders/</a>

### PR DESCRIPTION
**Pull request by yuchaosydney**
fixes #12620

## Description
Input tag value from `VSlider` shall be mutated ONLY based on `this.internalValue` from
`VSlider`. Therefore, always disabling input tag in `VSlider` level will make sure its value is not
changed by other events (e.g. label click)

## Motivation and Context

fixes #12620

## How Has This Been Tested?

unit testing & visually

## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

File: packages/vuetify/src/components/VSlider/VSlider.ts [hunk 1]
```diff
@@ -283,7 +283,7 @@ export default mixins<options &
         attrs: {
           value: this.internalValue,
           id: this.computedId,
-          disabled: this.isDisabled,
+          disabled: true,
```
Comment (yuchaosydney) [inline packages/vuetify/src/components/VSlider/VSlider.ts:286]: Value of this input tag in `VSlider` shall be only changed by `this.internalValue`. Disable it always will make sure its value will not be changed by other events.

All other changes in this pull request is html snapshot in unit tests.

**Review by MajesticPotatoe — APPROVED** [review]
LGTM 👍 
Thank you for your contribution and interest in improving Vuetify! Make sure to join us in the [Discord community](https://community.vuetifyjs.com).
