### PR TITLE
fix(VDatePicker): use start of week to calculate week numbers

### LINKED ISSUE #20490: [Bug Report][3.6.7] Wrong calculation of the calendar week in date composable
### Environment
**Vuetify Version:** 3.6.7
**Vue Version:** 3.4.23
**Browsers:** Chrome 128.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
use a v-date-picker, display calendar week and navigate to December 2024

### Expected Behavior
The week starting the 30th of December should be week 1 not week 53

### Actual Behavior
Week 53 is dispayed instead of week 1

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpNjc0KwyAQhF9FPNdKrsEW+hy1BzEbIjG6+JNQSt+9W6XQy7LfzOzO/cVzsvKGeN4r8JGrAht6U+CqA2NqFwaxrQ0mMgQ6u0JieYmHOABWNm4xlOWi+TBozny0xgPRBESzS7nQ3VPEuaW/MdJl/y9/BUr+FRNmmxwWlqHUbneBVv4+hep9G48PCGZBHw==)

### Other comments
I guess it's a bug in the getWeek function in https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/composables/date/date.ts 

I tried this function also and it returns 53. 

According to the ISO standard it should be week 1: https://en.wikipedia.org/wiki/ISO_week_date

"... 
First week
The ISO 8601 definition for week 01 is the week with the first Thursday of the Gregorian year (i.e. of January) in it. The following definitions based on properties of this week are mutually equivalent, since the ISO week starts with Monday:

It is the first week with a majority (4 or more) of its days in January.
Its first day is the Monday nearest to 1 January.
It has 4 January in it. Hence the earliest possible first week extends from Monday 29 December (previous Gregorian year) to Sunday 4 January, the latest possible first week extends from Monday 4 January to Sunday 10 January.
It has the year's first working day in it, if Saturdays, Sundays and 1 January are not working days.
..."

Also performed a Wolfram Alpha search: https://www.wolframalpha.com/input?input=what+is+the+date+of+the+first+week+of+2025

There is a working implementation here: https://gist.github.com/vincentorback/8edffeca20e7a9e5e2a6?permalink_comment_id=1769808 and some more info here https://stackoverflow.com/questions/58708417/why-is-1-added but I don't know whether you can use this code (licence?).

### LINKED ISSUE #20724: [Bug Report][3.7.4] Wrong number week with locale-provider "fr"
### Environment
**Vuetify Version:** 3.7.4
**Vue Version:** 3.5.13
**Browsers:** Firefox 128.0, Google Chrome
**OS:** Windows 10

### Steps to reproduce
When I use the v-locale-provider with "fr" around the v-date-picker, the weekNumber for the first week of 2025, the date-picker write the week 53.
The weekNumber will be week 01 for the December 30, 2024 to January 5, 2025.

### Expected Behavior
Display the week 01 for the December 30, 2024 to January 5, 2025. ISO 8601 right

### Actual Behavior
Display the weekNumber 53 for the December 30, 2024 to January 5, 2025.

### Reproduction Link
[Original Playground](https://play.vuetifyjs.com/#eNplUMsOwiAQ/BXCWezFk6lN/A7rgdDVYilsePVg/HeRqqV6IczMzmZ2TnfqrKiOiNsYgO5p7WFExT00rSakjowj5m8GwmjPpQb7pjKpjOAKGFoTZQeWzPjQ0ott6Xcwj3ZpMUMpBrALT4jrzcQmgKEkx6C8xLzIcn2Flv5ZeHfjArRnY8rVu1IHBZF7aXSy70prGahaJVpuSvzPUZ8KkrLu4MXMFdVVUV2CTliJnjjwAZu6mmGS6GOjg1L5OT8BVDN3lw==)

[Playground for v3.8.0](https://play.vuetifyjs.com/?active-file=src%2FApp.vue#eNqVU0tu2zAQvQrBjVrAFFukBQrDCdI7FN2UXdDSyGLCH0hKTmH47h1RtCPbWSQbiTPvze9x+OdAY2j4OEBS3b/6KdI1Vca7kMiBNAFkgt8zRo6kC86QqnArYc/ELlyjXLtGakCSsPCSaY2zMZGCk/vL7J8OwhKSejCwJvlMSAudHHT6NTsrrXZ9qlYzxvn0P2ZrLnUOO5lVF05sAzHKHUTk5F6ze/oePwtLV1mCn97X2BzOv0lgvMbeHibaZmTS+3zMBo6RpLIQiis755rMBzeqFkLp4V7QLgh6JmZqi4mZV80zhFc/IbF3e7YHeF46DY6vfE4UpN2BoDchsn2SDdjEDPbVxyUOGkaZlLMY/m0ZumyIX3T0OhP6r4Y6SYDIpQaTZ5ZowxfSoRmboHwiEdLgHzZ8NhFCyefdYUZ6XDpnUfZ8faIAUdDzhQqK9zLZgvYp+bjmvGkthrWg1RhqC4lbb/gj0ngYbFIGWOvM4139vf56x1sV09JfQzRsG9w+QsAsgpYtyXWmZXxHrcLEEj/qL3OF4mJabuNU4s3U5V18uIJW2xLKlW3h5SY5x2FGCCwAwgF36516XYVdaHaF3eiWXxE+IrzQ48oOWufP3/+56m/8)

### PR DESCRIPTION
**Pull request by J-Sek**
## Description

fixes #20724
fixes #20490

- ~~ISO-ish 4-day requirement for the first week~~ defaults to match `en-US`

## Markup:

```vue
<template>
  <v-app style="background-color: rgba(var(--v-theme-on-surface), 0.2)">
    <v-container>
      <div class="d-flex justify-center align-center ga-3">
        <span class="opacity-70">locale:</span>
        <v-chip-group v-model="currentLocale">
          <v-chip filter label text="en" value="en"></v-chip>
          <v-chip filter label text="pl" value="pl"></v-chip>
          <v-chip filter label text="fr" value="fr"></v-chip>
          <v-chip filter label text="pt" value="pt"></v-chip>
        </v-chip-group>
      </div>
      <div class="d-flex justify-center align-center ga-3">
        <span class="opacity-70">startOfWeek:</span>
        <v-chip-group v-model="startOfWeek">
          <v-chip
            v-for="o in startOfWeekOptions"
            v-bind="o"
            :key="o.value"
            filter
            label
          ></v-chip>
        </v-chip-group>
      </div>
      <div class="d-flex flex-wrap justify-center ga-6">
        <v-locale-provider :locale="currentLocale">
          <v-date-picker
            v-for="d in 6"
            :key="d"
            :elevation="5"
            :first-day-of-week="startOfWeek"
            :model-value="new Date(2023 + d, 0, 1)"
            class="mt-3"
            hide-header
            show-adjacent-months
            show-week
          ></v-date-picker>
        </v-locale-provider>
      </div>
    </v-container>
  </v-app>
</template>

<script setup>
  import { ref } from 'vue'

  const currentLocale = ref('en')
  const startOfWeek = ref(undefined)
  const startOfWeekOptions = 'Sun|Mon|Tue|Wed|Thu|Fri|Sat'
    .split('|')
    .map((x, i) => ({ text: x, value: i }))
</script>
```

### CODE REVIEW

File: packages/vuetify/src/composables/calendar.ts [hunk 1]
```diff
@@ -186,7 +186,7 @@ export function useCalendar (props: CalendarProps) {
 
   const weekNumbers = computed(() => {
     return weeksInMonth.value.map(week => {
-      return week.length ? getWeek(adapter, week[0]) : null
+      return week.length ? getWeek(adapter, week[0], { startOfWeek: Number(props.firstDayOfWeek ?? 0) }) : null
```
Comment (johnleider) [inline packages/vuetify/src/composables/calendar.ts:189]: This will probably have to change: https://github.com/vuetifyjs/vuetify/pull/20794

**Review by johnleider — COMMENTED** [review]
Please make sure to check https://github.com/vuetifyjs/vuetify/pull/20794 as I think some of the changes might effect your P.R.

**Comment by J-Sek** [comment]
If we decide to trust `Intl.Locale` we could rewrite `firstDay = [ ... ]` into `weekInfo = [ ... ]`
It is just a matter of mapping all the codes

```js
[
    {code: 'US', intlCode: 'en-US'},
    {code: 'FR', intlCode: 'fr'},
    {code: 'PL', intlCode: 'pl'},
    // etc...
]
.map(({code, intlCode}) => {
    const {firstDay, minimalDays} = new Intl.Locale(intlCode).getWeekInfo()
    return `'${code}': { firstDay: ${firstDay}, minimalDays: ${minimalDays} },`
})
.join('\n')
```

**Comment by J-Sek** [comment]
Ok, this PR was wrong in the state when `firstWeekSize` was forced to `4` (ISO) while it is `0` in United States.
I am trying to align with #20794 so we can merge it together.
When generating `weekInfo` dictionary in place of `firstDay` map, there are sometimes multiple matches and the old value do not align. It would be great if we could resolve this quickly.

**Comment by J-Sek** [comment]
Glad I had this test case for Portugal. It was incorrectly assigned during refactoring.

**Comment by johnleider** [comment]
> this PR can be merged instead of https://github.com/vuetifyjs/vuetify/pull/20794 once we resolve changes to firstDay

What changes are left for firstDay?

File: packages/vuetify/src/composables/date/DateAdapter.ts [hunk 2]
```diff
@@ -37,6 +37,7 @@ export interface DateAdapter<T = unknown> {
   getDiff (date: T, comparing: T | string, unit?: string): number
   getWeekArray (date: T, firstDayOfWeek?: number | string): T[][]
   getWeekdays (firstDayOfWeek?: number | string): string[]
+  getWeek (date: T, firstDayOfWeek?: number | string, firstWeekMinSize?: number): number
```
Comment (johnleider) [inline packages/vuetify/src/composables/date/DateAdapter.ts:40]: I know that I added new arguments to some of the typings but it was probably the wrong move. We need to figure out a way to get this information without needing to change the interface.

**Review by johnleider — APPROVED** [review]

File: packages/vuetify/src/composables/date/adapters/vuetify.ts [hunk 3]
```diff
@@ -6,166 +6,46 @@ import type { DateAdapter } from '../DateAdapter'
...
-  XK: 1,
-  YE: 0,
-  ZA: 0,
-  ZW: 0,
+function weekInfo (locale: string): { firstDay: number, firstWeekSize: number } | null {
+  // https://simplelocalize.io/data/locales/
+  // then `new Intl.Locale(...).getWeekInfo()`
+  const code = locale.slice(-2).toUpperCase()
+  switch (true) {
+    case code === '001': {
```
Comment (KaelWD) [inline packages/vuetify/src/composables/date/adapters/vuetify.ts:14]: `.slice(-2)` will never be 3 characters

File: packages/vuetify/src/composables/date/adapters/vuetify.ts [hunk 4]
```diff
@@ -6,166 +6,46 @@ import type { DateAdapter } from '../DateAdapter'
...
+      return { firstDay: 1, firstWeekSize: 1 }
+    }
+    case locale === 'GB-alt-variant': {
+      return { firstDay: 0, firstWeekSize: 4 }
+    }
+    case `AG AI AL AM AR AS AU AZ BA BD BM BN BR BS BT BW BY BZ CA CL CM CN CO CR CY DM DO
```
Comment (KaelWD) [inline packages/vuetify/src/composables/date/adapters/vuetify.ts:20]: Where is this data from? AU should be monday.

**Comment by KaelWD** [comment]
Sounds like we should just be using ISO rules for week of year https://unicode-org.atlassian.net/browse/CLDR-18275

File: packages/vuetify/src/composables/date/adapters/vuetify.ts (hunk 4 above)
Comment (J-Sek) [reply packages/vuetify/src/composables/date/adapters/vuetify.ts]: I have regenerated the switch statement using these scripts:

- [compress with Intl](https://bin.vuetifyjs.com/bins/90jY6w)
- [compress from static info](https://bin.vuetifyjs.com/bins/xHGx8A)

Both yield us the same result. Second one is just to prove the commit prior to [6674fa23](https://github.com/vuetifyjs/vuetify/pull/21199/commits/6674fa23306c7b1c34eef86c2c89d3127e75227b) had correct data.

**Comment by J-Sek** [comment]
> Sounds like we should just be using ISO rules for week of year [unicode-org.atlassian.net/browse/CLDR-18275](https://unicode-org.atlassian.net/browse/CLDR-18275)

We could, but I can only see this being rolled out in Vuetify if we also let users opt-out with `first-day-of-year` prop or some other non-hacky way.

**Comment by J-Sek** [comment]
One last fix.. hopefully. I just realized when clicking on the playground - after choosing non-us locale, selecting `startOfWeek: Sun` was ignored.

**Review by ikushum — APPROVED** [review]

**Review by johnleider — APPROVED** [review]
