### PR TITLE
fix(VAutocomplete, VCombobox): skip subheader for `auto-select-first`

### LINKED ISSUE #22398: [Bug Report][3.11.2] `auto-select-first` doesn't work well with `subheader` items
### Environment
**Vuetify Version:** 3.11.2
**Vue Version:** 3.5.25
**OS:** macOS 10.15.7 (current)

### Steps to reproduce
1. Open auto-complete that has "auto-select-first" prop
2. Write "1.1"
3. Press "Enter" key

### Expected Behavior
- Open auto-complete
- Write "1.1"
- First item gets highlighted
- Press Enter
- First item is selected

### Actual Behavior
- Open auto-complete
- Write "1.1"
- No item is highlighted ( I guess vuetify internally highlights the subheader )
- Press Enter
- Subheader is selected

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq1VU2PmzAQ/SsjLtmV4iBI9oLYSD1VK/VWqZfNHhwYEqsOWLahWSH+ewdD+GgVVquqp5jnNzNv3niU19ozOvG/KLWpSvQiL7Z4UZJb3B9ygLhiSZFbLnLUDnAQL22RFERDix0IEAkKNM8Hz/0evBsu+RElwd8VJoJLcNcgxU8EkcOPb8LYkdwmZgYlJpZlQtOVu9jH/rwoSfknMS9w5hVCUhpbXCAVlUhRfygDIDkLZW4fl1JaQWV7jTd4MBAqZmRhoz49la1B6UIZaA7eQKcAIkAiuWkFpyyTeIUTZzvgUpxylmBuW3GTCNd3n9Z5cztPKXVfbWPxaqFpPhUe+4SNLfmzR9EC/3Mepjyekc8msmD8/VdzdyJDgfszqZikl8kG5jCgjNaB/UJxOlt2LGQKxxNTWly4fh/luvLjAISVSBNoXZtnHfmf8roDp4s5i6JPk2ihrKPiVRXaQooZJ9+g7rKm3PIIHh7heQ8PPQbdckbwOuqqwb4rjGA1aF6twTVE2FddlAqCFTTrWUR//ULZINgEFFFxWRIUBMvUcEINl6nbCXW7TN1NqLs/qV13/Qa0vdG2EFDov7r6yIdw0Ydw6kO46EM49SFc9CGc+hBOfXjrT82jO9D6x/7wKrxm7W03T5vwyWsPATnvrTMuDa5nfwcd9vYbh/HdEQ==)

### PR DESCRIPTION
**Pull request by J-Sek**
fixes #22398

## Markup:

```vue
<template>
  <v-app theme="dark">
    <v-container max-width="450">
      <v-autocomplete :items="items" label="v-autocomplete" auto-select-first />
      <v-combobox :items="items" label="v-combobox" auto-select-first />
    </v-container>
  </v-app>
</template>

<script>
  export default {
    data: () => ({
      items: [
        { type: 'subheader', title: 'Group 1' },
        { title: 'Item 1.1', value: 11 },
        { title: 'Item 1.2', value: 12 },
        { title: 'Item 1.3', value: 13 },
        { title: 'Item 1.4', value: 14 },
        { type: 'divider', text: 'or' },
        { type: 'subheader', title: 'Group 2' },
        { title: 'Item 2.1', value: 21 },
        { title: 'Item 2.2', value: 22 },
        { title: 'Item 2.3', value: 23 },
      ],
    }),
  }
</script>
```

### CODE REVIEW

File: packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx [hunk 1]
```diff
@@ -503,7 +507,7 @@ export const VAutocomplete = genericComponent<new <
                           const itemProps = mergeProps(item.props, {
                             ref: itemRef,
                             key: item.value,
-                            active: (highlightFirst.value && index === 0) ? true : undefined,
+                            active: (highlightFirst.value && item.value === firstSelectableItem.value?.value) ? true : undefined,
```
Comment (KaelWD) [inline packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx]: `item` and `firstSelectableItem` are both derived from `displayItems` so `item === firstSelectableItem.value` should be safe here.
