### PR TITLE
fix(VCarousel): fix carousel direction props

### LINKED ISSUE #17586: [Bug Report][3.3.3] Setting the direction prop to vertical on the carousel does not work
### Environment
**Vuetify Version:** 3.3.3
**Last working version:** 2.6.14
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Add a `<v-carousel>` component to a page.
2. Set the `direction` prop to `vertical`.
3. Scroll through the windows.

### Expected Behavior
The carousel items should scroll vertically as described in the API documentation:
https://vuetifyjs.com/en/api/v-carousel/#props-direction

### Actual Behavior
The carousel items scroll horizontally, ignoring the direction prop.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrFks9uwyAMxl8l4tzAoTtV2dQ9R+mBgteShT/CJNNU9d0HNF2T9tJpmnaDD9s/+zObI3n1ng49kBVpIhjfiQgv3FZVM9TC+3IsF+lsFNpCGKWzKILrEbpK6QAyamefORkgRC1Fx8l36Cy41gl0fakqDDKlHWL0uGJMKpsbivrts0UqnWHaiD0gS/kKmXLyHWnr95xMa0iXsFeB/QX64CJ0/4PG3uIhuf8DesOu8MsaszTbY1bOa27YZP1kQbTxLsTaCE9bdDb9j2NO4OMDcrKqipK11Hm+z8dpUUGnh0AtRGa9YesUxkJvozZQK2fWS7qkT0xpjFOZApp6F9wHQkhFOFlMMNmgB1BjZCEsz4RRqjuxw4y4K80SL3lZB7AKQjL1wYlu0qZT3TzdTZbpJ25Pye9O2/yvZ1ZLLDZvLk3+auRSLFfaZuBpQUqfiVwSyPYLJ8tOxQ==)

### PR DESCRIPTION
**Pull request by SonTT19**
## Description

fixes #17586 

## Markup:

```vue
<template>
  <v-app>
    <v-container>
      <v-carousel direction="vertical">
        <v-carousel-item
          src="https://cdn.vuetifyjs.com/images/cards/docks.jpg"
          cover
        />
        <v-carousel-item
          src="https://cdn.vuetifyjs.com/images/cards/hotel.jpg"
          cover
        />
        <v-carousel-item
          src="https://cdn.vuetifyjs.com/images/cards/sunshine.jpg"
          cover
        />
      </v-carousel>

      <v-carousel>
        <v-carousel-item
          src="https://cdn.vuetifyjs.com/images/cards/docks.jpg"
          cover
        />
        <v-carousel-item
          src="https://cdn.vuetifyjs.com/images/cards/hotel.jpg"
          cover
        />
        <v-carousel-item
          src="https://cdn.vuetifyjs.com/images/cards/sunshine.jpg"
          cover
        />
      </v-carousel>
    </v-container>
  </v-app>
</template>
```

### CODE REVIEW

**Review by KaelWD — CHANGES_REQUESTED** [review]
This should use filterProps() like other components do.

File: packages/vuetify/src/components/VCarousel/VCarousel.tsx [hunk 1]
```diff
@@ -46,6 +46,7 @@ export const makeVCarouselProps = propsFactory({
     continuous: true,
     mandatory: 'force' as const,
     showArrows: true,
+    direction: 'horizontal' as const,
```
Comment (johnleider) [inline packages/vuetify/src/components/VCarousel/VCarousel.tsx:49]: VWindow is horizontal by default

File: packages/vuetify/src/components/VCarousel/VCarousel.tsx [hunk 2]
```diff
@@ -95,81 +96,83 @@ export const VCarousel = genericComponent<VCarouselSlots>()({
...
-        }}
-      </VWindow>
-    ))
+    useRender(() => {
+      const [windowProps] = VWindow.filterProps(props)
+
+      return (
+        <VWindow
+          ref={ windowRef }
+          { ...windowProps }
```
Comment (johnleider) [inline packages/vuetify/src/components/VCarousel/VCarousel.tsx:105]: @KaelWD Couldn't this simply be `{ ...props }`?
