### PR TITLE
fix(VAutocomplete): check for inital search input prop

### LINKED ISSUE #9757: [Bug Report] VAutocomplete ignore initial value of search-input prop
### Environment
**Vuetify Version:** 2.1.11
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.97
**OS:** Windows 10

### Steps to reproduce
Create a VAutocomplete with a property initialized with a value

### Expected Behavior
The field should contain the initial search value

### Actual Behavior
The field is empty

### Reproduction Link
<a href="https://codepen.io/Alex83690/pen/Yzzggzq" target="_blank">https://codepen.io/Alex83690/pen/Yzzggzq</a>

### Other comments
If you set the search value after a delay, it works

### PR DESCRIPTION
**Pull request by tanmoyopenroot**
## Description

fix #9757

## Motivation and Context

Check for internalSeach value instead of directly replacing it will null

## How Has This Been Tested?

unit | visually

## Markup:

<details>

```vue
<template>
  <div id="app">
    <v-app>
      <v-content>
        <v-container>
          <v-autocomplete
            :search-input.sync="search"
            :items="items"
          />
        </v-container>
      </v-content>
    </v-app>
  </div>
</template>

<script>
  export default {
    data: () => ({
      search: 'foo',
      items: ['foo', 'bar', 'fizz', 'buzz'],
    }),
  }
</script>
```

```vue
<template>
  <div id="app">
    <v-app>
      <v-content>
        <v-container>
          <v-autocomplete
            :search-input.sync="search"
          />
        </v-container>
      </v-content>
    </v-app>
  </div>
</template>

<script>
  export default {
    data: () => ({
      search: 'foo',
    }),
  }
</script>
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

File: packages/vuetify/src/components/VAutocomplete/VAutocomplete.ts [hunk 1]
```diff
@@ -373,7 +373,7 @@ export default VSelect.extend({
             this.multiple ||
             this.hasSlot
           )
-            ? null
+            ? this.internalSearch ? this.internalSearch : null
```
Comment (MajesticPotatoe) [inline packages/vuetify/src/components/VAutocomplete/VAutocomplete.ts]:
```suggestion
            ? this.internalSearch || null
```

Comment (tanmoyopenroot) [reply packages/vuetify/src/components/VAutocomplete/VAutocomplete.ts]: Done
