### PR TITLE
fix: generate row in data-table no-data slot

### LINKED ISSUE #3088: [Bug Report] v-alert in data-table no-data slot doesn't expand to full width
### Versions and Environment
**Vuetify:** 1.0.0-beta.5
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Windows 10

### Steps to reproduce
Look at the example on https://next.vuetifyjs.com/en/components/data-tables#example-no-data

### Expected Behavior
v-alert should span the full width if no custom ```<td>``` is present

### Actual Behavior
v-alert spans only a single column even when no ```<td>``` is present

### Reproduction Link
[https://github.com/vuetifyjs/vuetifyjs.com/blob/master/examples/data-tables/noData.vue](https://github.com/vuetifyjs/vuetifyjs.com/blob/master/examples/data-tables/noData.vue)

### Other comments
Assuming this has to do with the updates to the slot to allow ```<tr>``` and ```<td>```s

### PR DESCRIPTION
**Pull request by nekosaur**
## Description
make sure to generate tr/td for no-data slot when needed

## Motivation and Context
closes #3088

## How Has This Been Tested?
created test. tested manually

## Markup:
```
<v-data-table
    :headers="headers"
    :items="items"
  >
  <template slot="no-data">
    <v-alert :value="true" color="error" icon="warning">
      Sorry, nothing to display here :(
    </v-alert>
  </template>
</v-data-table>
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have created a PR in the [documentation](https://github.com/vuetifyjs/vuetifyjs.com) with the necessary changes.

### CODE REVIEW

File: src/components/VDataTable/mixins/body.js [hunk 1]
```diff
@@ -57,13 +57,14 @@ export default {
       return rows
     },
     genEmptyItems (content) {
-      if (typeof content === 'string') {
+      if (typeof content === 'string' || (!this.hasTR(content) && !this.needsTR(content))) {
         return this.genTR([this.$createElement('td', {
-          'class': 'text-xs-center',
```
Comment (jacekkarczmarczyk) [inline src/components/VDataTable/mixins/body.js]: I'd keep the `text-xs-center` if content is a string

File: src/components/VDataTable/mixins/body.js [hunk 2]
```diff
@@ -57,13 +57,14 @@ export default {
       return rows
     },
     genEmptyItems (content) {
-      if (typeof content === 'string') {
+      if (typeof content === 'string' || (!this.hasTR(content) && !this.needsTR(content))) {
```
Comment (jacekkarczmarczyk) [inline src/components/VDataTable/mixins/body.js]: Generating TR when `!needsTR()` was a bit confusing for me when reading the code. I'd replace `hasTR` and `needsTR` with `hasTag(tag1, tag2, ...)`:
```js
if (hasTag('tr')) {
  return content
} else if (hasTag('td', 'th')) {
   return genTR(content)
} else {
  return genTR(genTD(...))
}
```
