### PR TITLE
fix(vdatatable): add display style to <tr> when Mobile

### LINKED ISSUE #8799: v-data-table with tooltip breaking design in Chrome mobile view
### Environment
**Vuetify Version:** 2.0.11
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 10

### Steps to reproduce
Create a data table with a column that contains a tooltip and at least 2 additional columns afterwards. so for example:
- column 1
- column 2 with tooltip
- column 3
- column 4

If you then resize the viewport then down to the mobile view, then rendering of the columns below the one with the tooltip breaks.

Instead of the expected
- column 1
- column 2 with tooltip
- column 3
- column 4

it actually looks like
- column 1                       |  - column 3
- column 2 with tooltip  |  - column 4

This does not happen when loading the page directly in the mobile view, only when resizing it down from desktop to mobile version.

### Expected Behavior
All columns are arranged under each other and not in two columns.

### Actual Behavior
The columns AFTER the one with tooltip are placed on a second column.

### Reproduction Link
<a href="https://codepen.io/DonDozone/pen/MWgvYvE" target="_blank">https://codepen.io/DonDozone/pen/MWgvYvE</a>

### Other comments
This only happens in Chrome for me, not in Firefox or Edge. I can also reproduce it on my phone with chrome browser

### PR DESCRIPTION
**Pull request by YipingRuan**
fix #8799

## Description
Override user agent stylesheet for chrome <tr>

## Motivation and Context
https://github.com/vuetifyjs/vuetify/issues/8799

## How Has This Been Tested?
visually

## Markup:

<details>

```vue
<template>
  <div id="app">
  <v-app>
    <v-content>
      <v-data-table :headers="headers" :items="items" disable-pagination hide-default-footer>
              <template v-slot:item.tooltip="{ item }">
              <v-tooltip bottom>
                <template v-slot:activator="{ on }">
                  <span v-on="on">{{item.tooltip}}</span>
                </template>
                <span>This is the tooltip</span>
              </v-tooltip>
            </template>
        </v-data-table>
    </v-content>
  </v-app>
</div>
</template>

<script>
export default {
  data: () => ({
    headers: [
      { text: 'Header 1', value: 'valueA' },
      { text: 'Tooltip', value: 'tooltip' },
      { text: 'Header after', value: 'valueC' },
      { text: 'Header 2 after', value: 'valueD' },
    ],
    items: [{
       valueA: 'asd',
       tooltip: 2,
       valueC: 12345,
       valueD: 12345
    }
    ]
    //
  })
}
</script>
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)
- [ ] I've added new examples to the kitchen (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by YipingRuan** [comment]
Before:
Before
After:
After

File: packages/vuetify/src/components/VDataTable/VSimpleTable.ts [hunk 1]
```diff
@@ -33,7 +34,7 @@ export default mixins(Themeable).extend({
           height: convertToUnit(this.height),
         },
       }, [
-        this.$createElement('table', this.$slots.default),
+        this.$createElement('table', { class: { 'v-data-table__mobile': this.isMobile } }, this.$slots.default),
```
Comment (nekosaur) [inline packages/vuetify/src/components/VDataTable/VSimpleTable.ts]: Apply this class from v-data-table since it is a data-table specific class

File: packages/vuetify/src/components/VDataTable/VDataTable.ts [hunk 2]
```diff
@@ -514,6 +514,9 @@ export default VDataIterator.extend({
         height: this.height,
         fixedHeader: this.fixedHeader,
         dense: this.dense,
+        tableClasses: {
+          'v-data-table__mobile': this.isMobile,
```
Comment (johnleider) [inline packages/vuetify/src/components/VDataTable/VDataTable.ts]:
```suggestion
          'v-data-table--is-mobile': this.isMobile,
```

File: packages/vuetify/src/components/VDataTable/VSimpleTable.ts [hunk 3]
```diff
@@ -12,6 +12,7 @@ export default mixins(Themeable).extend({
     dense: Boolean,
     fixedHeader: Boolean,
     height: [Number, String],
+    tableClasses: Object,
```
Comment (johnleider) [inline packages/vuetify/src/components/VDataTable/VSimpleTable.ts]: Should have a default value

```
tableClasses: {
  type: Object,
  default: () => ({}),
}
```

File: packages/vuetify/src/components/VDataTable/VSimpleTable.ts [hunk 4]
```diff
@@ -33,7 +34,7 @@ export default mixins(Themeable).extend({
           height: convertToUnit(this.height),
         },
       }, [
-        this.$createElement('table', this.$slots.default),
+        this.$createElement('table', { class: { ...this.tableClasses } }, this.$slots.default),
```
Comment (johnleider) [inline packages/vuetify/src/components/VDataTable/VSimpleTable.ts]: This should be done differently, there is no reason change the snapshots.

File: packages/vuetify/src/components/VDataTable/VSimpleTable.ts (hunk 3 above)
Comment (YipingRuan) [reply packages/vuetify/src/components/VDataTable/VSimpleTable.ts]: Tried move the mobile css to tr at MobileRow
