### PR TITLE
fix(VNavigationDrawer): always bind mouseover events

### LINKED ISSUE #13309: [Bug Report][2.4.7] Navigation Drawer - expand-on-hover, mini-variant and v-main width
### Environment
**Vuetify Version:** 2.4.7
**Vue Version:** 2.6.12
**Browsers:** Chrome 89.0.4389.90
**OS:** Linux x86_64

### Steps to reproduce
1. Hover over navigation drawer
2. Click on plus icon to expand navigation drawer (Working as expected)
3. Click again on minus icon to collapse it (make it mini and enable expand on hover - Main content should update according to navigation drawer width)

### Expected Behavior
When we click on minus icon. Navigation menu should collapse and v-main should get more width as navigation have less width.

Also when navigation drawer is collapsed it should have expand on hover functionality.

In short, when navigation drawer is collapsed it can be viewd as full on hover. And width of v-main should update according to width of navigation drawer except navigation drawer is mini and user hovers it for temporary view.

### Actual Behavior
v-main is not adapting remaining space when we collapse the navigation drawer again.

### Reproduction Link
<a href="https://codepen.io/jd-0001/pen/JjEPRqY?editors=101" target="_blank">https://codepen.io/jd-0001/pen/JjEPRqY?editors=101</a>

### Other comments
Expected behavior: https://pixinvent.com/demo/vuexy-vuejs-admin-dashboard-template/demo-1/dashboard/analytics

Check pinning the navigation drawer and content area width according to width of navigation drawer.

### PR DESCRIPTION
**Pull request by johnleider**
## Description
Updated `v-navigation-drawer` to use its real width for application layout calculations. As a consequence to this change, a bug with **expand-on-hover** and listeners was resolved.

## Motivation and Context
fixes #13309

## How Has This Been Tested?

visually

## Markup:

<details>

```vue
<template>
  <div>
    <v-navigation-drawer
      v-model="drawer"
      :mini-variant="mini"
      :expand-on-hover="mini"
      app
    >
      <v-list-item class="px-2">
        <v-list-item-avatar>
          <v-img src="https://randomuser.me/api/portraits/men/85.jpg"></v-img>
        </v-list-item-avatar>

        <v-list-item-title>John Leider</v-list-item-title>

        <v-btn
          icon
          @click="mini = !mini"
        >
          <v-icon v-show="mini">mdi-plus</v-icon>
          <v-icon v-show="!mini">mdi-minus</v-icon>
        </v-btn>
      </v-list-item>
    </v-navigation-drawer>
    <v-main app>
      <div class="pa-8">
        <p>Content</p>
        <v-switch
          v-model="mini"
          label="Is Mini"
        />
      </div>
    </v-main>
  </div>
</template>

<script>
  export default {
    data () {
      return {
        drawer: true,
        items: [
          { title: 'Home', icon: 'mdi-home-city' },
          { title: 'My Account', icon: 'mdi-account' },
          { title: 'Users', icon: 'mdi-account-group-outline' },
        ],
        mini: true,
      }
    },

  }
</script>

```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Review by ElijahKotyluk — APPROVED** [review]

File: packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.ts [hunk 1]
```diff
@@ -442,7 +439,7 @@ export default baseMixins.extend({
         !this.$el
       ) return 0
 
-      const width = Number(this.computedWidth)
+      const width = Number(this.miniVariant ? this.miniVariantWidth : this.width)
```
Comment (KaelWD) [inline packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.ts:442]:
```suggestion
      const width = Number(this.computedWidth)
```

Comment (johnleider) [reply packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.ts:442]: this is intended. computedWidth is for the component's width, not the layout area that it effects. Expand on hover creates a larger computed width but we don't want to use that for the layout.

Unless you know something that I don't.

Comment (KaelWD) [reply packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.ts:442]: Because `computedWidth` is that exact same statement. https://github.com/vuetifyjs/vuetify/blob/ef1fb632c93542d1d70d477cce53a6a2a3d14c6a/packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.ts#L170-L172

Comment (KaelWD) [reply packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.ts:442]: Fuckin hell I'm blind, nvm. Maybe that should be a separate computed property.

**Review by KaelWD — APPROVED** [review]

File: packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.ts [hunk 2]
```diff
@@ -351,6 +351,8 @@ export default baseMixins.extend({
     },
     genListeners () {
       const on: Record<string, (e: Event) => void> = {
+        mouseenter: () => (this.isMouseover = true),
+        mouseleave: () => (this.isMouseover = false),
```
Comment (hadalin) [inline packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.ts:355]: Is it possible that these two lines should be enclosed in `if (this.expandOnHover) {`?

Comment (hadalin) [inline packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.ts:355]: Is it possible that these two lines should be added only `if (this.expandOnHover)`, like it was [before](https://github.com/vuetifyjs/vuetify/pull/14523/files#diff-98d92001e9cf0f207f45c674457cea37a833979a1b0f0b143cb3714454acdddeL369)?
