### PR TITLE
fix(VDataTable): show correct aria-labels for sorting

### LINKED ISSUE #4975: [Bug Report] v-data-table header aria-label doesn't account for must-sort prop
### Versions and Environment
**Vuetify:** 1.2.0
**Vue:** 2.5.17
**Browsers:** Chrome 68.0.3440.106
**OS:** Windows 7

### Steps to reproduce
Sort a data table column ascending, then descending
View the aria-label attribute in the header

### Expected Behavior
When the must-sort prop is included and the sort is currently descending the aria-label should read 'Sorted descending. Activate to sort ascending.'

### Actual Behavior
When the must-sort prop is included and the sort is currently descending the aria-label reads
'Sorted descending. Activate to remove sorting.'

### Reproduction Link
[https://codepen.io/ddelorenzo/pen/vzKMvY](https://codepen.io/ddelorenzo/pen/vzKMvY)

### PR DESCRIPTION
**Pull request by nekosaur**
## Description
This necessitated the creation of three new locale strings. I tried to
convert most of the existing locales, but was unable to make good enough
educated guesses for a couple, including all RTL languages

## Motivation and Context
close #4975

## Markup:

<details>

```vue
<template>
  <div>
    <v-data-table
      :headers="headers"
      :items="values"
      must-sort
      class="elevation-1"
    >
      <template slot="items" slot-scope="props">
        <td>{{ props.item.letter }}</td>
        <td class="text-xs-right">{{ props.item.number }}</td>
      </template>
    </v-data-table>
  </div>
</template>

<script>
export default {
  data: () => ({
    headers: [
      {
        text: 'Letter',
        sortable: true,
        value: 'letter'
      },
      { text: 'Number',
        sortable: true
      }
    ],
    values: [
      {
        letter: 'A',
        number: 1
      },
      {
        letter: 'B',
        number: 2
      },
      {
        letter: 'C',
        number: 3
      }
    ]
  })
}
</script>

```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)
- [ ] I've added new examples to the kitchen (applies to new features and breaking changes in core library)

### CODE REVIEW

File: packages/vuetify/src/components/VDataTable/VDataTableHeaderDesktop.ts [hunk 1]
```diff
@@ -55,14 +55,30 @@ export default mixins(header).extend({
 
           if (beingSorted) {
             classes.push('active')
-            classes.push(isDesc ? 'desc' : 'asc')
 
-            attrs['aria-sort'] = isDesc ? 'descending' : 'ascending'
-            attrs['aria-label'] += isDesc
-              ? this.$vuetify.lang.t('$vuetify.dataTable.ariaLabel.sortDescending')
-              : this.$vuetify.lang.t('$vuetify.dataTable.ariaLabel.sortAscending')
+            if (isDesc) {
```
Comment (johnleider) [inline packages/vuetify/src/components/VDataTable/VDataTableHeaderDesktop.ts]: Is it possible to reduce the nested blocks?

**Comment by johnleider** [comment]
Pulse check.

**Comment by johnleider** [comment]
This Pull Request is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by nekosaur** [comment]
;(

File: packages/vuetify/src/components/VDataTable/VDataTableHeaderDesktop.ts [hunk 2]
```diff
@@ -16,76 +16,95 @@ export default mixins(header).extend({
         },
       }, ['group'])
     },
-    // eslint-disable-next-line max-statements
+    getAria (beingSorted: boolean, isDesc: boolean) {
+      let ariaSort = 'none'
+      let ariaLabel = [
+        this.$vuetify.lang.t('$vuetify.dataTable.ariaLabel.sortNone'),
```
Comment (johnleider) [inline packages/vuetify/src/components/VDataTable/VDataTableHeaderDesktop.ts]: I would assign `$vuetify.dataTable.ariaLabel` to a string and use it in all of the lines below.

File: packages/vuetify/src/components/VDataTable/VDataTableHeaderDesktop.ts [hunk 3]
```diff
@@ -16,76 +16,95 @@ export default mixins(header).extend({
         },
       }, ['group'])
     },
-    // eslint-disable-next-line max-statements
+    getAria (beingSorted: boolean, isDesc: boolean) {
+      let ariaSort = 'none'
+      let ariaLabel = [
```
Comment (johnleider) [inline packages/vuetify/src/components/VDataTable/VDataTableHeaderDesktop.ts]: make this a const and instead of reassigning below, push into the array.

File: packages/vuetify/src/components/VDataTable/VDataTableHeaderDesktop.ts [hunk 4]
```diff
@@ -16,76 +16,95 @@ export default mixins(header).extend({
...
+        this.$vuetify.lang.t('$vuetify.dataTable.ariaLabel.sortNone'),
+        this.$vuetify.lang.t('$vuetify.dataTable.ariaLabel.activateAscending'),
+      ]
+
+      if (beingSorted) {
```
Comment (johnleider) [inline packages/vuetify/src/components/VDataTable/VDataTableHeaderDesktop.ts]: Assigning a default object:

```ts
const aria = { ariaSort: 'none', ariaLabel: '' }
```

Means that we can return early and avoid the nested conditionals:

```ts
if (!beingSorted) {
  aria.ariaLabel = ariaLabel.join(' ')
  
  return
}
```

File: packages/vuetify/src/components/VDataTable/VDataTableHeaderDesktop.ts [hunk 5]
```diff
@@ -16,76 +16,95 @@ export default mixins(header).extend({
...
+        if (isDesc) {
+          ariaSort = 'descending'
```
Comment (johnleider) [inline packages/vuetify/src/components/VDataTable/VDataTableHeaderDesktop.ts]: can be removed

File: packages/vuetify/src/components/VDataTable/VDataTableHeaderDesktop.ts [hunk 6]
```diff
@@ -16,76 +16,95 @@ export default mixins(header).extend({
...
+          ariaLabel = [
```
Comment (johnleider) [inline packages/vuetify/src/components/VDataTable/VDataTableHeaderDesktop.ts]:
```ts
const $t = str => this.$vuetify.lang.t(`$vuetify.dataTable.${str}`) // Should probably create a function to avoid having to write so much.
const activated = this.options.mustSort ? 'activeAscending' : 'activateNone'

ariaLabel.push($t('sortDescending'))
ariaLabel.push($t(activated))
```

File: packages/vuetify/src/components/VDataTable/VDataTableHeaderDesktop.ts [hunk 7]
```diff
@@ -16,76 +16,95 @@ export default mixins(header).extend({
...
+            this.$vuetify.lang.t('$vuetify.dataTable.ariaLabel.sortDescending'),
+            this.$vuetify.lang.t(this.options.mustSort
+              ? '$vuetify.dataTable.ariaLabel.activateAscending'
+              : '$vuetify.dataTable.ariaLabel.activateNone'
+            ),
+          ]
+        } else {
+          ariaSort = 'ascending'
+          ariaLabel = [
```
Comment (johnleider) [inline packages/vuetify/src/components/VDataTable/VDataTableHeaderDesktop.ts]: same thing as above

File: packages/vuetify/src/components/VDataTable/VDataTableHeaderDesktop.ts [hunk 8]
```diff
@@ -16,76 +16,95 @@ export default mixins(header).extend({
...
+            this.$vuetify.lang.t('$vuetify.dataTable.ariaLabel.sortAscending'),
+            this.$vuetify.lang.t('$vuetify.dataTable.ariaLabel.activateDescending'),
+          ]
+        }
+      }
+
+      return { ariaSort, ariaLabel: ariaLabel.join(' ') }
```
Comment (johnleider) [inline packages/vuetify/src/components/VDataTable/VDataTableHeaderDesktop.ts]: This is the only area I haven't figured out how to reduce the duplication.

```ts
aria.ariaLabel = ariaLabel.join(' ')

return aria
```

File: packages/vuetify/src/components/VDataTable/VDataTableHeaderDesktop.ts [hunk 9]
```diff
@@ -16,76 +16,95 @@ export default mixins(header).extend({
...
-      const attrs = {
-        role: 'columnheader',
-        scope: 'col',
-        'aria-label': header.text || '',
-        'aria-sort': 'none',
+      const data: Required<Pick<VNodeData, 'attrs' | 'on' | 'class' | 'style'>> = {
+        attrs: {
+          role: 'columnheader',
+          scope: 'col',
+          'aria-label': header.text || '',
```
Comment (johnleider) [inline packages/vuetify/src/components/VDataTable/VDataTableHeaderDesktop.ts]: I think that should have a fallback of some sort but I'm not sure exactly how. @phiter  should we ever provide an empty aria-label?

File: packages/vuetify/src/components/VDataTable/VDataTableHeaderDesktop.ts [hunk 10]
```diff
@@ -16,76 +16,95 @@ export default mixins(header).extend({
...
+      if (header.value === 'data-table-select' && !this.singleSelect) {
+        return this.$createElement('th', data, [this.genSelectAll()])
       }
 
-      const classes = [
-        `text-${header.align || 'start'}`,
-        ...wrapInArray(header.class),
-        header.divider && 'v-data-table__divider',
-      ]
+      children.push(this.$scopedSlots[header.value]
```
Comment (johnleider) [inline packages/vuetify/src/components/VDataTable/VDataTableHeaderDesktop.ts]: Not crazy about this styling. Thoughts on this?

```ts
children.push(
  this.$scopedSlots[header.value]
    ? this.$scopedSlots[header.value]!({ header })
    : this.$createElement('span', [header.text])
)
```

File: packages/vuetify/src/components/VDataTable/VDataTableHeaderDesktop.ts [hunk 11]
```diff
@@ -16,76 +16,95 @@ export default mixins(header).extend({
...
       }
 
-      return this.$createElement('th', {
-        attrs,
-        class: classes,
-        style: styles,
-        on: listeners,
-      }, children)
+      if (this.showGroupBy) {
+        children.push(this.genGroupByToggle(header))
```
Comment (johnleider) [inline packages/vuetify/src/components/VDataTable/VDataTableHeaderDesktop.ts]: Should be on one line like https://github.com/vuetifyjs/vuetify/pull/9638/files#diff-68e6ca531cb03e1916cea6cdc06df029R95

File: packages/vuetify/src/locale/af.ts [hunk 12]
```diff
@@ -8,9 +8,12 @@ export default {
   dataTable: {
     itemsPerPageText: 'Rye per bladsy:',
     ariaLabel: {
-      sortDescending: ': Sorted descending. Activate to remove sorting.',
-      sortAscending: ': Sorted ascending. Activate to sort descending.',
-      sortNone: ': Not sorted. Activate to sort ascending.',
+      sortDescending: 'Sorted descending.',
```
Comment (johnleider) [inline packages/vuetify/src/locale/af.ts]: I know it's nit-picky but could these be in alpha order?

File: packages/vuetify/src/components/VDataTable/VDataTableHeaderDesktop.ts (hunk 9 above)
Comment (phiter) [reply packages/vuetify/src/components/VDataTable/VDataTableHeaderDesktop.ts]: You don't really need `aria-label` on a `columnheader` if the column already has the same text as a text node.

Comment (phiter) [reply packages/vuetify/src/components/VDataTable/VDataTableHeaderDesktop.ts]: We only need `aria-label` when the element does not have a text (if it only has an icon, for example) or if we want to provide a different text for the screen reader.

File: packages/vuetify/src/locale/af.ts (hunk 12 above)
Comment (nekosaur) [reply packages/vuetify/src/locale/af.ts]: I don't really feel like changing this in 35 files.

**Comment by nekosaur** [comment]
fixed some of your feedback, but I feel like your suggested changes to getAria were not an improvement over what's there now.

**Comment by johnleider** [comment]
I can’t see anything gained by typing out the dataTable language path.
