### PR TITLE
fix(VTimePicker): better sizing

### LINKED ISSUE #3123: [Bug Report] v-picker destroyed in dialog view in mobile(iphone5)
@jacekkarczmarczyk 

### Versions and Environment
**Vuetify:** 1.0.0-beta.5
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.119
**OS:** Windows 10

### Steps to reproduce
Run this in browser 
change the iPhone5 view 
Open the picker
see the screen

### Expected Behavior
Both picker should fit based on device / screen

### Actual Behavior
Not fited

### Reproduction Link
[https://codepen.io/ksankumar/pen/oEvqGe](https://codepen.io/ksankumar/pen/oEvqGe)

[](url)

### PR DESCRIPTION
**Pull request by jacekkarczmarczyk**
## Description
- `full-width` prop wasn't really working for VPicker, it's fixed now
- pickers use `convertToUnit` for defining size
- VDatePicker/VTimePicker with `full-width` prop will properly scale in menu (mobiles)

## Motivation and Context
fixes #3123

## How Has This Been Tested?
visually, updated snaps

## Markup:

<details>

```vue
<template>
  <v-app id="inspire">
    <v-content>
      <v-dialog width="290px">
        <v-text-field slot="activator" label="Picker in dialog"></v-text-field>
        <v-time-picker format="24hr" full-width></v-time-picker>
      </v-dialog>
      <v-dialog width="290px">
        <v-text-field slot="activator" label="Picker in dialog"></v-text-field>
        <v-date-picker full-width></v-date-picker>
      </v-dialog>
      <div><v-date-picker full-width></v-date-picker></div>
      <div><v-time-picker format="24hr" full-width></v-time-picker></div>
      <div><v-date-picker></v-date-picker></div>
      <div><v-time-picker format="24hr"></v-time-picker></div>
      <div><v-date-picker landscape full-width></v-date-picker></div>
      <div><v-time-picker format="24hr" landscape full-width></v-time-picker></div>
      <div><v-date-picker landscape></v-date-picker></div>
      <div><v-time-picker format="24hr" landscape></v-time-picker></div>
    </v-content>
  </v-app>
</template>
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have created a PR in the [documentation](https://github.com/vuetifyjs/vuetifyjs.com) with the necessary changes.

### CODE REVIEW

File: src/components/VTimePicker/VTimePickerClock.js [hunk 1]
```diff
@@ -102,21 +92,25 @@ export default {
...
+    },
     handScale (value) {
-      return this.double && (value - this.min >= this.roundCount) ? (this.innerRadius / this.radius) : (this.outerRadius / this.radius)
+      return this.isInner(value) ? this.innerRadius : 1
     },
     isAllowed (value) {
       return !this.allowedValues || this.allowedValues(value)
     },
-    genValues () {
+    genValues (h) {
```
Comment (johnleider) [inline src/components/VTimePicker/VTimePickerClock.js]: this is inconsistent with other parts of the framework, use `this.$createElement`

File: src/components/VTimePicker/VTimePickerClock.js [hunk 2]
```diff
@@ -125,27 +119,32 @@ export default {
 
       return children
     },
-    genHand () {
+    genHand (h) {
```
Comment (johnleider) [inline src/components/VTimePicker/VTimePickerClock.js]: same here

**Comment by jacekkarczmarczyk** [comment]
done()
