### PR TITLE
Bug fixes on v-text-field

### LINKED ISSUE #2057: Masked inputs emit invalid characters
### Steps to reproduce
1. Type a letter into the input
2. Paste a multi-letter string into the input (`foobar`)
3. Paste a multi-character string starting with a number (`1twothree`)

### Versions
0.16.3

### What is expected ?
(1, 2) Nothing should happen, the value should be rejected and the model remain empty
(3) Only the valid character (`1`) should be accepted and emitted

### What is actually happening ?
1. The `input` event fires with the character that was typed, even if it doesn't match the mask
2. The input value doesn't change, but it emits the full string that was pasted in, up to the mask length
3. The input value is set to `1`, but the full string is still emitted as in (2)

### Reproduction Link
https://codepen.io/anon/pen/wryEBb

### LINKED ISSUE #2096: The <v-text-field return-masked-input> is not the same as the masked input field.
### Steps to reproduce

1. Set `mask="phone"` and `return-masked-input`
2. Type numbers
3. Type alphabets

### Versions
0.16.4

### What is expected ?
The returned `input` value must exactly be the same as what is displayed in the `input` field.

### What is actually happening ?
1. The returned value appears a few steps behind the `input` value as characters are progressively inserted.
2. The returned value contains illegal characters according to the mask rule.

### Reproduction Link
https://codepen.io/azaars/pen/XeEYpq

### LINKED ISSUE #2097: Illegal value inserted externally into <v-text-field> is not processed correctly.
### Steps to reproduce

1. Set `mask="phone"` and set to update `input` field externally with an illegal value.
2. Type a phone number.

### Versions
0.16.4

### What is expected ?
The value inserted externally should be masked and an input event should emit the correct (possibly modified) value.

### What is actually happening ?
No input event is emitted and the incorrect input value remains verbatim.

### Reproduction Link
https://codepen.io/azaars/pen/wrmEYw

### LINKED ISSUE #2136: <v-text-field> doesn't display the number 0.
### Steps to reproduce
1. Create a v-text-field
2. Bind it to a property and give it the value 0 (Number)

### Versions
0.16.4

### What is expected ?
The v-text-field should display the value '0'. Please notice that the string '0' is displayed correctly.

### What is actually happening ?
The v-text-field is left blank and the placeholder text also doesn't appear.

### Reproduction Link
https://codepen.io/bspg/pen/yzEXQR

### LINKED ISSUE #2137: <v-text-field> mask doesn't work when combined with .number modifier
### Steps to reproduce
1. Create a v-text-field with the mask "##.##" and set the .number modifier to its v-model.
2. Type '1234' on the text field.

### Versions
0.16.4

### What is expected ?
The text field should display '12.34'

### What is actually happening ?
The text field is not formatted and the console in devtools shows errors.

### Reproduction Link
https://codepen.io/bspg/pen/aLKybz

### LINKED ISSUE #2158: VTextField selectionEnd error
@KaelWD 

### Steps to reproduce
Put a type="number" inside v-text-field, like:
`<v-text-field  v-model="example" hide-details type="number"></v-text-field>`

When you change to fill other input, it appears an error: 

**Failed to read the 'selectionEnd' property from 'HTMLInputElement': The input element's type ('number') does not support selection**

### Versions

With android devices, with vue 2.4.4 and at least with vuetify 0.16.4

### What is expected ?
We expected that the content of input is not deleted.

### What is actually happening ?
When I want to fill in another entry, the previous entry is empty.

### Reproduction Link

 https://codepen.io/anon/pen/OxwONy

### PR DESCRIPTION
**Pull request by azaars**
1. Resolves #2057
2. Resolves #2096
3. Resolves #2097
4. Resolves #2136 
5. Resolves #2137 
6. Resolves #2158

### CODE REVIEW

**Comment by azaars** [comment]
Ups... It breaks some of the tests.

I think those tests are no longer applicable and should be replaced with something else.

**Comment by KaelWD** [comment]
It breaks *one* of the tests. Have you checked that clearable still works after these changes?

**Comment by azaars** [comment]
Ok, will do so.

File: src/components/VTextField/VTextField.js [hunk 1]
```diff
@@ -84,12 +84,14 @@ export default {
...
       },
       set (val) {
-        this.lazyValue = val
-        this.mask && this.setSelectionRange()
-        this.$emit('input', val)
+        // Inner unmaskText() strips of non-alphanum
+        // maskText() masks and removes dirty alphanum
+        // Outer unmaskText() provides a clean lazyValue
+        this.lazyValue = this.unmaskText(this.maskText(this.unmaskText(val)))
+        this.setSelectionRange()
```
Comment (KaelWD) [inline src/components/VTextField/VTextField.js]: What about non-masked inputs? This will probably break text fields with `type="number"` as they don't support `setSelectionRange()`.

Comment (azaars) [reply src/components/VTextField/VTextField.js]: I did look at non-mask input. I even did some tests on first with a mask then later removed it on the fly.

Yeah you're probably right about `type="number"`. Well, it's not really related to the issues this PR is trying to resolve. There are several other issues that exist even before this PR, which are overlooked yet to surface sooner or later. IMHO lets handle these separately as different issues.

**Comment by azaars** [comment]
Yeay the test passed :-)

File: src/util/mask.js [hunk 2]
```diff
@@ -90,7 +90,7 @@ const maskValidates = (mask, char) => {
  * @return {String}
  */
 export const maskText = (text, masked, dontFillMaskBlanks) => {
-  if (!masked.length || !text.length) return text
+  if (!masked.length || !text || !text.length) return text
```
Comment (jacekkarczmarczyk) [inline src/util/mask.js]: `if (!masked.length || !text) return text` should be enough

Comment (azaars) [reply src/util/mask.js]: Really? I'm already too deep into strongly typed language hahaa.

Thanks @jacekkarczmarczyk

**Comment by johnleider** [comment]
Tests need to be written for each issue.

**Comment by azaars** [comment]
I'm sorry. I'm not familiar with the test tools at all. Will surely explore but for now it would take me ages to do that.

**Comment by johnleider** [comment]
Sorry, response was mainly for myself to remember to do it :)

File: src/components/VTextField/VTextField.js (hunk 1 above)
Comment (KaelWD) [reply src/components/VTextField/VTextField.js]: I mean `type="number"` in general. Currently `setSelectionRange` is only called if a mask is set:
```js
this.mask && this.setSelectionRange()
```

What happens with this patch if you just have a number input without a mask?

```html
<v-text-field v-model="number" type="number">
```

Comment (azaars) [reply src/components/VTextField/VTextField.js]: Now I see what you mean.

Comment (KaelWD) [reply src/components/VTextField/VTextField.js]: You can probably just put the `this.mask &&` back in.

Comment (azaars) [reply src/components/VTextField/VTextField.js]: Placing back merely the `this.mask &&` caused the `clearable` test to fail once again. This time it's expecting an `emit()`.

Admittedly, I did not give much attention to the totally valid `null` value for input field before. So now I've fixed some more lines here and there. For the same reason, the extra check needs to be there once again @jacekkarczmarczyk : 

```javascript
if (!masked.length || !text || !text.length) return text
```

File: src/mixins/maskable.js [hunk 3]
```diff
@@ -60,8 +60,10 @@ export default {
       let position = 0
       let selection = this.selection
 
-      for (const char of oldText.substr(0, selection)) {
-        isMaskDelimiter(char) || position++
+      if (oldText) {
+        for (const char of oldText.substr(0, selection)) {
+          isMaskDelimiter(char) || position++
+        }
```
Comment (KaelWD) [inline src/mixins/maskable.js]: `oldText` will always be a string, this is redundant

Comment (azaars) [reply src/mixins/maskable.js]: Well, that's because I  expect `null` to be a valid value, and that `this.lazyValue` has to be able to accept null.

File: src/util/mask.js [hunk 4]
```diff
@@ -90,14 +90,15 @@ const maskValidates = (mask, char) => {
  * @return {String}
  */
 export const maskText = (text, masked, dontFillMaskBlanks) => {
-  if (text == null) return ''
-  text = String(text)
-  if (!masked.length || !text.length) return text
+  if (!masked.length || !text) return text
```
Comment (azaars) [inline src/util/mask.js]: I just found out that `!'' === true`, so `!text.length` not only is redundant but will fail when `text === null`. Still learning :blush:

File: src/mixins/maskable.js (hunk 3 above)
Comment (KaelWD) [reply src/mixins/maskable.js]: `oldText` is directly from the html element, which is *always* a string, even if you set it to null first.

File: src/components/VTextField/VTextField.js [hunk 5]
```diff
@@ -84,12 +84,17 @@ export default {
...
-        this.mask && this.setSelectionRange()
-        this.$emit('input', val)
+        // Inner unmaskText() strips off non-alphanum
+        // maskText() masks and removes dirty alphanum
+        // Outer unmaskText() provides a clean lazyValue
+        const value = this.unmaskText(this.maskText(this.unmaskText(val)))
+        this.lazyValue = typeof val === 'number' ? +value : value
+        this.mask ? this.setSelectionRange()
+          : this.$emit('input', this.returnMaskedValue
+            ? this.$refs.input.value : this.lazyValue)
```
Comment (KaelWD) [inline src/components/VTextField/VTextField.js]: Why are we returning different values based on `returnMaskedValue` when there is no mask?

File: src/util/mask.js [hunk 6]
```diff
@@ -90,14 +90,15 @@ const maskValidates = (mask, char) => {
  * @return {String}
```
Comment (KaelWD) [inline src/util/mask.js]: This docblock needs updating if you're returning arbitrary values. Does jsdoc have generics?

File: src/components/VTextField/VTextField.js (hunk 5 above)
Comment (KaelWD) [reply src/components/VTextField/VTextField.js]: Also, this whole function should probably be split by an if statement so none of this casting is happening on non-masked inputs. The same applies for the value watcher too.

File: src/util/mask.js (hunk 6 above)
Comment (azaars) [reply src/util/mask.js]: You know better than I do.

**Comment by azaars** [comment]
Please let me know if I miss anything else.

File: src/mixins/maskable.js (hunk 3 above)
Comment (KaelWD) [reply src/mixins/maskable.js]: This is still redundant

File: src/util/mask.js [hunk 7]
```diff
@@ -90,14 +90,15 @@ const maskValidates = (mask, char) => {
...
  */
 export const maskText = (text, masked, dontFillMaskBlanks) => {
-  if (text == null) return ''
-  text = String(text)
```
Comment (KaelWD) [inline src/util/mask.js]: These lines were here for a reason. The value should still be cast to a string before calculating the cursor position, because that's what's going to be set on the input in the end.

File: src/components/VTextField/VTextField.js [hunk 8]
```diff
@@ -128,6 +132,23 @@ export default {
...
+      this.$nextTick(() => {
+        this.$refs.input.value = masked
+        this.$emit('input', this.lazyValue)
+      })
+    },
+    updateOnValueChange (val) {
+      this.lazyValue = val
+      this.$emit('input', this.lazyValue)
+    },
+    getLazyValue (val) {
```
Comment (KaelWD) [inline src/components/VTextField/VTextField.js]: This name is bad, it doesn't accurately describe what the function is doing. Is this method even needed? You only use it in one place.

File: src/components/VTextField/VTextField.js [hunk 9]
```diff
@@ -128,6 +132,23 @@ export default {
...
+
+      this.lazyValue = this.getLazyValue(value)
+      this.$nextTick(() => {
+        this.$refs.input.value = masked
+        this.$emit('input', this.lazyValue)
+      })
+    },
+    updateOnValueChange (val) {
+      this.lazyValue = val
+      this.$emit('input', this.lazyValue)
```
Comment (KaelWD) [inline src/components/VTextField/VTextField.js]: This is causing `input` to be emitted twice, as you're also doing it in both `inputValue.set()` and `updateRange()`

File: src/components/VTextField/VTextField.js [hunk 10]
```diff
@@ -128,6 +132,23 @@ export default {
...
 
   methods: {
+    maskedUpdateOnValueChange (val) {
+      const masked = this.maskText(this.unmaskText(val))
+      const value = this.unmaskText(masked)
+
+      this.lazyValue = this.getLazyValue(value)
+      this.$nextTick(() => {
+        this.$refs.input.value = masked
+        this.$emit('input', this.lazyValue)
```
Comment (KaelWD) [inline src/components/VTextField/VTextField.js]: This one too.

File: src/mixins/maskable.js (hunk 3 above)
Comment (azaars) [reply src/mixins/maskable.js]: Indeed it is. `input.value` never becomes null. Even if it's explicitly set to null, it turns to an empty string. At least in the latest Firefox. I'm changing it right away.

File: src/components/VTextField/VTextField.js (hunk 8 above)
Comment (azaars) [reply src/components/VTextField/VTextField.js]: It's used in 2 places. The other one is at line 92 of `VTextField.js`. Do you prefer not to have this this function? I'll just put the content where it was before.

File: src/components/VTextField/VTextField.js (hunk 9 above)
Comment (azaars) [reply src/components/VTextField/VTextField.js]: Well, actually I didn't quite get it when you said:

> Also, this whole function should probably be split by an if statement so none of this casting is happening on non-masked inputs. The same applies for the value watcher too.

I understood it as having if statement to call different functions. Maybe because I didn't understand what you meant about casting issue anywhere in that function. Frankly I also don't like the changes I made and in fact I don't like the new function names I gave. Perhaps you would want to elaborate your suggestion.

File: src/util/mask.js (hunk 7 above)
Comment (KaelWD) [reply src/util/mask.js]: I think accepting null is fine, but completely removing this means that the cursor position is wrong if the mask changes when the value is falsy (`0` with `v-model.number` for example`). You should be casting `newText` to string (with a *proper* null check) in `updateRange()` and `watch.mask()` before the loop. This will also allow the removal of the ifs, because `for..of` on an empty string just gets skipped.

File: src/components/VTextField/VTextField.js (hunk 9 above)
Comment (azaars) [reply src/components/VTextField/VTextField.js]: On multiple emit problem, I realize that the `watch.value` has never been completed for what it's supposed to function as. From the comment, it should handle external change but there is nothing in the function to detect whether the change is external or internal. So, there have always been multiple emits from internally. I'm going to address this in a later PR.

File: src/components/VTextField/VTextField.js (hunk 8 above)
Comment (KaelWD) [reply src/components/VTextField/VTextField.js]: What is it actually doing anyway? It looks like it just casts `val` to a number when it already is one.

File: src/components/VTextField/VTextField.js (hunk 9 above)
Comment (KaelWD) [reply src/components/VTextField/VTextField.js]: I said that because `this.unmaskText(this.maskText(this.unmaskText(val)))` was being run on every change, even on non-masked inputs.

File: src/components/VTextField/VTextField.js (hunk 8 above)
Comment (azaars) [reply src/components/VTextField/VTextField.js]: Actually it casts to the type that the dev enters in `props.value`

File: src/components/VTextField/VTextField.js (hunk 9 above)
Comment (KaelWD) [reply src/components/VTextField/VTextField.js]: > there have always been multiple emits from internally

`<v-text-field :mask="####" v-model.number="num"/>`

Click inside, type `1`, blur. 

On dev:
image

On this branch:
image

File: src/components/VTextField/VTextField.js (hunk 8 above)
Comment (KaelWD) [reply src/components/VTextField/VTextField.js]: It was [here](https://github.com/vuetifyjs/vuetify/pull/2099/commits/58524576273d9d9f203d8eb1e06d204cddca1d0c#diff-c2cbb2f11cf8c97e6eff0981f9927269L124), but now it does nothing.

**Comment by azaars** [comment]
What exactly does codeclimate means in the last commit?

File: src/components/VTextField/VTextField.js (hunk 8 above)
Comment (azaars) [reply src/components/VTextField/VTextField.js]: OMG what was I thinking when I did that.

You're damn sharp man. I salute

**Comment by johnleider** [comment]
Don't worry about codeclimate for now

File: src/util/mask.js (hunk 7 above)
Comment (azaars) [reply src/util/mask.js]: I can see your point now. All codes that requires the return value of `maskText()` are expecting a string. So, converting the falsy to `'0'` is indeed correct. I'm reverting to your last commit.

Comment (KaelWD) [reply src/util/mask.js]:
```js
if (text == null) return text
text = String(text)
```
Might work

**Comment by azaars** [comment]
is it always returning string?

File: src/util/mask.js (hunk 7 above)
Comment (azaars) [reply src/util/mask.js]: Well, now I prefer your last commit. Like I said, all readers of `maskText()` including `newValue` and `domProps.value` are expecting string.

File: src/util/mask.js (hunk 6 above)
Comment (jacekkarczmarczyk) [reply src/util/mask.js]: http://usejsdoc.org/tags-param.html#multiple-types-and-repeatable-parameters

**Comment by azaars** [comment]
@KaelWD I've commited the post-review changes.

File: src/components/VTextField/VTextField.js [hunk 11]
```diff
@@ -112,8 +119,25 @@ export default {
...
+
       // Value was changed externally, update lazy
-      this.lazyValue = val
+      if (this.mask) {
+        const masked = this.maskText(this.unmaskText(val))
+        const value = this.unmaskText(masked)
+        this.lazyValue = typeof val === 'number' ? +value : value
+
+        // Emit when the externally set value was modified internally
+        val !== this.lazyValue && this.$nextTick(() => {
```
Comment (KaelWD) [inline src/components/VTextField/VTextField.js]: why the nextTick here?

File: src/mixins/maskable.js [hunk 12]
```diff
@@ -55,23 +55,28 @@ export default {
...
+      if (newValue) {
+        for (const char of newValue) {
+          isMaskDelimiter(char) || position--
+          selection++
+          if (position <= 0) break
+        }
       }
 
-      this.setCaretPosition(selection)
+      this.$nextTick(() => {
```
Comment (KaelWD) [inline src/mixins/maskable.js]: and here too I guess
