### PR TITLE
fix(VIcon): svg icon style when using the prominent prop

### LINKED ISSUE #9670: [Bug Report] SVG icons in prominent alerts displayed differently than non-svg icons
### Environment
**Vuetify Version:** 2.1.9
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.97
**OS:** Mac OS 10.14.6

### Steps to reproduce
Use `v-alert` with `prominent` and `icon` attributes when using SVG icon font:

```
<v-alert prominent type="error" icon="$alert">Test</v-alert>
```

See reproduction link for a complete example.

### Expected Behavior
SVG icons in prominent styled alerts display the same as non-svg icons.

### Actual Behavior
The icon is too big and the rounded background is missing completely.

### Reproduction Link
<a href="https://codepen.io/janvennemann/pen/gOOdpvq" target="_blank">https://codepen.io/janvennemann/pen/gOOdpvq</a>

How it should look like: https://codepen.io/janvennemann/pen/xxxaGmY

### PR DESCRIPTION
**Pull request by yazfield**
## Description
Fixes SVG icon style for prominent VAlert cound't be applied on SVG. This commit fixes the issue by wrapping the SVG with a span element. Relevant classes are applied to the wrapper.

fix #9670

## How Has This Been Tested?
Tested visually. Updated snapshots.

## Markup:
Steps to reproduce from #9670:
https://codepen.io/janvennemann/pen/gOOdpvq
How it should look:  https://codepen.io/janvennemann/pen/xxxaGmY

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)
- [ ] I've added new examples to the kitchen (applies to new features and breaking changes in core library)

### CODE REVIEW

File: packages/vuetify/src/components/VIcon/VIcon.ts [hunk 1]
```diff
@@ -138,38 +138,38 @@ const VIcon = mixins(
...
-        'aria-hidden': !this.attrs$['aria-label'],
-        'aria-label': this.attrs$['aria-label'],
-      }
-
       const fontSize = this.getSize()
-      if (fontSize) {
-        data.style = {
+      const wrapperData = {
+        ...this.getDefaultData(),
+        style: !fontSize ? undefined : {
```
Comment (jacekkarczmarczyk) [inline packages/vuetify/src/components/VIcon/VIcon.ts]: `style: fontSize ? {...} : undefined`

Comment (yazfield) [reply packages/vuetify/src/components/VIcon/VIcon.ts]: done
