### PR TITLE
fix(VTextField): show label slot when filled prop is used

### LINKED ISSUE #11533: [Bug Report] v-text-field + filled (v-slot:label not working)
### Environment
**Vuetify Version:** 2.2.30
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.61
**OS:** Windows 10

### Steps to reproduce
Add prop "filled" in v-text-field;
Add v-slot:label.

### Expected Behavior
Same as without filled.

### Actual Behavior
No functionality.

### Reproduction Link
<a href="https://codepen.io/dinver/pen/oNbvxJM?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Ftext-fields%2F" target="_blank">https://codepen.io/dinver/pen/oNbvxJM?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Ftext-fields%2F</a>

### PR DESCRIPTION
**Pull request by KaelWD**
fixes #11533
see https://github.com/vuejs/vue/issues/11714

Does this break anything? Is there some way `setLabelWidth` would need to be called before the watcher is set up?

## Markup:

<details>

```vue
<template>
  <v-container>
    <v-text-field filled>
      <template #label><span>#Slot label</span></template>
    </v-text-field>

    <v-text-field filled>
      <template slot="label"><span>Slot label</span></template>
    </v-text-field>

    <v-text-field filled label="Prop label" />
  </v-container>
</template>
```
</details>

### CODE REVIEW

File: packages/vuetify/src/components/VTextField/VTextField.ts [hunk 1]
```diff
@@ -196,7 +196,7 @@ export default baseMixins.extend<options>().extend({
   },
 
   watch: {
-    labelValue: 'setLabelWidth',
+    // labelValue: 'setLabelWidth', // moved to mounted, see #11533
```
Comment (johnleider) [inline packages/vuetify/src/components/VTextField/VTextField.ts:199]: Do you intent to leave this or just remaining dev code?

**Comment by johnleider** [comment]
I don't see anything that this would obviously break.

File: packages/vuetify/src/components/VTextField/VTextField.ts (hunk 1 above)
Comment (KaelWD) [reply packages/vuetify/src/components/VTextField/VTextField.ts:199]: Intended, can remove though if you like
