### PR TITLE
fix(VSpeedDial): fixed transition animation

### LINKED ISSUE #5735: [Bug Report] Speed-dial animation only works for 7 buttons
### Versions and Environment
**Vuetify:** 1.3.9
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.102
**OS:** Windows 10

### Steps to reproduce
Add more than 7 buttons to v-speed-dial

### Expected Behavior
Animation works on every button regardless how many they are

### Actual Behavior
Animation runs only on the first 7 buttons

### Reproduction Link
<a href="https://codepen.io/anon/pen/mQKoRv" target="_blank">https://codepen.io/anon/pen/mQKoRv</a>

### PR DESCRIPTION
**Pull request by kuromoka**
## Description
`VSpeedDial` transition animation only works until 7 buttons. Fixed that to work more than 7 buttons

## Motivation and Context
fixes #5735

## How Has This Been Tested?
visually

## Markup:

<details>

```vue
<template>
  <v-app>
    <v-card id="create">
      <v-speed-dial
        v-model="fab"
        top
        left
        direction="right"
        transition="slide-x-transition"
      >
        <v-btn
          slot="activator"
          v-model="fab"
          color="blue darken-2"
          dark
          fab
        >
          <v-icon>account_circle</v-icon>
          <v-icon>close</v-icon>
        </v-btn>
        <v-btn
          fab
          dark
          small
          color="green"
        >
          <v-icon>edit</v-icon>
        </v-btn>
        <v-btn
          fab
          dark
          small
          color="indigo"
        >
          <v-icon>add</v-icon>
        </v-btn>
        <v-btn
          fab
          dark
          small
          color="red"
        >
          <v-icon>delete</v-icon>
        </v-btn>
        <v-btn
          fab
          dark
          small
          color="red"
        >
          <v-icon>delete</v-icon>
        </v-btn>
        <v-btn
          fab
          dark
          small
          color="red"
        >
          <v-icon>delete</v-icon>
        </v-btn>
        <v-btn
          fab
          dark
          small
          color="red"
        >
          <v-icon>delete</v-icon>
        </v-btn>
        <v-btn
          fab
          dark
          small
          color="red"
        >
          <v-icon>delete</v-icon>
        </v-btn>
        <v-btn
          fab
          dark
          small
          color="red"
        >
          <v-icon>delete</v-icon>
        </v-btn>
      </v-speed-dial>
    </v-card>
  </v-app>
</template>

<style>
  #create .v-speed-dial {
    position: absolute;
  }

  #create .v-btn--floating {
    position: relative;
  }
</style>

<script>
export default {
  data: () => ({
    fab: false
  })
}
</script>

```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

File: packages/vuetify/src/components/VSpeedDial/VSpeedDial.js [hunk 1]
```diff
@@ -63,10 +63,20 @@ export default {
...
-        b.key = i
-
-        return b
+        if (b.tag && b.componentOptions.Ctor.options.name === 'v-btn') {
+          btnCount++
+          return h('div', {
+            style: {
+              transitionDelay: btnCount * 0.05 + 's'
+            },
+            key: btnCount
```
Comment (jacekkarczmarczyk) [inline packages/vuetify/src/components/VSpeedDial/VSpeedDial.js]: Shouldn't it be `key: i` here? Also there should be a possibility to provide keys by dev, not sure if it would work now

Comment (kuromoka) [reply packages/vuetify/src/components/VSpeedDial/VSpeedDial.js]: thanks for review
fixed d805ed3

**Comment by sh7dm** [comment]
@kuromoka don't worry, build failed because of our internal problems, I'll restart it

**Comment by kuromoka** [comment]
I will add unit tests because of ci fail

**Comment by kuromoka** [comment]
added unit test cf57183
I can't apply `transition-delay` style via unit test maybe because of https://github.com/vuejs/vue-test-utils/issues/839#issuecomment-410474714
let me know if problems

**Comment by sh7dm** [comment]
@kuromoka thanks!
