### PR TITLE
fix(VMaskInput): fix caret position while editing

### LINKED ISSUE #21776: [Bug Report][3.9.0] VMaskInput caret position while editing an input
### Environment
**Vuetify Version:** 3.9.0
**Vue Version:** 3.5.17
**Browsers:** Chrome 138.0.0.0
**OS:** Windows 10

### Steps to reproduce
The playground explains it, just try to edit an input in the middle and observe the result.

### Expected Behavior
The caret would stay after user input and on keydown would (try to) replace the next character.

### Actual Behavior
Caret position jumps to end, the next character gets properly replaced but the last character is deleted.
Delete and backspace buttons work weirdly as well - delete does nothing, backspace deletes everything that's on the right.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqFVG1v2jAQ/iunMCmgEdKu66p2gBRN+1i+rJq2ApPc5CDeHNuyHaCj/PedHRABdZuEZPvuuXueeyHTbWRNnmZaD1Y1RnfR0GGlBXM4nkmA4SphWodreORKOsYlmr0pGI1ajx/MMzgFtS4oFNjCoYFZ9O374ywCzYyDNXclWFUhyLp6QmOHaRN5lujwDIaK2V8Jl7p2RzMA2VWBYjSLKrucRW3XnakFWvKE88zns/kgOs48VHCOpRIFmlcA6VHj65ofSgTrDJdL4BaW6Jy/6tqWWDSFM5C43lcOTBYgmHVQ8CWnzqhaFPCEQDWhw+IvJJ83GnNyE7JkK66M56KWa4MWzQrBkYqcGXSgleWOK7mfQ2hgYP1ZE6vBUG7AS9w4yEtmGKU2sC65IIRUpM2L8WXghttwCWlOxfnX6Up4S7Mxw7S1SfS0ueHagUVXNwvFK61oMbYkaNGHXFWUnsrbwcKoCmJax/ijxxEBaVJSPGdCl4yaiIbnnw6iLYwg/TFlye8sebxIbudv36StOD9MQhBHN+5mWS/pdDrJZDKhk35x74gMK0PQaXfFRI09GI3/wTpwaN0B+fIC8b3v7b4ZwFoxx/7aeN4SZpcHXdmXy3dX9F95f/3hJu61xHN77zf9KxO8IPChR91uELdthkATr438r1TiGzRyA8HOH8O0mQrNI9r1o6vB9eDyJvKX28FF1F8wYbF/8oFobPM/F9xiCA==)

### PR DESCRIPTION
**Pull request by ikushum**
fixes #21776

## Description
Fix caret position while editing mask value from middle

## Markup:

```vue
<template>
  <v-app>
    <v-container>
      <v-row>
        <v-mask-input
          v-model="msg"
          :mask="mask"
          :placeholder="mask"
        />
      </v-row>
    </v-container>
  </v-app>
</template>

<script setup>
  import { ref, computed } from 'vue';
  const mask = ref('(AA)-###-NNN-##-##')
  const msg = ref('AS123XYZ4567');
</script>

```

### CODE REVIEW

File: packages/vuetify/src/labs/VMaskInput/VMaskInput.tsx [hunk 1]
```diff
@@ -47,62 +47,91 @@ export const VMaskInput = genericComponent<VMaskInputSlots>()({
...
-      selection.value = newSelection
-      vTextFieldRef.value && vTextFieldRef.value.setSelectionRange(selection.value, selection.value)
-    }
-
-    function resetSelections () {
-      if (!vTextFieldRef.value?.selectionEnd) return
-
-      selection.value = vTextFieldRef.value.selectionEnd
-      lazySelection.value = 0
+    function handleKeyDown (e: KeyboardEvent) {
```
Comment (J-Sek) [inline packages/vuetify/src/labs/VMaskInput/VMaskInput.tsx]: We mostly stick to on* prefix for event handlers

File: packages/vuetify/src/labs/VMaskInput/VMaskInput.tsx [hunk 2]
```diff
@@ -47,62 +47,91 @@ export const VMaskInput = genericComponent<VMaskInputSlots>()({
...
-      if (newValue) {
-        for (let index = 0; index < newValue.length; index++) {
-          if (lazySelection.value <= 0) break
-          isMaskDelimiter(newValue[index]) || lazySelection.value--
-          selection++
-        }
-      }
-      setCaretPosition(selection)
+    function handleClipboardEvent (e: Event) {
+      caretPosition.value = vTextFieldRef.value?.selectionEnd || 0
```
Comment (J-Sek) [inline packages/vuetify/src/labs/VMaskInput/VMaskInput.tsx]:
```suggestion
      caretPosition.value = e.target.selectionEnd
```

Comment (J-Sek) [reply packages/vuetify/src/labs/VMaskInput/VMaskInput.tsx]: similar case few lines above

**Comment by J-Sek** [comment]
When cutting off (and pasting) fragments containing separator(s) there is a minor miss in cursor position (by 1).

<details>
<summary>Recording</summary>

[Screencast from 2025-08-18 22-06-39.webm](https://github.com/user-attachments/assets/7abcf50b-792d-4da1-b904-76a443051047)

</details>

BTW. [vue-mask-input](https://github.com/niksmr/vue-masked-input) (judging by a brief manual test) seems to be particuarly resilient to this kind of interaction and does not lose typed values when the potential result does not match the mask - as it does not shift them left. I am interested in your opinion about their implementation and the potential of VMaskInput to adopt this behavior (in the future).

**Comment by ikushum** [comment]
> BTW. [vue-mask-input](https://github.com/niksmr/vue-masked-input?rgh-link-date=2025-08-18T20%3A21%3A56Z) (judging by a brief manual test) seems to be particuarly resilient to this kind of interaction and does not lose typed values when the potential result does not match the mask - as it does not shift them left. I am interested in your opinion about their implementation and the potential of VMaskInput to adopt this behavior (in the future).

I 100% agree, it's worth the improvement. Will plan to adopt this soon.

**Comment by ikushum** [comment]
> When cutting off (and pasting) fragments containing separator(s) there is a minor miss in cursor position (by 1).

Made some improvements to the logic, please have a look. Thanks

**Comment by J-Sek** [comment]
There is a minor regression:
- with the example `(AS)-123-XYZ-45-67`
  - previously I was able to paste "h" in place of either "A" or "S" or 2 characters to replace both
  - now the paste action is removing everything after `)-` and does not apply the text from clipboard (or does it incorrectly)

File: packages/vuetify/src/labs/VMaskInput/VMaskInput.tsx [hunk 3]
```diff
@@ -47,62 +47,141 @@ export const VMaskInput = genericComponent<VMaskInputSlots>()({
...
+    async function onCut (e: Event) {
+      e.preventDefault()
+
+      copySelectionToClipboard(e)
+      deleteSelection(e)
     }
 
-    function resetSelections () {
-      if (!vTextFieldRef.value?.selectionEnd) return
+    async function onPaste (e: ClipboardEvent) {
```
Comment (J-Sek) [inline packages/vuetify/src/labs/VMaskInput/VMaskInput.tsx:134]: <details><summary>Suggestion</summary>

```ts
async function onPaste (e: ClipboardEvent) {
  e.preventDefault()

  const pastedString = e.clipboardData?.getData('text')
  if (!pastedString) return

  const inputElement = e.target as HTMLInputElement
  const { value: existingTxt, selectionStart: start, selectionEnd: end } = inputElement ?? {}

  const potentialNewInputVal =
    existingTxt
      ? existingTxt.slice(0, start as number | undefined) + pastedString + existingTxt.slice(end as number | undefined)
      : pastedString

  const potentialValueUntilCaret =
    existingTxt
      ? existingTxt.slice(0, start as number | undefined) + pastedString
      : pastedString

  model.value = mask.mask(mask.unmask(potentialNewInputVal))
  await nextTick()
  const newCaretPosition = mask.mask(mask.unmask(potentialValueUntilCaret)).length
  inputElement.setSelectionRange(newCaretPosition, newCaretPosition)
}
```

</details>

Fixes those new tests (once 2 test cases get their fixes).

No need to apply it directly. I was just trying out my luck.

File: packages/vuetify/src/labs/VMaskInput/__tests__/VMaskInput.spec.browser.tsx [hunk 4]
```diff
@@ -31,4 +31,319 @@ describe('VMaskInput', () => {
...
+        navigator.clipboard.writeText('CD')
+        await insertCaretAt(10, 12)
+        await userEvent.paste()
+
+        // TODO: Fix this test
+        expect(input.selectionStart).toBe(12)
+        expect(model.value).toBe('(AS)-123-XCD-45-67')
+      })
+
+      it('pasted when selection is in middle', async () => {
```
Comment (J-Sek) [inline packages/vuetify/src/labs/VMaskInput/__tests__/VMaskInput.spec.browser.tsx]: It would be good to use it.each here. We would sacrifice the descriptions, but they seem redundant anyway.

File: packages/vuetify/src/labs/VMaskInput/__tests__/VMaskInput.spec.browser.tsx [hunk 5]
```diff
@@ -31,4 +31,319 @@ describe('VMaskInput', () => {
...
+        const { input, model, insertCaretAt } = renderComponent()
+
+        navigator.clipboard.writeText('CD')
+        await insertCaretAt(1, 3)
+        await userEvent.paste()
+
+        // TODO: Fix this test
+        expect(input.selectionStart).toBe(5)
+        expect(model.value).toBe('(CD)-123-XCD-45-67')
```
Comment (J-Sek) [inline packages/vuetify/src/labs/VMaskInput/__tests__/VMaskInput.spec.browser.tsx]: I'd flip the order, first assert the value, then the caret position. It was easier to work with the pasting handler when I could make sure the value is right and only then focus on the caret, which is arguably a secondary concern.

File: packages/vuetify/src/labs/VMaskInput/__tests__/VMaskInput.spec.browser.tsx [hunk 6]
```diff
@@ -31,4 +31,319 @@ describe('VMaskInput', () => {
...
+
+        navigator.clipboard.writeText('A0')
+        await insertCaretAt(11, 14)
+        await userEvent.paste()
+
+        // TODO: Fix this test
+        expect(input.selectionStart).toBe(14)
+        expect(model.value).toBe('(AS)-123-XYA-05-67')
+      })
+    })
```
Comment (J-Sek) [inline packages/vuetify/src/labs/VMaskInput/__tests__/VMaskInput.spec.browser.tsx:329]: I imagine pasting handler could to be more "greedy" to support users because selecting and copying is sometimes hard (user might be in a rush, habe vision impairment or a PDF is dirty).

Idea for an additional test case:
- paste "_ccc." to (10, 12), expecting "CCC" to appear in place of "XYZ"

can be achieved by:

```ts
const pastedString = removeMaskDelimiters(e.clipboardData?.getData('text') ?? '')
```
