### PR TITLE
fix(VSelect/VAutocomplete/VCombobox): add missing item-color prop

### LINKED ISSUE #16351: [Bug Report][3.0.6] VSelect with checkboxes (multiple) does not inherit color anymore
### Environment
**Vuetify Version:** 3.0.6
**Last working version:** 2.6.13
**Vue Version:** 3.2.45
**Browsers:** Edge 108.0.1462.54
**OS:** Windows 10

### Steps to reproduce
Open the codepen link
Open the second or the fourth select
See that the checkboxes are black

### Expected Behavior
The checkboxes should inherit the color specified in the v-select, as it was the case after #2189 was merged

### Actual Behavior
The checkboxes are black

### Reproduction Link
[https://codepen.io/jeremyVignelles/pen/LYBNBpx](https://codepen.io/jeremyVignelles/pen/LYBNBpx)

### Other comments
See #2174 and #2189

### PR DESCRIPTION
**Pull request by prashantsinghb**
fix(VAutocomplete) : add color prop to VList

fixes #16351

## Description

Resolves #16351 

Added color prop to VList in VSelect, VCombobox and VAutocomplete
Added itemColor prop to VSelect

## Markup:

```vue
<template>
  <v-app>
    <v-container>
      <v-select :items="items" color="green" v-model="select" label="Select" item-title="state" item-value="abbr"></v-select>
      <v-select :items="items" color="green" multiple v-model="select2" label="Select" item-title="state" item-value="abbr"></v-select>
      <v-select :items="items" color="green" item-color="red" v-model="select3" label="Select" item-title="state" item-value="abbr"></v-select>
      <v-select :items="items" color="green" item-color="red" multiple v-model="select4" label="Select" item-title="state" item-value="abbr"></v-select>
      <v-autocomplete :items="items" color="green" v-model="select5" label="Select" item-title="state" item-value="abbr"></v-autocomplete>
      <v-autocomplete :items="items" color="green" multiple v-model="select6" label="Select" item-title="state" item-value="abbr"></v-autocomplete>
      <v-autocomplete :items="items" color="green" item-color="red" v-model="select7" label="Select" item-title="state" item-value="abbr"></v-autocomplete>
      <v-autocomplete :items="items" color="green" item-color="red" multiple v-model="select8" label="Select" item-title="state" item-value="abbr"></v-autocomplete>
      <v-combobox :items="items" color="green" v-model="select9" label="Select" item-title="state" item-value="abbr"></v-combobox>
      <v-combobox :items="items" color="green" multiple v-model="select10" label="Select" item-title="state" item-value="abbr"></v-combobox>
      <v-combobox :items="items" color="green" item-color="red" v-model="select11" label="Select" item-title="state" item-value="abbr"></v-combobox>
      <v-combobox :items="items" color="green" item-color="red" multiple v-model="select12" label="Select" item-title="state" item-value="abbr"></v-combobox>
    </v-container>
  </v-app>
</template>

<script>
  import { ref } from 'vue'
  export default {
    name: 'Playground',
    setup () {
      const select = ref({ state: 'Florida', abbr: 'FL' })
      const select2 = ref([{ state: 'Florida', abbr: 'FL' }])
      const select3 = ref([{ state: 'Florida', abbr: 'FL' }])
      const select4 = ref([{ state: 'Florida', abbr: 'FL' }])
      const select5 = ref([{ state: 'Florida', abbr: 'FL' }])
      const select6 = ref([{ state: 'Florida', abbr: 'FL' }])
      const select7 = ref([{ state: 'Florida', abbr: 'FL' }])
      const select8 = ref([{ state: 'Florida', abbr: 'FL' }])
      const select9 = ref([{ state: 'Florida', abbr: 'FL' }])
      const select10 = ref([{ state: 'Florida', abbr: 'FL' }])
      const select11 = ref([{ state: 'Florida', abbr: 'FL' }])
      const select12 = ref([{ state: 'Florida', abbr: 'FL' }])
      const items = [
        { state: 'Florida', abbr: 'FL' },
        { state: 'Georgia', abbr: 'GA' },
        { state: 'Nebraska', abbr: 'NE' },
        { state: 'California', abbr: 'CA' },
        { state: 'New York', abbr: 'NY' },
      ]
      return {
        select,
        select2,
        select3,
        select4,
        select5,
        select6,
        select7,
        select8,
        select9,
        select10,
        select11,
        select12,
        items,
      }
    },
  }
</script>

```

### CODE REVIEW

**Review by KaelWD — CHANGES_REQUESTED** [review]
You forgot combobox

v2 also had a itemColor prop, should we bring that back?

File: packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx [hunk 1]
```diff
@@ -425,6 +425,7 @@ export const VAutocomplete = genericComponent<new <
                       onFocusout={ onFocusout }
                       onScrollPassive={ onListScroll }
                       tabindex="-1"
+                      color={ props.itemColor ? props.itemColor : props.color}
```
Comment (yuwu9145) [inline packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx:428]: `props.itemColor ?? props.color`
