### PR TITLE
fix(VCalendar): correct interval and event offset with custom firstTime

### LINKED ISSUE #12563: [Bug Report] Calendar day view with multi-day-spanning events and a custom firstInterval doesn't render such events.
### Environment
**Vuetify Version:** 2.3.16
**Vue Version:** 2.6.11
**Browsers:** Firefox 82.0
**OS:** Windows 10

### Steps to reproduce
Add a calendar in day view with a defined `firstInterval` prop. Add an event that spans from the end of one day into the start of the next.

### Expected Behavior
Multi-day event is visible from its start time to the end of the first day 

### Actual Behavior
Event is not present.

### Reproduction Link
<a href="https://codepen.io/lakueyg/pen/RwRBdMK" target="_blank">https://codepen.io/lakueyg/pen/RwRBdMK</a>

### Other comments
This is because the time calculation in https://github.com/vuetifyjs/vuetify/blob/aac7c54b053af96881c36efa222243d7206df73e/packages/vuetify/src/components/VCalendar/mixins/calendar-with-intervals.ts#L149 does not account correctly for days - it assumes that all times it is dealing with happen on the same day.

### LINKED ISSUE #12681: [Bug Report] VCalendar first-time prop result end of the day interval not correct
### Environment
**Vuetify Version:** 2.3.19
**Vue Version:** 2.6.11
**Browsers:** Edge 86.0.622.69
**OS:** Windows 10

### Steps to reproduce
Set first-time to "08:00", score to end of the day

### Expected Behavior
Day ends at 12AM

### Actual Behavior
Extra intervales

### Reproduction Link
<a href="https://codepen.io/yipingruan/pen/RwGwYjK" target="_blank">https://codepen.io/yipingruan/pen/RwGwYjK</a>
image

### PR DESCRIPTION
**Pull request by KaelWD**
## Description

fixes #12563
fixes #12681

TODO: events starting "tomorrow" but before the first interval are still not displayed

## Markup:

```vue
<template>
  <v-app>
    <v-container>
      <v-calendar
        :events
        :max-days="2"
        color="primary"
        end="2025-11-19"
        first-time="08:00"
        type="custom-daily"
      />
    </v-container>
  </v-app>
</template>

<script setup>
  const events = [
    // { start: '2025-11-18T15:09', end: '2025-11-19T16:16', timed: true },
    // { start: '2025-11-18T16:08', end: '2025-11-19T02:16', timed: true },
    { start: '2025-11-19T02:00', end: '2025-11-19T06:23', timed: true },
  ]
</script>
```

### CODE REVIEW

**Comment by KaelWD** [comment]
The fundamental flaw here is we're filtering events by day (00:00 - 23:59) but then offsetting what times a day actually includes. `day` in `getSlotChildren` needs be changed to `[start, end]` timestamps to fully support days that don't start and end at midnight, which would also mean having to make calendarWithEvents aware of calendarWithIntervals for access to firstMinute, intervalCount, and intervalMinutes.

File: packages/vuetify/src/components/VCalendar/composables/calendarWithEvents.tsx [hunk 1]
```diff
@@ -348,8 +349,8 @@ export function useCalendarWithEvents (props: CalendarWithEventsProps, slots: an
     const dayIdentifier = getDayIdentifier(day)
     const start = event.startIdentifier >= dayIdentifier
     const end = event.endIdentifier > dayIdentifier
```
Comment (KaelWD) [inline packages/vuetify/src/components/VCalendar/composables/calendarWithEvents.tsx:351]: These still don't account for firstTime

**Comment by Joebayld** [comment]
This is working much better. But I've found that the `timeToY` function doesn't seem to work past midnight. If you change your firstInterval and try to use the code from the docs, it doesn't allow you to get the Y pixel position of a time past midnight. https://vuetifyjs.com/en/components/calendars/#day-body

**Comment by Joebayld** [comment]
> This is working much better. But I've found that the `timeToY` function doesn't seem to work past midnight. If you change your firstInterval and try to use the code from the docs, it doesn't allow you to get the Y pixel position of a time past midnight. https://vuetifyjs.com/en/components/calendars/#day-body

Hey @KaelWD, I'm not sure the best way to make a demo of this, but the timeToY functionality does not account for the first interval offset, and wraps around at midnight regardless of the interval. If you need a demo of this issue let me know - would love to help where possible to fix it though.
