### PR TITLE
[Bug] fix(VDataTable): fix passing kebab-cased footer props

### LINKED ISSUE #8254: [Bug Report] VDataTable footer-props.item-per-page-text not working
### Environment
**Vuetify Version:** 2.0.3
**Vue Version:** 2.6.10
**Browsers:** Safari 12.1.1
**OS:** Mac OS 10.14.5

### Steps to reproduce
See CodePen.

### Expected Behavior
Table should show the contents of items-per-page-text.

### Actual Behavior
Default text is shown instead.

### Reproduction Link
<a href="https://codepen.io/anon/pen/pMrjax" target="_blank">https://codepen.io/anon/pen/pMrjax</a>

### Other comments
Guys, this Vuetify Issue Creator sucks. Please:
* Make the CodePen template link open in a new window, so we don't lose everything we have written.
* Do not require us to fill all stuff, be glad that we report at least something. If you require CodePen, do not require Steps to reproduce.
* Do not require reproduction link, it is not always possible to create one.

Cheers!

### PR DESCRIPTION
**Pull request by nekosaur**
## Description
items-per-page-text kebab-cased footer prop was not passed correctly
to v-data-footer because v-data-table sets a different default value
using camelCase. also fixed passing header props.

## Motivation and Context

closes #8254

## How Has This Been Tested?

playground, unit test

## Markup:

<details>

```vue
<template>
  <div>
    <v-data-table
          :headers="[]"
          :items="[]"
          :footer-props="{ 'items-per-page-options': [10, 25, 50, -1],
                           'items-per-page-text': 'Showing items:',
                           'items-per-page-all-text': 'All of it'}">
        </v-data-table>
  </div>
</template>
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)
- [ ] I've added new examples to the kitchen (applies to new features and breaking changes in core library)

### CODE REVIEW

File: packages/vuetify/src/util/helpers.ts [hunk 1]
```diff
@@ -506,3 +506,12 @@ export function humanReadableFileSize (bytes: number, binary = false): string {
   }
   return `${bytes.toFixed(1)} ${prefix[unit]}B`
 }
+
+export function camelizeObjectKeys (obj: Record<string, any> | null | undefined) {
+  if (!obj) return {}
```
Comment (johnleider) [inline packages/vuetify/src/util/helpers.ts]:
```suggestion
  if (obj == nul) return {}
```

Thoughts on this?

Comment (nekosaur) [reply packages/vuetify/src/util/helpers.ts]: double equality will fail if `obj` is an empty string
