### PR TITLE
Fix(VSelect): don't dispatch click event on arrow keys

### LINKED ISSUE #12723: [Bug Report] v-menu as popup closes on arrow keys v-select
### Environment
**Vuetify Version:** 2.3.18
**Vue Version:** 2.6.11
**Browsers:** Chrome 87.0.4280.88
**OS:** Windows 10

### Steps to reproduce
1. Add v-select to v-menu as popup
2. Focus select input and press up or down arrow keys

### Expected Behavior
Popup menu does not close

### Actual Behavior
Popup menu closes automatically

### Reproduction Link
<a href="https://codepen.io/neno-petkov/pen/gOwPPpJ" target="_blank">https://codepen.io/neno-petkov/pen/gOwPPpJ</a>

### LINKED ISSUE #12769: [Bug Report] Pressing key up/down on focused v-select inside fullscreen v-dialog closes the dialog
### Environment
**Vuetify Version:** 2.3.21
**Vue Version:** 2.6.12
**Browsers:** Firefox 83.0
**OS:** Windows 10

### Steps to reproduce
Place a v-select in a fullscreen v-dialog. Press tab to set focus in the v-select then press key up or down.

### Expected Behavior
Pressing key up or down when focus is on the v-select should select the previous or next item in the list. Alternatively it should open the menu with items.

### Actual Behavior
Pressing key up or down when focus is on the v-select will close the dialog. This only happens on fullscreen dialogs, not normal ones.

### Reproduction Link
<a href="https://codepen.io/nerderer/pen/oNzYPYL" target="_blank">https://codepen.io/nerderer/pen/oNzYPYL</a>

### Other comments
Pressing up or down currently doesn't work as expected even if it's not inside a dialog. It just select the previous or next item then loses focus. But inside fullscreen dialogs there's also this side effect.

### PR DESCRIPTION
**Pull request by yuwu9145**
fixes #12769

fixes #12723

## Description

When using up & down keys to cycle through available select items, `VSelect` use `menu.activeTile.click()` event to do selection. 

However when dropdown list is not active, this `MouseEvent` is actually a click event from clicking the position of `x:0, y:0` which is equivalent to clicking outside of parent `Dialog` or `Menu` (this can be verified by logging out event object `e` in line 123 of file `packages/vuetify/src/components/VList/VListItem.ts`, you shall see x and y from that event object are all `0`). 

Therefore, `Dialog` or `Menu` will be closed by **clicking outside**

## Motivation and Context

closes #12769

closes #12723

## How Has This Been Tested?

visually

## Markup:

<details>

```vue
<template>
  <v-container>
    <h1>12769 Reproduce</h1>
    <v-btn @click="toggleFullscreenDialog = !toggleFullscreenDialog">Toggle fullscreen dialog</v-btn>
      <v-dialog v-model="toggleFullscreenDialog" fullscreen>
        <v-card>
          <v-card-text>
            Press tab to focus on the select then press key up/down to close dialog
            <v-select label="Test" :items="items" />
          </v-card-text>
        </v-card>
      </v-dialog>



    <h1>12723 Reproduce</h1>
    <p>
        The v-input doesn't emit update:error when its error state is changed via the form and not input. See console log for when event is emitted.
      </p>
    <div class="text-center">
    <v-menu
      v-model="menu"
      :close-on-content-click="false"
      :nudge-width="200"
      offset-x
    >
      <template v-slot:activator="{ on, attrs }">
        <v-btn
          color="indigo"
          dark
          v-bind="attrs"
          v-on="on"
        >
          Menu as Popover
        </v-btn>
      </template>

      <v-card>
        <v-list>
          <v-list-item>
            <v-list-item-avatar>
              <img src="https://cdn.vuetifyjs.com/images/john.jpg" alt="John">
            </v-list-item-avatar>

            <v-list-item-content>
              <v-list-item-title>John Leider</v-list-item-title>
              <v-list-item-subtitle>Founder of Vuetify.js</v-list-item-subtitle>
            </v-list-item-content>

            <v-list-item-action>
              <v-btn
                :class="fav ? 'red--text' : ''"
                icon
                @click="fav = !fav"
              >
                <v-icon>mdi-heart</v-icon>
              </v-btn>
            </v-list-item-action>
          </v-list-item>
        </v-list>

        <v-divider></v-divider>

        <v-list>
          <v-list-item>
            <v-list-item-action>
              <v-switch v-model="message" color="purple"></v-switch>
            </v-list-item-action>
            <v-list-item-title>Enable messages</v-list-item-title>
          </v-list-item>

          <v-list-item>
            <v-list-item-action>
              <v-switch v-model="hints" color="purple"></v-switch>
            </v-list-item-action>
            <v-list-item-title>Enable hints</v-list-item-title>
          </v-list-item>
        </v-list>
       <v-select
          autofocus
          :items="items"
          label="Standard"
        ></v-select>
        <v-card-actions>
          <v-spacer></v-spacer>

          <v-btn text @click="menu = false">Cancel</v-btn>
          <v-btn color="primary" text @click="menu = false">Save</v-btn>
        </v-card-actions>
      </v-card>
    </v-menu>
  </div>
  </v-container>
</template>

<script>
export default {
  data() {
    return {
      toggleFullscreenDialog: false,
      items: ["Foo", "Bar", "Fizz", "Buzz"],
      fav: true,
      menu: false,
      message: false,
      hints: true,
    };
  }
};
</script>

```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

File: packages/vuetify/src/components/VSelect/VSelect.ts [hunk 1]
```diff
@@ -790,7 +790,8 @@ export default baseMixins.extend<options>().extend({
       window.requestAnimationFrame(() => {
         menu.getTiles()
         keyCodes.up === keyCode ? menu.prevTile() : menu.nextTile()
-        menu.activeTile && menu.activeTile.click()
```
Comment (yuwu9145) [inline packages/vuetify/src/components/VSelect/VSelect.ts:793]: When using up & down keys to cycle through available select items, VSelect use menu.activeTile.click() event to do selection. However when dropdown list is not active, this MouseEvent is from clicking the position of x===0, y===0 which is equivalent to clicking outside parent Dialog or Menu. Therefore, Dialog or Menu will be closed by "clicking outside"

Solution: In order to select new item, Instead of dispatching wrong `MouseEvent` from an invisible dom, directly set select Item in `VSelect` level

**Comment by johnleider** [comment]
Thank you for your interest in improving Vuetify. Please create unit tests that correlate to the changes made in this request.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by yuwu9145** [comment]
@johnleider Thanks for the feedback. Unit test will be added soon.

**Comment by yuwu9145** [comment]
@johnleider unit test has been added. It shall validate the issue scenario

**Comment by j1mmie** [comment]
@yuwu9145 thank you for submitting this fix. I noticed that the bug in #12769 occurs even without the v-dialog. Do you know if your fix solves the simpler case as well? Example here: https://codepen.io/j1mmie/pen/WNGVJOw . If not, happy to look into it myself.

Looking forward to seeing this one merged in.

**Comment by yuwu9145** [comment]
> @yuwu9145 thank you for submitting this fix. I noticed that the bug in #12769 occurs even without the v-dialog. Do you know if your fix solves the simpler case as well? Example here: https://codepen.io/j1mmie/pen/WNGVJOw . If not, happy to look into it myself.
> 
> Looking forward to seeing this one merged in.

Hi @j1mmie I did a testing now, it does resolve.

Basically pressing key up/down will result in wrong mouse click event from dropdown list dialog.

I am also looking forward that this pull request could be further reviewed

File: packages/vuetify/src/components/VSelect/VSelect.ts [hunk 2]
```diff
@@ -803,7 +803,8 @@ export default baseMixins.extend<options>().extend({
             menu.lastTile()
             break
         }
-        menu.activeTile && menu.activeTile.click()
+        const newItemValue = this.allItems[this.getMenuIndex()]
+        this.selectItem(newItemValue)
```
Comment (johnleider) [inline packages/vuetify/src/components/VSelect/VSelect.ts:807]:
```suggestion
        this.selectItem(this.allItems[this.getMenuIndex()])
```

**Review by johnleider — CHANGES_REQUESTED** [review]
Can the spec test not use VDialog? What is the logic behind it?

**Comment by yuwu9145** [comment]
> Can the spec test not use VDialog? What is the logic behind it?

Hi @johnleider , thanks for your time for reviewing. The only purpose to include `VDialog` into spec file is simulating #12769: An open Dialog hosts a VSelect, and using keyboard to cycle through VSelect item will close its hosting VDialog.

As the cause is cycling through VSelect item with keyboard results in wrong mouse click event, the test case could be simplied to only check if any mouse event being dispatched or not. So VSelect spec file does not have to include VDialog. Would this be better?

**Review by KaelWD — APPROVED** [review]
