### PR TITLE
fix(VTextField): change order of events for checking input focus state

### LINKED ISSUE #20558: [Bug Report][3.7.2] Autocomplete focus event can trigger twice
### Environment
**Vuetify Version:** 3.7.2
**Vue Version:** 3.5.11
**Browsers:** Chrome 129.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
If you click precisely on the zone where the text input is, the event is fired once only as intended.

However, if you click, still within the input in the same general are, but slightly off centered from the text area, the event will trigger twice.

### Expected Behavior
The event fires once on focus, wherever we click inside of the input.

### Actual Behavior
The event is triggered twice depending of the zone in which the component is clicked

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVj8FqwzAMhl9F8yUtLM29pGW7jL3BDssOwVFKwLaMLYdByLtPtjtoL0b6+SR/+t5UDLp79/60JlRn1TNab0bG6+AA+rUdvS9laTQ5HheH4R6VkPGX23lBM8HaWprQXAZl421Q0An3QI6JSZPsR0Z4S36Sf84z6RRxkhlyH7ke1LXvnuF/A4mfFQpYDPvuwVzaqMPiGSJyqgcs1lNg2CDgDDvMgSw0cnRTFWVvZBBtuGTi0HyiMQRfFMz00hwrNCeneSEHd9XDeoStuuV5MngydJM0Z3uWqhoioPZXl4wpz88fAhp+2Q==)

### Other comments
Try clicking close to the bottom of the input, this happens 100% of the time.

### PR DESCRIPTION
**Pull request by johnleider**
fixes #20558

TODO:

- [x] v-date-input
- [x] v-number-input
- [x] v-color-input

## Markup:

```vue
<template>
  <v-app>
    <v-container>
      <v-text-field v-model="msg" />
      <v-select @update:focused="onFocus"></v-select>
      <v-autocomplete @update:focused="onFocus"></v-autocomplete>
      <v-combobox @update:focused="onFocus"></v-combobox>
      <v-date-input @update:focused="onFocus"></v-date-input>
      <v-number-input @update:focused="onFocus"></v-number-input>
    </v-container>
  </v-app>
</template>

<script setup>
  import { ref } from 'vue'

  const msg = ref('Hello World!')

  function onFocus(v) {
    console.log(v)
  }
</script>

```

### CODE REVIEW

**Comment by ikushum** [comment]
Found problem with `VNumberInput`, converting to draft

**Comment by J-Sek** [comment]
> Found problem with `VNumberInput`, converting to draft

Something that #21217 could help with?

**Comment by ikushum** [comment]
@J-Sek I merged but it didn't help, it was a different problem which I just fixed in latest commit. 

Thanks for the comment

File: packages/vuetify/src/components/VNumberInput/VNumberInput.tsx [hunk 1]
```diff
@@ -294,17 +294,15 @@ export const VNumberInput = genericComponent<VNumberInputSlots>()({
...
     }
 
     function onBlur () {
-      blur()
       clampModel()
     }
 
     useRender(() => {
-      const { modelValue: _, ...textFieldProps } = VTextField.filterProps(props)
+      const { modelValue: _, ...textFieldProps } = omit(VTextField.filterProps(props), ['focused'])
```
Comment (johnleider) [inline packages/vuetify/src/components/VNumberInput/VNumberInput.tsx:305]: @ikushum Is there a reason we don't need to do this on other components that call VTextField.filterProps?

image

Comment (ikushum) [reply packages/vuetify/src/components/VNumberInput/VNumberInput.tsx]: @johnleider 

This is because in VNumberInput `textFieldProps` was being spread into `<VTextField>` in the end but in other components, it was being spread at the beginning.

Since in `VNumberInput` it was being spread in the end, `v-model:focused={ isFocused.value }` would always be overwritten by `focused` of `textFieldProps`.

Comment (ikushum) [reply packages/vuetify/src/components/VNumberInput/VNumberInput.tsx]: After careful observation, I think this spread behaviour in `VNumberInput` is problematic so in the latest commit I'm now spreading it at the end and removed the omit.

**Review by johnleider — COMMENTED** [review]
focused is a boolean by default, no need to !!

**Review by ikushum — APPROVED** [review]

**Comment by J-Sek** [comment]
Text fields within dropdown menu appear readonly [(example)](https://play.vuetifyjs.com/#eNptkc1qwzAQhF9FqAdf/EMppW1wAyXQPkALPSQ5bK11EGwkISkmpfTdo584sSG30berYTRa/3Fnu+bNmHo4IF/w1uPeEHhcbhRj7VCBMUmmQ6eVB6nQnlGCDgk7PwLGCH6QXjf8M3N+nSxkcHdhtC5WQLLXVkkoSlasNGkLQkf9HqQUCX+gtru88YVHcFF8/+q9VLtiOzUewEpQPjjrg6cQUFynl6gh7Pg4dmcsGlSiiokmG+lBHo++6iWSuGm8bJvpztS/mbWX0VjQ2GIA8xojyS3P7vP/kj/Uj/X9E4/iuX7hZQ/ksJx9WWbbEzsji80=) and require `@mousedown.stop` to work around this.

I am not sure why nobody have raised an issue yet, so I leave it as a note here.

**Comment by parag-n** [comment]
> Text fields within dropdown menu appear readonly [(example)](https://play.vuetifyjs.com/#eNptkc1qwzAQhF9FqAdf/EMppW1wAyXQPkALPSQ5bK11EGwkISkmpfTdo584sSG30berYTRa/3Fnu+bNmHo4IF/w1uPeEHhcbhRj7VCBMUmmQ6eVB6nQnlGCDgk7PwLGCH6QXjf8M3N+nSxkcHdhtC5WQLLXVkkoSlasNGkLQkf9HqQUCX+gtru88YVHcFF8/+q9VLtiOzUewEpQPjjrg6cQUFynl6gh7Pg4dmcsGlSiiokmG+lBHo++6iWSuGm8bJvpztS/mbWX0VjQ2GIA8xojyS3P7vP/kj/Uj/X9E4/iuX7hZQ/ksJx9WWbbEzsji80=) and require `@mousedown.stop` to work around this.
> 
> I am not sure why nobody have raised an issue yet, so I leave it as a note here.

+1

I am also facing the same issue


Worked as expected till v3.8.5

**Comment by coderPaddyS** [comment]
> Text fields within dropdown menu appear readonly [(example)](https://play.vuetifyjs.com/#eNptkc1qwzAQhF9FqAdf/EMppW1wAyXQPkALPSQ5bK11EGwkISkmpfTdo584sSG30berYTRa/3Fnu+bNmHo4IF/w1uPeEHhcbhRj7VCBMUmmQ6eVB6nQnlGCDgk7PwLGCH6QXjf8M3N+nSxkcHdhtC5WQLLXVkkoSlasNGkLQkf9HqQUCX+gtru88YVHcFF8/+q9VLtiOzUewEpQPjjrg6cQUFynl6gh7Pg4dmcsGlSiiokmG+lBHo++6iWSuGm8bJvpztS/mbWX0VjQ2GIA8xojyS3P7vP/kj/Uj/X9E4/iuX7hZQ/ksJx9WWbbEzsji80=) and require `@mousedown.stop` to work around this

For anyone encountering a similar issue, e.g. text fields in a `#no-data` slot of a select, since v3.12.0 there is the menu-header slot which resolves this issue for me if used instead of the `#no-data` slot.
