### PR TITLE
[Bug] fix(VDataTable): show no-results when custom filter returns zero rows

### LINKED ISSUE #8131: [Bug Report] VDataTable with all items filtered out does not display 'no-results-text'
### Versions and Environment
**Vuetify:** 2.0.2
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.14.5

### Steps to reproduce
1. Use `filter: () => false` for a header

### Expected Behavior
Since all results are filtered out, 'no-results-text' should be displayed

### Actual Behavior
Table displays no rows

### Reproduction Link
<a href="https://codepen.io/anon/pen/MNJypL" target="_blank">https://codepen.io/anon/pen/MNJypL</a>

### Other comments
This behavior is especially inconsistent if you have both filters and and search available on a table, as when there is a search query 'no-results-text' will be displayed when all items are filtered out, but with no search query, nothing is displayed.

### PR DESCRIPTION
**Pull request by nekosaur**
## Description

changed logic around showing empty messages so that it uses original items length and filtered items length instead of relying on `search` prop.

## Motivation and Context

closes #8131

## How Has This Been Tested?

playground

## Markup:

<details>

```vue
<template>
  <div>
    <v-data-table
      :headers="headers"
      :items="items"
    />
    <v-data-table
      :headers="headers"
      :items="[]"
    />
    <v-data-table
      :headers="headers"
      :items="[]"
      loading
    />
    <v-data-table
      :headers="headers2"
      :items="items"
      search="ö"
    />
    <v-data-table
      :headers="headers2"
      :items="items"
    />
  </div>
</template>

<script>
export default {
  data: () => ({
    headers: [
      {
        value: 'foo',
        text: 'Foo',
        filter: () => false
      }
    ],
    headers2: [
      {
        value: 'foo',
        text: 'Foo',
      }
    ],
    items: [
      { foo: 1 }
    ]
  })
}
</script>
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)
- [ ] I've added new examples to the kitchen (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by jacekkarczmarczyk** [comment]
Should the first example display 'No matching records found' if there's no search?

**Comment by nekosaur** [comment]
There is a search, header item has `filter` property

File: packages/vuetify/src/components/VDataIterator/VDataIterator.ts [hunk 1]
```diff
@@ -180,22 +180,22 @@ export default Themeable.extend({
     genEmptyWrapper (content: VNodeChildren) {
       return this.$createElement('div', content)
     },
-    genEmpty (itemsLength: number) {
-      if (itemsLength <= 0 && this.loading) {
+    genEmpty (originalItemsLength: number, filteredItemsLength: number) {
+      if (originalItemsLength <= 0 && this.loading) {
```
Comment (johnleider) [inline packages/vuetify/src/components/VDataIterator/VDataIterator.ts]:
```suggestion
      if (originalItemsLength === 0 && this.loading) {
```

File: packages/vuetify/src/components/VDataIterator/VDataIterator.ts [hunk 2]
```diff
@@ -180,22 +180,22 @@ export default Themeable.extend({
...
         const loading = this.$slots['loading'] || this.$vuetify.lang.t(this.loadingText)
         return this.genEmptyWrapper(loading)
-      } else if (itemsLength <= 0 && !this.items.length) {
+      } else if (originalItemsLength <= 0) {
```
Comment (johnleider) [inline packages/vuetify/src/components/VDataIterator/VDataIterator.ts]:
```suggestion
      } else if (originalItemsLength === 0) {
```

File: packages/vuetify/src/components/VDataIterator/VDataIterator.ts [hunk 3]
```diff
@@ -180,22 +180,22 @@ export default Themeable.extend({
...
         const noData = this.$slots['no-data'] || this.$vuetify.lang.t(this.noDataText)
         return this.genEmptyWrapper(noData)
-      } else if (itemsLength <= 0 && this.search) {
+      } else if (filteredItemsLength <= 0) {
```
Comment (johnleider) [inline packages/vuetify/src/components/VDataIterator/VDataIterator.ts]:
```suggestion
      } else if (filteredItemsLength === 0) {
```
