### PR TITLE
fix(VCalendar): add nativeEvent to all re-emitted events

### LINKED ISSUE #9485: [Bug Report] Unable to use native event in v-calendar in @click:more event
### Environment
**Vuetify Version:** 2.1.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.87
**OS:** Linux x86_64

### Steps to reproduce
1) set event @click:event="eventClicked" and add eventClicked({ nativeEvent, event })
both parameters are defined and work properly
2) set event @click:more="clickedMore" and add clickedMore({ nativeEvent, event })
nativeEvent is undefined

### Expected Behavior
@click:more will provide native JS and vue events. 

### Actual Behavior
native event is undefined

### Reproduction Link
<a href="https://codepen.io/slash006/pen/KKKvPqw" target="_blank">https://codepen.io/slash006/pen/KKKvPqw</a>

### PR DESCRIPTION
**Pull request by Meplos**
## Description
Fixes #9485
This PR allow calendar event emit the native event (MouseEvent, etc...) in :time and :date custom event.
Before native event was pass only on the :event event.

## Motivation and Context

This change is require for all features which need raw event information. Like open a context menu at the click position. 

Fix issue [ issue #14298](https://github.com/vuetifyjs/vuetify/issues/14298).

## How Has This Been Tested?
Test with log information. In fact this PR don't affect beheavior of the VCalendar, just add information.

## Markup:
<details>

```vue
<template>
  <v-container>
    <!--  -->
    <v-calendar
      type="day"
      @contextmenu:time="log('CONTEXT TIME', $event)"
      @click:time="log('CLICK TIME', $event)"
    ></v-calendar>
    <v-calendar
      type="week"
      @contextmenu:time="log('CONTEXT TIME', $event)"
      @click:time="log('CLICK TIME', $event)"
    ></v-calendar>
    <v-calendar
      type="month"
      @contextmenu:day="log('CONTEXT DAY', $event)"
      @click:day="log('CLICK DAY', $event)"
    ></v-calendar>

  </v-container>
</template>

<script>
  export default {
    data: () => ({
    //
    }),
    methods: {
      log (msg, event) {
        console.log(msg, event)
      },
    },
  }
</script>
```
</details>

## Types of changes

- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [ x ] The PR title is no longer than 64 characters.
- [ x ] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [ x ] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Review by James3987 — DISMISSED** [review]

**Comment by KaelWD** [comment]
@Meplos There are more events missing: https://github.com/vuetifyjs/vuetify/issues/9485

**Comment by Meplos** [comment]
Ok, @KaelWD  I will work on this in the next days.

File: packages/vuetify/src/components/VCalendar/VCalendarWeekly.ts [hunk 1]
```diff
@@ -184,7 +186,7 @@ export default CalendarBase.extend({
         on: this.getMouseEventHandlers({
           'click:date': { event: 'click', stop: true },
           'contextmenu:date': { event: 'contextmenu', stop: true, prevent: true, result: false },
-        }, _e => day),
+        }, nativeEvent => { return { nativeEvent, ...day } }),
```
Comment (KaelWD) [inline packages/vuetify/src/components/VCalendar/VCalendarWeekly.ts:189]:
```suggestion
        }, nativeEvent => ({ nativeEvent, ...day })),
```

**Review by KaelWD — APPROVED** [review]
