### PR TITLE
fix(nested): prevent parent node activate firing for singleLeaf

### LINKED ISSUE #20946: [Bug Report][3.7.9] VTreeView update:activated will be fired if a non activateable node is activated
### Environment
**Vuetify Version:** 3.7.9
**Vue Version:** 3.4.27
**Browsers:** Edge 132.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Open the  link and the  dev console of the browser
2. click on a leave and you see that update:activated is fired with the id of the leaf
3. click on a node (at the name) with children (for instance "public") you see that update:activated is fired with the id last activated leaf

### Expected Behavior
in step 3  update:activated will not be fired, because there is no change

### Actual Behavior
In step 3 update:activated is fired with the id last activated leaf

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlVUtvozAQ/iteLrRSTE57idLuVtoeVyvttYlWDgzUrbGRbWiqiP++M4CBvJRDOUA832PG40deDpGz6fKpqpKmhmgVrT2UlRIeHjeasXXDvQVoJHzQkLGfdZUhuBKplw3+yB42kbCFYw+PLDXaGQWJMsVdPBLiBSPC/SbqHVYSMziUdd8xairQnZvU0kuh1OcfjASYuLwRqgZkeOkVBGTII3YYmgLAnbeYvfhEvpO6UMAViDyoKBvHJDTqJopTDRNnDXfK+FVlAVlU0qHLv2DSUU2s3USDpmuQxHmjRubI/EbEJJdU38hh7IAOvfYHi8tM8tyoDCynMmK2msdi1raj+bJ3v5ANlINH8qVc7mVMu0X5qW69PF5TRMOiYuAIxaFLraw8c+DrquPLsjLWswOzkLOW5daULMbNEhOddavu2dGqsQfi3r3EVb1TMo239xOxq3cgHPr6Xn2phh4ooYtaFMAp9j1e9IQ3N8DaZPDmprDRA5AiwGkcsDI7dSyFfc/Mx8iosjw0HkviOOQ7sx9RXcxRWaJFwPzez7HMpHUJ2nNTeyX1SNurUHZHg30KqsfaWT+6UxAa1guHtmAi2ujokRTSB9d2+J6RqDf/SpPV2N+b5GFhBhhreZUqs4DtHGo4Us2Vzgs/V15VnznMXfCKMAn2+NiHHuoVFXiOhcn0z3Y2miMXi85FQ+chwdex6+VsN/2kzmCf0B69aHcKTH6h6qsLQ0stC23suI1GV9x2N9d1J3agEpxqLotkOimjxxS6vjVE+o6bHdXTaZrpp+BVh7/PT79+PyclXv0n8il0VYwXy9fq/xRW419Q+n67gXQvrZf9hYdXXdQudK1U99r+B7ZOGfo=)

### PR DESCRIPTION
**Pull request by yuwu9145**
## Description

fixes #20946
## Markup:

```vue
<template>
  <v-treeview
    @update:activated="args => console.log('activated', args)"
    :items="items"
    :opened="initiallyOpen"
    item-value="title"
    activatable
    active-strategy="single-leaf"
    open-all
  >
    <template v-slot:prepend="{ item, isOpen }">
      <v-icon v-if="!item.file">
        {{ isOpen ? 'mdi-folder-open' : 'mdi-folder' }}
      </v-icon>
      <v-icon v-else> {{ files[item.file] }} </v-icon>
    </template>
  </v-treeview>
</template>

<script setup>
  import { ref } from 'vue'

  const initiallyOpen = ref(['public'])
  const files = ref({
    html: 'mdi-language-html5',
    js: 'mdi-nodejs',
    json: 'mdi-code-json',
    md: 'mdi-language-markdown',
    pdf: 'mdi-file-pdf-box',
    png: 'mdi-file-image',
    txt: 'mdi-file-document-outline',
    xls: 'mdi-file-excel',
  })
  const items = ref([
    {
      title: '.git',
    },
    {
      title: 'node_modules',
    },
    {
      title: 'public',
      children: [
        {
          title: 'static',
          children: [
            {
              title: 'logo.png',
              file: 'png',
            },
          ],
        },
        {
          title: 'favicon.ico',
          file: 'png',
        },
        {
          title: 'index.html',
          file: 'html',
        },
      ],
    },
    {
      title: '.gitignore',
      file: 'txt',
    },
    {
      title: 'babel.config.js',
      file: 'js',
    },
    {
      title: 'package.json',
      file: 'json',
    },
    {
      title: 'README.md',
      file: 'md',
    },
    {
      title: 'vue.config.js',
      file: 'js',
    },
    {
      title: 'yarn.lock',
      file: 'txt',
    },
  ])
</script>


```

### CODE REVIEW

File: packages/vuetify/src/util/helpers.ts [hunk 1]
```diff
@@ -378,11 +378,14 @@ export function filterInputAttrs (attrs: Record<string, unknown>) {
 
 /**
  * Returns the set difference of B and A, i.e. the set of elements in B but not in A
+ * A and B can be sets, but the function always returns the result as an array.
```
Comment (yuwu9145) [inline packages/vuetify/src/util/helpers.ts:381]: @KaelWD What do you think of this change?

Comment (KaelWD) [reply packages/vuetify/src/util/helpers.ts:381]: If they're already sets .has should be faster than .includes

Comment (yuwu9145) [reply packages/vuetify/src/util/helpers.ts]: Refactored to use `symmetricDifference` instead

Comment (KaelWD) [reply packages/vuetify/src/util/helpers.ts]: We can't use these yet unfortunately: https://caniuse.com/mdn-javascript_builtins_set_symmetricdifference
