### PR TITLE
fix(VIconBtn): Add Button Type 

### LINKED ISSUE #21634: [Bug Report][3.8.11] [VIconBtn] click in a form will trigger page reload
### Environment
**Vuetify Version:** 3.8.11
**Vue Version:** 3.5.17
**Browsers:** Edge 137.0.0.0
**OS:** Windows 10

### Steps to reproduce
click the <v-icon-btn> in a <v-form> will cause the page to reload

### Expected Behavior
not reload

### Actual Behavior
reload

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVUMsKwjAQ/JVlL1XogyKiSBTFz7Aeakwg2DzIo5fSfzdpxcfR2+zszszuXgZ0llYnY8o+MNwh8UyarvXs0CgA0hdcWznhqRJUq+LmFRxpJ+hj36BW54QahNSLhLyLoqVUB+UjWX20/8tI9c4n1ddisXTUCuPBMR/MNCuk0dbDAJZxGIFbLSGLN2VpHIAHRb3QCl7BiyUMc2dM5rNdNMIxx1W5LusNJrAt6xpz3naO5T+fmrnrE53GaWI=)

### PR DESCRIPTION
**Pull request by Haviles04**
## Description
Added type to button to prevent form submission
fixes #21634 

## Markup:
```
<template>
  <v-form>
    <v-icon-btn icon="mdi-account" @click="onClick" />
    <v-btn icon="mdi-account" @click="onClick" />
  </v-form>
</template>

<script setup>
  function onClick () {
    console.log('Clicked')
  }
</script>

```

### CODE REVIEW

File: packages/vuetify/src/labs/VIconBtn/VIconBtn.tsx [hunk 1]
```diff
@@ -161,6 +161,7 @@ export const VIconBtn = genericComponent<VIconBtnSlots>()({
 
       return (
         <props.tag
+          type={ props.tag === 'a' ? undefined : 'button' }
```
Comment (KaelWD) [inline packages/vuetify/src/labs/VIconBtn/VIconBtn.tsx]: tag could be router-link

```suggestion
          type={ props.tag === 'button' ? 'button' : undefined }
```

**Review by KaelWD — APPROVED** [review]
