### PR TITLE
Focus menu activator when clicked

### LINKED ISSUE #1817: Menu popup doesn't close on tab if activating with button
### Steps to reproduce
1. Click Menu Button 1
2. Hit Tab and notice the menu is still open

Behavior if you activate the menu with space and then tab is correct.

### Versions
Latest

### What is expected ?
Tabbing away from the menu should close it

### What is actually happening ?
Tab after click doesn't cause the menu to close

### Reproduction Link
https://codepen.io/jayblanchard/pen/mBPpdd?editors=1010

### PR DESCRIPTION
**Pull request by KaelWD**
Fixes #1817

### CODE REVIEW

**Comment by KaelWD** [comment]
wtf codebeat

File: src/components/VMenu/mixins/menu-activator.js [hunk 1]
```diff
@@ -21,11 +21,15 @@ export default {
   methods: {
     activatorClickHandler (e) {
       if (this.disabled) return
-      else if (this.openOnClick && !this.isActive) {
+      if (this.openOnClick && !this.isActive) {
+        this.$slots.activator[0].elm.focus()
```
Comment (johnleider) [inline src/components/VMenu/mixins/menu-activator.js]: What happens if this.$slots.activator is empty?

Comment (KaelWD) [reply src/components/VMenu/mixins/menu-activator.js]: Fixed, I didn't realise that there was an `activator` prop. We really need to figure out how to get mixins into the docs.
