### PR TITLE
fix(VDialog): remove console error on escape keypress

### LINKED ISSUE #7008: [Bug Report] VDialog - "[Vuetify] No activator found" error on escape keypress
### Versions and Environment
**Vuetify:** 1.5.12
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.103
**OS:** Windows 10

### Steps to reproduce
Open dialog with button click. Hit escape key. Note error in console.

### Expected Behavior
No error in console.

### Actual Behavior
Error message in console:

"[Vuetify] No activator found"

### Reproduction Link
<a href="https://codepen.io/anon/pen/gyodPp?editors=1011" target="_blank">https://codepen.io/anon/pen/gyodPp?editors=1011</a>

### PR DESCRIPTION
**Pull request by kuromoka**
## Description
removed `[Vuetify] No activator found` error on escape keypress when dialog is active.

## Motivation and Context
fixes #7008 

## How Has This Been Tested?
visually

## Markup:

<details>

```vue
<template>
  <v-app>
    <v-content>
      <v-layout row justify-center>
        <v-btn
          color="primary"
          dark
          @click.stop="dialog = true"
        >
          Open Dialog
        </v-btn>
        <v-dialog
          v-model="dialog"
          max-width="290"
        >
          <v-card>
            <v-card-title class="headline">Use Google's location service?</v-card-title>
            <v-card-text>
              Let Google help apps determine location. This means sending anonymous location data to Google, even when no apps are running.
            </v-card-text>
            <v-card-actions>
              <v-spacer />
              <v-btn
                color="green darken-1"
                flat="flat"
                @click="dialog = false"
              >
                Disagree
              </v-btn>
              <v-btn
                color="green darken-1"
                flat="flat"
                @click="dialog = false"
              >
                Agree
              </v-btn>
            </v-card-actions>
          </v-card>
        </v-dialog>
      </v-layout>
    </v-content>
  </v-app>
</template>

<script>
  export default {
    data () {
      return {
        dialog: false
      }
    }
  }
</script>
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

File: packages/vuetify/src/components/VDialog/VDialog.js [hunk 1]
```diff
@@ -188,7 +188,7 @@ export default {
       if (e.keyCode === keyCodes.esc && !this.getOpenDependents().length) {
         if (!this.persistent) {
           this.isActive = false
-          const activator = this.getActivator()
+          const activator = this.getActivator(e)
```
Comment (KaelWD) [inline packages/vuetify/src/components/VDialog/VDialog.js]: You can just remove the warning instead, this will try to focus the dialog again once it's closed.

Comment (kuromoka) [reply packages/vuetify/src/components/VDialog/VDialog.js]: fixed 6963943
