### PR TITLE
Fixes for button-group button state synching and tracking

### LINKED ISSUE #3136: [Bug Report] v-btn-toggle:  Error in beforeDestroy hook: 'TypeError: Cannot read property 'value' of undefined'
### Versions and Environment
**Vuetify:** 1.0.0-beta.5
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.119
**OS:** Windows 7

### Steps to reproduce
1. Add a `v-btn-toggle` with `mandatory` prop
2. Set the v-model to the value of the first button
3. Do something that triggers destroy of the component (e.g. router navigation, v-if conditional..)

See codepen.

### Expected Behavior
No errors thrown

### Actual Behavior
The following error is thrown on the console:

```
"[Vue warn]: Error in beforeDestroy hook: 'TypeError: Cannot read property 'value' of undefined'

found in

---> <VBtn>
       <VBtnToggle>
         <VContent>
           <VApp>
             <Root>"
```

### Reproduction Link
[https://codepen.io/anon/pen/oEgxGr](https://codepen.io/anon/pen/oEgxGr)

### Other comments
From what I could find, it only happens when `mandatory` prop is used and the `value` assigned to the first button is set as the initial `v-model` value.

### PR DESCRIPTION
**Pull request by Phlow2001**
## Description
This resolves #3136 and also fixes internal and external state tracking when doing things like v-if with buttons within the button group.  2 new warnings were added to assist users with invalid usage.

## Motivation and Context

Fixes #3136 

## How Has This Been Tested?

New tests added, and manual testing using the following Playground

## Markup:

```html
<template>
  <Boilerplate>
    <v-layout row>
      <v-btn @click="showToggle = !showToggle">{{ showToggle ? 'Hide' : 'Show' }} button toggle</v-btn>
      <v-btn @click="showBtn = !showBtn">{{ showBtn ? 'Hide' : 'Show' }} buttons</v-btn>
    </v-layout>
    <v-layout row>
      <v-btn-toggle v-if="showToggle" mandatory multiple v-model="toggle">
        <v-btn v-if="showBtn" value="val1">Val 1</v-btn>
        <v-btn value="val2">Val 2</v-btn>
        <v-btn v-if="showBtn" value="val3">Val 3</v-btn>
        <v-btn value="val4">Val 4</v-btn>
        <v-btn v-if="showBtn" value="val5">Val 5</v-btn>
      </v-btn-toggle>
    </v-layout>
    <v-layout row>
      <v-btn-toggle v-if="showToggle" mandatory v-model="toggle2">
        <v-btn v-if="showBtn" value="val1">Val 1</v-btn>
        <v-btn value="val2">Val 2</v-btn>
        <v-btn v-if="showBtn" value="val3">Val 3</v-btn>
        <v-btn value="val4">Val 4</v-btn>
        <v-btn v-if="showBtn" value="val5">Val 5</v-btn>
      </v-btn-toggle>
    </v-layout>
  </Boilerplate>
</template>

<script>
  export default {
    data: () => ({
      showToggle: true,
      showBtn: true,
      toggle: [],
      toggle2: 'val1'
    })
  }
</script>
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have created a PR in the [documentation](https://github.com/vuetifyjs/vuetifyjs.com) with the necessary changes.

### CODE REVIEW

File: src/mixins/button-group.js [hunk 1]
```diff
@@ -45,36 +53,72 @@ export default {
...
+      this.ensureMandatoryInvariant(selectedCount > 0)
+      this.updateAllValues && this.updateAllValues()
+    },
+    ensureMandatoryInvariant (hasSelectedAlready) {
       // Preserve the mandatory invariant
-      if (wasSelected &&
-          this.mandatory &&
-          this.buttons.every((_, i) => !this.isSelected(i)) &&
-          this.listeners.length > 0) {
+      if (this.mandatory && !hasSelectedAlready) {
```
Comment (johnleider) [inline src/mixins/button-group.js]: Change to `if (!this.mandatory || !hasSelectedAlready) return`

File: src/mixins/button-group.js [hunk 2]
```diff
@@ -45,36 +53,72 @@ export default {
...
       }
     }
   },
 
   mounted () {
     this.update()
+  },
+
+  beforeDestroy () {
+    this.destroying = true
```
Comment (johnleider) [inline src/mixins/button-group.js]: change to `isDestroying`

File: src/mixins/button-group.js [hunk 3]
```diff
@@ -45,36 +53,72 @@ export default {
...
+    },
+    redoRegistrations (buttonToUnregister) {
+      let selectedCount = 0
+
+      const buttons = []
+      for (let index = 0; index < this.buttons.length; ++index) {
+        const button = this.buttons[index]
+        if (button !== buttonToUnregister) {
+          buttons.push(button)
+          if (this.isSelected(index)) {
```
Comment (johnleider) [inline src/mixins/button-group.js]: would it look terrible if this was:
`this.isSelected(index) && ++selectedCount`

File: src/mixins/button-group.js [hunk 4]
```diff
@@ -8,7 +9,14 @@ export default {
...
     return {
       buttons: [],
-      listeners: []
+      listeners: [],
+      destroying: false
+    }
+  },
+
+  watch: {
+    buttons () {
```
Comment (johnleider) [inline src/mixins/button-group.js]: change to:
```
watch: {
  buttons: 'update'
}
```

File: src/mixins/button-group.js [hunk 5]
```diff
@@ -45,36 +53,72 @@ export default {
...
-      this.buttons.splice(index, 1)
-      this.listeners.splice(index, 1)
+        button.$off('click', this.listeners[index])
+      }
 
+      this.buttons = []
+      this.listeners = []
+
+      for (let index = 0; index < buttons.length; ++index) {
+        const button = buttons[index]
```
Comment (johnleider) [inline src/mixins/button-group.js]: does this need to be declared or can we simply pass `buttons[index]` to `this.register`?

File: src/components/VBtnToggle/VBtnToggle.js [hunk 6]
```diff
@@ -73,6 +74,29 @@ export default {
...
+        }
+      }
+
+      this.$emit('change', items)
+    }
+  },
+
+  created () {
+    if (this.multiple && !Array.isArray(this.inputValue)) {
+      consoleWarn('v-btn-toggle model must be bound to an array if the multiple property is true.')
```
Comment (johnleider) [inline src/components/VBtnToggle/VBtnToggle.js]: I will have to check, but I think we have a default way of showing components in the error messages, such as:

```consoleWarn('`v-btn-toggle` model must be...')```

File: src/components/VBtnToggle/VBtnToggle.js [hunk 7]
```diff
@@ -73,6 +74,29 @@ export default {
       }
 
       this.$emit('change', items)
+    },
+    updateAllValues () {
+      if (!this.multiple) {
```
Comment (johnleider) [inline src/components/VBtnToggle/VBtnToggle.js]: can we make this one line

File: src/components/VBtnToggle/VBtnToggle.js (hunk 6 above)
Comment (jacekkarczmarczyk) [reply src/components/VBtnToggle/VBtnToggle.js]: Yes, pass `this` as a second arg of `consoleWarn` and it will show the name of the component

File: src/mixins/button-group.js [hunk 8]
```diff
@@ -45,36 +51,70 @@ export default {
...
       this.buttons.push(button)
       this.listeners.push(this.updateValue.bind(this, index))
       button.$on('click', this.listeners[index])
     },
-    unregister (button) {
-      const index = this.buttons.indexOf(button)
-      if (index === -1) {
+    unregister (buttonToUnregister) {
+      // Basic cleanup if we're destroying
+      if (this.destroying) {
```
Comment (johnleider) [inline src/mixins/button-group.js]: This should be isDestroying
