### PR TITLE
Focus v-select's internal input when focus() is called

### LINKED ISSUE #1819: v-select function focus() does not work
### Steps to reproduce
1) create v-select with autocomplete
2) call focus()

### Versions
0.15.7

### What is expected ?
keyboard focus into select

### What is actually happening ?
select highlighted, but no focused

### Reproduction Link
https://codepen.io/anon/pen/gGrezV?editors=1010#0

Not work after commit e96ca54317995eaf56eef53cd6724a8bad57b2e2
src/components/VSelect/VSelect.vue
line 369

### PR DESCRIPTION
**Pull request by KaelWD**
Fixes #1819

### CODE REVIEW

File: src/components/VSelect/VSelect.js [hunk 1]
```diff
@@ -248,7 +248,7 @@ export default {
     },
     isBooted () {
       this.$nextTick(() => {
-        if (this.content) {
+        if (this.content instanceof EventTarget) {
```
Comment (KaelWD) [inline src/components/VSelect/VSelect.js]: `this.content` is always an object, so this was basically doing `if (true) {`
