### PR TITLE
fix(VDataTable): respect hide-default-header prop on mobile

### LINKED ISSUE #8774: [Bug Report] Data table's hide-default-header not working on mobile viewport
### Environment
**Vuetify Version:** 2.0.11
**Vue Version:** 2.6.10
**Browsers:** Firefox 68.0
**OS:** Ubuntu undefined

### Steps to reproduce
1. Created a data table with headers and some items data
2. Add hide-default-header to the data table
3. Confirm the headers are gone
4. Change view port to mobile on Firefox
5. The headers appear again because you changed the viewport

### Expected Behavior
Headers are kept hidden even on mobile when hide-default-header is true

### Actual Behavior
Headers are being displayed on mobile

### Reproduction Link
<a href="https://codepen.io/kinow/pen/XWrgpQz" target="_blank">https://codepen.io/kinow/pen/XWrgpQz</a>

### PR DESCRIPTION
**Pull request by IwalkAlone**
## Description
Don't render the inline column headers on mobile when hide-default-header is specified on the VDataTable. Fixes #8774

## Motivation and Context
Fixes #8774

## How Has This Been Tested?
unit, visually

## Markup:

<details>

```vue
<template>
  <v-container>
    <h1>Table below</h1>
    <v-data-table
      :headers="headers"
      :items="names"
      :items-per-page="5"
      class="elevation-1"
    ></v-data-table>
  </v-container>
</template>

<script>
export default {
  data: () => ({
    headers: [
      {
        text: "Name",
        value: "name",
      },
    ],
    names: [
      {
        name: "Oscar",
      },
      {
        name: "Orlando",
      },
      {
        name: "Osvaldo",
      },
    ],
  }),
};
</script>
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

File: packages/vuetify/src/components/VDataTable/MobileRow.ts [hunk 1]
```diff
@@ -11,6 +11,7 @@ export default Vue.extend({
     headers: Array as PropType<DataTableHeader[]>,
     item: Object,
     rtl: Boolean,
+    hideDefaultHeader: Boolean,
```
Comment (Kawacrepe) [inline packages/vuetify/src/components/VDataTable/MobileRow.ts:14]: Can you please put `hideDefaultHeader` below `headers` to respect alphabetical order

Comment (johnleider) [reply packages/vuetify/src/components/VDataTable/MobileRow.ts:14]: Leave this as a review. It let's me know that we are waiting on something and I can skip over it.

Comment (IwalkAlone) [reply packages/vuetify/src/components/VDataTable/MobileRow.ts]: @Kawacrepe Fixed

Comment (Kawacrepe) [reply packages/vuetify/src/components/VDataTable/MobileRow.ts]: Thanks you
