### PR TITLE
fix(VDatePicker): weeknumber calculation refactored to fix bug

### LINKED ISSUE #9764: [Bug Report] v-date-picker displays the wrong week number when first-day-of-week="1"
### Environment
**Vuetify Version:** 2.1.11
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.97
**OS:** Windows 10

### Steps to reproduce
Using v-date-picker with the following attr: `show-week` and `first-day-of-week="1"`

Set the date to e.g. `2017-08-17`, the week number is displayed is `34`. Expected: `33`.

v-date-picker week number bug

### Expected Behavior
Week number `33` displayed for the selected date `2017-08-17`

### Actual Behavior
Week number `34` is displayed for the selected date `2017-08-17`

### Reproduction Link
<a href="https://codepen.io/knekk/pen/oNNOZMd" target="_blank">https://codepen.io/knekk/pen/oNNOZMd</a>

### Other comments
It seems like the bug is only occuring for certain years e.g. `2017`

### PR DESCRIPTION
**Pull request by abbierwolf**
Instead of calculating only the weeknumber for the first week shown and increment it, it is now
calcuted for every week.

fix #9764

## Description
fixes #9764

## Motivation and Context
https://github.com/vuetifyjs/vuetify/issues/9764

## How Has This Been Tested?
unit | visually

## Markup:
<details>

```vue
<template>
  <v-container>
    <!--  -->
    <v-date-picker
      show-week
      first-day-of-week="1"
    ></v-date-picker>
  </v-container>
</template>

<script>
export default {
  data: () => ({
    //
  })
};
</script>

```
</details>

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by abbierwolf** [comment]
> Need to clean up the code styling. I'm surprised it passed lint. More information is located in our [Coding Guidelines](https://www.notion.so/vuetify/Coding-Guidelines-86c96a7da947421bb88515a966e71df0).
I applied all coding guidelines I could find in the document. I could not find tslint or eslint configuration to make sure I found all the issues.

**Comment by abbierwolf** [comment]
@johnleider Travis CI had problems yesterday can you trigger a rebuild? Or is this not needed?

**Comment by johnleider** [comment]
@jacekkarczmarczyk Please leave that in a review.

File: packages/vuetify/src/components/VDatePicker/VDatePickerDateTable.ts [hunk 1]
```diff
@@ -48,29 +52,21 @@ export default mixins(
...
-      const offset = (
-        this.displayedYear +
-        ((this.displayedYear - 1) >> 2) -
-        Math.floor((this.displayedYear - 1) / 100) +
-        Math.floor((this.displayedYear - 1) / 400) -
-        Number(this.firstDayOfWeek)
-      ) % 7 // https://en.wikipedia.org/wiki/Zeller%27s_congruence
-      return Math.floor((dayOfYear + offset) / 7) + 1
+    getWeekNumber (dayInMonth: number) {
+      console.log(parseInt(this.firstDayOfYear))
```
Comment (johnleider) [inline packages/vuetify/src/components/VDatePicker/VDatePickerDateTable.ts]: remove dev code

File: packages/vuetify/src/components/VDatePicker/VDatePickerDateTable.ts [hunk 2]
```diff
@@ -48,29 +52,21 @@ export default mixins(
...
+
+      return determineWeeknumber(this.displayedYear, this.displayedMonth, dayInMonth,
```
Comment (johnleider) [inline packages/vuetify/src/components/VDatePicker/VDatePickerDateTable.ts]: This is unreadable, break up into new lines

File: packages/vuetify/src/components/VDatePicker/VDatePickerDateTable.ts [hunk 3]
```diff
@@ -99,7 +94,7 @@ export default mixins(
         if (rows.length % (this.showWeek ? 8 : 7) === 0) {
           children.push(this.genTR(rows))
           rows = []
-          day < daysInMonth && this.showWeek && rows.push(this.genWeekNumber(weekNumber++))
+          day < daysInMonth && this.showWeek && rows.push(this.genWeekNumber(this.getWeekNumber(day + 7)))
```
Comment (johnleider) [inline packages/vuetify/src/components/VDatePicker/VDatePickerDateTable.ts]: Do not use &&

File: packages/vuetify/src/components/VDatePicker/VDatePickerDateTable.ts (hunk 1 above)
Comment (abbierwolf) [reply packages/vuetify/src/components/VDatePicker/VDatePickerDateTable.ts]: Removed lline

File: packages/vuetify/src/components/VDatePicker/VDatePickerDateTable.ts (hunk 2 above)
Comment (abbierwolf) [reply packages/vuetify/src/components/VDatePicker/VDatePickerDateTable.ts]: Every argument is now on a single line

File: packages/vuetify/src/components/VDatePicker/VDatePickerDateTable.ts (hunk 3 above)
Comment (abbierwolf) [reply packages/vuetify/src/components/VDatePicker/VDatePickerDateTable.ts]: Rewritten to use if statement. && was used in the original implementation that's why I left it

File: packages/vuetify/src/components/VDatePicker/VDatePicker.ts [hunk 4]
```diff
@@ -65,6 +65,10 @@ export default mixins(
       type: [String, Number],
       default: 0,
     },
+    firstDayOfYear: {
```
Comment (jacekkarczmarczyk) [inline packages/vuetify/src/components/VDatePicker/VDatePicker.ts]: I don't quite get the idea of this prop... Why first day of the year is thursday by default? When it could be/should be changed? What's the practical example of usage?

File: packages/vuetify/src/components/VDatePicker/VDatePickerDateTable.ts (hunk 2 above)
Comment (jacekkarczmarczyk) [reply packages/vuetify/src/components/VDatePicker/VDatePickerDateTable.ts]: Not really, there are 5 arguments but only 2 lines

File: packages/vuetify/src/components/VDatePicker/util/index.ts [hunk 5]
```diff
@@ -1,9 +1,11 @@
 import createNativeLocaleFormatter from './createNativeLocaleFormatter'
 import monthChange from './monthChange'
 import pad from './pad'
+import determineWeeknumber from './determineWeeknumber'
```
Comment (jacekkarczmarczyk) [inline packages/vuetify/src/components/VDatePicker/util/index.ts]: capitalize number (`determineWeekNumber`), here and in numerous other places

File: packages/vuetify/src/components/VDatePicker/util/__tests__/determineWeeknumber.spec.ts [hunk 6]
```diff
@@ -0,0 +1,30 @@
+import determineWeeknumber from '../determineWeeknumber'
+
+describe('VDatePicker/util/determineWeeknumber.ts', () => {
+  it('should return 53 as weeknumber', () => {
```
Comment (jacekkarczmarczyk) [inline packages/vuetify/src/components/VDatePicker/util/__tests__/determineWeeknumber.spec.ts]: i don't think it's necessary to split examples into separate tests, maybe just merge them together and call it `it('should return valid week number', ...)`
Also if the `firstDayOfWeek` argument matters there could be test showing different week numbers for different values of this argument

File: packages/vuetify/src/components/VDatePicker/util/determineWeeknumber.ts [hunk 7]
```diff
@@ -0,0 +1,58 @@
...
+    weeknumber = week
+  }
+
+  return weeknumber
+}
+
+function weeksInYear (year: number, firstDayOfWeek: number, firstDayOfYear: number) {
+  const weekOffset = firstWeekOffset(year, firstDayOfWeek, firstDayOfYear)
+  const weekOffsetNext = firstWeekOffset(year + 1, firstDayOfWeek, firstDayOfYear)
+  const daysInYear = (year % 4 === 0 && year % 100 !== 0) || year % 400 === 0 ? 366 : 365
```
Comment (jacekkarczmarczyk) [inline packages/vuetify/src/components/VDatePicker/util/determineWeeknumber.ts]: we have `isLeapYear` method in `VCalendar/util/timestamp.ts`, it could be extracted to common utils and used here

File: packages/vuetify/src/components/VDatePicker/util/determineWeeknumber.ts [hunk 8]
```diff
@@ -0,0 +1,58 @@
...
+  } else {
+    date = new Date(Date.UTC(year, month, day))
+  }
+
+  return date
+}
+
+function firstWeekOffset (year: number, firstDayOfWeek: number, firstDayOfYear: number) {
+  const fwd = 7 + firstDayOfWeek - firstDayOfYear
+  const fwdlw = (7 + createUTCDate(year, 0, fwd).getUTCDay() - firstDayOfWeek) % 7
```
Comment (jacekkarczmarczyk) [inline packages/vuetify/src/components/VDatePicker/util/determineWeeknumber.ts]: give more meaningful names

File: packages/vuetify/src/components/VDatePicker/util/determineWeeknumber.ts [hunk 9]
```diff
@@ -0,0 +1,58 @@
+const hourInMilliseconds = 60 * 1000
+const dayInMilliseconds = 24 * 60 * hourInMilliseconds
```
Comment (jacekkarczmarczyk) [inline packages/vuetify/src/components/VDatePicker/util/determineWeeknumber.ts]: `millisecondsInHour`, `millisecondsInDay`

File: packages/vuetify/src/components/VDatePicker/util/determineWeeknumber.ts [hunk 10]
```diff
@@ -0,0 +1,58 @@
...
+}
+
+function dayOfYear (determineDate: Date, newYear: Date) {
+  return Math.floor((determineDate.getTime() - newYear.getTime() -
+    (determineDate.getTimezoneOffset() - newYear.getTimezoneOffset()) * hourInMilliseconds) / dayInMilliseconds) + 1
+}
+
+function weekOfYear (year: number, month: number, day: number, firstDayOfWeek: number, firstDayOfYear: number) {
+  const weekOffset = firstWeekOffset(year, firstDayOfWeek, firstDayOfYear)
+  const week = Math.floor((dayOfYear(createUTCDate(year, month, day), createUTCDate(year)) - weekOffset - 1) / 7) + 1
```
Comment (jacekkarczmarczyk) [inline packages/vuetify/src/components/VDatePicker/util/determineWeeknumber.ts]:
```suggestion
  const week = Math.ceil((dayOfYear(createUTCDate(year, month, day), createUTCDate(year)) - weekOffset) / 7)
```

File: packages/vuetify/src/components/VDatePicker/util/determineWeeknumber.ts [hunk 11]
```diff
@@ -0,0 +1,58 @@
...
+
+  if (week < 1) {
+    weeknumber = week + weeksInYear(year - 1, firstDayOfWeek, firstDayOfYear)
+  } else if (week > weeksInYear(year, firstDayOfWeek, firstDayOfYear)) {
+    weeknumber = week - weeksInYear(year, firstDayOfWeek, firstDayOfYear)
+  } else {
+    weeknumber = week
+  }
+
+  return weeknumber
```
Comment (jacekkarczmarczyk) [inline packages/vuetify/src/components/VDatePicker/util/determineWeeknumber.ts]:
```suggestion
  if (week < 1) {
    return week + weeksInYear(year - 1, firstDayOfWeek, firstDayOfYear)
  } else if (week > weeksInYear(year, firstDayOfWeek, firstDayOfYear)) {
    return week - weeksInYear(year, firstDayOfWeek, firstDayOfYear)
  } else {
    return week
  }
```

File: packages/vuetify/src/components/VDatePicker/util/determineWeeknumber.ts [hunk 12]
```diff
@@ -0,0 +1,58 @@
...
+}
+
+function firstWeekOffset (year: number, firstDayOfWeek: number, firstDayOfYear: number) {
+  const fwd = 7 + firstDayOfWeek - firstDayOfYear
+  const fwdlw = (7 + createUTCDate(year, 0, fwd).getUTCDay() - firstDayOfWeek) % 7
+
+  return -fwdlw + fwd - 1
+}
+
+function dayOfYear (determineDate: Date, newYear: Date) {
```
Comment (jacekkarczmarczyk) [inline packages/vuetify/src/components/VDatePicker/util/determineWeeknumber.ts]: `newYear` can be calculated from `date` (`newYear = createUTCDate(date.getFullYear())`)

Also does this code works fine with changing timezones? I think it's safer to use the previous method https://github.com/vuetifyjs/vuetify/pull/10926/files#diff-fad712b1d24c3d982c0bd796f2ee28d1L60 (and provide year/month/day as arguments instead of Date object)

File: packages/vuetify/src/components/VDatePicker/util/determineWeeknumber.ts [hunk 13]
```diff
@@ -0,0 +1,58 @@
...
+
+function weeksInYear (year: number, firstDayOfWeek: number, firstDayOfYear: number) {
+  const weekOffset = firstWeekOffset(year, firstDayOfWeek, firstDayOfYear)
+  const weekOffsetNext = firstWeekOffset(year + 1, firstDayOfWeek, firstDayOfYear)
+  const daysInYear = (year % 4 === 0 && year % 100 !== 0) || year % 400 === 0 ? 366 : 365
+
+  return (daysInYear - weekOffset + weekOffsetNext) / 7
+}
+
+export default function determineWeeknumber (year: number, month: number, day: number, firstDayOfWeek: number, firstDayOfYear: number) {
```
Comment (jacekkarczmarczyk) [inline packages/vuetify/src/components/VDatePicker/util/determineWeeknumber.ts]: how about assuming here that year/month/day are always valid and moving this `createUTCDate` thing to `VDatePickerDateTable.ts`?

File: packages/vuetify/src/components/VDatePicker/VDatePicker.ts (hunk 4 above)
Comment (abbierwolf) [reply packages/vuetify/src/components/VDatePicker/VDatePicker.ts]: I added the prefix locale to indicate it is a locale determined property. In the US first day of week  is Sunday and the 1st of January is always in week 1. With the ISO 8601 standard the first day of the week is Monday and the week containing 4th of January determines week 1. So localeFirstDayOfYear should be 4 then.

File: packages/vuetify/src/components/VDatePicker/util/index.ts (hunk 5 above)
Comment (abbierwolf) [reply packages/vuetify/src/components/VDatePicker/util/index.ts]: I moved the content of this file to the new dateTimeUtils.js file in the global util directory and renamed it to weekNumber.

File: packages/vuetify/src/components/VDatePicker/util/__tests__/determineWeeknumber.spec.ts (hunk 6 above)
Comment (abbierwolf) [reply packages/vuetify/src/components/VDatePicker/util/__tests__/determineWeeknumber.spec.ts]: Combined all tests to one case

File: packages/vuetify/src/components/VDatePicker/util/determineWeeknumber.ts (hunk 7 above)
Comment (abbierwolf) [reply packages/vuetify/src/components/VDatePicker/util/determineWeeknumber.ts]: Moved isLeapYear of VCalendar/util/timestamp.ts to global util file dateTimeUtils.ts.

File: packages/vuetify/src/components/VDatePicker/util/determineWeeknumber.ts (hunk 9 above)
Comment (abbierwolf) [reply packages/vuetify/src/components/VDatePicker/util/determineWeeknumber.ts]: Refactored dayOfYear method without the use of the constants so removed them

File: packages/vuetify/src/components/VDatePicker/util/determineWeeknumber.ts (hunk 10 above)
Comment (abbierwolf) [reply packages/vuetify/src/components/VDatePicker/util/determineWeeknumber.ts]: Refactored dayOfYear method

File: packages/vuetify/src/components/VDatePicker/util/determineWeeknumber.ts (hunk 11 above)
Comment (abbierwolf) [reply packages/vuetify/src/components/VDatePicker/util/determineWeeknumber.ts]: Refactored to return directly instead of assigning value to week.

File: packages/vuetify/src/components/VDatePicker/util/determineWeeknumber.ts (hunk 12 above)
Comment (abbierwolf) [reply packages/vuetify/src/components/VDatePicker/util/determineWeeknumber.ts]: Refactored dayOfYear method

File: packages/vuetify/src/components/VDatePicker/util/determineWeeknumber.ts (hunk 13 above)
Comment (abbierwolf) [reply packages/vuetify/src/components/VDatePicker/util/determineWeeknumber.ts]: Removed creation of UTC date

File: packages/vuetify/src/components/VDatePicker/VDatePicker.ts [hunk 14]
```diff
@@ -65,6 +65,10 @@ export default mixins(
       type: [String, Number],
       default: 0,
     },
+    localeFirstDayOfYear: {
```
Comment (johnleider) [inline packages/vuetify/src/components/VDatePicker/VDatePicker.ts:68]: Order alpha.

File: packages/vuetify/src/components/VDatePicker/VDatePicker.ts [hunk 15]
```diff
@@ -384,6 +388,7 @@ export default mixins(
           events: this.events,
           eventColor: this.eventColor,
           firstDayOfWeek: this.firstDayOfWeek,
+          localeFirstDayOfYear: this.localeFirstDayOfYear,
```
Comment (johnleider) [inline packages/vuetify/src/components/VDatePicker/VDatePicker.ts:391]: Order alpha.

File: packages/vuetify/src/components/VDatePicker/VDatePickerDateTable.ts [hunk 16]
```diff
@@ -5,6 +5,7 @@ import DatePickerTable from './mixins/date-picker-table'
 import { pad, createNativeLocaleFormatter, monthChange } from './util'
 import { createRange } from '../../util/helpers'
 import mixins from '../../util/mixins'
+import { weekNumber } from '../../util/dateTimeUtils'
```
Comment (johnleider) [inline packages/vuetify/src/components/VDatePicker/VDatePickerDateTable.ts:8]: Move to Line 5 and push the rest down.

File: packages/vuetify/src/components/VDatePicker/VDatePickerDateTable.ts [hunk 17]
```diff
@@ -47,30 +52,25 @@ export default mixins(
...
-      }
-      const offset = (
-        this.displayedYear +
-        ((this.displayedYear - 1) >> 2) -
-        Math.floor((this.displayedYear - 1) / 100) +
-        Math.floor((this.displayedYear - 1) / 400) -
-        Number(this.firstDayOfWeek)
-      ) % 7 // https://en.wikipedia.org/wiki/Zeller%27s_congruence
-      return Math.floor((dayOfYear + offset) / 7) + 1
+    getWeekNumber (dayInMonth: number) {
```
Comment (johnleider) [inline packages/vuetify/src/components/VDatePicker/VDatePickerDateTable.ts:68]: Re-format this similar to:

```typescript

return weekNumber(
  arg1,
  arg2,
  arg3,
)
```

File: packages/vuetify/src/components/VDatePicker/VDatePickerDateTable.ts [hunk 18]
```diff
@@ -99,7 +100,9 @@ export default mixins(
         if (rows.length % (this.showWeek ? 8 : 7) === 0) {
           children.push(this.genTR(rows))
           rows = []
-          day < daysInMonth && this.showWeek && rows.push(this.genWeekNumber(weekNumber++))
+          if (this.showWeek && day < daysInMonth) {
```
Comment (johnleider) [inline packages/vuetify/src/components/VDatePicker/VDatePickerDateTable.ts:103]:
```suggestion
          if ((this.showWeek && day) < daysInMonth) {
```

File: packages/vuetify/src/util/__tests__/dateTimeUtils.spec.ts [hunk 19]
```diff
@@ -0,0 +1,27 @@
+import { weekNumber } from '../dateTimeUtils'
+
+describe('/util/dateTimeUtils.ts', () => {
+  it('should return correct weeknumber', () => {
+    expect(weekNumber(2010, 0, 1, 1, 4)).toBe(53)
```
Comment (johnleider) [inline packages/vuetify/src/util/__tests__/dateTimeUtils.spec.ts:5]: Could this be a collection of iterated arrays to reduce the spec size?

```ts
it('should return correct weeknumber', () => {
  for (const [val, ...args] of [
    [53, 2010, 0, 1, 1, 4],
    [53, 2016, 0, 1, 0, 4],
    ...etc
  ]) {
    expect(weekNumber(...args).toBe(val)
  }
})
```

File: packages/vuetify/src/util/dateTimeUtils.ts [hunk 20]
```diff
@@ -0,0 +1,56 @@
+const DAY_OF_YEAR_PER_FIRST_OF_MONTH = [0, 31, 59, 90, 120, 151, 181, 212, 243, 273, 304, 334]
```
Comment (johnleider) [inline packages/vuetify/src/util/dateTimeUtils.ts:1]: This needs a style / readability pass.

File: packages/vuetify/src/components/VDatePicker/VDatePicker.ts (hunk 14 above)
Comment (abbierwolf) [reply packages/vuetify/src/components/VDatePicker/VDatePicker.ts:68]: Do you mean that the props should be ordered in alpabetical order?

File: packages/vuetify/src/util/__tests__/dateTimeUtils.spec.ts (hunk 19 above)
Comment (nekosaur) [reply packages/vuetify/src/util/__tests__/dateTimeUtils.spec.ts:5]: https://jestjs.io/docs/en/api#testeachtablename-fn-timeout

File: packages/vuetify/src/components/VDatePicker/VDatePicker.ts (hunk 14 above)
Comment (abbierwolf) [reply packages/vuetify/src/components/VDatePicker/VDatePicker.ts:70]: Ordering in alpha order done

File: packages/vuetify/src/components/VDatePicker/VDatePicker.ts (hunk 15 above)
Comment (abbierwolf) [reply packages/vuetify/src/components/VDatePicker/VDatePicker.ts]: Ordering in alpha order done

File: packages/vuetify/src/components/VDatePicker/VDatePickerDateTable.ts (hunk 16 above)
Comment (abbierwolf) [reply packages/vuetify/src/components/VDatePicker/VDatePickerDateTable.ts]: Moved the line up

File: packages/vuetify/src/components/VDatePicker/VDatePickerDateTable.ts (hunk 17 above)
Comment (abbierwolf) [reply packages/vuetify/src/components/VDatePicker/VDatePickerDateTable.ts:68]: First argument is on its own line

File: packages/vuetify/src/components/VDatePicker/VDatePickerDateTable.ts (hunk 18 above)
Comment (abbierwolf) [reply packages/vuetify/src/components/VDatePicker/VDatePickerDateTable.ts]: Added extra () to make correct if check

File: packages/vuetify/src/util/__tests__/dateTimeUtils.spec.ts (hunk 19 above)
Comment (abbierwolf) [reply packages/vuetify/src/util/__tests__/dateTimeUtils.spec.ts]: Used suggested test.each

File: packages/vuetify/src/util/dateTimeUtils.ts (hunk 20 above)
Comment (abbierwolf) [reply packages/vuetify/src/util/dateTimeUtils.ts]: Restored array on its original position in method body. But I couldn't find anything in the coding guidelines which I could use for this. Maybe you can point me out where I can find it.

File: packages/vuetify/src/components/VDatePicker/VDatePickerDateTable.ts (hunk 17 above)
Comment (johnleider) [reply packages/vuetify/src/components/VDatePicker/VDatePickerDateTable.ts:68]: This was meant for line 69

File: packages/vuetify/src/util/dateTimeUtils.ts [hunk 21]
```diff
@@ -0,0 +1,56 @@
...
+
+function createUTCDate (year: number, month = 0, day = 1) {
+  var date
```
Comment (johnleider) [inline packages/vuetify/src/util/dateTimeUtils.ts:2]: should be `let`

Comment (abbierwolf) [reply packages/vuetify/src/util/dateTimeUtils.ts]: Changed var to let

File: packages/vuetify/src/components/VDatePicker/VDatePickerDateTable.ts [hunk 22]
```diff
@@ -47,30 +52,26 @@ export default mixins(
...
-        Number(this.firstDayOfWeek)
-      ) % 7 // https://en.wikipedia.org/wiki/Zeller%27s_congruence
-      return Math.floor((dayOfYear + offset) / 7) + 1
+    getWeekNumber (dayInMonth: number) {
+      return weekNumber(
+        this.displayedYear,
+        this.displayedMonth,
+        dayInMonth,
+        parseInt(this.firstDayOfWeek),
+        parseInt(this.localeFirstDayOfYear))
```
Comment (johnleider) [inline packages/vuetify/src/components/VDatePicker/VDatePickerDateTable.ts:74]: second parenthesis should be on next line
