### PR TITLE
fix(VCombobox): menu position may not update if multiple

### LINKED ISSUE #5082: [Bug Report] Multiple combobox doesn't adjust the top style of suggestions
### Versions and Environment
**Vuetify:** 1.2.3
**Vue:** 2.5.17
**Browsers:** Chrome 68 / Safari 11.1
**OS:** Windows 10 / Mac OS 10.13

### Steps to reproduce
Scroll the window to a position where suggestions appear above the input.
Search for a unique result or type some nonsense into the search field.

### Expected Behavior
Suggestions are displayed above the input.

### Actual Behavior
Big gap between suggestions and input.

### Reproduction Link
https://codepen.io/joke1/pen/zJjOMJ

### PR DESCRIPTION
**Pull request by dima74**
## Description

There is method `onInternalSearchChanged` in `v-combobox`. If combobox has `multiple` prop, then this method may return earlier than method `updateMenuDimensions` is called. It is the reason for issue #5082. This pr change `onInternalSearchChanged` method, so now `updateMenuDimensions` will always be called.

## Motivation and Context

Fix #5082

## How Has This Been Tested?

visually

## Markup:

<details>

```vue
<template>
  <v-layout
    class="wrapper"
    align-end
  >
    <v-combobox
      chips
      multiple
      v-model="model"
      :items="items"
    />

    <v-spacer />

    <v-combobox
      chips
      multiple
      v-model="model"
      :items="items"
      :delimiters="[',']"
    />
  </v-layout>
</template>

<style scoped>
  .wrapper {
    height: 95vh;
  }
</style>

<script>
  export default {
    data: () => ({
      items: ['Gaming', 'Programming', 'Vue', 'Vuetify'],
      model: ['Vuetify'],
    }),
  };
</script>
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

File: packages/vuetify/src/components/VCombobox/VCombobox.js [hunk 1]
```diff
@@ -60,10 +60,10 @@ export default {
         this.delimiters
```
Comment (KaelWD) [inline packages/vuetify/src/components/VCombobox/VCombobox.js]:
```suggestion
         this.delimiters.length
```

It defaults to an array, so the current condition is always true
