### PR TITLE
fix(VBtn): accept value prop for underlying DOM element 

### LINKED ISSUE #16188: [Bug Report][3.0.2] v-btn's value props does not works
### Environment
**Vuetify Version:** 3.0.2
**Last working version:** 3.0.2
**Vue Version:** 3.2.45
**Browsers:** Chrome 107.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Put a value prop in v-btn.
2. Assign a method to the `click` event to display its own value (`e.target.value`) attribute as an `alert`.
3. When clicked, it becomes undefined and does not contain the value defined in `value` props.

### Expected Behavior
The value of the value prop is displayed

https://next.vuetifyjs.com/en/api/v-btn/#props-value

### Actual Behavior
The value of the `value` prop is ignored. 
When I checked the DOM in the console log, the value attribute was not included.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9UstOwzAQ/JXFl7ZSYyMel9JWhRN/wAFzSJNtCfVL9qaAqv47m6SU0ApyiDQ745nxys87cR+C3NYoJmKailgFgoRUh7l2lQ0+Euwg4gr2sIrewoClA+20K7xLBDatYdbww8EjGuPhyUdTXgxGPxJC/s1giCOYzWGnHUBuMNIQJeVxjSS3ualxdKfdXrup6kpwPANCG0xOyAhgus3y0PQC/hjYvHIH1GLCD8pWFZoSmPQlmpkWXFALUH3dkhy0kUw35ZhfFKYqNkc8f6iJPHdpxd+JjI6RDejKTFWvpBiLbmmsDPItecdrba+sD0TSYtItoZnxMhusxStRSBOlahc2a1l4qxbMqVg7qixmpbeLa3klb25VWSXqzyUmmy2jf08YOVGLcc+cqtXnXwEHmn0v5VVnexg1lmdWiv23GLOIrsSI8d/eJ9pf3U+4s/5NJj+EvdiPRXeOt9qWFC9ftdXkxQ==)

### PR DESCRIPTION
**Pull request by floroz**
## Description

- Implements the logic to allow consumers to provide a `value` prop that will be attached as Node attribute to the underlying DOM element.

## Motivation and Context

fix #16188

## How Has This Been Tested?

Added Cypress Component testing

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

File: packages/vuetify/src/components/VBtn/VBtn.tsx [hunk 1]
```diff
@@ -113,6 +113,17 @@ export const VBtn = defineComponent({
       return props.variant === 'elevated' && !(props.disabled || props.flat || props.border)
     })
 
+    const buttonId = String(Math.random()).replace('.', '')
+
```
Comment (floroz) [inline packages/vuetify/src/components/VBtn/VBtn.tsx:117]: this could be extracted into a separate function `generateRandomId` but I wanted to check first where would be the correct place for this helper.

File: packages/vuetify/src/components/VBtn/VBtn.tsx [hunk 2]
```diff
@@ -155,23 +166,24 @@ export const VBtn = defineComponent({
             locationStyles.value,
             sizeStyles.value,
           ]}
-          disabled={ isDisabled.value || undefined }
-          href={ link.href.value }
+          disabled={isDisabled.value || undefined}
+          href={link.href.value}
```
Comment (floroz) [inline packages/vuetify/src/components/VBtn/VBtn.tsx:170]: I've reset my VSCode settings to make sure I wasn't picking up any other configuration, and run separately the linter.

These fixes seem to be legit so the file was not formatted correctly previously.

File: packages/vuetify/src/components/VBtn/VBtn.tsx [hunk 3]
```diff
@@ -212,24 +220,26 @@ export const VBtn = defineComponent({
...
+              <span class="v-btn__append">{slots.append?.() ?? <VIcon />}</span>
             </VDefaultsProvider>
-          ) }
+          )}
 
-          { !!props.loading && (
+          {!!props.loading && (
             <span key="loader" class="v-btn__loader">
-              { slots.loader?.() ?? (
+              {slots.loader?.() ?? (
```
Comment (floroz) [inline packages/vuetify/src/components/VBtn/VBtn.tsx:229]: wasn't clear from the issue open whether the `value` prop should actually be displayed in place of the `slot`.

I don't think that would be the correct behaviour as the `value` on button seems to only be useful when passed via a Group?

**Comment by floroz** [comment]
If these changes are fine, I'd be happy to also tackle the `group:selected` event which seems to have an incorrect signature, since it set to only emit `true` but never invoked upon click.

I assume the correct behaviour should be to emit the `props.value` ad added in the `onClick`

File: packages/vuetify/src/components/VBtn/VBtn.tsx (hunk 2 above)
Comment (nekosaur) [reply packages/vuetify/src/components/VBtn/VBtn.tsx:170]: No it is correctly formatted. There should be spaces.

**Comment by nekosaur** [comment]
> If these changes are fine, I'd be happy to also tackle the `group:selected` event which seems to have an incorrect signature, since it set to only emit `true` but never invoked upon click.
> 
> I assume the correct behaviour should be to emit the `props.value` ad added in the `onClick`

That emit declaration is correct iirc. It is emitted from the useGroupItem composable

File: packages/vuetify/src/components/VBtn/VBtn.tsx (hunk 2 above)
Comment (KaelWD) [reply packages/vuetify/src/components/VBtn/VBtn.tsx:170]: You have prettier or something running

File: packages/vuetify/src/components/VBtn/VBtn.tsx (hunk 1 above)
Comment (KaelWD) [reply packages/vuetify/src/components/VBtn/VBtn.tsx:117]: What is the purpose of a random ID?

Comment (floroz) [reply packages/vuetify/src/components/VBtn/VBtn.tsx:117]: > What is the purpose of a random ID?

The docs state: 

>The value used when the component is selected in a group. If not provided, a unique ID will be used.

Comment (KaelWD) [reply packages/vuetify/src/components/VBtn/VBtn.tsx:117]: It already uses the index of the item in the group.

File: packages/vuetify/src/components/VBtn/VBtn.tsx [hunk 4]
```diff
@@ -113,6 +113,14 @@ export const VBtn = defineComponent({
...
     })
 
+    const valueAttr = computed((): string | undefined => {
+      if (props.value === undefined) {
+        return undefined
+      }
+
+      return typeof props.value === 'string' ? props.value : JSON.stringify(props.value, null, 0)
+    })
+
```
Comment (floroz) [inline packages/vuetify/src/components/VBtn/VBtn.tsx:123]: I can inline this computed property as

```ts
const valueAttr = computed((): string | undefined => typeof props.value === 'undefined'
      ? undefined : typeof props.value === 'string'
        ? props.value : JSON.stringify(props.value, null, 0))
```

not a fan of shortening a few chars and losing readability, but happy to change if better reflects the style

File: packages/vuetify/src/components/VBtn/VBtn.tsx [hunk 5]
```diff
@@ -113,6 +113,14 @@ export const VBtn = defineComponent({
       return props.variant === 'elevated' && !(props.disabled || props.flat || props.border)
     })
 
+    const valueAttr = computed((): string | undefined => {
+      if (props.value === undefined) {
+        return undefined
+      }
+
+      return typeof props.value === 'string' ? props.value : JSON.stringify(props.value, null, 0)
```
Comment (johnleider) [inline packages/vuetify/src/components/VBtn/VBtn.tsx:121]: What is the use-case for object value?

**Review by johnleider — CHANGES_REQUESTED** [review]

File: packages/vuetify/src/components/VBtn/VBtn.tsx [hunk 6]
```diff
@@ -113,6 +113,14 @@ export const VBtn = defineComponent({
       return props.variant === 'elevated' && !(props.disabled || props.flat || props.border)
     })
 
+    const valueAttr = computed((): string | undefined => {
```
Comment (johnleider) [inline packages/vuetify/src/components/VBtn/VBtn.tsx:116]: you shouldn't need to define the return type

File: packages/vuetify/src/components/VBtn/VBtn.tsx [hunk 7]
```diff
@@ -113,6 +113,14 @@ export const VBtn = defineComponent({
       return props.variant === 'elevated' && !(props.disabled || props.flat || props.border)
     })
```
Comment (johnleider) [inline packages/vuetify/src/components/VBtn/VBtn.tsx:115]:
```suggestion
```

File: packages/vuetify/src/components/VBtn/VBtn.tsx (hunk 4 above)
Comment (johnleider) [reply packages/vuetify/src/components/VBtn/VBtn.tsx:123]: if you want you could do the following to remove 2 loc

`if (props.value === undefined) return undefined`

**Review by johnleider — CHANGES_REQUESTED** [review]

**Comment by floroz** [comment]
Thanks for the detailed feedback @johnleider. 

I've polished the PR and implemented your suggestions.

File: packages/vuetify/src/components/VBtn/VBtn.tsx [hunk 8]
```diff
@@ -167,7 +173,8 @@ export const VBtn = defineComponent({
 
             link.navigate?.(e)
             group?.toggle()
-          } }
+          }}
```
Comment (johnleider) [inline packages/vuetify/src/components/VBtn/VBtn.tsx:176]:
```suggestion
          } }
```

**Review by johnleider — CHANGES_REQUESTED** [review]

File: packages/vuetify/src/components/VBtn/VBtn.tsx (hunk 8 above)
Comment (floroz) [reply packages/vuetify/src/components/VBtn/VBtn.tsx:176]: is there a way for eslint (via prettier?) to automatically apply this formatting rule?

Comment (johnleider) [reply packages/vuetify/src/components/VBtn/VBtn.tsx:176]: I wish lol. For now it's just an internal team guideline.

**Review by johnleider — APPROVED** [review]
