### PR TITLE
fix(VSelect, VAutocomplete): modelValue respects [null]

### LINKED ISSUE #16442: [Bug Report][3.1.1] SelectItemKey doesn't support title for item with value = null
### Environment
**Vuetify Version:** 3.1.1
**Vue Version:** 3.2.45
**Browsers:** Chrome 108.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Create a v-select, add items as objects (with a title and a value) and use null as one of the values.
After that v-select renders empty instead of with the title for the null-value

[Recreation: play.vuetifyjs](https://play.vuetifyjs.com/#eNp9kk1P4zAQhv+K5Ut3pSYW+3HJlhVIIC7cEKe6B5NMisF2LNspQlX+O2M7oaEUbpl5Zt55Z5z1nl5aW+56oBVdBdBWiQD/uSFktSuEtekzBVpIM0Yp9qCgDlOCEKzoGlDnnI6EHpgSD4ncCrPtxRYOjIdK4liPUI3QzzsjLIIMCrDCCP3eygPHNMKdUH2ENU4/dLLJOJs5j0HeacVmu2LoaydtIB5CH7HUtnOB7ImDlgykdZ0mCzzSIhbXnfEBVxrdknOyjuJ7MhmsOL2CVvQqkMPCS8TZYmV6pciwnJrGLKdgivu7XNlKNcuVr0KrDN4nXJutkv6R01NKDRRX10dKKXdK6QacFmYS2vyLatOW+SlxRTzEj+j7J2LGTsBFcrqIfMXyOfGQdEnzLfERbPnkO4P/2T5NGAG+dkVSJubwxjHm9DEE6yvGemOft2XdaXaBjLneBKmhaDp98bv8Vf75yxrpwzxfgtfFg+tePDiciMvOxINsX78aMGLUPSvPsuyYipKfpBjq78AVDkwDDty3vo9qP3g/Yp/8x5kDNwPeUknz7I/OWPt0wvUmlgxLmqWxOO1BN2/d+EFC)

### Expected Behavior
Display the title for the null-value.

### Actual Behavior
Stays empty as no-value is selected

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9kk1P4zAQhv+K5Ut3pSYW+3HJlhVIIC7cEKe6B5NMisF2LNspQlX+O2M7oaEUbpl5Zt55Z5z1nl5aW+56oBVdBdBWiQD/uSFktSuEtekzBVpIM0Yp9qCgDlOCEKzoGlDnnI6EHpgSD4ncCrPtxRYOjIdK4liPUI3QzzsjLIIMCrDCCP3eygPHNMKdUH2ENU4/dLLJOJs5j0HeacVmu2LoaydtIB5CH7HUtnOB7ImDlgykdZ0mCzzSIhbXnfEBVxrdknOyjuJ7MhmsOL2CVvQqkMPCS8TZYmV6pciwnJrGLKdgivu7XNlKNcuVr0KrDN4nXJutkv6R01NKDRRX10dKKXdK6QacFmYS2vyLatOW+SlxRTzEj+j7J2LGTsBFcrqIfMXyOfGQdEnzLfERbPnkO4P/2T5NGAG+dkVSJubwxjHm9DEE6yvGemOft2XdaXaBjLneBKmhaDp98bv8Vf75yxrpwzxfgtfFg+tePDiciMvOxINsX78aMGLUPSvPsuyYipKfpBjq78AVDkwDDty3vo9qP3g/Yp/8x5kDNwPeUknz7I/OWPt0wvUmlgxLmqWxOO1BN2/d+EFC)

### PR DESCRIPTION
**Pull request by yuwu9145**
fix #16442

It also happens to `Autocomplete`: [reproduce link](https://play.vuetifyjs.com/#eNp9UsFu2zAM/RVBl2xAbGHddvHSoQNa7LLbsFOUg2rTqVZJFiQ6QxH430dZduOmaW/me+Tj45O3R/7D+/LQA6/4BsF6oxC+S8fY5lAo78fPsbBKu6nKZI9d3dEAIMwwY9TXNWCuJY9goEbJT5xR9yPzS7l9r/Zw4iRWmpZHIs1ExuVkIgvUaIA6nLLPoxIlwUQelOkTWdP206SY7YuF/1TkyzZicTGVsQ7aI4uAfaK19V1AdmQBWjawNnSWrSiqVWquOxeRTprcsmu2TeJHNhusJL+FVvUG2engNdHZYuV6Y9iwnocmVHJwxZ/fubPVZoGVT8qaTDxvuHN7o+OD5JeUGihu786URuyS0k8IVrlZaPctqUknRL4zPyYdSVF8SM4/UsMFajU6XSV2I3KcFCRf85wlPYIv/8bO0d92HDdMBL12xUYkYZRxqiV/QPSxEqJ3/nFf0t8mbogToXeoLRRNZ28+l1fll6+i0RGXeAnRFveh+xch0EY6diGOun16a8FEk+6n8irLTlCSfCUlSP8AoQjgGggQ3vV91vvC+xn3yn/aOUg3UJZGu8d4FmMdxwi3u9QyrHmWpubxDr77D6+FQ9Y=)

## Markup:

```vue
<template>
  <v-app>
    <v-main>
      <v-select
        v-model="select"
        label="Language"
      	:items="languages"
        item-title="name"
    		item-value="code"
      />
<v-autocomplete
        v-model="select"
        label="Language"
      	:items="languages"
        item-title="name"
    		item-value="code"
      />
    </v-main>
  </v-app>
</template>

<script setup>
import { ref } from 'vue'

const languages = [
  { "name":"Default Language", "code":null },
  { "code":"en-US", "file":"en-US.yaml", "name":"English" },
  { "code":"de-DE", "file":"de-DE.yaml", "name":"German" },
 ];
  
// const select = ref(null);
const select = ref('en-US');
</script>

```

### CODE REVIEW

**Comment by yuwu9145** [comment]
Adding tests...

**Comment by KaelWD** [comment]
Should the item be highlighted?
Screenshot_20230201_000747

If the model is null but there's no null items the label is still active
Screenshot_20230201_000823

Basically everything in vuetify treats null and undefined as "no value"

**Comment by yuwu9145** [comment]
@KaelWD does it mean `null` should not be used as a legit `itemValue`?

**Comment by johnleider** [comment]
> Basically everything in vuetify treats null and undefined as "no value"

It was my understanding that null was a valid value.

File: packages/vuetify/src/composables/nested/nested.ts [hunk 1]
```diff
@@ -217,8 +217,7 @@ export const useNested = (props: NestedProps) => {
 export const useNestedItem = (id: Ref<unknown>, isGroup: boolean) => {
   const parent = inject(VNestedSymbol, emptyNested)
 
-  const uidSymbol = Symbol(getUid())
-  const computedId = computed(() => id.value ?? uidSymbol)
+  const computedId = computed(() => id.value)
```
Comment (yuwu9145) [inline packages/vuetify/src/composables/nested/nested.ts:220]: @KaelWD If both `undefined` and `null` are legit prop value/id, do you have any concern of not using Symbol here?

**Comment by yuwu9145** [comment]
> If the model is null but there's no null items the label is still active

`TextField` dirty state should be based on selections. In addition, selections should only be returned as none-empty array when model.value is part of items. e.g. if `model.value === 1` but `items === [0, 2]`, then selections should be empty array `[]`

> Should the item be highlighted?

`null` & `undefined` should be treated as legit `computedId` in `useNestedItem`

**Comment by johnleider** [comment]
What are your thoughts on this? @nekosaur @santiagoaloi

File: packages/vuetify/src/composables/nested/nested.ts (hunk 1 above)
Comment (johnleider) [reply packages/vuetify/src/composables/nested/nested.ts:220]: getUid returns a number and I'm also not sure how this is related

**Comment by santiagoaloi** [comment]
I answered here https://github.com/vuetifyjs/vuetify/issues/16442

File: packages/vuetify/src/composables/nested/nested.ts (hunk 1 above)
Comment (yuwu9145) [reply packages/vuetify/src/composables/nested/nested.ts:220]: This impacts ListItem's `isSelected` state when `item-value` is null or undefined

File: packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx [hunk 2]
```diff
@@ -127,7 +127,7 @@ export const VAutocomplete = genericComponent<new <
       props,
       'modelValue',
       [],
-      v => transformIn(wrapInArray(v)),
+      v => transformIn(v == null ? [null] : wrapInArray(v)),
```
Comment (johnleider) [inline packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx:130]: this will also treat undefined as null

File: packages/vuetify/src/components/VSelect/VSelect.tsx [hunk 3]
```diff
@@ -126,7 +126,7 @@ export const VSelect = genericComponent<new <
       props,
       'modelValue',
       [],
-      v => transformIn(wrapInArray(v)),
+      v => transformIn(v == null ? [null] : wrapInArray(v)),
```
Comment (johnleider) [inline packages/vuetify/src/components/VSelect/VSelect.tsx:129]: this will also treat undefined as null

File: packages/vuetify/src/composables/items.ts [hunk 4]
```diff
@@ -93,12 +93,16 @@ export function useItems (props: ItemProps) {
...
-    return value.map(v => {
-      const existingItem = items.value.find(item => deepEqual(v, item.value))
-      // Nullish existingItem means value is a custom input value from combobox
-      // In this case, use transformItem to create an InternalItem based on value
-      return existingItem ?? transformItem(props, v)
-    })
+    return value
+      // When the model value is null, returns an InternalItem based on null
+      // only if null is one of the items
+      .filter(v => v != null || (v == null && items.value.some(item => item.value == null)))
```
Comment (johnleider) [inline packages/vuetify/src/composables/items.ts:99]: You don't need to check if `v == null` because it's implied. Same feedback as other null comparisons.

**Review by johnleider — CHANGES_REQUESTED** [review]

File: packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx (hunk 2 above)
Comment (yuwu9145) [reply packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx]: Thanks addressed

File: packages/vuetify/src/composables/items.ts (hunk 4 above)
Comment (yuwu9145) [reply packages/vuetify/src/composables/items.ts]: thanks heaps, removed `v == null` and only check if null is one of the items

Comment (yuwu9145) [reply packages/vuetify/src/composables/items.ts]: Refactored, it should be as simple as always only checking if model value is one of items

**Review by johnleider — APPROVED** [review]

**Comment by yuwu9145** [comment]
Ready for a further review

**Review by johnleider — APPROVED** [review]
