### PR TITLE
fix(VColorPicker): hide alpha input correctly

### LINKED ISSUE #10402: [Bug Report] VColorPicker alpha settings not shown when using v-model
### Environment
**Vuetify Version:** 2.2.8
**Vue Version:** 2.6.11
**Browsers:** Firefox 72.0
**OS:** Linux

### Steps to reproduce
add v-model to color picker

### Expected Behavior
color picker should show alpha settings by default even if v-model is used

### Actual Behavior
color picker doesn't show alpha settings if v-model is used

### Reproduction Link
<a href="https://codepen.io/Kruskovac/pen/GRgbXQL" target="_blank">https://codepen.io/Kruskovac/pen/GRgbXQL</a>

### PR DESCRIPTION
**Pull request by nekosaur**
## Description

alpha input should be hidden if value prop does not include alpha information.

an exception is made for null/undefined value

## Motivation and Context

closes #10402

## Markup:

<details>

```vue
<template>
  <div>
    <v-color-picker mode="rgba" v-model="color1"/>
    <v-color-picker mode="rgba" v-model="color2"/>
    <v-color-picker mode="rgba" v-model="color3"/>
    <v-color-picker mode="rgba" v-model="color4"/>
    <v-color-picker mode="rgba" v-model="color5"/>
  </div>
</template>

<script>
  export default {
    data: () => ({
      color1: null,
      color2: '#FF00FF',
      color3: '#FF00FFAA',
      color4: { r: 10, g: 20, b: 30 },
      color5: { r: 10, g: 20, b: 30, a: 1 },
    }),
  }
</script>

```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

File: packages/vuetify/src/components/VColorPicker/util/index.ts [hunk 1]
```diff
@@ -126,6 +126,13 @@ export function parseColor (color: any, oldColor: VColorPickerColor | null) {
   return fromRGBA({ r: 255, g: 0, b: 0, a: 1 })
 }
 
+function stripAlpha (color: any, stripAlpha: boolean) {
+  if (stripAlpha) {
+    const { a, ...rest } = color
+    return rest
```
Comment (johnleider) [inline packages/vuetify/src/components/VColorPicker/util/index.ts]: should have a blank line after line 131

File: packages/vuetify/src/components/VColorPicker/util/index.ts [hunk 2]
```diff
@@ -126,6 +126,13 @@ export function parseColor (color: any, oldColor: VColorPickerColor | null) {
...
+  } else return color
```
Comment (johnleider) [inline packages/vuetify/src/components/VColorPicker/util/index.ts]: should skip the else and return on a new line
