### PR TITLE
[Bug] fix(VDataTable): replace hardcoded icons for presets in grouped rows

### LINKED ISSUE #8255: [Bug Report] Google MD Icons are still being used in data tables groups
### Environment
**Vuetify Version:** 2.0.3
**Vue Version:** 2.6.10
**Browsers:** Mozilla Firefox, Safari, Microsoft Edge, Internet Explorer, Opera, Other
**OS:** Windows, Android, iOS, Mac OSX, Linux

### Steps to reproduce
Please refer to the reproduction link.

### Expected Behavior
Grouped tables should use the configured icon font only (MDI, FA, etc.)

### Actual Behavior
Grouped tables still use Google MD Icons in some places.

### Reproduction Link
<a href="https://codepen.io/anon/pen/oKejpb" target="_blank">https://codepen.io/anon/pen/oKejpb</a>

### PR DESCRIPTION
**Pull request by nekosaur**
## Description
grouped row headers used hardcoded MD icons instead of using presets.

## Motivation and Context
closes #8255

## How Has This Been Tested?

playground, unit test snapshot

## Markup:

<details>

```vue
<template>
  <div>
    <v-data-table
      :headers="headers"
      :items="desserts"
      item-key="name"
      group-by="category"
      class="elevation-1"
      show-group-by
    ></v-data-table>
  </div>
</template>

<script>
export default {
  data () {
    return {
      headers: [
        {
          text: 'Dessert (100g serving)',
          align: 'left',
          value: 'name',
        },
        { text: 'Category', value: 'category' },
      ],
      desserts: [
        {
          name: 'Frozen Yogurt',
          category: 'Ice cream',
        },
        {
          name: 'Ice cream sandwich',
          category: 'Ice cream',
        },
        {
          name: 'Eclair',
          category: 'Cookie',
        },
        {
          name: 'Cupcake',
          category: 'Pastry',
        },
        {
          name: 'Gingerbread',
          category: 'Cookie',
        },
        {
          name: 'Jelly bean',
          category: 'Candy',
        },
        {
          name: 'Lollipop',
          category: 'Candy',
        },
        {
          name: 'Honeycomb',
          category: 'Toffee',
        },
        {
          name: 'Donut',
          category: 'Pastry',
        },
        {
          name: 'KitKat',
          category: 'Candy',
        },
      ],
    }
  },
}
</script>
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)
- [ ] I've added new examples to the kitchen (applies to new features and breaking changes in core library)

### CODE REVIEW

File: packages/vuetify/src/components/VDataTable/VDataTable.ts [hunk 1]
```diff
@@ -316,7 +316,7 @@ export default VDataIterator.extend({
           on: {
             click: () => this.$set(this.openCache, group, !this.openCache[group]),
           },
-        }, [this.$createElement(VIcon, [isOpen ? 'remove' : 'add'])])
+        }, [this.$createElement(VIcon, [isOpen ? '$vuetify.icons.minus' : '$vuetify.icons.plus'])])
```
Comment (jacekkarczmarczyk) [inline packages/vuetify/src/components/VDataTable/VDataTable.ts]: I feel like icon names should be based on what they are doing, not how do they look like (by default)

Comment (nekosaur) [reply packages/vuetify/src/components/VDataTable/VDataTable.ts]: I agree, kind of. I feel that plus and minus are so generic, and might very well be used for other components in vuetify, that coupling their names too strongly to their usage in this might not be preferable.

**Comment by jacekkarczmarczyk** [comment]
@kb-cs please create a new issue and provide a reproduction if there's still a bug
