### PR TITLE
fix(VCalendar): Stop day row content overflowing its parent

### LINKED ISSUE #18968: [Bug Report][3.4.9] VCalendar: rendering issue when events titles is too long
### Environment
**Vuetify Version:** 3.4.9
**Vue Version:** 3.4.4
**Browsers:** Firefox 121.0
**OS:** Windows 10

### Steps to reproduce
Create an hour-long event with a long title, the end date of the event will be invalid.

### Expected Behavior
The overflow of the title must be hidden to allow events to be placed correctly according to the calendar's time scale.

### Actual Behavior
A one-hour event can be presented as a multi-hour event.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp1UUFugzAQ/MrKFxopEBK4FJFIlfqEnBpycGGTWDU2sh3TKsrfu+DQpmorIeEdjWdmx7sLs6ZePHVd4s/IClY6bDvJHW4qBVD6mHfdeByHWivHhUJzgwLIJaqGG/BxqxuU64q19lgx8AL7ESKkR3wjqECPylkCwqFim3LxLTE5DdAPqwEJScrFXUIabW1E58CiO4egou20cXABgwe4wsHoFiJaLhroAKRrHQR3WMMuOF6mfZxwEotpAoi2JwSH7w6EBac1SK2OwFUD2qM5SN3PgaJDQ4EGilCeS9EQODiAVvIDJLfkxRWc9NlE80ncOm5cAQp7eKbbD9EqXeVxuoxX2TbNijSl7yWaffHJ5h92/ptca6lNAdGrpM1v6HX87+97oIeiEqiph92fysu8yG7S+9lQfqibimbXOcuSPEljUycZC8Mj238CXbm14w==)

### PR DESCRIPTION
**Pull request by yuwu9145**
fixes #18968

## Markup:

```vue
<template>
  <v-app>
    <v-container>
      <v-calendar v-model="msg" view-mode="week" :events="events"></v-calendar>
    </v-container>
  </v-app>
</template>

<script setup>
  import { ref } from 'vue'

  const events = [
    {
      title:
        'The text is too long and overflow, end date is invalid, event only lasts an hour',
      start: new Date('2024-01-23T03:00:00Z'),
      end: new Date('2024-01-23T4:00:00Z'),
      color: 'blue',
    },
  ]

  const msg = ref([new Date('2024-01-23T14:30:00Z')])
</script>


```

### CODE REVIEW

File: packages/vuetify/src/labs/VCalendar/VCalendarIntervalEvent.tsx [hunk 1]
```diff
@@ -55,8 +58,8 @@ export const VCalendarIntervalEvent = genericComponent()({
         <VSheet
```
Comment (johnleider) [inline packages/vuetify/src/labs/VCalendar/VCalendarIntervalEvent.tsx:58]: @blalan @yuwu9145 - I moved out some of the utility classes, but rounded needs to be ultimately removed or specifically added since a user might not have utility classes enabled.

**Review by johnleider — APPROVED** [review]
