### PR TITLE
fix(router): replace `next()` deprecated in Vue Router v5

### LINKED ISSUE #22632: [Bug Report][3.11.8] useBackButton uses deprecated Vue Router next() callback
### Environment
**Vuetify Version:** 3.11.8
**Vue Version:** 3.5.28
**OS:** Windows 10 (current)

### Expected Behavior
useBackButton in vuetify/lib/composables/router.js registers a router.beforeEach guard using the deprecated next() callback pattern, which Vue Router 4 has deprecated in favor of returning values directly.

### Actual Behavior
useBackButton in vuetify/lib/composables/router.js registers a router.beforeEach guard using the deprecated next() callback pattern, which Vue Router 4 has deprecated in favor of returning values directly.

### Notes
[https://bin.vuetifyjs.com/...](https://bin.vuetifyjs.com/?code=eJydVV1v40QUfZ9fcZHQNpEat6gt0EQFWihSBSyoLbtCqxWd2NfObO0Za2acD6FKPPHMA79wfwnn2mm-usuijaoqHs89c-ace08umoKuuXY-DqkJfKHT-4smRmflKVDGtedUR87oRcN07ZrInizPY69PqS7LMQrUTVNV2i_UNoCxNG04mnxxUJrxQeqq2gU9Ljkc-BYneRPIc2ECvgfStFwdc-48X-p0QkWjfQYmxhYUJ7xJZ4cD1Tqi2O7TbGJQucH2mCZ66yYgluup8-RynB8bbwV_qstGbmywLZaLRF3aqfHOVmyjegGGxlmgyn2OktPkZH3CcTLHw1EyVzeR60DRiaTeZU3KSl3ZEEFSGEktYR_NTNymiNpfA5O2C2p1sjgUN9YRZOVaAMAb_A87LvU4KRKaDqyemkJHcBxkXs_Y99XzbolpzHHGbDt9g_q5xvexd7OAk7_j6a1zgE2dDa4E38t5DQEg0wVPgOC8eu5W6gGfZroVLIiOYsqyMlHnaWx0ua67xcvclaWbib7LMjJies3iBO7ElYFvGQGXp-wXtL7IUL3akEjKXw9JMO867-_W5oPJuq7rGtDbND1R163TLePWahSh8TSOzlsg4dYht6_7dwnsFPDodcpDJQQ-_Yy-kaYerBp4ePT5yYnaXTw-PDzFYjpp7P3g9scfrm5-O7-WF1-eUvd5-9ff204-wTg6_eJUXTsX6VuNnegjsi7j3yv0lczQB2drf6dVNkftP2bMlVuzfvRk0s5_uRqqN-Hg4MPjrTxXbsoX7Wl09nTCe73o9in3rtpvz-nT2Vf0hyIyOfU-MfbWaxuMuNpvl4kCx1tTMYB6IIXdtatrNNDXlI57HcRwSbk_IpAUpdd9AIwH4hKz1sG9v3q0dGrz8044YbtBFNeMvuGReuiPkIxFwRA9o-_NXP1kCi8DiYAQpeEkRns7qro8GnQdulT6_4v4EfJ1y11FJwasHuP67brcYUexd218rwa0vNCGJIiTyN0gi9DYkLNnm2Ig0ZllcIjyENqYhk4rW97--U-XNo9tGExhNbCho0ZsMCqwf8wAnBqe4RGpX2sfZcDjBOC5mSdKvXT-XkNDm0nkyjQAIm08OCD2EVg-7aBCU8PmgDzHsY_pVWmLjMM-RE6ljZVJhUWSgTjIm8Igq19iMyR4DEapHanNJ7zsJUmifRFWJnQQFQ7UhdgsL18dvhYNRfK4qBkXWb0_O6O9ED047dGzZ4_ribFp2WQcentdF-_1-0sLBGiTYKLrulz0lrT22_Ngz8MIuQ2x8GeRPZoCQjXkOo0O6Vw6WwzQfRWhqGmthsomwo1SPAxUImWiqaTNVz8U0poSRh6XzPArF2jGZZn8CxUG7GI)

### PR DESCRIPTION
**Pull request by dennybiasiolli**
## Description

resolves #22632

vue-router v5 added a deprecation notice in the usage of a `NavigationGuardNext` function (https://router.vuejs.org/api/interfaces/NavigationGuardNext.html), the "new way" of using it is returning a `NavigationGuardReturn` directly.

**NOTE**: consider upgrading to vue-router v5.x in the repo before accepting/merging this

```
pnpm --filter vuetify add vue-router@5
git add packages/vuetify/package.json pnpm-lock.yaml
git commit -m "feat: upgrading vue-router to v5 in vuetify package"
git push
```

## Markup:

Upgrade to vue-router 5.x to get the console warning:

```
pnpm --filter vuetify add vue-router@5
```

```vue
<template>
  <v-app>
    <v-container>
      <v-overlay />
    </v-container>
  </v-app>
</template>

<script>
  import { useRouter } from 'vue-router'

  export default {
    name: 'Playground',
    setup () {
      const router = useRouter()
      router.push('/page1').then(() => {
        router.push('/')
      })
      return {
        //
      }
    },
  }
</script>
```

### CODE REVIEW

**Comment by wusonw** [comment]
Hey guys, patches below works fine for me :
```diff
diff --git a/lib/composables/router.js b/lib/composables/router.js
index fd42accc1674e85a542ca960e38676fd6878e2e5..3790ca4f5b3b9ec817f4907c138c2c1382703ec6 100644
--- a/lib/composables/router.js
+++ b/lib/composables/router.js
@@ -75,13 +75,25 @@ export function useBackButton(router, cb) {
   if (IN_BROWSER && router?.beforeEach) {
     nextTick(() => {
       window.addEventListener('popstate', onPopstate);
-      removeBefore = router.beforeEach((to, from, next) => {
+      removeBefore = router.beforeEach((to, from) => {
+        if (to === from) return;
+        const runCallback = () => {
+          let result;
+          const next = (val) => { result = val; };
+          if (popped) {
+            cb(next);
+            return result;
+          }
+          return undefined;
+        };
         if (!inTransition) {
-          setTimeout(() => popped ? cb(next) : next());
-        } else {
-          popped ? cb(next) : next();
+          inTransition = true;
+          return new Promise((resolve) => {
+            setTimeout(() => resolve(runCallback()));
+          });
         }
         inTransition = true;
+        return runCallback();
       });
       removeAfter = router?.afterEach(() => {
         inTransition = false;
```

**Comment by dennybiasiolli** [comment]
@wusonw what do you think about my proposed change in this PR?
I also updated the typing of `useBackButton` function in the same file and the related `packages/vuetify/src/components/VOverlay/VOverlay.tsx` and `packages/docs/src/main.ts`.
Also added a few tests for `useBackButton`

File: packages/vuetify/src/composables/router.tsx [hunk 1]
```diff
@@ -118,21 +118,23 @@ export const makeRouterProps = propsFactory({
...
   if (IN_BROWSER && router?.beforeEach) {
     nextTick(() => {
       window.addEventListener('popstate', onPopstate)
-      removeBefore = router.beforeEach((to, from, next) => {
+      removeBefore = router.beforeEach(() => {
+        const isPopped = popped // capture before any async gap
         if (!inTransition) {
-          setTimeout(() => popped ? cb(next) : next())
+          inTransition = true
+          return new Promise<NavigationGuardReturn>(resolve => setTimeout(() => resolve(isPopped ? cb() : undefined)))
```
Comment (J-Sek) [inline packages/vuetify/src/composables/router.tsx]: `isPopped` breaks the behavior. Do we need it?

```suggestion
      removeBefore = router.beforeEach(() => {
        if (!inTransition) {
          inTransition = true
          return new Promise<NavigationGuardReturn>(resolve => {
            setTimeout(() => resolve(popped ? cb() : undefined))
          })
```

Comment (dennybiasiolli) [reply packages/vuetify/src/composables/router.tsx]: Oh you are right, sorry. Changed code and tests, and rebased

**Comment by Elchin5757** [comment]
When will this warning be fixed/removed?

**Comment by J-Sek** [comment]
> @Elchin5757: When will this warning be fixed/removed?

rude 😛  I am sick now and do it for free anyway since OC funds dried up.

Can you download the repo, checkout this branch, build, point your app's package.json to the `file:{path}/packages/vuetify`, rebuild and verify it works fine in multiple scenarios (mostly dialogs and menus with `persistent`) while keeping in mind it was the not very reliable in the first place (#18505)? It genuinely would help even after merging this PR.

Tip: add `{ outline: '2px solid red' }` to the styles below `v-overlay__content` in VOverlay.tsx to make sure your app loaded the local version. If you work with Nuxt, anytime you rebuild local vuetify, remove both `node_modules` and `.nuxt` and re-install dependencies.

**Comment by dennybiasiolli** [comment]
It was to unit-test the `useBackButton` that was missing tests.
Let me remove them and try to add a test inside `VDialog.spec.browser.tsx` if possible.
If you have suggestions about the tests that needs to be performed, let me know, I will try to figure out something in the meantime

**Comment by dennybiasiolli** [comment]
BTW, I think the issue in `VDialog` is out of the topic of this PR, I will try to investigate that in another PR right after this one, is that ok for you?

The current PR removes the deprecation warning in the console when using the `next` parameter in navigation guards from vue-router inside `v-overlay` components.

I know, they are used in `VDialog`, but also in `VMenu`, `VOtpInput` and others.

**Comment by J-Sek** [comment]
Hi, thanks for taking time to resolve the deprecation warnings. I would not mind unit-tests, but those were some kind of accidental nonsense that would only hurt us in the long run - by giving false confidence or failing for non-obvious reason. The more practical approach will be to have test for VDialog that are easy to grasp and repeat manually. You have proven the `useBackButton` can be broken in non-obvious way and I have spent hours on verification, so we will definitely benefit from the coverage.

If you can tackle any other outstanding issue with `useBackButton`, it would be of great help. Just prepare yourself to be questioned about the reason behind any changes in the code that are not 100% related to the problem 😉  If you got help from LLM-based tools, remember to trim, self-review and check the final output to avoid pushing slop with logical errors.

**Comment by pizzaeater** [comment]
Can the warning be fixed in the Vuetify 3? Thanks in advance.

**Comment by J-Sek** [comment]
> @pizzaeater, _Can the warning be fixed in the Vuetify 4? Thanks in advance._

What do you mean? Is it still a problem after upgrading to v4.0.2?

**Comment by pizzaeater** [comment]
> > @pizzaeater, _Can the warning be fixed in the Vuetify 4? Thanks in advance._
> 
> What do you mean? Is it still a problem after upgrading to v4.0.2?

I'm sorry, I meant Veutify 3, not 4.
I edited the comment.

**Comment by J-Sek** [comment]
[4e93846](https://github.com/vuetifyjs/vuetify/commit/4e93846) landed in [v3.12.3](https://github.com/vuetifyjs/vuetify/releases/v3.12.3)
Do you observe the warnings after the update?

**Comment by dennybiasiolli** [comment]
Warning gone after updating to the newly released v3.12.3

**Comment by pizzaeater** [comment]
> [4e93846](https://github.com/vuetifyjs/vuetify/commit/4e93846) landed in [v3.12.3](https://github.com/vuetifyjs/vuetify/releases/v3.12.3) Do you observe the warnings after the update?

Yes, it seems like it's fixed now! Thanks.
