### PR TITLE
fix(VSlider): remove attributes inherit from thumb container

### LINKED ISSUE #14010: [Bug Report][2.5.7] VSlider inherit $attrs twice, in input and div container
### Environment
**Vuetify Version:** 2.5.7
**Vue Version:** 2.6.14
**Browsers:** Firefox 90.0
**OS:** Windows 10

### Steps to reproduce
Create a `v-slider` and pass non-prop attributes to it.

```html
<v-slider data-test="slider" />
```

### Expected Behavior
Only `input` inherits `data-test`

### Actual Behavior
Both `input` and `div` container inherits `data-test`

### Reproduction Link
<a href="https://codepen.io/allanchain/pen/VwbxeJg?editors=1010" target="_blank">https://codepen.io/allanchain/pen/VwbxeJg?editors=1010</a>

### Other comments
Context: I am using cypress to test my web app, and it is recommended to use `data-cy` to target elements. Passing `data-cy` to `VSlider` and getting two elements with `[data-cy="slider"]` is quite unexpected.

### PR DESCRIPTION
**Pull request by yuwu9145**
fixes #14010

## Description

resolves #14010

## Motivation and Context

resolves #14010

## How Has This Been Tested?

visually 

## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
<template>
  <v-container>
    <h4>VSlider inherit is wrong</h4>
    <p>[data-test="slider"] count: {{sliderCount}}</p>
    <v-slider data-test="slider" />
    <h4>VSwitch inherit is correct</h4>
    <p>[data-test="switch"] count: {{switchCount}}</p>
    <v-switch data-test="switch" />
  </v-container>
</template>

<script>
export default {
  data: () => ({
    sliderCount: 0,
    switchCount: 0
  }),
  mounted () {
    this.sliderCount = document.querySelectorAll('[data-test="slider"]').length
    this.switchCount = document.querySelectorAll('[data-test="switch"]').length
  }
};
</script>
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

File: packages/vuetify/src/components/VSlider/VSlider.ts [hunk 1]
```diff
@@ -388,13 +388,12 @@ export default mixins<options &
...
           role: 'slider',
           tabindex: this.isDisabled ? -1 : this.$attrs.tabindex ? this.$attrs.tabindex : 0,
-          'aria-label': this.label,
+          'aria-label': this.$attrs['aria-label'] || this.label,
           'aria-valuemin': this.min,
           'aria-valuemax': this.max,
           'aria-valuenow': this.internalValue,
           'aria-readonly': String(this.isReadonly),
           'aria-orientation': this.vertical ? 'vertical' : 'horizontal',
-          ...this.$attrs,
```
Comment (yuwu9145) [inline packages/vuetify/src/components/VSlider/VSlider.ts:397]: Looks like the only purpose of non-prop attributes inherit here is for making sure `aria-label` takes highest precedence over `label` prop.

In addition, with this change applied, all events from ThumbContainer are consistent

**Review by KaelWD — APPROVED** [review]
