### PR TITLE
fix(VStepperStep): editable step tab navigation

### LINKED ISSUE #14022: [Bug Report][2.4.9] Editable Stepper Header Not Keyboard Accessible
### Environment
**Vuetify Version:** 2.4.9
**Vue Version:** 2.6.12
**Browsers:** Chrome 92.0.4515.107, Google Chrome, Mozilla Firefox
**OS:** Windows 10

### Steps to reproduce
When on a page with a stepper that includes headers using the editable prop, attempt to use the keyboard to focus on and execute that step.

### Expected Behavior
keyboard focus should be moved to the actionable element, in this case the stepper header, and be executable with the keyboard. All focus styles that apply when clicked should apply when focused with the keyboard. 

### Actual Behavior
The keyboard skips over the clickable header entirely and is therefore not executable with the keyboard 

### Reproduction Link
<a href="https://codepen.io/flpehr0/pen/yLbqZJe" target="_blank">https://codepen.io/flpehr0/pen/yLbqZJe</a>

### Other comments
Adding a tabindex="0" when editable should be a good first step as well as ensuring that it will execute with a keyboard and not only a mouse.

### PR DESCRIPTION
**Pull request by lentyaevpk**
## Description

Added tab navigation for editable stepper steps.
Fixes #14022 

## How Has This Been Tested?

Visually 

## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
<template>
  <v-stepper>
    <v-stepper-header>
      <v-stepper-step
        editable
        step="1"
      >
        Select campaign settings
      </v-stepper-step>

      <v-divider></v-divider>

      <v-stepper-step
        editable
        step="2"
      >
        Create an ad group
      </v-stepper-step>

      <v-divider></v-divider>

      <v-stepper-step
        step="3"
        editable
      >
        Create an ad
      </v-stepper-step>
    </v-stepper-header>
  </v-stepper>
</template>
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

File: packages/vuetify/src/components/VStepper/VStepperStep.ts [hunk 1]
```diff
@@ -131,6 +131,11 @@ export default baseMixins.extend<options>().extend({
 
       return children
     },
+    keyboardClick (e: KeyboardEvent) {
+      if (e.keyCode === 32) {
```
Comment (johnleider) [inline packages/vuetify/src/components/VStepper/VStepperStep.ts:135]: use https://github.com/vuetifyjs/vuetify/blob/3171d6f460ef41758817d54f18e20d6196ef05fb/packages/vuetify/src/util/helpers.ts#L200

**Review by johnleider — CHANGES_REQUESTED** [review]

File: packages/vuetify/src/components/VStepper/VStepperStep.ts (hunk 1 above)
Comment (lentyaevpk) [reply packages/vuetify/src/components/VStepper/VStepperStep.ts]: Done

**Review by johnleider — APPROVED** [review]
