### PR TITLE
fix(goTo) Always respect progressPercentage. Fixes #3608

### LINKED ISSUE #3608: [Bug Report] $vuetify.goTo never completes and never releases scroll
### Versions and Environment
**Vuetify:** 1.0.8
**Vue:** 2.5.16
**Browsers:** Chrome 64.0.3282.140
**OS:** Linux x86_64

### Steps to reproduce
Use browser's zoom feature, then programatically scroll to an off-screen element

### Expected Behavior
The scroll animation stops after the set duration.

### Actual Behavior
goTo keeps requesting animation frames as it will never reach the target. Thus, locking the scrolling behaviour permanently.

This never triggers:
```javascript
    if (Math.round(window.pageYOffset) === targetLocation) return
```

### Reproduction Link
[https://codepen.io/anon/pen/MVbyNp](https://codepen.io/anon/pen/MVbyNp)

### Other comments
I tested on my machine, and a possible solution would be to besides the check above, a check on `progressPercentage` could be done as well. This works for my reproduction link.

I can provide a PR if needed.

### PR DESCRIPTION
**Pull request by moustacheful**
## Description

When using `goTo` the `step` function will check `progressPercentage`. If it reaches 1 it means the animation should be finished, according to the given time.

## Motivation and Context

This fixes https://github.com/vuetifyjs/vuetify/issues/3608, where a different zoom setting could result in a target that will never be reached, thus locking the scroll permanently.

## How Has This Been Tested?

Visually.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have created a PR in the [documentation](https://github.com/vuetifyjs/vuetifyjs.com) with the necessary changes.

### CODE REVIEW

File: src/components/Vuetify/util/goTo.js [hunk 1]
```diff
@@ -74,7 +74,12 @@ export default function goTo (target, options) {
     let targetPosition = Math.floor(startLocation + distanceToScroll * easingFunction(progressPercentage))
 
     window.scrollTo(0, targetPosition)
-    if (Math.round(window.pageYOffset) === targetLocation) return
+
+    if (
+      Math.round(window.pageYOffset) === targetLocation ||
+      progressPercentage === 1
```
Comment (jacekkarczmarczyk) [inline src/components/Vuetify/util/goTo.js]: First condition could be removed (it will behave wrong for easing function like http://easings.net/en#easeInOutElastic - i'm aware that it's not in the scope of this issue) and `===` could be changed to `>=`

Comment (moustacheful) [reply src/components/Vuetify/util/goTo.js]: I wanted to introduce as little changes to the original code as possible, but what you're saying makes sense. If it's no issue with you guys I can make that modification in this same PR.

Regarding the `>=` though that should never trigger because of the `Math.min` a bit above that part. The maximum value of `progressPercentage` is effectively 1.

Comment (jacekkarczmarczyk) [reply src/components/Vuetify/util/goTo.js]: You're right, i missed the `min` part
