### PR TITLE
fix(VMaskInput): Fixes error when mask input is cleared

### LINKED ISSUE #22174: [Bug Report][3.10.0] VMaskInput - clear does not work and throws error
### Environment
**Vuetify Version:** 3.10.5
**Vue Version:** 3.5.21
**OS:** macOS 10.15.7 (current)

### Steps to reproduce
1. Fill the input with "1" (for example)
2. Click on the clear icon

### Expected Behavior
It clears the input

### Actual Behavior
It doesn't clear the input and a JS error is thrown `Cannot read properties of null (reading 'split')`

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVj0EOgjAQRa8ymTUU0bAxlcQDeALrYihjQiy1KYWN8e621AXsXt5k5v+5f3Dyuro6J5aZ8Ywy8OgMBW6VlUtJzkUAgMj6bQMNln02qxtpepWDdXMAbZg8dYYhyYtC7bkfQqnJ9wrBUMcm2lscwrqhsJXV9sQ/KbpdVBK5h6w27fBb4Ek04lhjgvogGiyeZCYudj9l9/gBK4ZNFg==)

### Other comments
According to the stacktrace, removeMaskDelimiters (VMaskInput.tsx) is called with null
FYI @ikushum

### PR DESCRIPTION
**Pull request by ikushum**
fixes #22174

## Description
Fixes error when mask input is cleared

## Markup:
```vue
<template>
  <v-app>
    <v-container>
      <v-mask-input label="Mask input" mask="credit-card" clearable persistent-clear />
    </v-container>
  </v-app>
</template>

```

### CODE REVIEW

File: packages/vuetify/src/labs/VMaskInput/VMaskInput.tsx [hunk 1]
```diff
@@ -72,6 +72,8 @@ export const VMaskInput = genericComponent<VMaskInputSlots>()({
     const validationValue = toRef(() => returnMaskedValue.value ? model.value : mask.unmask(model.value))
 
     function removeMaskDelimiters (val: string): string {
+      if (!val) return ''
```
Comment (J-Sek) [inline packages/vuetify/src/labs/VMaskInput/VMaskInput.tsx]: Slightly buried... and looks suspicious without `val: string | null` above. @babu-ch already merged a fix one level above. His change could be further shortened to `removeMaskDelimiters(val ?? '')`, but it feels reasonable to skip the function, actually.

**Comment by J-Sek** [comment]
We could benefit from making `model` type more precise with additional ` as string | null` at the end of line 47

https://github.com/vuetifyjs/vuetify/blob/46e3a84b582aa0c8f7e8aba4e00be3b1a6f7bddd/packages/vuetify/src/labs/VMaskInput/VMaskInput.tsx#L47

**Comment by KaelWD** [comment]
Replaced with #22175
