### PR TITLE
fix(VNavigationDrawer): should emit update:mini-variant

### LINKED ISSUE #8133: [Bug Report] [VNavigationDrawer] mini-variant.sync doesn't reflect the correct value if expand-on-hover is set true
### Environment
**Vuetify Version:** 2.0.2
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.14.6

### Steps to reproduce
Set `expand-on-hover` to `true`, move mouse over and off the drawer and observe the value of `mini` which is bound to `mini-variant.sync`. The value doesn't change regardless.

If `expand-on-hover` is set to `false`,  `mini` becomes 'live' again.

### Expected Behavior
`mini-variant.sync` should give true or false when the drawer switches between mini and normal state, with `expand-on-hover` set to true.

### Actual Behavior
`mini-variant.sync` stops responding to the drawer's mini-variant state.

### Reproduction Link
<a href="https://codepen.io/myleslee/pen/JgbMVP" target="_blank">https://codepen.io/myleslee/pen/JgbMVP</a>

### PR DESCRIPTION
**Pull request by bludnic**
## Motivation and Context
Fixes #8133

## How Has This Been Tested?
unit, visually

## Markup:

<details>

```vue
<template>
  <v-app id="inspire">
    <v-navigation-drawer
      :mini-variant.sync="mini"
      :expand-on-hover="expandOnHover"
      app
    >
      <v-list-item-group dense v-model="current">
        <template v-for="item in items">
          <v-row
            v-if="item.heading"
            :key="item.heading"
            align="center"
          >
            <v-col cols="6">
              <v-subheader v-if="item.heading">
                {{ item.heading }}
              </v-subheader>
            </v-col>
            <v-col
              cols="6"
              class="text-center"
            >
              <a
                href="#!"
                class="body-2 black--text"
              >EDIT</a>
            </v-col>
          </v-row>
          <v-list-group
            v-else-if="item.children"
            :key="item.text"
            v-model="item.model"
            :prepend-icon="item.model ? item.icon : item['icon-alt']"
            append-icon=""
          >
            <template v-slot:activator>
              <v-list-item>
                <v-list-item-content>
                  <v-list-item-title>
                    {{ item.text }}
                  </v-list-item-title>
                </v-list-item-content>
              </v-list-item>
            </template>
            <v-list-item
              v-for="(child, i) in item.children"
              :key="i"
              @click=""
            >
              <v-list-item-action v-if="child.icon">
                <v-icon>{{ child.icon }}</v-icon>
              </v-list-item-action>
              <v-list-item-content>
                <v-list-item-title>
                  {{ child.text }}
                </v-list-item-title>
              </v-list-item-content>
            </v-list-item>
          </v-list-group>
          <v-list-item
            v-else
            :key="item.text"
            @click=""
          >
            <v-list-item-action>
              <v-icon>{{ item.icon }}</v-icon>
            </v-list-item-action>
            <v-list-item-content>
              <v-list-item-title>
                {{ item.text }}
              </v-list-item-title>
            </v-list-item-content>
          </v-list-item>
        </template>
      </v-list-item-group>
    </v-navigation-drawer>

    <v-content>
      <v-container
        class="fill-height"
        fluid
      >
        <v-row
          align="center"
          justify="center"
        >
          <v-btn @click="mini = !mini">Toggle mini</v-btn>
          <v-btn @click="expandOnHover = !expandOnHover">Toggle expandOnHover</v-btn>

          <v-card>
            <v-card-text :class="mini ? 'green--text' : 'red--text'">mini-variant: {{ mini }}</v-card-text>
            <v-card-text :class="expandOnHover ? 'green--text' : 'red--text'">expand-on-hover: {{ expandOnHover }}</v-card-text>
          </v-card>
        </v-row>
      </v-container>
    </v-content>
  </v-app>
</template>

<script>
  export default {
    data: () => ({
      current: null,
      mini: false,
      expandOnHover: false,
      items: [
        { icon: 'contacts', text: 'Contacts' },
        { icon: 'history', text: 'Frequently contacted' },
        { icon: 'content_copy', text: 'Duplicates' },
      ],
    }),
  }
</script>
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)
- [ ] I've added new examples to the kitchen (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by phiter** [comment]
I hope this is merged. Right now I'm using MutationObserver on the navigation drawer ref.

File: packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.ts [hunk 1]
```diff
@@ -131,7 +131,7 @@ export default baseMixins.extend({
         'v-navigation-drawer--floating': this.floating,
         'v-navigation-drawer--is-mobile': this.isMobile,
         'v-navigation-drawer--is-mouseover': this.isMouseover,
-        'v-navigation-drawer--mini-variant': this.miniVariant || (this.expandOnHover && !this.isMouseover),
+        'v-navigation-drawer--mini-variant': this.isMiniVariant || (this.expandOnHover && !this.isMouseover),
```
Comment (johnleider) [inline packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.ts]: looks like the second conditional can go into **isMiniVariant** as well since the only places that **miniVariant** was used also checks **expandOnHover** and **isMouseOver**.

File: packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.ts [hunk 2]
```diff
@@ -185,6 +185,9 @@ export default baseMixins.extend({
     isBottom (): boolean {
       return this.bottom && this.isMobile
     },
+    isMiniVariant (): boolean {
+      return !this.expandOnHover && this.miniVariant
```
Comment (johnleider) [inline packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.ts]:
```suggestion
      return (
        !this.expandOnHover &&
        this.miniVariant
      ) || (
        this.expandOnHover &&
        !this.isMouseOver
      ) 
```

File: packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.ts [hunk 3]
```diff
@@ -171,7 +171,7 @@ export default baseMixins.extend({
     computedWidth (): string | number {
       if (
```
Comment (johnleider) [inline packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.ts]:
```suggestion
      return this.isMiniVariant ? this.miniVariantWidth : this.width
```

File: packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.ts [hunk 4]
```diff
@@ -171,7 +171,7 @@ export default baseMixins.extend({
...
         (this.expandOnHover && !this.isMouseover) ||
```
Comment (johnleider) [inline packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.ts]:
```suggestion
```

File: packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.ts [hunk 5]
```diff
@@ -171,7 +171,7 @@ export default baseMixins.extend({
...
-        this.miniVariant
+        this.isMiniVariant
```
Comment (johnleider) [inline packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.ts]:
```suggestion
```

File: packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.ts [hunk 6]
```diff
@@ -171,7 +171,7 @@ export default baseMixins.extend({
...
       ) return this.miniVariantWidth
```
Comment (johnleider) [inline packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.ts]:
```suggestion
```

File: packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.ts [hunk 7]
```diff
@@ -171,7 +171,7 @@ export default baseMixins.extend({
...
```
Comment (johnleider) [inline packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.ts]:
```suggestion
```

File: packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.ts [hunk 8]
```diff
@@ -171,7 +171,7 @@ export default baseMixins.extend({
...
 
       return this.width
```
Comment (johnleider) [inline packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.ts]:
```suggestion
```

File: packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.ts (hunk 1 above)
Comment (johnleider) [reply packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.ts]:
```suggestion
        'v-navigation-drawer--mini-variant': this.isMiniVariant,
```

File: packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.ts [hunk 9]
```diff
@@ -280,6 +283,12 @@ export default baseMixins.extend({
 
       if (val !== this.isActive) this.isActive = val
     },
+    expandOnHover (val) {
+      this.updateMiniVariant(val)
+    },
```
Comment (johnleider) [inline packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.ts]:
```suggestion
```

File: packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.ts [hunk 10]
```diff
@@ -280,6 +283,12 @@ export default baseMixins.extend({
 
       if (val !== this.isActive) this.isActive = val
     },
+    expandOnHover (val) {
+      this.updateMiniVariant(val)
```
Comment (johnleider) [inline packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.ts]:
```suggestion
```

File: packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.ts [hunk 11]
```diff
@@ -280,6 +283,12 @@ export default baseMixins.extend({
 
       if (val !== this.isActive) this.isActive = val
     },
+    expandOnHover (val) {
```
Comment (johnleider) [inline packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.ts]:
```suggestion
    expandOnHover: 'updateMiniVariant',
```

**Comment by sh7dm** [comment]
@bludnic why don't you use suggested changes feature to fix PRs easily? It's much more convenient.

**Comment by bludnic** [comment]
@sh7dm I know about Commit Suggestion. @johnleider suggested a lot of changes. I wanted to do this with a single commit and also test it properly.

**Comment by sh7dm** [comment]
@bludnic nice tip: use `add to batch`! ;)
