### PR TITLE
fix(VSelect): scroll to newly selected item in long lists

### LINKED ISSUE #10406: [Bug Report] v-select keyboard lookup on long lists
### Environment
**Vuetify Version:** 2.2.8
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.117
**OS:** Windows 10

### Steps to reproduce
1. Open the select input.
2. Press "V" on keyboard. The list doesn't jump to any value because they are hidden (too far on the list).
3. Click outside the dropdown to close.
4. The value on the input is now "Vermont".

### Expected Behavior
After pressing a key, jump to that value.

### Actual Behavior
If the key is of a hidden item that is not rendered on a long list, it doesn't jump to that value but still selects it, resulting in bad UX.

### Reproduction Link
<a href="https://codepen.io/tamirvs/pen/mdyZoax" target="_blank">https://codepen.io/tamirvs/pen/mdyZoax</a>

### PR DESCRIPTION
**Pull request by KaelWD**
## Description

fixes #10406

## Markup:

<details>

```vue
<template>
  <v-container>
    <v-select :items="items" v-model="selected"></v-select>
    <pre>{{ selected }}</pre>
  </v-container>
</template>

<script>
  export default {
    data: () => ({
      items: [
        'Alabama', 'Alaska', 'American Samoa', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'District of Columbia', 'Federated States of Micronesia', 'Florida', 'Georgia', 'Guam', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Marshall Islands', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Northern Mariana Islands', 'Ohio', 'Oklahoma', 'Oregon', 'Palau', 'Pennsylvania', 'Puerto Rico', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virgin Island', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming',
      ],
      selected: null,
    })
  }
</script>
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

### CODE REVIEW

File: packages/vuetify/src/components/VSelect/VSelect.ts [hunk 1]
```diff
@@ -637,7 +637,9 @@ export default baseMixins.extend<options>().extend({
       })
       const item = this.allItems[index]
       if (index !== -1) {
+        this.lastItem = Math.max(this.lastItem, index + 5)
```
Comment (johnleider) [inline packages/vuetify/src/components/VSelect/VSelect.ts]: Why the +5?

File: packages/vuetify/src/components/VSelect/VSelect.ts [hunk 2]
```diff
@@ -637,7 +637,9 @@ export default baseMixins.extend<options>().extend({
...
         this.setValue(this.returnObject ? item : this.getValue(item))
+        this.$nextTick(() => this.$refs.menu.getTiles())
```
Comment (johnleider) [inline packages/vuetify/src/components/VSelect/VSelect.ts]: Does this need to occur within the next tick?

File: packages/vuetify/src/components/VSelect/VSelect.ts (hunk 1 above)
Comment (KaelWD) [reply packages/vuetify/src/components/VSelect/VSelect.ts:640]: It's arbitrary

**Comment by KaelWD** [comment]
gj merging a pr with failing ci
