### PR TITLE
fix(vselect, vcombobox): update inner input element

### LINKED ISSUE #6310: [Bug Report] v-select doesn't update inner input element
### Versions and Environment
**Vuetify:** 1.4.3
**Vue:** 2.5.21
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 10

### Steps to reproduce
Select something in the select component

### Expected Behavior
the selected item has to be set as value in the input

### Actual Behavior
nothing is set

### Reproduction Link
<a href="https://jsfiddle.net/javaeagle/e8nft0mz/4/" target="_blank">https://jsfiddle.net/javaeagle/e8nft0mz/4/</a>

### PR DESCRIPTION
**Pull request by Mouquette**
Fix #6310
Add a hidden input for users using formData

## Description
Add a hidden input in VSelect and VCombobox. The input will take the

## Motivation and Context
Fix #6310 
Can use formData with VSelect and VCombobox

## How Has This Been Tested?
None

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:
- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)
- [ ] I've added new examples to the kitchen (applies to new features and breaking changes in core library)

### CODE REVIEW

File: packages/vuetify/src/components/VSelect/VSelect.ts [hunk 1]
```diff
@@ -419,6 +421,16 @@ export default baseMixins.extend<options>().extend({
 
       return input
     },
+    genHiddenInput (): VNode {
+      return this.$createElement('input', {
+        domProps: {
```
Comment (johnleider) [inline packages/vuetify/src/components/VSelect/VSelect.ts]: reduce domProps and attrs to 1 line

**Comment by ndesorden** [comment]
Hi,

this fix remove attr name from textfield without add this attribute to input hidden field.
So form serialization for posting is now broken.
