### PR TITLE
fix(VField): Fix label accessibility

### LINKED ISSUE #21025: [Bug Report][3.7.13] v-text-field has two labels rendered for variants filled and solo
### Environment
**Vuetify Version:** 3.7.13
**Vue Version:** 3.5.13
**Browsers:** Firefox 135.0
**OS:** Mac OS 10.15

### Steps to reproduce
- use v-text-field, with single-line false, and either no variant or variant set as filled or solo
- inspect the rendered HTML

### Expected Behavior
there should only be one label tag generated when using no variant or using filled or solo variants

### Actual Behavior
two label tags generated when using no variant or using filled or solo variants

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrNlE1Lw0AQhv/Ksuc2qR94kFjw4lVRPBkPazLRhcnush9REP+7002pm9pCoaHkEJh35p3JPITMyzd3tspvjcm6APyaFx5ag8LDslSMFd1cGBPDKBpt27WKutLKC6nAbpIxbfVnklg7kdHjbkp+dl5y1tYUXVLgWgquSj5oiC0evvy8kYD1sMQYijdAanuE94DClnzbQAQVfGiswZLt4U9tW5dFnr5ouDWVaGXKnYLlSaM+AoSxTlgplCeb2zFqOqB3EhHqkVCbncOmA3sfPNL/MRau3jNuOsAEItVItNT0f9Z0UJ8V7T/m1w17Bx4GnWbSE9w7hpd6ldtc85Xo73yRJ/efpKusNJ458MHQEr2kEv+ZqYA44xfZIlvw11+hibUd)

### Other comments
This has been an issue since Vuetify 3.0.0 and currently exists up to the latest version; 3.7.13 at the time of the report. This is an accessibility issue. Supporting documentation: https://dequeuniversity.com/rules/axe/4.7/form-field-multiple-labels

### PR DESCRIPTION
**Pull request by ikushum**
fixes #21025

## Description
For floating labels, set `aria-hidden` to true if field is active, false if not active

## Markup:

```vue
<template>
  <v-app>
    <v-form>
      <v-container>
        <v-row>
          <v-col cols="12" md="4" sm="6">
            <v-text-field
              label="Regular"
              placeholder="Placeholder"
            ></v-text-field>
          </v-col>

          <v-col cols="12" md="4" sm="6">
            <v-text-field
              label="Solo"
              placeholder="Placeholder"
              variant="solo"
            ></v-text-field>
          </v-col>

          <v-col cols="12" md="4" sm="6">
            <v-text-field
              label="Filled"
              placeholder="Placeholder"
              variant="filled"
            ></v-text-field>
          </v-col>

          <v-col cols="12" md="4" sm="6">
            <v-text-field
              label="Outlined"
              placeholder="Placeholder"
              variant="outlined"
            ></v-text-field>
          </v-col>

          <v-col cols="12" md="4" sm="6">
            <v-text-field
              label="Plain"
              placeholder="Placeholder"
              variant="plain"
            ></v-text-field>
          </v-col>

          <v-col cols="12" md="4" sm="6">
            <v-text-field
              label="Underlined"
              placeholder="Placeholder"
              variant="underlined"
            ></v-text-field>
          </v-col>
        </v-row>
      </v-container>
    </v-form>
  </v-app>
</template>
```

### CODE REVIEW

File: packages/vuetify/src/components/VField/VFieldLabel.tsx [hunk 1]
```diff
@@ -27,7 +27,6 @@ export const VFieldLabel = genericComponent()({
           props.class,
         ]}
         style={ props.style }
-        aria-hidden={ props.floating || undefined }
```
Comment (ikushum) [inline packages/vuetify/src/components/VField/VFieldLabel.tsx:30]: Should I not remove this to prevent breaking change?

Comment (johnleider) [reply packages/vuetify/src/components/VField/VFieldLabel.tsx:30]: I wouldn't remove it unless it's not needed or was invalid before.

**Review by johnleider — APPROVED** [review]
