### PR TITLE
fix(VGrid): fix breakpoints types

### LINKED ISSUE #16604: [Bug Report][3.1.2] No types for VGrid components' props
### Environment
**Vuetify Version:** 3.1.2
**Last working version:** 2.6.14
**Vue Version:** 3.2.39
**Browsers:** Edge 109.0.1518.78
**OS:** Windows 11

### Steps to reproduce
* Clone the repo and checkout to the specified branch
* Run ``npm run typecheck``
* See the huge amount of type errors caused by VRow and VCol components

### Expected Behavior
All VGrid components (VRow and VCol) should have proper types declared. They're also missing in the documentation, probably because of the lack of declared typings as well (which prevents the generator from picking up those props)

### Actual Behavior
* No breakpoint props types are provided and they don't exist in the docs, besides them working perfectly

### Reproduction Link
[https://github.com/jellyfin/jellyfin-vue/tree/vite](https://github.com/jellyfin/jellyfin-vue/tree/vite)

### PR DESCRIPTION
**Pull request by yuwu9145**
fix #16604

## Description

resolves #16604

## Markup:

```vue
<template>
  <v-app>
    <v-main>
      <v-row
        alignSm="end"
        alignMd="end"
        align-lg="end"
        alignXl="end"
        alignXxl="end"
        alignContent="start"
        alignContentSm="start"
        align-content-md="start"
        align-content-lg="start"
        alignContentXl="start"
        alignContentXxl="start"
        justify-sm="space-between"
        justifyMd="space-between"
        justify-lg="space-between"
        justify-xl="space-between"
        justify-xxl="space-between"
      >
        <v-col 
          cols="12"
          sm="7"
          md="7"
          lg="7"
          xl="7"
          xxl="7"
          offset-sm="7"
          offsetMd="7"
          offset-lg="7"
          offsetXl="7"
          offsetXxl="7"
          orderSm="7"
          orderMd="7"
          orderLg="7"
          orderXl="7"
          orderXxl="7"
        ></v-col>
      </v-row>
    </v-main>
  </v-app>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
export default defineComponent({
})
</script>



```

### CODE REVIEW

**Comment by johnleider** [comment]
I think the script should be a separate PR. @KaelWD needs to chime in on this as well.

**Comment by yuwu9145** [comment]
Script has been move to PR #16843

File: packages/vuetify/src/components/VGrid/breakpoints.ts [hunk 1]
```diff
@@ -0,0 +1,3 @@
+export const breakpoints = ['sm', 'md', 'lg', 'xl', 'xxl'] as const // no xs
```
Comment (johnleider) [inline packages/vuetify/src/components/VGrid/breakpoints.ts:1]: we need to come up with a way to propagate this sizing information as part of the framework simply because of how many places it is used in.

Comment (johnleider) [reply packages/vuetify/src/components/VGrid/breakpoints.ts:1]: After thinking on this, I felt the most natural place would be within the display composable. What do you think @vuetifyjs/core-team ?

Comment (yuwu9145) [reply packages/vuetify/src/components/VGrid/breakpoints.ts:1]: What about this change in display composable?

image

**Comment by yuwu9145** [comment]
To make feedback process smooth, I moved breakpoints to display composable.

I also did a local testing via `yarn build` & `yarn link` against issue repo, type errors from VGrid disappears.

**Review by ferferga — COMMENTED** [review]
LGTM

**Review by KaelWD — APPROVED** [review]
