### PR TITLE
fix(application): abstracting applicationable functionality

### LINKED ISSUE #2679: [Bug Report] Navigation Drawer right-watch always resets application padding
### Versions and Environment
**Vuetify:** 0.17.3
**Vue:** 2.5.9
**Browsers:** Firefox 57.0
**OS:** Windows 10

### Steps to reproduce
I installed the webpack-advanced template with vue-cli and had problems with the right temporary Navigation Drawer.
- Click on the top-right button to open the temporary drawer
- Now use the 'Switch drawer' button

### Expected Behavior
Because the right Navigation drawer is temporary, you would expect it to switch from right to left and back, without changing the application paddings, because it is temporary.

### Actual Behavior
You'll see that the toolbar, content and footer lose their left padding. Now the toolbar is behind the left Navigation drawer and it will not come back.

### Reproduction Link
[https://codepen.io/anon/pen/EbOeVq](https://codepen.io/anon/pen/EbOeVq)

### Other comments
The problem is not only in the webpack-advanced template, I think it is also a small mistake in the source of the Navigation Drawer. 

To match the *webpack-advanced* template with the *webpack* and *webpack-ssr* templates, the **app** property of the right Navigation Drawer should probably be changed to **fixed**.

To fix the Navigation Drawer:
File: *vuetify/src/components/VNavigationDrawer/VNavigationDrawer.js*
In the **watch** of property **right** on line **192**
Original: `if (prev != null)`
I think it should be: `if (prev != null && this.app)`

After these changes all works well and as expected.

### PR DESCRIPTION
**Pull request by johnleider**
Turned applicationable into a factory function, added ability to have a `v-bottom-nav` and `v-footer`. Using the **app** prop now automatically adds **fixed** as we will not support any other behavior. Added **height** prop to `v-bottom-nav`, `v-footer`, and `v-system-bar`. Add tons of new tests. Added missing directive **scroll** in `v-toolbar`. Normalized property names in layout files. Added **inset** prop to `v-footer`. Updated style declarations to be lazy.

fixes #2679

### CODE REVIEW

File: src/components/VApp/VApp.js [hunk 1]
```diff
@@ -32,6 +32,9 @@ export default {
   },
 
   computed: {
+    application () {
+      return this.$vuetify.application
+    },
```
Comment (johnleider) [inline src/components/VApp/VApp.js]: Should this be removed? I added it but I'm not sure.

Comment (KaelWD) [reply src/components/VApp/VApp.js]: I don't see any reason to leave it in.

File: src/mixins/applicationable.spec.js [hunk 2]
```diff
@@ -3,26 +3,102 @@ import { test } from '~util/testing'
 import Applicationable from '~mixins/applicationable'
 
 test('applicationable.js', ({ mount }) => {
-  it('should update application on mount', async () => {
+  it.skip('should update application on mount', async () => {
```
Comment (KaelWD) [inline src/mixins/applicationable.spec.js]: Add a `// TODO: reason` when skipping tests

File: src/mixins/button-group.js [hunk 3]
```diff
@@ -8,6 +8,8 @@ export default {
 
   methods: {
     getValue (i) {
+      if (this.buttons.length < 1) return i
+
```
Comment (KaelWD) [inline src/mixins/button-group.js]: I don't think this is relevant

File: src/components/VToolbar/VToolbar.js [hunk 4]
```diff
@@ -241,6 +242,10 @@ export default {
       }, this.$slots.extension))
     }
 
-    return h('nav', data, children)
+    return h('nav', data, [
+      h('div', {
+        staticClass: 'toolbar__wrapper'
```
Comment (KaelWD) [inline src/components/VToolbar/VToolbar.js]: What's this for? I don't see it in any stylesheets

File: src/mixins/applicationable.js [hunk 5]
```diff
@@ -1,15 +1,51 @@
...
+  return {
+    props: {
+      absolute: Boolean,
+      app: Boolean,
+      fixed: Boolean
+    },
+
+    computed: {
+      applicationProperty () {
+        return value
```
Comment (KaelWD) [inline src/mixins/applicationable.js]: This should probably be data instead of a computed property

File: src/mixins/applicationable.js [hunk 6]
```diff
@@ -1,15 +1,51 @@
...
-  props: {
-    app: Boolean
-  },
-
-  watch: {
-    app () {
-      this.updateApplication()
-    }
-  },
+export default function (value, events = []) {
```
[the remark this answers is not in the document]
Comment (KaelWD) [reply src/mixins/applicationable.js]: And that somehow ticked off codebeat 😄
