### PR TITLE
fix(VColorPicker): extractColor util

### LINKED ISSUE #12183: [Bug Report] Color Picker breaks once you select transparent color
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.12
**Browsers:** Chrome 84.0.4147.135
**OS:** Mac OS 10.15.6

### Steps to reproduce
- Go to Model example in the Vuetify documentation https://vuetifyjs.com/en/components/color-pickers/#color-pickers
- Choose RGBA
- Slide "alpha" control all the way to the left (in order to set a transparent color)

### Expected Behavior
You can set a transparent color (with property "a" equals to 0). You can continue to use color picker after that

### Actual Behavior
- the "a" property disappears from the return, 
- the alpha bar disappears, 
- there is no way to bring "alpha" control back whatever you do, even when you switch to hsla and back. Only page refresh fixes it

### PR DESCRIPTION
**Pull request by ElijahKotyluk**
## Description

fixes #12183 
## How Has This Been Tested?

Visually/Playground && Jest
## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
<template>
  <v-container>
    <v-row>
      <v-col
        cols="12"
        md="4"
      >
        <v-btn
          v-for="t in types"
          :key="t"
          class="my-4"
          block
          @click="type = t"
        >{{ t }}</v-btn>
      </v-col>
      <v-col
        class="d-flex justify-center"
      >
        <v-color-picker v-model="color"></v-color-picker>
      </v-col>
      <v-col
        cols="12"
        md="4"
      >
        <v-sheet
          dark
          class="pa-4"
        >
          <pre>{{ showColor }}</pre>
        </v-sheet>
      </v-col>
    </v-row>
  </v-container>
</template>

<script>
  export default {
    data: () => ({
      types: ['hex', 'hexa', 'rgba', 'hsla', 'hsva'],
      type: 'hex',
      hex: '#FF00FF',
      hexa: '#FF00FFFF',
      rgba: { r: 255, g: 0, b: 255, a: 1 },
      hsla: { h: 300, s: 1, l: 0.5, a: 1 },
      hsva: { h: 300, s: 1, v: 1, a: 1 },
    }),

    computed: {
      color: {
        get () {
          return this[this.type]
        },
        set (v) {
          this[this.type] = v
        },
      },
      showColor () {
        if (typeof this.color === 'string') return this.color

        return JSON.stringify(Object.keys(this.color).reduce((color, key) => {
          color[key] = Number(this.color[key].toFixed(2))
          return color
        }, {}), null, 2)
      },
    },
  }
</script>
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Review by johnleider — COMMENTED** [review]
This might be a good use-case for `it.each`

https://jestjs.io/docs/en/api#testeachtablename-fn-timeout

**Comment by ElijahKotyluk** [comment]
Good call, looks a lot better now.

File: packages/vuetify/src/components/VColorPicker/util/index.ts [hunk 1]
```diff
@@ -144,9 +144,10 @@ export function extractColor (color: VColorPickerColor, input: any) {
   }
 
   if (typeof input === 'object') {
-    if (has(input, ['r', 'g', 'b'])) return stripAlpha(color.rgba, !input.a)
-    else if (has(input, ['h', 's', 'l'])) return stripAlpha(color.hsla, !input.a)
-    else if (has(input, ['h', 's', 'v'])) return stripAlpha(color.hsva, !input.a)
+    const shouldStrip = typeof input.a === 'number' && input.a === 0 ? !!input.a : !input.a
```
Comment (sh7dm) [inline packages/vuetify/src/components/VColorPicker/util/index.ts:147]: Why is `typeof input.a === 'number'` necessary here, strict comparison to number checks type as well.

**Review by sh7dm — APPROVED** [review]
