### PR TITLE
fix(VDataTable): detect changes in options prop

### LINKED ISSUE #8707: [Bug Report] Data table options do not sync when directly updating a prop
### Environment
**Vuetify Version:** 2.0.10
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Mac OS 10.14.6

### Steps to reproduce
1. Open sandbox link
2. Go to page 2 ( using the table footer control ). The button is not visible, because fonts are not imported
3. Click the Set page to 1 button

### Expected Behavior
1. Change is detected
2. Table state is updated
3. update:options event is triggered

### Actual Behavior
Change is not detected by the watcher

### Reproduction Link
<a href="https://codesandbox.io/s/vue-template-6qzdd" target="_blank">https://codesandbox.io/s/vue-template-6qzdd</a>

### Other comments
Likely cause : https://github.com/vuetifyjs/vuetify/blob/485a88cbc47bf8741fe360aa18ea9f78396b4579/packages/vuetify/src/components/VData/VData.ts#L193

### PR DESCRIPTION
**Pull request by nekosaur**
## Description
added proxy computed object for options prop to get around vue
limitation of new/old value being the same for watched objects

## Motivation and Context
fixes #8707

## How Has This Been Tested?

playground

## Markup:

<details>

```vue
<template>
  <div>
     <v-container>
        <v-data-table
          :headers="headers"
          :items="items"
          :options.sync="paginationOptions"
          :footer-props="{
          itemsPerPageOptions: paginationOptions.itemsRange,
          showCurrentPage: true,
          showFirstLastPage: true,
        }"
          @update:options="updated"
        />
        <v-btn @click="updatePage">Set page to 1</v-btn>
      </v-container>
  </div>
</template>

<script>
export default {
  data: () => ({
    paginationOptions: {
      sortBy: ["h1"],
      sortDesc: [true],
      page: 1,
      itemsPerPage: 2,
      itemsRange: [1, 2]
    },
    headers: [
      { text: "h1", value: "itemData1" },
      { text: "h2", value: "itemData2" },
      { text: "h3", value: "itemData3" }
    ],
    items: [
      { itemData1: 1, itemData2: "dwdd2d", itemData3: "awdawdaw" },
      { itemData1: 2, itemData2: "dwdd2d", itemData3: "awdawdaw" },
      { itemData1: 3, itemData2: "dwdd2d", itemData3: "awdawdaw" },
      { itemData1: 4, itemData2: "dwdd2d", itemData3: "awdawdaw" }
    ]
  }),
  methods: {
    updatePage() {
      this.paginationOptions.page = 1;
    },
    updated() {
    }
  }
}
</script>

```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)
- [ ] I've added new examples to the kitchen (applies to new features and breaking changes in core library)

### CODE REVIEW

File: packages/vuetify/src/components/VData/VData.ts [hunk 1]
```diff
@@ -187,10 +187,13 @@ export default Vue.extend({
 
       return props
     },
+    computedOptions (): DataOptions {
+      return Object.assign({}, this.options) as DataOptions
```
Comment (sh7dm) [inline packages/vuetify/src/components/VData/VData.ts]:
```suggestion
      return { ...this.options } as DataOptions
```
