### PR TITLE
fix(VDatePicker): correctly show weeks and dates

### LINKED ISSUE #13058: [Bug Report] Issue with days and weeks in datepicker
### Environment
**Vuetify Version:** 2.4.3
**Vue Version:** 3.0.5
**Browsers:** Chrome 88.0.4324.150
**OS:** Windows 10

### Steps to reproduce
1. Set props for datepicker: 

```
      first-day-of-week="1"
      show-week
      show-adjacent-months
```
2. Change month until the number of the last week disappears and the date in the last line in sunday disappears.
Image of issue with datepicker

### Expected Behavior
Display the last week number when current month has no days in last line
Display the last day of the week on the last line if the last line contains a week number

### Actual Behavior
No last week number when current month has no days in last line
No last day of the week on the last line if the last line contains a week number

### Reproduction Link
<a href="https://codepen.io/denisemenov/pen/poNgPRM?editors=101" target="_blank">https://codepen.io/denisemenov/pen/poNgPRM?editors=101</a>

### PR DESCRIPTION
**Pull request by inottn**
## Description

fixes #13058

## Motivation and Context

fixes #13058

## How Has This Been Tested?

add unit test case
## Markup:

<details>

```vue
<template>
  <v-container>
    <v-date-picker
      v-model="picker"
      first-day-of-week="1"
      show-week
      show-adjacent-months
    ></v-date-picker>
  </v-container>
</template>

<script>
export default {
  data: () => ({
    picker: '2021-02-01',
  }),
};
</script>

```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

File: packages/vuetify/src/components/VDatePicker/VDatePickerDateTable.ts [hunk 1]
```diff
@@ -115,7 +115,7 @@ export default mixins(
         if (rows.length % (this.showWeek ? 8 : 7) === 0) {
```
Comment (jacekkarczmarczyk) [inline packages/vuetify/src/components/VDatePicker/VDatePickerDateTable.ts:115]: extract `this.showWeek ? 8 : 7` to a separate var (in line 128 as well)

otherwise looks good

Comment (inottn) [reply packages/vuetify/src/components/VDatePicker/VDatePickerDateTable.ts:115]: Thanks for review. Do you have a suggestion about variable name?

Comment (jacekkarczmarczyk) [reply packages/vuetify/src/components/VDatePicker/VDatePickerDateTable.ts:115]: Maybe rowLength or cellsInRow

**Review by jacekkarczmarczyk — APPROVED** [review]
