### PR TITLE
fix(VNavigationDrawer): add RTL support

### LINKED ISSUE #15364: [Bug Report][3.0.0-beta.5] Navigation Drawer location="right" position is incorrect  when RTL is active
### Environment
**Vuetify Version:** 3.0.0-beta.5
**Vue Version:** 3.2.36
**Browsers:** Chrome 103.0.0.0
**OS:** Windows 10

### Steps to reproduce
- Add v-navigation drawer and set location to right
- set rtl enabled locale

### Expected Behavior
drawer position shoud be in the right side

### Actual Behavior
shows in wrong position

### Reproduction Link
<a href="https://codepen.io/uzvoolaiyaxe-logicstreak-com/pen/ExEaMYv" target="_blank">https://codepen.io/uzvoolaiyaxe-logicstreak-com/pen/ExEaMYv</a>

### Other comments
fixed by 
```css
.v-navigation-drawer--end.v-locale--is-rtl, .v-locale--is-rtl .v-navigation-drawer--end{
    left:auto !important;
}
```

### PR DESCRIPTION
**Pull request by nekosaur**
closes #15364

## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [ ] The PR title is no longer than 64 characters.
- [ ] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [ ] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

File: packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.tsx [hunk 1]
```diff
@@ -156,13 +163,13 @@ export const VNavigationDrawer = defineComponent({
             class={[
               'v-navigation-drawer',
               {
-                'v-navigation-drawer--bottom': props.location === 'bottom',
-                'v-navigation-drawer--end': props.location === 'right',
+                'v-navigation-drawer--left': location.value === 'left',
+                'v-navigation-drawer--right': location.value === 'right',
+                'v-navigation-drawer--bottom': location.value === 'bottom',
```
Comment (johnleider) [inline packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.tsx:168]:
```suggestion
                [`v-navigation-drawer--${location.value}`]: !!location.value,
```

**Review by johnleider — CHANGES_REQUESTED** [review]

**Review by johnleider — APPROVED** [review]
