### PR TITLE
fix(VTreeview): emit opened nodes when using load-children

### LINKED ISSUE #9693: [Bug Report] Tree view problem with property open-on-click
### Environment
**Vuetify Version:** 2.1.10
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Mac OS 10.14.6

### Steps to reproduce
Click on item (on the label, not on the toggle button).

### Expected Behavior
Show folder in the right list. (List of openned folders).
Right list show open variable data property. It is updated when tree view open a folder 
 through open.sync="open" property of tree-view.

### Actual Behavior
Folder is not showed on the right list, because open data is not updated when folder is open through label click (it is available because tree-view has open-on-click property). 

### Reproduction Link
<a href="https://codepen.io/IbanLaya/pen/oNNaQQJ" target="_blank">https://codepen.io/IbanLaya/pen/oNNaQQJ</a>

### PR DESCRIPTION
**Pull request by nekosaur**
## Description

using load-children together with open-on-click and clicking on
root div of node, treeview was not emitting the newly opened node.

## Motivation and Context

closes #9693

## How Has This Been Tested?

playground, unit test

## Markup:

<details>

```vue
<template>
  <v-container>
    <v-treeview
      :active.sync="active"
      :items="items"
      :load-children="fetchUsers"
      :open.sync="open"
      activatable
      color="warning"
      open-on-click
      transition
    >
      <template v-slot:prepend="{ item }">
        <v-icon v-if="!item.children">mdi-account</v-icon>
      </template>
    </v-treeview>
    <div><b>Opened:</b> {{ open.join(", ") }}</div>
  </v-container>
</template>

<script>
  const pause = ms => new Promise(resolve => setTimeout(resolve, ms))

  export default {
    data: () => ({
      active: [],
      avatar: null,
      open: [],
      users: [],
    }),

    computed: {
      items () {
        return [
          {
            id: 'Folder1',
            name: 'Folder1',
            children: this.users,
          },
        ]
      },
      selected () {
        if (!this.active.length) return undefined

        const id = this.active[0]

        return this.users.find(user => user.id === id)
      },
    },

    watch: {
      selected: 'randomAvatar',
    },

    methods: {
      async fetchUsers (item) {
        // Remove in 6 months and say
        // you've made optimizations! :)
        await pause(1500);
        item.children.push(...([
          {
            id: item.id + "_1",
            name: item.id + "_1",
            children: []
          },
          {
            id: item.id + "_2",
            name: item.id + "_2",
            children: []
          },
          {
            id: item.id + "_3",
            name: item.id + "_3",
            children: []
          }
        ]));
        return;
      }
    }
  }
</script>

```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

File: packages/vuetify/src/components/VTreeview/VTreeviewNode.ts [hunk 1]
```diff
@@ -284,7 +284,7 @@ const VTreeviewNode = baseMixins.extend<options>().extend({
             if (this.disabled) return
 
             if (this.openOnClick && this.hasChildren) {
-              this.open()
+              this.checkChildren().then(() => this.open())
```
Comment (jacekkarczmarczyk) [inline packages/vuetify/src/components/VTreeview/VTreeviewNode.ts:287]:
```suggestion
              this.checkChildren().then(this.open)
```
