### PR TITLE
fix(useDisplay): more intuitive use of `mobile-breakpoint`

### LINKED ISSUE #19883: [Bug Report][3.6.4] Mobile breakpoint doesn't work anymore
### Environment
**Vuetify Version:** 3.6.4
**Last working version:** 3.6.3
**Vue Version:** 3.4.0
**Browsers:** Chrome 125.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
minimize the window on vuetify version 3.6.3 then do the same on version 3.6.4.

### Expected Behavior
VDataTable mobile appearance 

### Actual Behavior
There is no breakpoint the VDataTable is not flex.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtlW9v2jAQxr/KKZpEK5U/AQID0UmsGkyd2KrCtEmFF25yQDQnjmyHiSG++y4JCbQEBdTyhviSx/e7x/b5aWMoaVf7QVBZhWh0jZ5GL+BM46epD9BblVkQxI/xwBa+Zq6PcheKgw7TrKzZM0fouiRXt1PDZlJNDegukTkoo8juiYK24EJS5JmHSEMumOP6C6imaaqv80SRBKNXPcCjobKlG2hQqMOE0vUCITVsQOIctjCXwoMSVVaKPgdK7SsNERzcwlOSb5OW4jMPu1AaCOnAKFSa+YvSTfpyKaTCQPxF2YWmVcvi8xA5iYZMCU7Ae4GQ7sL16dXPcX8fDaRrUxLLqtXSOba7/9ccE1ScwUg4yGGcD9JqH4F84WhrSnImSLtDvwKQz6NfMGrkE1i1xgVWDFF6zF8fU5AbRXb0Q8eFx3HrBEfHfAcOs9YpBrlb4koKjhrumMekOLE0b94jrXoxywNltJcIHdPMx2i009V9my9mMcs9W4RMwqA8WQcHk79YpbZ1iSnfjj05g2PE/jl0bn6XrXwI8+MlW+WeBcw/4qi3ijm+u0oxH4aT8uMJN1qXuJEPYpoNq1noCEobHVTl/mhIPCdo6u9xkk3ToiP0gmd22Hp3twB1X2rQV2kHBu1qHp8t2kBxxyvdwB9cUyQqgQaMu4soL3VlqUv7SjPl16yUTLqv7mAC9J08+YAqhmTj7tSRB+ck/hFbkskSh84RPkSOwdWH60wbe5jPOruOLr/kuqOLztjeGI1Ks1JvG9FDq9I2Zv8Bpl09nA==)

### Other comments
VDataTableComponent since version 3.6.4 is no longer 'flex'. Before this version you had a breakpoint that transformed the VDataTable into It's mobile appearance.

### PR DESCRIPTION
**Pull request by J-Sek**
resolves #19883 

## Description
The `mobile-breakpoint` prop requires `:mobile='null'` to work, otherwise it is ignored. It is not intuitive and developers ask about it on Discord or assume it does not work, because components' API docs don't mention this requirement.

> The reason Docs do not use description from api-generator » ... » [display.json](https://github.com/vuetifyjs/vuetify/blob/master/packages/api-generator/src/locale/en/display.json) is that most components already have their own description for `mobile` prop.

I wish we could let user work with `mobile-breakpoint` and don't bother about the other prop. The logic could then be:
1. If `mobile === true`, then force mobile view
2. If `mobile-breakpoint` is set, accept it's value to resolve mobile state
3. All defaults (not using these props) means no responsiveness (as suggested by [comment](https://github.com/vuetifyjs/vuetify/issues/19726#issuecomment-2092005717) under #19726)
4. `mobile='null'` makes the component rely on default mobile breakpoint

## Markup:

```vue
<template>
  <v-app theme="dark">
    <v-container>
      <pre class="mt-8">
      $vuetify.display.width: {{ $vuetify.display.width }}px
      mobile-breakpoint="md" instructs labels to hide below the 960px (md breakpoint)
      </pre>
      <v-stepper mobile-breakpoint="md">
        <v-stepper-header>
          <template v-for="(item, i) in items" :key="i">
            <v-divider v-if="i" />
            <v-stepper-item v-bind="item" />
          </template>
        </v-stepper-header>
      </v-stepper>

      <pre class="mt-8">
      $vuetify.display.width: {{ $vuetify.display.width }}px
      :mobile-breakpoint="800" instructs labels to hide below the 800px
      </pre>
      <v-stepper :mobile-breakpoint="800">
        <v-stepper-header>
          <template v-for="(item, i) in items" :key="i">
            <v-divider v-if="i" />
            <v-stepper-item v-bind="item" />
          </template>
        </v-stepper-header>
      </v-stepper>
    </v-container>
  </v-app>
</template>

<script setup lang="ts">
  const items = Array.from({ length: 4 }).map((_, i) => ({
    title: `Step ${i + 1}`,
    subtitle: `Step ${i + 1} subtitle`,
    value: i + 1,
  }))
</script>
```

### CODE REVIEW

File: packages/vuetify/src/composables/display.ts [hunk 1]
```diff
@@ -231,14 +231,17 @@ export function useDisplay (
...
-      : display.thresholds.value[props.mobileBreakpoint]
-
-    return display.width.value < breakpointValue
+    if (props.mobile) {
+      return true
+    } else if (typeof props.mobileBreakpoint === 'number') {
+      return display.width.value < props.mobileBreakpoint
+    } else if (props.mobileBreakpoint) {
+      return display.width.value < display.thresholds.value[props.mobileBreakpoint]
+    } else if (props.mobile == null) {
```
Comment (johnleider) [inline packages/vuetify/src/composables/display.ts:240]:
```suggestion
    } else if (props.mobile === null) {
```

**Review by johnleider — APPROVED** [review]

**Review by johnleider — APPROVED** [review]
