### PR TITLE
fix(VDataTable): include rows that exclusively match custom filters

### LINKED ISSUE #9887: [Bug Report] DataTable seach using custom filter function inside TableHeader doesn't work properly
### Environment
**Vuetify Version:** 2.1.13
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Windows 10

### Steps to reproduce
Try to search something using search text field

### Expected Behavior
It works properly

### Actual Behavior
It doesn't search properly

### Reproduction Link
<a href="https://codesandbox.io/s/condescending-butterfly-2099q?fontsize=14&hidenavigation=1&theme=dark" target="_blank">https://codesandbox.io/s/condescending-butterfly-2099q?fontsize=14&hidenavigation=1&theme=dark</a>

### Other comments
If all headers has custom search function or if noone has - it works. But not in that case.

### LINKED ISSUE #11179: [Bug Report] Custom filters on VDataTable columns are not evaluated if the search term does not match other columns
### Environment
**Vuetify Version:** 2.3.0-beta.0
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.163
**OS:** Mac OS 10.15.4

### Steps to reproduce
- Add a custom `filter` function to any column header config
- This custom filter should represents a unique match that won't exist on any other column (example in the Codepen link is a case sensitive comparison to the Dessert name)
- Use a search term that should only match a row on the column with a custom filter

### Expected Behavior
The custom filter should match the row before and after the search term is entered.

### Actual Behavior
The custom filter is run before any search term is entered. Once a search term is entered it will never match the row because `headersWithCustomFilters` are run after matches are determined by `headersWithoutCustomFilters`

### Reproduction Link
<a href="https://codepen.io/Ignigena/pen/dyYOmxj?editors=1011" target="_blank">https://codepen.io/Ignigena/pen/dyYOmxj?editors=1011</a>

### PR DESCRIPTION
**Pull request by Ignigena**
## Description

Currently, if a custom filter is used on a header config, it won't evaluate on any `search` term that exclusively match this custom filter. The term must match one or more columns that fall under `headersWithoutCustomFilters`.

Closes #9887 

## Motivation and Context

Behaviour is inconsistent since the custom filter will be evaluated up until the point that a search term is entered. Once a term is entered, even if the term matches the custom filter, the row is excluded from the results if none of the other columns match.

A simple example is provided in the Codepen in the linked issue: by adding a custom filter with a case-sensitive search for Dessert Name, the ability to search is lost.

## How Has This Been Tested?

- Tested in our own project which uses Vuetify
- Playground reproduction (below)
- Added a unit test verifying the Codepen/playground reproduction

## Markup:

<details>

```vue
<template>
  <v-data-table
    :headers="headers"
    :items="desserts"
    :search="search"
    item-key="name"
  >
    <template v-slot:top>
      <v-text-field v-model="search" label="Search (EXACT MATCH)" class="mx-4"></v-text-field>
    </template>
  </v-data-table>
</template>

<script>
  export default {
    data: () => ({
      search: '',
      headers: [
        {
          text: 'Dessert (100g serving)',
          align: 'left',
          sortable: false,
          value: 'name',
          filter: (value, search) => {
            if (!search) return true
            return value === search
          }
        },
        { text: 'Calories', value: 'calories' },
        { text: 'Fat (g)', value: 'fat' },
        { text: 'Carbs (g)', value: 'carbs' },
        { text: 'Protein (g)', value: 'protein' },
        { text: 'Iron (%)', value: 'iron' }
      ],
      desserts: [
        {
          value: false,
          name: 'Frozen Yogurt',
          calories: 159,
          fat: 6.0,
          carbs: 24,
          protein: 4.0,
          iron: '1%',
          brands: [
            {
              name: 'Blue Bell',
              calories: 237,
              fat: 9.0,
              carbs: 37,
              protein: 4.3,
              iron: '1%'
            },
            {
              name: 'Tilamook',
              calories: 262,
              fat: 16.0,
              carbs: 23,
              protein: 6.0,
              iron: '7%'
            }
          ]
        },
        {
          value: false,
          name: 'Ice cream sandwich',
          calories: 237,
          fat: 9.0,
          carbs: 37,
          protein: 4.3,
          iron: '1%'
        },
        {
          value: false,
          name: 'Eclair',
          calories: 262,
          fat: 16.0,
          carbs: 23,
          protein: 6.0,
          iron: '7%'
        },
        {
          value: false,
          name: 'Cupcake',
          calories: 305,
          fat: 3.7,
          carbs: 67,
          protein: 4.3,
          iron: '8%'
        },
        {
          value: false,
          name: 'Gingerbread',
          calories: 356,
          fat: 16.0,
          carbs: 49,
          protein: 3.9,
          iron: '16%'
        },
        {
          value: false,
          name: 'Jelly bean',
          calories: 375,
          fat: 0.0,
          carbs: 94,
          protein: 0.0,
          iron: '0%'
        },
        {
          value: false,
          name: 'Lollipop',
          calories: 392,
          fat: 0.2,
          carbs: 98,
          protein: 0,
          iron: '2%'
        },
        {
          value: false,
          name: 'Honeycomb',
          calories: 408,
          fat: 3.2,
          carbs: 87,
          protein: 6.5,
          iron: '45%'
        },
        {
          value: false,
          name: 'Donut',
          calories: 452,
          fat: 25.0,
          carbs: 51,
          protein: 4.9,
          iron: '22%'
        },
        {
          value: false,
          name: 'KitKat',
          calories: 518,
          fat: 26.0,
          carbs: 65,
          protein: 7,
          iron: '6%'
        }
      ]
    })
  }
</script>

```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

File: packages/vuetify/src/components/VDataTable/VDataTable.ts [hunk 1]
```diff
@@ -49,17 +49,13 @@ function searchTableItems (
...
-  }
-
-  if (headersWithCustomFilters.length) {
-    filtered = filtered.filter(item => headersWithCustomFilters.every(filterFn(item, search, defaultFilter)))
-  }
+  if (!(search && headersWithoutCustomFilters.length) && !headersWithCustomFilters.length) return items
 
-  return filtered
+  return items.filter(item =>
+    (headersWithCustomFilters.length && headersWithCustomFilters.every(filterFn(item, search, defaultFilter))) ||
```
Comment (johnleider) [inline packages/vuetify/src/components/VDataTable/VDataTable.ts:56]: this should be broken up so it's easier to understand, possibly with some comments

Comment (Ignigena) [reply packages/vuetify/src/components/VDataTable/VDataTable.ts]: I broke up the callback a bit and added some comments so it's a bit easier to parse the flow of logic. Let me know if this is what you were going for or if you'd like something else 🙂

**Comment by johnleider** [comment]
Requesting **Final** comments from @vuetifyjs/contributors @vuetifyjs/core-team
