### PR TITLE
Fix several radio issues

### LINKED ISSUE #1654: v-radios all have an input with name test
### Steps to reproduce
Insert a v-radio and inspect the element using the browser dev tools. You will see an input with the name test as part of the node.

### Versions
Vue 2.4.2, Vuetify 0.15.2, Edge 15

### What is expected ?
Either an input with individual name or no input (?)

### What is actually happening ?
All v-radios have an input with name test

### Reproduction Link
https://codepen.io/smares/pen/RZXZjz

### PR DESCRIPTION
**Pull request by KaelWD**
Fixes #1654, #1661, and #1667

### CODE REVIEW

File: src/components/VBtn/VBtn.vue [hunk 1]
```diff
@@ -126,9 +126,9 @@
       tag === 'button' && (data.attrs.type = this.type)
       this.loading && children.push(this.genLoader())
 
-      if (typeof this.value !== 'undefined') {
-        data.attrs.value = this.value
-      }
+      data.attrs.value = ['string', 'number'].includes(typeof this.value)
+        ? this.value
+        : JSON.stringify(this.value)
```
Comment (johnleider) [inline src/components/VBtn/VBtn.vue]: Didn't we talk about this and decided to not stringify the value?

Comment (KaelWD) [reply src/components/VBtn/VBtn.vue]: Yeah, but `value = false` would result in no value at all, and I figured it'd make sense to have similar behaviour for both radios and button toggles. I did try using `toString` in one of the other commits in this PR, but it was messy and still didn't work properly.
