### PR TITLE
fix(defaults): explicitly define inherited props

### LINKED ISSUE #16837: [Bug Report][3.1.7] Global defaults not working for showArrows and centerActive in VTabs
### Environment
**Vuetify Version:** 3.1.7
**Vue Version:** 3.2.47
**Browsers:** Chrome 110.0.0.0
**OS:** Windows 10, Linux

### Steps to reproduce
define global defaults for VTabs, e.g.
```js
export const vuetify = createVuetify({
  	defaults: {
		VTabs: {
			bgColor: 'primary',
			showArrows: true,
			centerActive: true,
		},
	},
})
```

### Expected Behavior
tabs should show arrows on vertical overflow and center the active tab.

### Actual Behavior
alas, they are not. the `bgColor` setting is working though.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVU9uO2jAQ/RXLL2wlk+y126LsalF/YbUveB9CYsAlsSN7EopQ/r3jSyBAW6l5iDRz5szljGdxoF0rQK72yU9LZ1TWjTZADqQwIgfxETDSk5XRNZnE2AlXXIlfPrTQygKJAHk5J94cuCIENqIWM0xailXeVvAe7EmZm+2E9MzFcIigxUBMDxw+3vPlyeKwXP/QlTZIbIysc7OfIDNAdqN3c2P0DuPBtOIIFEKBMPMCZIcVR5CrGv79F64oo/OmSXAK1CCzhZENECugbV65OmpixGqshFchjJ/7AtgvCoBRN0+YMyCAM6Bzccvu2D17YI/siX1lz+wb+87ubj+5ytJQDguhAaJuKtQPLUKybpo3rgOCHxp1LlW0nGDZAIUvK3QpXqNIWeotIi3ZabOVak1yS9aVXubVsAZGli1E2knAgZmrMmJjDY+oEURpSIYGstQ1EzTHzrqpm/vk4IDdI7F64fSoFacjykAaexxrpQ1yECBSeTE5PQ+ZbcU+RFwhXV614k/YWV0Oh4PLTPr+rJ3U9zOeKnjssBA0jxtxRthVlo52iO8qvB6MbPDCtML35W+CRwDn8U/cr9TdorM53QA0dpamrWq266TQdfqGWGpaBbIW01LXbw/JffL4nJbSwtifCFtPl26TwmBFTv15xeTuJv9WIMKY9y6JaaNrWuHULu9VvhSLdMJMjVClMML8s/mL2LMBLrCrIVxNXE+PglZSbe2FloX1Oi6G1v5/Op/B0fEke9ozGrrDep5BP38DETDHyA==)

### LINKED ISSUE #17075: [Bug Report][3.1.8] v-tabs next-icon prev-icon seems to be working but not included in documentation nor in definition
### Environment
**Vuetify Version:** 3.1.8
**Vue Version:** 3.2.47
**Browsers:** Chrome 111.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
in v-tabs use next-icon prev-icon

### Expected Behavior
ts Definition is available(volar suggestion)
and api-document has the definition

### Actual Behavior
no definition at all

### Reproduction Link
[https://codesandbox.io/s/recursing-andras-gqqrew?file=/src/App.vue](https://codesandbox.io/s/recursing-andras-gqqrew?file=/src/App.vue)

### PR DESCRIPTION
**Pull request by johnleider**
## Motivation and Context
fixes #16837
fixes #17075

## Markup:
<details>

```vue
<template>
  <v-app>
    <div class="ma-4 pa-4">
      <v-defaults-provider :defaults="defaults">
        <v-tabs center-active>
          <v-tab>One</v-tab>
          <v-tab>Two</v-tab>
          <v-tab>Three</v-tab>
        </v-tabs>
      </v-defaults-provider>
    </div>
  </v-app>
</template>

<script setup>
  import { ref } from 'vue'

  const defaults = {
    VTabs: {
      bgColor: 'primary',
      showArrows: 'always',
    },
  }
</script>

```
</details>

### CODE REVIEW

File: packages/vuetify/src/components/VColorPicker/VColorPicker.tsx [hunk 1]
```diff
@@ -117,69 +114,74 @@ export const VColorPicker = defineComponent({
...
+          elevation={ props.elevation }
+          theme={ props.theme }
+          class={[
+            'v-color-picker',
+          ]}
+          style={{
+            '--v-color-picker-color-hsv': HSVtoCSS({ ...(currentColor.value ?? nullColor), a: 1 }),
+          }}
+          { ...sheetProps }
+          maxWidth={ props.width }
```
Comment (KaelWD) [inline packages/vuetify/src/components/VColorPicker/VColorPicker.tsx:132]: I think this'll override any maxWidth from props, should that be added to the omit?

File: packages/vuetify/src/components/VTabs/VTabs.tsx [hunk 2]
```diff
@@ -59,14 +55,15 @@ export const VTabs = genericComponent()({
...
-    },
 
+    ...makeVSlideGroupProps(),
     ...makeDensityProps(),
     ...makeTagProps(),
+
+    direction: {
+      type: String as PropType<'horizontal' | 'vertical'>,
+      default: 'horizontal',
+    },
```
Comment (KaelWD) [inline packages/vuetify/src/components/VTabs/VTabs.tsx:66]: Why move this?

File: packages/vuetify/src/components/VTabs/VTabs.tsx [hunk 3]
```diff
@@ -59,14 +55,15 @@ export const VTabs = genericComponent()({
...
-      type: [Boolean, String] as PropType<boolean | 'force'>,
-      default: 'force',
-    },
 
+    ...makeVSlideGroupProps(),
     ...makeDensityProps(),
     ...makeTagProps(),
+
+    direction: {
+      type: String as PropType<'horizontal' | 'vertical'>,
```
Comment (KaelWD) [inline packages/vuetify/src/components/VTabs/VTabs.tsx:64]: Should this just be added to VSlideGroup instead?

**Review by KaelWD — APPROVED** [review]
