### PR TITLE
fix(VSelect): add backspace handler to clear

### LINKED ISSUE #22422: [Bug Report][3.11.2] v-select can't be cleared from keyboard
### Environment
**Vuetify Version:** 3.11.2
**Vue Version:** 3.5.25
**OS:** macOS 10.15.7 (current)

### Steps to reproduce
1. select some item
2. try to clear selected item with keyboard

### Expected Behavior
1. use keyboard only
2. select some item from dropdown list
3. focus on clear icon and clear selection  

### Actual Behavior
clear icon has tabindex="-1" and can't be focused

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVkMFqwzAQRH/F7MUXRyEJuRg3UALtB7TQg+3DxtkGtbJWSEpoMf73rqMUJzrNvhmkWdUDPDunLmeCEqpIvTMYadfY6rJA50RkWSa6YxtRW/KJXFkgQ128zXI6Q+jxYGhGBg9knhp4S1GYnVLLY0GsOt+j0Z/srca8yPI9G/Z45Em/iNTHK34l9qeUeKcfDJP4+OVe21PezhfvquV/sVt3mR/KTyBtVi3v9oUCjLbfQX0FtvIXQwNdCA2UdTuKp3vHPi56dHeBBKfQMI4wFrBRW7XeSnyjViu1hiL6M7V/THJu2A==)

### Other comments
The same issue with other inputs is presented but v-select can't be cleared with backspace button

### PR DESCRIPTION
**Pull request by Haviles04**
## Description
fixes #22422

## Markup:

```vue
<template>
  <v-app theme="dark">
    <v-container class="d-flex align-center ga-3" max-width="600">
      <v-select v-model="selectedItems" :items="items" clearable multiple />
    </v-container>
  </v-app>
</template>

<script setup>
  import { shallowRef } from 'vue'
  const selectedItems = shallowRef([])
  const items = ['New York', 'California', 'New Jersey', 'Maine']
</script>

```

### CODE REVIEW

File: packages/vuetify/src/components/VSelect/VSelect.tsx [hunk 1]
```diff
@@ -236,6 +236,13 @@ export const VSelect = genericComponent<new <
         menu.value = false
       }
 
+      if (e.key === 'Backspace') {
```
Comment (J-Sek) [inline packages/vuetify/src/components/VSelect/VSelect.tsx]: I have a feeling we should guard it with additional `prop.clearable`
