### PR TITLE
fix(VFileUpload): adding/replacing files with dropzone click

### LINKED ISSUE #22737: [Bug Report][3.12.3] VFileUpload with `multiple` not clickable for density="compact" when file is added
### Environment
**Vuetify Version:** 3.12.3
**Vue Version:** 3.5.30
**OS:** Linux

### Steps to reproduce
1. Click the compact Dropzone
2. Choose a file
3. Try to click the Dropzone again

### Expected Behavior
The Dropzone is clickable when a file is currently added even for density="compact". This is important to change the file.

### Actual Behavior
The Dropzone is not clickable when a file is currently added.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlVdtu00AQ/ZXFPHgjJeugghBRA0UIBBIPCBAvdR+29jhZ2IvZXYdGVf6d2YvTJK1QJR6sOHM558zs7PjythCqN9bPFO/ZT2d0sShua01InR2uLhYkWoJtM0D4Xxdr73u3qKqm1ZjWghQbyzT4SvequsCwyg7aCwWz1qiLM/aCnc2rVjh/aGfg1Ozamj8OLKLUxfSAp0LjBuzMgm7Bgn0s70naEfeJ75/8XnTbR3DmyIvnbM7OEks2zSS/doEiQgfkXa13xbSQQv9yJ81uXGz05SjgvzgjWEC6SoTONtXbvmcYhIznHlQvuYfXIeR8M+N9H1/jn8Zoz4UGm03R2AkJs6GXhrekBe2E3y5Rs1E9b3xdkGrMr04BgiXhn1cHvFmUwkDmHYpKw0ZuSWMBQ1At2ZHOGkVKVF3Weh+QK9272Vj7XVDIHp257jsn2hz4oUdLrVGs8wQFkuUdM8VnUmu0MvR3YsXAWmM/ct1KsBgJZPmahFQjIfkoYEJKGRzQrGhvUwaHnpZP8b1EY64+ykjlW1BmA9/8VsJ3vqIY8wX1CweMS0kvQ+M/YF/pZErC+6dATidXkaAbdOOF0eQYhNBJurepRo+WJWlNMyjQnv0ewG6/gYTGo/ry6Tg/fg14N13AcGsAH+QSIjpCnyDCBDn8YJGUBEDWc7xK/r3EHMRM/O/WQrY0BOPwHekLyqO6iEzo2kKXNSZYouEPyYVTagH7u4EpOn+izEloel5EqaRwjw5rSgeY1dAyuJN8EkNRn8Tw8qC4A2cQg97wc2Dlbft+g2if8Y4BzjSiYhFl0BTFHcLfj42jEYNjASl2L/fatFuGE4HLiAaA6N892LVw9vvzzL067iYtx43RYaxjK2NWEngvcBsYVeFGeNNxJeR2+dVcG28Wz+bz6Rk+z/F5gc9LfF7N56Fh9/njvD1WwMOrWbUiSrt4yW6CHLz7HqzgsgUnVloEBqZwHaAvi8jXJI/mg3vix8kyuFsFtYabGJpmZdwa4zXPiTQWFId+/5VroeOD9N+TEcdotfZl/jJUVTwk/BcOqthNi/R5QalxGRfTjksHxyt3tGUNxfR2/7rIaburvxI5mas=)

### Other comments
Drag & Drop still works normally. The onClick handler is unregistered when a file is added, the drop handlers aren't.

### PR DESCRIPTION
**Pull request by Abdulqudus001**
## Description

The file upload input component previously checked if the `hasBrowse` and `hasFiles` is enabled and subsequently disables the click handler. This created a weird behaviour where users are not able to select a different file after the first selection. This PR removes the `hasFiles` check to allow users click the file upload to re-upload another file
Resolves #22737

## Markup:

```vue
<v-container>
      <v-file-upload density="compact" />
</v-container>
```

### CODE REVIEW

**Comment by J-Sek** [comment]
- [x] should not break with `inset-file-list`
- [x] existing problem of clearing the field when user closes file dialog without selection.. it is easier to accidentally click on the drop area than the Browse button, so it would be nice to include a fix

**Comment by Abdulqudus001** [comment]
@J-Sek 

 - I have resolved the bug with the inset-file list
 - For the field clearing when user doesn't select an item, I added a check to only allow setting the model value when  the selectedFile array is not empty

File: packages/vuetify/src/labs/VFileUpload/VFileUploadDropzone.tsx [hunk 1]
```diff
@@ -181,7 +181,7 @@ export const VFileUploadDropzone = genericComponent<VFileUploadDropzoneSlots>()(
           class={[
             'v-file-upload-dropzone',
             {
-              'v-file-upload-dropzone--clickable': !hasBrowse && !hasFiles,
+              'v-file-upload-dropzone--clickable': !hasBrowse,
```
Comment (poettig) [inline packages/vuetify/src/labs/VFileUpload/VFileUploadDropzone.tsx:184]: Question: Shouldn't this have the same condition as the onClick-Listener?

Comment (Abdulqudus001) [reply packages/vuetify/src/labs/VFileUpload/VFileUploadDropzone.tsx:184]: With the `inset-file-list` prop enabled, this section gets hidden when a file is selected, so we don't need to apply the logic here
