### PR TITLE
fix(VTreeview): independent children should be selectable when parent is disabled

### LINKED ISSUE #10770: [Bug Report] v-treeview disable disables both parent and children nodes when mode is independent
### Environment
**Vuetify Version:** 2.1.15
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.122
**OS:** Linux x86_64

### Steps to reproduce
By setting the parent to disabled to true and children disabled to false disables both parent and children

### Expected Behavior
I expected that by setting disabled to false on children even if the parent disabled is true the children should not be disabled.

### Actual Behavior
Parent disabled set to true disables the children nodes even though the children node disabled is set to false

### Reproduction Link
<a href="https://codepen.io/geowan/pen/PoqOOMX" target="_blank">https://codepen.io/geowan/pen/PoqOOMX</a>

### LINKED ISSUE #10990: [Bug Report] Treeview selection-type='independent' if item-disabled on parent cannot select / open children
### Environment
**Vuetify Version:** 2.1.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 80.0.3987.149
**OS:** Mac OS 10.14.6

### Steps to reproduce
Create a v-treeview, give it a tree data, set selection-type='independent' and disable one of the node items that has children by setting the item-disabled prop and then try to open the node.

### Expected Behavior
The disabled parent node should still be able to be opened so that it is possible to select / unselect the children if the selection-type='independent'

### Actual Behavior
Cannot open a disabled parent node when selection-type='independent'

### Reproduction Link
<a href="https://codepen.io/erikjonker/pen/eYNXjKQ" target="_blank">https://codepen.io/erikjonker/pen/eYNXjKQ</a>

### PR DESCRIPTION
**Pull request by nekosaur**
## Description

it was not possible to select children of disabled parents in independent mode

## Motivation and Context

closes #10770, closes #10990

## How Has This Been Tested?

playground, unit test

## Markup:

<details>

```vue
<template>
  <v-container>
    <v-treeview
      open-on-click
      :items="tree"
      item-text="text"
      item-key="id"
      selectable
      :value="selected"
      selection-type="independent"
      item-disabled="item_disabled"
    ></v-treeview>
    <hr/>
    <v-treeview
      open-on-click
      :items="tree"
      item-text="text"
      item-key="id"
      selectable
      :value="selected2"
      item-disabled="item_disabled"
    ></v-treeview>
    <v-treeview
        v-model="selected3"
        activatable
        selectable
        selection-type="independent"
        :active.sync="selected3"
        hoverable
        return-object
        dense
        open-all
        open-on-click
        :items="items"
        :search="search"
        :open.sync="open"
        item-disabled="disabled"
      >
        <template v-slot:prepend="{ item }">
          <v-icon
            v-if="item.children"
            v-text="`mdi-${item.id === 1 ? 'home-variant' : 'folder-network'}`"
          ></v-icon>
        </template>
      </v-treeview>
    </v-container>
  </v-container>
</template>

<script>
  export default {
    data: () => ({
      items: [
        {
          id: 2,
          name: 'Electronics',
          disabled:true,
          children: [
            {
              id: 201,
              name: 'John',
              disabled:false,
            },
            {
              id: 202,
              name: 'Kael',
              disabled:false,
            },

          ],
        },
        {
          id: 3,
          name: 'Administrators',
          children: [
            {
              id: 301,
              name: 'Ranee',
            },
            {
              id: 302,
              name: 'Rachel',
            },
          ],
        },
       ],
      open: [],
      search: null,
      selected3: [],
      selected: [1,3,8],
      selected2: [1,3,8],
      tree: [
        {text: 'Foo', id: '1', item_disabled:false, children: []},
        {text: 'Bar', id: '2', item_disabled:true, children: [
          {text: 'Select', id: '3', item_disabled:false, children: []},
          {text: 'One of', id: '4', item_disabled:false, children: []},
          {text: 'These', id: '5', item_disabled:false, children: []},
        ]},
        {text: 'Lorem', id: '6', item_disabled:false, children: [
          {text: 'Ipsum', id: '7', item_disabled:false, children: []},
          {text: 'Dolor', id: '8', item_disabled:false, children: []},
        ]},

      ]
    })
  }
</script>

```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

File: packages/vuetify/src/components/VTreeview/VTreeviewNode.ts [hunk 1]
```diff
@@ -213,11 +218,14 @@ const VTreeviewNode = baseMixins.extend<options>().extend({
         class: {
           'v-treeview-node__toggle--open': this.isOpen,
           'v-treeview-node__toggle--loading': this.isLoading,
+          'v-treeview-node__toggle--disabled': this.disabled && this.selectionType === 'leaf',
```
Comment (johnleider) [inline packages/vuetify/src/components/VTreeview/VTreeviewNode.ts:221]: `this.disabled && this.selectionType === 'leaf'` is duplicated on line 221, 226, 293

File: packages/vuetify/src/components/VTreeview/__tests__/VTreeview.spec.ts [hunk 2]
```diff
@@ -749,4 +749,41 @@ describe('VTreeView.ts', () => { // eslint-disable-line max-statements
 
     expect(input).not.toHaveBeenCalled()
   })
+
+  // https://github.com/vuetifyjs/vuetify/issues/10990
+  // https://github.com/vuetifyjs/vuetify/issues/10770
+  it('should not disable children of disabled parent when in independent mode', async () => {
```
Comment (johnleider) [inline packages/vuetify/src/components/VTreeview/__tests__/VTreeview.spec.ts:755]: this passes regardless of the fix.

Comment (nekosaur) [reply packages/vuetify/src/components/VTreeview/__tests__/VTreeview.spec.ts:755]: that's partly because we didn't really check disabled correctly before for child nodes
