### PR TITLE
fix(VCombobox): prevent removing disabled items with backspace

### LINKED ISSUE #18298: [Bug Report][3.3.17] Disabled items can be removed using backspace in VCombobox & VAutocomplete
### Environment
**Vuetify Version:** 3.3.17
**Vue Version:** 3.3.4
**Browsers:** Edge 117.0.2045.31
**OS:** Windows 10

### Steps to reproduce
Focus on VAutocomplete or VCombobox input and press backspace twice.

### Expected Behavior
Disabled item must remain.

### Actual Behavior
Disabled item removed.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrVk9FqwjAUhl/lkBsVrKIdDEoVZFd7AW+sF2kbWUZsQpp2Qum7L0lbTTt1YyBjF6U55/+bk/P1ZFehXCbzjRCzsiAoQKEiR8GwIusoAwhLL8Eytesm4pnCNCMSDqygnWAlyT/OYetloJ98FaHFMkKOaGVcKJ5wXYwo4koApXfkKWH6u3LjmLaYFSSPUN8cUH1iU6PnfTXJoZXh2O66dZ1D07Fgimqln03eqMgHKcZzHDPiXdEkUYXMPB6/k0S50jqc9zt3kWlJ87ow1bEL9ReMdZWYx/x0k+9La/iObee7z7Vz/QHTrtMf82zUdpqbYTeZZtrDuXMNdJgnkgplXeQkuFSQkgPWXUHV7JZihQMYT2C1hnGb06C/jGQAu8sBK1BUMRLAyGiwGE2hNP9BJwx4EwvJhf6ogpRaMGkAShYEaqinNzdaDjbSiXt2f2j3Xfv+vLpyGR/RjlOwN3X/Gl3/nj0SWz2xi9oM8XlsUT1F/syfPaHmvXhG+0+M+bq1)

### PR DESCRIPTION
**Pull request by gitemad**
## Description

Fix the issue by checking disabled prop when removing item using backspace.

fixes #18298 
## Markup:

```vue
<template>
  <v-card>
    <v-container fluid>
      <v-row>
        <v-col cols="12">
          <v-autocomplete
            v-model="vAutocompleteValues"
            :items="vAutocompleteItems"
            label="VAutocomplete"
            multiple
            chips
            closable-chips
            return-object
          ></v-autocomplete>
        </v-col>
      </v-row>
      <v-row>
        <v-col cols="12">
          <v-combobox
            v-model="vComboboxValues"
            :items="vComboboxItems"
            label="VCombobox"
            multiple
            chips
            closable-chips
            return-object
          ></v-combobox>
        </v-col>
      </v-row>
    </v-container>
  </v-card>
</template>

<script>
  export default {
    data: () => ({
      vAutocompleteItems: [
        { title: 'Item 1', value: 'item1', props: { disabled: true } },
        { title: 'Item 2', value: 'item 2' },
        { title: 'Item 3', value: 'item 3' },
      ],
      vAutocompleteValues: [
        { title: 'Item 1', value: 'item1', props: { disabled: true } },
      ],
      vComboboxItems: [
        { title: 'Item 1', value: 'item1', props: { disabled: true } },
        { title: 'Item 2', value: 'item 2' },
        { title: 'Item 3', value: 'item 3' },
      ],
      vComboboxValues: [
        { title: 'Item 1', value: 'item1', props: { disabled: true } },
      ],
    }),
  }
</script>

```

### CODE REVIEW

File: packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx [hunk 1]
```diff
@@ -244,7 +244,7 @@ export const VAutocomplete = genericComponent<new <
         const originalSelectionIndex = selectionIndex.value
 
         const selectedItem = model.value[selectionIndex.value]
-        if (selectedItem) select(selectedItem)
+        if (selectedItem && !selectedItem.props?.disabled) select(selectedItem)
```
Comment (KaelWD) [inline packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx:247]: Why optional chaining? Props is always defined.

**Review by KaelWD — CHANGES_REQUESTED** [review]

File: packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx (hunk 1 above)
Comment (jacekkarczmarczyk) [reply packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx:247]: should be detected with `@typescript-eslint/no-unnecessary-condition` but this rule seems to be turned off
