### PR TITLE
docs: fix radio button mandatory props default

### LINKED ISSUE #12435: [Documentation] Mandatory section of Radio Buttons component page incorrectly states radio-groups are mandatory by default
### Environment

**Browsers:** Chrome 86.0.4240.75
**OS:** Windows 10

### Steps to reproduce
This section states that radio-groups by default are mandatory. However, on the radio-groups API page, it states the prop "mandatory" is set to false by default

### Expected Behavior
Mandatory section of radio buttons components page correctly states that mandatory is set to false by default

### Actual Behavior
Currently the mandatory section incorrectly states that radio-groups by default are mandatory.

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/radio-buttons/#mandatory" target="_blank">https://vuetifyjs.com/en/components/radio-buttons/#mandatory</a>

### Other comments
https://vuetifyjs.com/en/api/v-radio-group/#props API page that shows 'mandatory' is set to false by default.

### PR DESCRIPTION
**Pull request by ripoul**
fix #12435

## Description

Fix the default value of radio-buttons mandatory props : from true to false.

## Motivation and Context

fix #12435 : have a documentation correct.

## How Has This Been Tested?

Build the docs and have a look on the result.

## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
```
</details>

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [x] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

File: packages/docs/src/examples/v-radio-group/prop-mandatory.vue [hunk 1]
```diff
@@ -3,7 +3,7 @@
     <p>{{ radios || 'null' }}</p>
     <v-radio-group
       v-model="radios"
-      :mandatory="false"
+      :mandatory="true"
```
Comment (jacekkarczmarczyk) [inline packages/docs/src/examples/v-radio-group/prop-mandatory.vue:6]:
```suggestion
      mandatory
```

**Review by jacekkarczmarczyk — CHANGES_REQUESTED** [review]
`radios` should have value set to `null`/`undefined`, otherwise you don't see the behaviour of automatic applying the value of the first radio

```js
  data () {
    return {
      radios: null,
    }
  },
```

Otherwise looks good

**Review by jacekkarczmarczyk — APPROVED** [review]
