### PR TITLE
fix(VSwitch): label when using direction vertical

### LINKED ISSUE #18952: [Bug Report][3.4.9] v-switch vertical direction not working
### Environment
**Vuetify Version:** 3.4.9
**Vue Version:** 3.4.0
**Browsers:** Edge 120.0.0.0
**OS:** Windows 10

### Steps to reproduce
Set `direction` prop to `vertical`.

### Expected Behavior
The switch appears vertically just like `v-slider`.

### Actual Behavior
the switch itself doesn't affect, the label becomes vertical but each char on new line.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpNjssKwjAQRX9lmFULfQi6sbQF/8GddRHTEQN9hGQahdJ/N01VXM3cw3DuXGa0RuYnrTM3ERZYMvW6E0x1MwCULrVPxfIBLu3HlrqqwTAbhE7cQj6TZR9bZUiyGgePHBlWUvirusy/Ci8s8z+7j1YapTk00UuPhqGlu5g6hnllAK1gUUAUQ1VD9GEA4YMC2EyUbGyJw7KsFT8pLgnus0O2w20e8foGNZFNUQ==)

### PR DESCRIPTION
**Pull request by De-Hann**
Feature to fix #18952

Added direction prop on ```VSelect``` and added styling to ```VSwitch```

```vue
<template>
  <v-app>
    <v-container>
      <v-switch
        v-model="model"
        direction="vertical"
        label="Vertical"
      ></v-switch>
      <v-switch
        v-model="model"
        direction="horizontal"
        label="Horizontal"
      ></v-switch>
      <v-switch v-model="model" label="Default"></v-switch>
    </v-container>
  </v-app>
</template>

<script>
export default {
  name: "Playground",
  data: () => ({
    model: false,
  }),
};
</script>
```

### CODE REVIEW

File: packages/vuetify/src/components/VSelect/VSelect.tsx [hunk 1]
```diff
@@ -356,6 +361,7 @@ export const VSelect = genericComponent<new <
               [`v-select--${props.multiple ? 'multiple' : 'single'}`]: true,
               'v-select--selected': model.value.length,
               'v-select--selection-slot': !!slots.selection,
+              [`v-input--${props.direction.valueOf}`]: true,
```
Comment (johnleider) [inline packages/vuetify/src/components/VSelect/VSelect.tsx:364]: Is valueOf needed?

File: packages/vuetify/src/components/VSelect/VSelect.tsx [hunk 2]
```diff
@@ -97,6 +97,11 @@ export const makeVSelectProps = propsFactory({
     role: 'combobox',
   }), ['validationValue', 'dirty', 'appendInnerIcon']),
   ...makeTransitionProps({ transition: { component: VDialogTransition as Component } }),
+  direction: {
```
Comment (johnleider) [inline packages/vuetify/src/components/VSelect/VSelect.tsx:100]: VSelect uses VTextField which uses VInput which already has this prop.

**Review by johnleider — CHANGES_REQUESTED** [review]

File: packages/vuetify/src/components/VSelect/VSelect.tsx (hunk 1 above)
Comment (De-Hann) [reply packages/vuetify/src/components/VSelect/VSelect.tsx]: It is not, removed it

File: packages/vuetify/src/components/VSelect/VSelect.tsx (hunk 2 above)
Comment (De-Hann) [reply packages/vuetify/src/components/VSelect/VSelect.tsx]: Thanks, missed that. Removed

**Comment by johnleider** [comment]
Could you reach out to me on Discord? https://community.vuetifyjs.com

**Review by johnleider — APPROVED** [review]
