### PR TITLE
fix(VCalendar): resolve wrong relative day span for 4day

### LINKED ISSUE #12666: [Bug Report] Calendar type 4day. Change event actually spans 5 days instead of 4
### Environment
**Vuetify Version:** 2.3.18
**Vue Version:** 2.6.11
**Browsers:** Chrome 86.0.4240.198
**OS:** Mac OS 10.15.7

### Steps to reproduce
Create a `v-calendar` with the props `type="4day"`, `start="2020-11-23"`, and `end="2020-11-26"`.

The calendar presents everything as intended, starting with Monday the 23rd going to Thursday the 26th.

The initial onChange event that triggers gives the incorrect end date of Friday the 27th (2020-11-27)

### Expected Behavior
The `change` event should be a range of 4 days

### Actual Behavior
The `change` event adds 4 days to the start date making it 5 days in total

### Reproduction Link
<a href="https://codepen.io/ChristerGustavsson/pen/WNGevwN" target="_blank">https://codepen.io/ChristerGustavsson/pen/WNGevwN</a>

### Other comments
I was using the `change` event to bind parameters used as query parameters to an API and noticed that they fetched more events than needed. 
It seems like the other calendar types of `day`, `week` & `month` do not have this issue. I haven't tested with `custom-weekly`, `custom-daily`, or `category`.

### PR DESCRIPTION
**Pull request by yuwu9145**
fixes #12666

## Description

fixes #12666
## Motivation and Context

close  #12666
## How Has This Been Tested?

visually

## Markup:

<details>

```vue
<template>
  <v-container>
    <v-row>
      <v-col cols="12">
        <v-calendar ref="calendar" type="4day" :start="start" :end="end" :events="events" @change="onChange" />
      </v-col>
    </v-row>
  </v-container>
</template>

<script>
  export default {
    data () {
      return {
        start: "2020-11-23",
        end: "2020-12-29",
        events: []
      }
    },
    methods: {
      onChange({ start, end }) {
        console.log("onChange:start", start)
        console.log("onChange:end", end)
        this.start = start.date
        this.end = end.date
      },
      onPrevClick() {
        this.$refs.calendar.prev()
      },
      onNextClick() {
        this.$refs.calendar.next()
      }
    }
  }
</script>
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

File: packages/vuetify/src/components/VCalendar/VCalendar.ts [hunk 1]
```diff
@@ -98,7 +98,7 @@ export default CalendarWithEvents.extend({
           break
         case '4day':
           component = VCalendarDaily
-          end = relativeDays(copyTimestamp(end), nextDay, 4)
+          end = relativeDays(copyTimestamp(end), nextDay, 3)
```
Comment (yuwu9145) [inline packages/vuetify/src/components/VCalendar/VCalendar.ts:101]: `relativeDays` working with `nextDay` is supposed to calculate end date from the next date of start date. e.g. If start date is `1` and days span is `1`, it will return 2. Therefore, when using `type` as `4day` it includes the start date, so days span shall be set as `3` here

**Review by MajesticPotatoe — APPROVED** [review]
👍 good catch
