### PR TITLE
fix(VListItem): infer link if click event is bound

### LINKED ISSUE #16014: [Bug Report][3.0.0] No `v-list-item--link` if there is only `@click` on `VListItem`
### Environment
**Vuetify Version:** 3.0.0
**Last working version:** 3.0.0-beta.15
**Vue Version:** 3.2.41
**Browsers:** Chrome 107.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Add `@click` on `VListItem`

### Expected Behavior
There is `v-list-item--link` class to make cursor be `pointer`

### Actual Behavior
No `v-list-item--link` on `VListItem`

### Reproduction Link
[https://codepen.io/0140454/pen/mdxePOw?editors=1010](https://codepen.io/0140454/pen/mdxePOw?editors=1010)

### PR DESCRIPTION
**Pull request by NoraH1to**
## Description

fixes #16014 

## Markup:

<details>

```vue
<template>
  <v-container>
    <v-menu>
      <template #activator="{props}">
        <v-btn v-bind="props">
          Dropdown Menu
        </v-btn>
      </template>
      <v-list>
        <v-list-item title="cursor = pointer" link="foo" />
        <v-list-item title="cursor != pointer" @click="foo" />
      </v-list>
    </v-menu>
  </v-container>
</template>

<script>
export default {
  methods: {
    foo() {
      console.log("foo");
    }
  }
};
</script>

```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [ ] The PR title is no longer than 64 characters.
- [ ] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [ ] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

File: packages/vuetify/src/components/VList/VListItem.tsx [hunk 1]
```diff
@@ -147,8 +143,6 @@ export const VListItem = genericComponent<new () => {
     }))
 
     function onClick (e: MouseEvent) {
-      emit('click', e)
```
Comment (KaelWD) [inline packages/vuetify/src/components/VList/VListItem.tsx:150]: It needs to emit click on space or enter keydown

**Review by KaelWD — CHANGES_REQUESTED** [review]

File: packages/vuetify/src/components/VList/VListItem.tsx (hunk 1 above)
Comment (NoraH1to) [reply packages/vuetify/src/components/VList/VListItem.tsx:150]: if add this, should add `emits: ['click']` too, or the event will trigger twice

and if add `emits: ['click']`, `useLink`  will not work well because **Events declared in emits will not exist in attrs**:

```typescript
export function useLink (props: LinkProps, attrs: SetupContext['attrs']): UseLink {
  ...
  const isClickable = computed(() => {
    // Events declared in emits will not exist in attrs
    return isLink?.value || !!(attrs.onClick || attrs.onClickOnce)
  })
  ...
}
```

so if we want to check a bound listener exists,  it needs to be declared in the component's props

```typescript
...
props: ['onClick'],
emits: ['onClick'],
...
```

and need to modify `isClickable` in `useLink` like

```typescript
isLink?.value || !!(attrs.onClick || attrs.onClickOnce || props.onClick || props.onClickOnce)
```

Comment (KaelWD) [reply packages/vuetify/src/components/VList/VListItem.tsx:150]: Yeah that's probably what I'd go with, we've done that in a couple of other places already. There's a `callEvent` function and `EventProp` interface you can use in `@/util`. I don't know if `@click.once` is passed as a separate prop, you'd have to check that.

Comment (NoraH1to) [reply packages/vuetify/src/components/VList/VListItem.tsx:150]: I notice that EventProp could be an array, dose it mean the listener could be like this?

```vue
<VListItem @click="[foo, bar]" />
```

If it is ,I dont think thats a good way

It will make `props.onClick` be a func like `($event) => [foo, bar]` instead of an array, if the user also passes a similar func, it's hard to tell if the func in the returned array should be executed

If not like this, i had already fixed the issue and could commit right now

Comment (KaelWD) [reply packages/vuetify/src/components/VList/VListItem.tsx:150]: Yes, that's how events work in vue: 

```js
mergeProps({ onClick: () => {} }, { onClick: () => {} }) === { onClick: [() => {}, () => {}] }
```

If the prop type is just `Function` you'll get runtime errors.
