### PR TITLE
fixes #2031

### LINKED ISSUE #2031: Input Masking - Cursor Issues on Android Oreo
### Steps to reproduce

1. Using Load [the Google Contacts example](https://vuetifyjs.com/examples/layouts/google-contacts) from documentation.
2. Click the FAB in bottom-right corner, to add a new contact.
3. In the phone field, type the number "1234567890"

### Versions

Vue 2.4.2
Vuetify 0.16.1
Android 8.0 / Chrome 59

### What is expected ?
A masked version of the number "1234567890".

### What is actually happening ?
Masking characters cause incorrect cursor position. If you don't manually adjust the cursor position in between number-clicks, your final/formatted number will be "(234) 789 - 0651".

### Reproduction Link
https://vuetifyjs.com/examples/layouts/google-contacts (on Android/Chrome)

screenshot_20171005-195022

### PR DESCRIPTION
**Pull request by azaars**
Android stores the caret position to later restore it after the component gets rendered. This exhibits a caret bug when we internally change the input text using masks. We need to delay our caret update right after Android is done with it's restoration.

### CODE REVIEW

File: src/mixins/maskable.js [hunk 1]
```diff
@@ -78,7 +81,13 @@ export default {
   methods: {
     setCaretPosition (selection) {
       this.selection = selection
-      this.$refs.input.setSelectionRange(selection, selection)
+      if (this.isAndroid) {
```
Comment (johnleider) [inline src/mixins/maskable.js]: Add comments as to what this is doing

Comment (azaars) [reply src/mixins/maskable.js]: That would do.

File: src/mixins/maskable.js [hunk 2]
```diff
@@ -82,6 +82,8 @@ export default {
     setCaretPosition (selection) {
       this.selection = selection
       if (this.isAndroid) {
+        // Android overrides the selection after nextTick().
+        // So defer the call to setSelectionRange().
```
Comment (KaelWD) [inline src/mixins/maskable.js]: Delay, not defer

**Comment by azaars** [comment]
Hahahaaa…

 

Thanks for that dictation.

 

Now you know why I can’t do documentations.

**Comment by KaelWD** [comment]
Yeah nah I was wrong, they mean basically the same thing.

**Comment by KaelWD** [comment]
This doesn't work, the problem is caused by `resetSelections()` running before the cursor position has updated.
