### PR TITLE
fix(VSelect): set model value to trigger emit

### LINKED ISSUE #15008: [Bug Report][3.0.0-beta.1] VSelect does not trigger @update:modelValue when items are selected in multiple mode
### Environment
**Vuetify Version:** 3.0.0-beta.1
**Vue Version:** 3.2.33
**Browsers:** Chrome 100.0.4896.127
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Add a VSelect component and bind it to a property using `v-model`, and include the `multiple` attribute.
2. Attach an event listeners for `@update:modelValue` to the component, and have it log the value to console.
3. Start interacting with the VSelect component.

### Expected Behavior
The event handler is triggered when items are selected AND deselected.

### Actual Behavior
The event handler is only triggered when items are deselected.

### Reproduction Link
<a href="https://codesandbox.io/s/vuetify-vselect-bug-update-modelvalue-only-triggered-when-removing-items-n9wkuh?file=/src/components/Playground.vue" target="_blank">https://codesandbox.io/s/vuetify-vselect-bug-update-modelvalue-only-triggered-when-removing-items-n9wkuh?file=/src/components/Playground.vue</a>

### PR DESCRIPTION
**Pull request by nekosaur**
closes #15008

## Markup:

<details>

```vue
<template>
  <div>
    <p>
      This sandbox demonstrates a bug in Vuetify v3 VSelect component where the
      "update:modelValue" event fails to trigger when items are selected in
      multiple mode, even though the bound model is kept in sync.
    </p>
    <v-select
      v-model="selectedUsers"
      @update:modelValue="onUpdate"
      :items="items"
      multiple
    />
    {{ selectedUsers }}
  </div>
</template>

<script>
import { defineComponent, ref } from "vue";

export default defineComponent({
  name: "playground",
  setup() {
    function onUpdate(value) {
      console.log("update:modelValue", value);
    }

    return {
      selectedUsers: ref([1, 2]),
      items: [
        {
          value: 1,
          title: "John Doe",
        },
        {
          value: 2,
          title: "Jane Doe",
        },
        {
          value: 3,
          title: "Jack Doe",
        },
        {
          value: 4,
          title: "Josh Doe",
        },
      ],
      onUpdate,
    };
  },
});
</script>

```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by KaelWD** [comment]
Type safety?
```diff
// proxiedModel
-   return computed<Inner>({
-     get () {
+   return computed<Inner extends Array<any> ? Readonly<Inner> : Inner>({
+     get (): any {
```

File: packages/vuetify/src/components/VExpansionPanel/VExpansionPanel.tsx [hunk 1]
```diff
@@ -38,16 +38,20 @@ export const VExpansionPanel = defineComponent({
     const { roundedClasses } = useRounded(props)
     const isDisabled = computed(() => groupItem?.disabled.value || props.disabled)
 
+    const selectedIndices = computed(() => groupItem.group.items.value.reduce<number[]>((arr, item, index) => {
+      return groupItem.group.selected.value.includes(item.id) ? [...arr, index] : arr
+    }, []))
```
Comment (KaelWD) [inline packages/vuetify/src/components/VExpansionPanel/VExpansionPanel.tsx:43]: Spread in reduce is slow as hell
```suggestion
    const selectedIndices = computed(() => groupItem.group.items.value.reduce<number[]>((arr, item, index) => {
      if (groupItem.group.selected.value.includes(item.id)) arr.push(index)
      return arr
    }, []))
```

File: packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx [hunk 2]
```diff
@@ -147,7 +147,7 @@ export const VAutocomplete = genericComponent<new <T>() => {
         const index = selections.value.findIndex(selection => selection.value === item.value)
 
         if (index === -1) {
-          model.value.push(item.value)
+          model.value = model.value.slice().concat([item.value])
```
Comment (KaelWD) [inline packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx:150]: This looks cleaner
```suggestion
          model.value = [...model.value, item.value]
```

File: packages/vuetify/src/components/VSelect/VSelect.tsx [hunk 3]
```diff
@@ -137,7 +137,7 @@ export const VSelect = genericComponent<new <T>() => {
         const index = selections.value.findIndex(selection => selection.value === item.value)
 
         if (index === -1) {
-          model.value.push(item.value)
+          model.value = model.value.slice().concat([item.value])
         } else {
           model.value = selected.value.filter(selection => selection !== item.value)
```
Comment (KaelWD) [inline packages/vuetify/src/components/VSelect/VSelect.tsx:142]: Unrelated, but if we already have the index can't we skip the filter to save a loop?
```suggestion
          const value = [...selected.value]
          value.splice(index, 1)
          model.value = value
```

**Review by KaelWD — APPROVED** [review]
