### PR TITLE
fix(VSelect/Auto/Combo): focus and activation of chips and clearable using keyboard

### LINKED ISSUE #18482: [Bug Report][3.3.21] Accessibility: v-select and v-autocomplete Clearable icon not keyboard accessible
### Environment
**Vuetify Version:** 3.3.21
**Vue Version:** 3.3.4
**Browsers:** Chrome 117.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Tab through the example page and use keyboard controls to interact with the v-select and v-autocomplete components. Both have the 'clearable' prop so an 'x' icon appears in the right hand side that can be clicked to clear the input, but there is no combination of keyboard controls that can access that button or achieve the same functionality.

### Expected Behavior
Is should be possible to focus on the 'x' icon and select it with keyboard controls

### Actual Behavior
It is not possible to use the 'clearable' functionality with just keyboard controls

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVj8EKgkAQhl9lmYuXUspOYkII9QAFHdTDqJMsrLvLalJE757uJtZp/vlmmPn/7AWdqYKD1v5wJ4gg7qnVAntKcslYPKxRayttUynZI5dkvsjCjgRV/QwYqwShwVLQggSWJPY5nN0qLJOIjw+7cZR5KQp+U0Zy9FbMS5VQBms16eMoeW3xiZRp3MaFHthN4vpULZeNVyyHkziYjc3uR/BvfyIuXRz8pIb3CkI/9Hfg6nYDxQc+rli6)

### PR DESCRIPTION
**Pull request by tmasrat**
## Description

If an icon is clickable, keyboard navigation to the icon should be allowed. If `onClick` is defined, I am setting the `tabindex` to 0
fixes #18482
## Markup:

```vue
<template>
  <v-app>
    <v-container>
      <v-select
          clearable
          label="Select"
          :items="['California', 'Colorado', 'Florida', 'Georgia', 'Texas', 'Wyoming']"
      ></v-select>
    </v-container>
  </v-app>
</template>

```

### CODE REVIEW

File: packages/vuetify/src/components/VIcon/VIcon.tsx [hunk 1]
```diff
@@ -74,6 +74,7 @@ export const VIcon = genericComponent()({
           ]}
           role={ attrs.onClick ? 'button' : undefined }
           aria-hidden={ !attrs.onClick }
+          tabindex={ attrs.onClick ? '0' : undefined }
```
Comment (johnleider) [inline packages/vuetify/src/components/VIcon/VIcon.tsx:77]: This doesn't work if the user supplies a meta argument like "@click.once", or "@click.stop".

```vue
<template>
  <v-app>
    <div class="ma-4 pa-4">
      <v-icon icon="$vuetify" @click.once="onClick" />
    </div>
  </v-app>
</template>

<script setup>
  function onClick () {
    alert('click')
  }
</script>
```

**Comment by tmasrat** [comment]
@johnleider this is ready to be reviewed again

**Comment by johnleider** [comment]
I don't have a good idea atm but I think running that function on every icon render is going to get expensive. @KaelWD, what are your thoughts?

**Comment by tmasrat** [comment]
@johnleider @KaelWD any update on this one? This change is a prerequisite to #18493

**Comment by johnleider** [comment]
I wouldn't expect too much movement on PRs until after Christmas.

**Comment by ibmalo95** [comment]
@johnleider @KaelWD any more thoughts or suggestions on this one? We would really appreciate any help you can give so we can get this issue fixed. Thanks!

**Comment by ibmalo95** [comment]
@tmasrat would it work if we just add these properties directly to where vicon is added in the autocomplete component? We know we need them for autocompletes and might be better than trying to make it work for all icons. I'm not at all familiar with how the code is setup so not sure if that would work or not, but just a thought.

**Comment by johnleider** [comment]
> @johnleider @KaelWD any more thoughts or suggestions on this one? We would really appreciate any help you can give so we can get this issue fixed. Thanks!

I'm drawing a blank. I'll add it as a task item for next week and spend some more thought time on it.

**Comment by tmasrat** [comment]
@johnleider I just pushed a new solution. It should fix all components that has VField as a child (VTextArea, VCombobox, VAutocomplete, VSelect...). There are conflicts on the PR but it's not related to the changes I made
Please let me know what you think about the new solution

**Comment by johnleider** [comment]
Did you merge a branch into this?

**Comment by tmasrat** [comment]
Yes, I merged the upstream master into it

**Comment by johnleider** [comment]
My suggestion would be to run `git reflog` and go back to the commit before your merge, then force push that up. It appears that you did something equivalent to `git merge --ff-only` instead of having an actual merge commit.

**Comment by tmasrat** [comment]
@johnleider this is ready to be reviewed. Thanks!

**Comment by tmasrat** [comment]
@KaelWD @johnleider any updates on this?

**Comment by johnleider** [comment]
I don't like the idea of every icon calling inject. I don't have a better answer solution atm but I'll try to make time for this in the near future. Thank you for your patience.

**Comment by johnleider** [comment]
@vuetifyjs/core-team I'd like everyone to chime in on this please.

**Comment by blalan05** [comment]
I agree provide/inject seems like a lot. Also this only solves clearable, I think there maybe a different solution that can also cover append/prepend icons, but as an option, not mandatory if hasClick is true.

**Comment by yuwu9145** [comment]
- Should be just as simple as `tabindex={ listener ? 0 : -1 }` in `InputIcon`, then tabindex will fall through to VIcon
- Need to do more work around blur, currently tab blur input will blur whole field, it's unable to focus icon via tab

Screenshot 2024-03-15 at 9 38 23 pm

**Comment by johnleider** [comment]
Partial fix here 9cbcea92f. The remaining I'm pushing to this P.R.

**Comment by johnleider** [comment]
@tmasrat can you confirm that this still resolves your issue? I made some changes.

**Comment by tmasrat** [comment]
@johnleider thanks for the update! It works for a case where you tab into the close button on a dropdown menu but it doesn't work for the chips. It tabs into the close icon but it opens the dropdown instead of closing the selected option
<template>
  <v-app>
    <v-container>
      <v-select
        :items="['California', 'Colorado', 'Florida', 'Georgia', 'Texas', 'Wyoming']"
        label="Select"
        chips
        closable-chips
        multiple
      ></v-select>
    </v-container>
  </v-app>
</template>

**Comment by johnleider** [comment]
Can you check now?

**Comment by tmasrat** [comment]
@johnleider the clearable chips are working but the other issue came back. The clear button is not clearing the selected value. It's opening the dropdown 
`<template>
  <v-app>
    <v-container>
      <v-select
        :items="['California', 'Colorado', 'Florida', 'Georgia', 'Texas', 'Wyoming']"
        label="Select"
        clearable
      ></v-select>
    </v-container>
  </v-app>
</template>`

**Comment by johnleider** [comment]
3rd times the charm.

**Comment by tmasrat** [comment]
Everything works now 🥳 . Thank you @johnleider

**Review by johnleider — APPROVED** [review]
