### PR TITLE
fix(V-Menu): only closing menu in closeParents if persistent is not set

### LINKED ISSUE #19780: [Bug Report][3.6.4] V-Menu Persistent Parent Closed by Child
### Environment
**Vuetify Version:** 3.6.4
**Vue Version:** 3.4.27
**Browsers:** Chrome 123.0.0.0
**OS:** Windows 10

### Steps to reproduce
* Create a parent v-menu with persistent set to true and close-on-content-click set to false (activator method does not seem to matter)
* Inside of this menu, create a new nested menu (in the reproduction link's case a menu to select a date)
* Notice that when the child menu closes from an outside click, it closes our parent menu, even though it has the persistent prop set to true. 

### Expected Behavior
If I've set a menu to persistent (defined in the docs as "Clicking outside of the element or pressing esc key will not deactivate it."), then I expect it to remain open even if a child menu closes. 

### Actual Behavior
Even with persistent set to true on a parent menu, the entire menu closes when a child component is closed via outside click. 

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdVUtv2kAQ/isj50AixYWkUg+IoPRxrSo1vZUeFnuAVde7q92xoUX8986uMRjbqGkjBbEz37y+efB9n3iXjd9b+6YqMZkmM8LCKkE4X2iAWZUKa+PX+MiMJiE1uqMoCpekQeZPi8QZQx9KIqMXyRy+WNTwGXUJDzAbR1jbqmBN8wTgt8lRsZMgf1gkZ9U0U8ZjanSMjprSTMnsJ0NXQnlsQ0VGshJkHCtv2tmcIRuU6w2x/u1kYndtjTKZIGk068jYtmYrc9qw+PFdx8Si89KHnBrZqcKaLuHyluQkS0mSwnmbnZZ4yEByWy4UUeXMtiM8dkkB/3tO+eGRW9GFRBDhjtKVRJV3yf/GmkUCSiyj7MUUCAHNsnE/XMjdqP9OI0TsJMDYvzd9wBv7a4YXbtqjsAfrjPVwuGLGhrmsOIul1GGOI5qT+J3yG3eh85PJ5Kpxl85pLCathCqRbXPOZ5C6hkCOPVzN+GIXB4IG16llXtANOz8TW2cxjKINFiFThWuR/bqGei5tcNKpLjYMnqC3i+e/ocrD2ATTV85TkHaH/bQ1vd1olibMgNG+vzfeigxdTKynC9esEk4KHa7Ece6fm+mLC3Iudw4fhc5Q9Q7chTuuJ86hdbIQjgn+hwBdfl5EhX1uuqFP3PQpaFTnW3zZiroB7TMfJPWvwMVE8tNnTloCj1Ravhd6HQrizYlmsrDGEezhK67uweEKDrBypoAR/9KMauY5kCeINU8DbrY0RqHQc2aALW4jC3eXyMdXI+Mlq9GenNTrBjwatZBxqCPoUyjsCNG4hfC+vWPobFxXynUlh3tdKhU/fvwB1ysJYQ==)

### Other comments
This is similar to #17004 which was fixed by #19239. This fix only addressed clicking on the parent content, but does not account for a parent component being persistent.

### PR DESCRIPTION
**Pull request by noahbare**
## Description
When using nested v-menus, if the parent has persistent set to true, it should remain open on an outside click even when the child menu is closed with an outside click.
When using a v-menu to get input from the user we set the parent menu to be persistent and expect it to remain open until the user cancels/saves. 

* Added check to `closeParents` function to take into account if the menu is persistent or not. 

This is related to #19239, which kept the parent menu open if the child menu was closed by clicking on the parent menu content. This extends this check to account for the parent being persistent, thus keeping the menu open even on outside clicks and resolves #19780.

## Markup:

```vue

<template>
  <v-app>
    <v-container>
      <v-btn id="rootButton">
        Open Menu 1
      </v-btn>
      <v-menu
        v-model="menu1"
        :close-on-content-click="false"
        activator="#rootButton"
        height="300px"
        location="top"
        width="260px"
        persistent
      >
        <v-card>
          <v-card-title>
            Menu 1
          </v-card-title>
          <v-card-item>
            <v-row>
              <v-col cols="12">
                <v-text-field v-model="menu1Text" label="Some text" />
              </v-col>
              <v-col cols="12">
                <v-menu
                  v-model="menu2"
                  :close-on-content-click="false"
                >
                  <template #activator="{ props }">
                    <div v-bind="props" z-index="2000">
                      <v-text-field
                        :model-value="date"
                      />
                    </div>
                  </template>
                  <v-date-picker
                    v-model="date"
                    theme="legacy"
                    @update:model-value="menu2 = false"
                  />
                </v-menu>
              </v-col>
            </v-row>
          </v-card-item>
          <v-card-actions>
            <v-spacer />

            <v-btn
              variant="text"
              @click="menu1 = false"
            >
              Cancel
            </v-btn>
            <v-btn
              color="primary"
              variant="text"
              @click="menu1 = false"
            >
              Save
            </v-btn>
          </v-card-actions>
        </v-card>
      </v-menu>
    </v-container>
  </v-app>
</template>

<script setup lang="ts">
  import { Ref, ref } from 'vue'

  const menu1: Ref<boolean> = ref(false)
  const menu2: Ref<boolean> = ref(false)
  const menu1Text: Ref<string> = ref('')
  const date: Ref<Date> = ref(new Date())
</script>

```

### CODE REVIEW

File: packages/vuetify/src/components/VMenu/VMenu.tsx [hunk 1]
```diff
@@ -77,7 +77,8 @@ export const VMenu = genericComponent<OverlaySlots>()({
       closeParents (e) {
         setTimeout(() => {
           if (!openChildren.value &&
-            (e == null || (e && !isClickInsideElement(e, overlay.value!.contentEl!)))
+            (e == null || (e && !isClickInsideElement(e, overlay.value!.contentEl!))) &&
+            !props.persistent
```
Comment (KaelWD) [inline packages/vuetify/src/components/VMenu/VMenu.tsx:81]: Move this to above the click check

**Review by KaelWD — CHANGES_REQUESTED** [review]

**Review by johnleider — APPROVED** [review]
