### PR TITLE
fix(VSelect): fix duplicated ID

### LINKED ISSUE #9819: [Bug Report] Selects dropdown has duplicate id.
### Environment
**Vuetify Version:** 2.1.10
**Vue Version:** 2.6.10
**Browsers:** Firefox 70.0
**OS:** Windows 10

### Steps to reproduce
Open devtools you will see the dropdown has duplicate id. https://www.screencast.com/t/klzE3y52

### Expected Behavior
Id should be unique

### Actual Behavior
Have tow elements with same id

### Reproduction Link
<a href="https://codepen.io/hkeyjun/pen/mddNXqG" target="_blank">https://codepen.io/hkeyjun/pen/mddNXqG</a>

### PR DESCRIPTION
**Pull request by abnersajr**
Added an Index based ID avoiding duplication

fix #9819

## Description

Select options were being generated with duplicated id. It was fixed appending to the old ID already generated an Index.

## Motivation and Context

Duplicated IDs aren't allowed in HTML. This PR fix #9819 

## How Has This Been Tested?

This was tested in the playground with developer tools.
## Markup:

<details>

```vue
<template>
  <div id="app">
  <v-app id="inspire">
    <v-container fluid>
      <v-row align="center">
        <v-col class="d-flex" cols="12" sm="6">
          <v-select
            :items="items"
            label="Standard"
          ></v-select>
        </v-col>
  
        <v-col class="d-flex" cols="12" sm="6">
          <v-select
            :items="items"
            filled
            label="Filled style"
          ></v-select>
        </v-col>
      </v-row>
    </v-container>
  </v-app>
</div>
</template>

<script>
export default {
  data: () => ({
    items: ['Foo', 'Bar', 'Fizz', 'Buzz'],
  }),
}
</script>

```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.

### CODE REVIEW

File: packages/vuetify/src/components/VSelect/VSelectList.ts [hunk 1]
```diff
@@ -206,12 +207,12 @@ export default mixins(Colorable, Themeable).extend({
         ? this.$createElement(VListItem, tile, scopedSlot)
         : scopedSlot
     },
-    genTileContent (item: any): VNode {
+    genTileContent (item: any, index = 0 as string | number): VNode {
```
Comment (jacekkarczmarczyk) [inline packages/vuetify/src/components/VSelect/VSelectList.ts]:
```suggestion
    genTileContent (item: any, index = 0 as string): VNode {
```

File: packages/vuetify/src/components/VSelect/VSelectList.ts [hunk 2]
```diff
@@ -164,7 +165,7 @@ export default mixins(Colorable, Themeable).extend({
           // Default behavior in list does not
           // contain aria-selected by default
           'aria-selected': String(value),
-          'aria-labelledby': this.genLabelledBy(item),
+          'aria-labelledby': `${this.genLabelledBy(item)}-${index}`,
```
Comment (jacekkarczmarczyk) [inline packages/vuetify/src/components/VSelect/VSelectList.ts]: Since we're using now `index` I guess the `const text = escapeHTML(this.getText(item).split(' ').join('-').toLowerCase())` part in `genLabelledBy` is not necessary anymore

File: packages/vuetify/src/components/VSelect/VSelectList.ts (hunk 1 above)
Comment (KaelWD) [reply packages/vuetify/src/components/VSelect/VSelectList.ts]: 0 isn't a string

Comment (KaelWD) [reply packages/vuetify/src/components/VSelect/VSelectList.ts]:
```suggestion
    genTileContent (item: any, index: string | number = 0): VNode {
```

Comment (jacekkarczmarczyk) [reply packages/vuetify/src/components/VSelect/VSelectList.ts]: removed the wrong type...

Comment (jacekkarczmarczyk) [reply packages/vuetify/src/components/VSelect/VSelectList.ts]: i've edited my comment (just removed the wrong type before), string is not necessary here

Comment (KaelWD) [reply packages/vuetify/src/components/VSelect/VSelectList.ts]: neither is `as number`

File: packages/vuetify/src/components/VSelect/VSelectList.ts [hunk 3]
```diff
@@ -146,11 +146,12 @@ export default mixins(Colorable, Themeable).extend({
...
-      item: object,
-      disabled = null as null | boolean,
-      value = false
-    ): VNode | VNode[] | undefined {
+    genTile ({
+      item,
+      index,
+      disabled = null,
+      value = false,
+    }: { item: any, disabled?: null | boolean, value?: boolean, index: number }): VNode | VNode[] | undefined {
```
Comment (johnleider) [inline packages/vuetify/src/components/VSelect/VSelectList.ts]: This seems like it should be a specific type.

**Comment by johnleider** [comment]
Requesting final comments @vuetifyjs/core-contributors @vuetifyjs/core-team

File: packages/vuetify/src/components/VSelect/VSelectList.ts (hunk 2 above)
Comment (abnersajr) [reply packages/vuetify/src/components/VSelect/VSelectList.ts]: I don't think so. In one scenario with multiple selects the Id's can be duplicated. This part doesn't avoid all possible duplications, but it's not common to have multiple selects with same options.

In case I'm wrong, please let me know.

Comment (jacekkarczmarczyk) [reply packages/vuetify/src/components/VSelect/VSelectList.ts]: This should be handled by `_uid`
```ts
genLabelledBy (item: object) {
      const text = escapeHTML(this.getText(item).split(' ').join('-').toLowerCase())

      return `${text}-list-item-${this._uid}`
    },
```
Can you check it?
Also it's very common to have multiple selets with same options, for example you can have selects with nully value ('not applicable', 'other', etc)

Comment (abnersajr) [reply packages/vuetify/src/components/VSelect/VSelectList.ts]: I will recheck the use of `_uid` in this function.

Comment (abnersajr) [reply packages/vuetify/src/components/VSelect/VSelectList.ts]: @jacekkarczmarczyk I checked again your point and isn't necessary anymore the text. Only `list-item-${this._uid}` with the index. I didn't get your point.
Thanks for your review.

File: packages/vuetify/src/components/VSelect/VSelectList.ts (hunk 3 above)
Comment (abnersajr) [reply packages/vuetify/src/components/VSelect/VSelectList.ts]: Added :)

**Comment by johnleider** [comment]
@phiter can you do a once over on to make sure none of this goes against or breaks a11y support?

**Comment by phiter** [comment]
@johnleider it is not beaking a11y. The `aria-labelledby` is still correct and in my tests the IDs are unique.
