### PR TITLE
fix(VCombobox): keep highlighted item on filteredItems change

### LINKED ISSUE #14194: [Bug Report][2.5.8] Combobox list-index doesn't update correctly on input
### Environment
**Vuetify Version:** 2.5.8
**Vue Version:** 2.6.14
**Browsers:** Firefox 92.0
**OS:** Linux

### Steps to reproduce
Using the provided sandbox

Example 1

* Focus the combobox
* Press 'a'
* Using arrows, move to the last entry
* Press 'a' again
* The list index now points outside of the search results

Example 2

* Focus the combobox
* Press 'a'
* Using arrows, select the second to last entry
* Press 'a'
* The list index now points to another entry, because it did not change

Example 3

* Focus the combobox
* Press 'a'
* Using arrows, select the first entry
* Press 'a' until all entries disappear
* The list index is still '0', even though no entries are selected
* Press 'a' again
* The list index is now updated correctly

### Expected Behavior
The selection should not change on search input, therefore the list index should be updated on search input

The list index should never point to a result that does not exist

### Actual Behavior
The list index keeps its value, sometimes even pointing to a absent search result

### Reproduction Link
<a href="https://codepen.io/lgarczyn/pen/eYRPmJJ?editors=1111" target="_blank">https://codepen.io/lgarczyn/pen/eYRPmJJ?editors=1111</a>

### Other comments
This might be linked to another bug I've experienced, where pressing enter does not actually add a new chip. This might be because the combobox believe a search result is still selected. The new chip is created on blur though, which is kinda weird.

### PR DESCRIPTION
**Pull request by yuwu9145**
fixes #14194 #6607

## Description

This pull request fixes #14194 as well as keeps fixing #6607

Test cases are added to cover both #14194 & #6607

## Motivation and Context

resolves #14194
## How Has This Been Tested?

visually | unit 

## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
<template>
  <v-container>
     <v-combobox
        clearable
        dense
        filled
        hide-selected
        multiple
        persistent-hint
        small-chips
        :items="['a', 'aa', 'aaa', 'bar']"
        @update:list-index="console.log($event)"
      ></v-combobox>

      <v-combobox :items="todos" :auto-select-first="true"></v-combobox>
  </v-container>
</template>

<script>
export default {
   data: () => ({
    console,
    todos: [
      { text: "Learn JavaScript", done: false },
      { text: "Learn Vue", done: false },
      { text: "Play around in JSFiddle", done: true },
      { text: "Build something awesome", done: true }
    ]
  }),
  mounted () {
  }
};
</script>
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

File: packages/vuetify/src/components/VCombobox/VCombobox.ts [hunk 1]
```diff
@@ -108,11 +108,6 @@ export default VAutocomplete.extend({
 
       this.$nextTick(this.updateSelf)
     },
-    onFilteredItemsChanged (val: never[], oldVal: never[]) {
-      if (!this.autoSelectFirst) return
```
Comment (yuwu9145) [inline packages/vuetify/src/components/VCombobox/VCombobox.ts:112]: The only purpose of this line code seems to be allowing entering a custom input as a final result, for example, if a list has element of "bar" but user inputs "ba" and hit enter, it should add "ba" as the final result. 

The tricky part is when user inputs "ba" it automatically selects the first option "bar" (due to line 231 in `VAutocomplete`) and when user hits enter it will set "bar" as final result.

However, this line of code is unnecessary, a proper fix is it should only select the first item when `autoSelectFirst=true` in `VAutocomplete`. This will make sure there is no default selection in `combobox` when `autoSelectFirst=false`

**Review by KaelWD — APPROVED** [review]
