### PR TITLE
Fix/2146

### LINKED ISSUE #2146: Dialog does not open in Edge
### Steps to reproduce
- Visit https://vuetifyjs.com/components/dialogs
- Clock any "Open Dialog" button

### Versions
Vuetify 0.16, Windows 10, build 1703, Edge 40.15063.674.0

### What is expected ?
dialog should render 
(in my memory this feature worked on edge in the previous release)

### What is actually happening ?
nothing visible changes. 
If console is open the message is "Object doesn't support property or method 'Symbol(Symbol.iterator)'"

### Reproduction Link
https://vuetifyjs.com/components/dialogs

### PR DESCRIPTION
**Pull request by johnleider**
Fixes #2146

Handles edge case where the Edge browser is unable to iterate an empty HTMLElementList, causing a fatal Symbol.iterator.

Also fixed a bug where the #1932 PR removed the logic that bound click events to `v-app`. This caused an issue on iOS devices not firing **click-outside** events.

### CODE REVIEW

**Comment by KaelWD** [comment]
Do you have a Playground.vue that can repro the issue? The codepen fails with `"[Vue warn]: Error in render function: 'TypeError: Object doesn't support property or method 'ToString''` which is different to what the issue states, but when I copy the code into my local environment it runs just fine.

File: src/mixins/stackable.js [hunk 1]
```diff
@@ -13,28 +13,33 @@ export default {
...
     getMaxZIndex (exclude = []) {
       const base = this.stackBase || this.$el
-      // start with lowest allowed z-index or z-index of base component's element, whichever is greater
+      // start with lowest allowed z-index or z-index of
+      // base component's element, whichever is greater
       const zis = [this.stackMinZIndex, getZIndex(base)]
       // get z-index for all active dialogs
-      const activeElements = document.getElementsByClassName(this.stackClass)
-      for (const activeElement of activeElements) {
+      const activeElements = [...document.getElementsByClassName(this.stackClass)]
```
Comment (KaelWD) [inline src/mixins/stackable.js]: This line is what actually fixes the issue, you can still use `for..of` after doing this.

File: src/stylus/components/_overlay.styl [hunk 2]
```diff
@@ -7,6 +7,12 @@
   right: 0
   bottom: 0
   pointer-events: none
+  // The overlay has a dynamically set
+  // z-index, we want the transition
+  // timing to affect its changing
+  // https://github.com/vuetifyjs/vuetify/issues/2146
+  transition: .5s $transition.swing
```
Comment (jacekkarczmarczyk) [inline src/stylus/components/_overlay.styl]: 0.5s here and 150ms below is calculated by trial and error method or are they related to some other props? Maybe they could be made as a consts and resused

Comment (johnleider) [reply src/stylus/components/_overlay.styl]: Trial and error

File: src/directives/click-outside.js [hunk 3]
```diff
@@ -54,14 +54,18 @@ export default {
...
+      const app = document.querySelector('[data-app]') ||
+        document.body // This is only for unit tests
+      app.addEventListener('click', onClick, true)
       el._clickOutside = onClick
     })
   },
 
   unbind (el) {
-    document.removeEventListener('click', el._clickOutside, true)
+    const app = document.querySelector('[data-app]')
```
Comment (nekosaur) [inline src/directives/click-outside.js]: Should probably do `|| document.body` here as well, so things get removed correctly in tests.
