### PR TITLE
fix(VTextField): avoid infinite focus loop

### LINKED ISSUE #21626: [Bug Report][3.8.9] CPU 100% with VTextField and Password Managers
### Environment
**Vuetify Version:** 3.8.9
**Last working version:** 3.8.8
**Vue Version:** 3.5.16
**Browsers:** Chrome 137.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Use Linux (Manjaro/Ubuntu) with Chromium/Chrome
Have LastPass password manager enabled
Automatically fill login information should be checked in LastPass options
Show fill options automatically, should also be checked in LastPass options
Save credentials for this page
Reload page - CPU should spike to 100%
ibus-daemon process will also spike on Linux

### Expected Behavior
Browser should stay responsive

### Actual Behavior
Chromiuum freezes and needs to be killed.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlVl1v2zYU/SsXAoYmmGWlbdalgRagKzbsIQOKZtke5j5Q4rXNhiIFftgOiv73XlIftiQn6UceYuny3qvDw8ND/v8psabM3tT1fOMxuUxyh1UtmcOrhQLINymr6/gYXyomVPsW30utHIXQ9MEmzAyHUjJrf1sk1S5l3ulFAhXbpVvB3Zqi52dni+Sgqq9LnXASr671Sij4U5sKUvjXoxPLe/jdr+A91kZzXzqhVZ4Nao51s76YDkLodAlv393C87Ozn2Ar3BpqgrvVBLxiiq3QWNAKroXyu7wwkI0adJBezi/mr3+Gk1JXlXDw6vziVfHixevTYzU3Dmt7CX8oVkiEa2bdO/pmNv7wDDbCUi+3FpZQrbDBZ9kG+bBhaZCjcoJJO5h7R8vRyfc8486NANLQkhgfRWM8ZKdLgXIEIfyRLjRHSavqLRrFKlwk0yzJiphz+0hOiD/RJmiJyK4luqdSa4M1Kp4KkmkQIhcpK0vtlTuWvWFGMOUoUXsnSdR8mhVW9LvJ6db5MXKCIB7Kacl5rI27r59KGfFXemNIQuljJUd4lLq8+xESBwSSXCey22/tsUw7/bJoAXYq4cIpKLXUJjBhRMXMPZlPESA3thJ6U9Lx703bdkODtQ/OKNHQLm0oF2oZLK43PZeej/3NOqPV6uofDcRn9DCkPY5QkBflWTs6qNByPDsprmj/NLYEJ38z9ZEZnd0WpGl/2vjE27XRlfBVFh8wz6hm2uUvcpPegibeBxg9ij9QPF7RN6SpijlRMinvYSmkBBn9O7BiwghZqV1rLzkUCOUayzvkNNojGHfUdVyFsVC+Cs3NWm8bEG2XqPke36xDQq6ph3DGnXp+vgXOTWD2wJmBKNh7+QNF71Fqxhu3T+PB1IK0tbgjmeh4UD1QLApvU86wIpZJWCUS4m2Yf5xh06E/y8Yt8myksrw778fC/U+bO1KbV3wvVwhqPDwLL4hG65Dmopft4TgbtuPCxvMvSN9t9YRkQGakIA026LXcoI3JNDWqq+ZD9Idow06Nu3J/Rwl7d3RJCbH+IhNL4hUnzw6uPvRqSyPqphPuak1bneOSeengU9Mn+PElPGtnTzeKw6vJs3bWnDl2ctqVAG19543avwN0Jxi16oqi6bZbMoS76OfmIf7QP1qFDmPyeZa8nP8yf/5rEh5oHZLZkgjE2eB+18Q+fAEgeeFA)

### PR DESCRIPTION
**Pull request by J-Sek**
## Description

Password managers attempt use `.focus()` when inserting value.
When 2 fields get focus, the `nextTick` makes them compete for focus in an infinite loop.

fixes #21626

[Playground](https://play.vuetifyjs.com/#eNrFVctu2zAQ/BWCF9uAZcduixaGE7QFGqBAD0VflygHmlrZRCiSpZZ+wMi/dynFD9mCE7SH6sQdzu6Sw1nobstLL4cfnBssA/AJnyIUTguEm9QwNl0mwrlqWQWFUOYpqmJpDRIEfg/WsPAZk1qU5XXKi3UiAtqUs0Ksk5XKcEHo66urlB9l7fMSVKjh5oudK8NurS9Ywn4FQJVv2McwZ9/AeZsFicqa6bCR01oN1tjYqLZyqnuCVnhkJ7kCnZ1uMqbFDDSd/GcJ3ogCUn7OiThRwgVK1EJa0hjwOarz4MBkiSKZo5CZSoSUNhhsYy+FV8IgEW1ATY+SnbOGdOm/vPZXes2V9S1F99d2Fyi4cc9RTpSRwXswmFxKaVFIW/nwL/I0pCF/tViFFJuhYdJq6+OdvCqE35DBZ7E5ey+1kg+0ES+UK63J6LtlrEi5TavuXdz06g4/DFwETiYuYvupjEE9r9Ph0RxTWEqvHLISMNTjnAdTjVClejxZt8e2dUlqUSJTxgUcsWuWWRkKeojB7wB+8x00SLS+26kId2eOv+/06jJ1gUFO6WW3iS2FDkClO8WG7TI7DUamSidQLj4tqXPXwIp9jht1mPKKlfL+04njNwuzmYZywtAH6B/wivqD3DdhMY+64a23BdkZ90P32Gue77z7rrFcCDOnvD7bNjvWNc4EHL9UwIPLmwKOWwQcNwTcZR4LOP6vArZ1f6GAVCqat7YrGZU/9vmrwZvB6C2Pi3eD0Yj3c6FL6Dd+XDV2/wcrLhIw)

### CODE REVIEW

**Comment by johnleider** [comment]
Definitely need a unit test for this one.

**Comment by J-Sek** [comment]
> _Definitely need a unit test for this one._

[Example](https://bin.vuetifyjs.com/?code=eJzFk01v4jAQhu_9FSMuSaQSWo4V9EDValfaSiuBuKz24DgDWOvYUTyBRlX_-05sWAzLdnvrJTD2zPPOl68AFOXW6C5NSosOjCWgRq3X2IAyK2UUIWhra9ht0IBoya6U1lhC0UEtnNvZpoRKGMERyTUI1xkJaQbTe3hlOkCDpsQmDUepPwKYlGp7v__P1nKBL_SkUJegRYF6OmgdNkZUOID-G9vU1WxjJZQewOhdyCG_A-RoB8jRPuHMyBxNgLmtEIqWyJrodLJ8RtOCkKS2gmzT07hUGsShoVCQmoWmg6obVhwzlNaQ9_Rk4qy51dBfTUYnfeHwkZeJshvF6UX-WXblfxnuel7d0i1MwckG0eRrpFn3MJ-nib_5cdbUn0nGk4Mvi-dvX_v7R42cDp0Dx_8D_mnov4CeGJLLV1a2Ls3io63QLbJIUnVwSC6JHUrlakFy87hlWmpwBwHvzZAKL2FYPOChFYVGd8cb3eL1_tA7LXj-d8ABLEJPja2-C0eYBJ837uW7mns5uRFmzUHweqrkAUfC-O9KxyeVHroWVTr-hEovaX64UrETiqD_pLc3N4EaNie8nEubk2-HBZkkOAdAP3SvmUut5K80BMceR4lIo387D-FVXRQ6e3l7SXypUVIaBWc52RkulVNcox_YW_Yb4YqYVA&lang=typescript) - simply placing the code from the playground in e2e test results in:
- test process hanging up, so CI will crash without clearly pointing to that test case
- memory leak (took 80% ~ 20GB until I killed it manually)

Those would be the symptoms of a regression we want to avoid - I doubt anyone would correlate them with VTextField though..

File: packages/vuetify/test/setup/browser-commands.ts [hunk 1]
```diff
@@ -68,7 +68,31 @@ async function setFocusEmulationEnabled (ctx: BrowserCommandContext) {
...
 }
 
-export const commands = { drag, scroll, isDisplayed, percySnapshot, waitStable, setFocusEmulationEnabled }
+let abortTimeout: ReturnType<typeof setTimeout> = null!
+function abortAfter (ctx: BrowserCommandContext, delay: number, name: string) {
+  abortTimeout = setTimeout(() => {
+    // eslint-disable-next-line no-console
+    console.error(`[Error] Test timeout: Aborting after ${delay}ms for ${name}.`)
+    // eslint-disable-next-line no-console
+    console.error('[Warning] "chrome" process might still be running and require manual shutdown.')
```
Comment (J-Sek) [inline packages/vuetify/test/setup/browser-commands.ts:77]: This is what happens if you ignore this line

image
