### PR TITLE
fix(VColorInput): ensure cancel action closes menu

### LINKED ISSUE #21655: [Bug Report][3.8.11] Not working `Cancel` button for VColorInput
### Environment
**Vuetify Version:** 3.8.11
**Vue Version:** 3.5.17
**Browsers:** Edge 137.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Focus input
2. Click Cancel button

### Expected Behavior
Should close menu

### Actual Behavior
Nothing

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVj8EKwjAQRH8l7LlNCCKKhILfoR5KWLEQmyXZ1IP47zaJVXubNzvsMKcnxGDVkUhOCeEAhvFOrmfszqMQZmqDfxRZwHr3gYLxhshfY0n40A4jJRbql1XrcOblV9a1xKi/8hmjDQOxiMiJOqMqzid4NbCRW6l3kMVeag3NtXcRm9Wa6l3eUE9GWg==)

### PR DESCRIPTION
**Pull request by oumoussa98**
## Description

fixes #21655 
## Markup:

```vue
<template>
  <v-container>
     <v-color-input />
  </v-container>
</template>
```

### CODE REVIEW

File: packages/vuetify/src/labs/VColorInput/VColorInput.tsx [hunk 1]
```diff
@@ -139,17 +143,14 @@ export const VColorInput = genericComponent<VColorInputSlots>()({
...
                     {{
                       default: ({ actions, model: proxyModel, save, cancel, isPristine }) => {
                         return (
                           <VColorPicker
                             { ...colorPickerProps }
-                            modelValue={ proxyModel.value }
-                            onUpdate:modelValue={ val => {
-                              proxyModel.value = val
-                              model.value = val
-                            }}
```
Comment (Haviles04) [inline packages/vuetify/src/labs/VColorInput/VColorInput.tsx:152]: I'm not sure removing this is the right move. It doesn't feel right to force the user to "save" when they can just unfocus it. It also feels like cancel should revert it to your previously selected value... What if we added a `previousModel` ref and reverted to that `onCancel`

Comment (oumoussa98) [reply packages/vuetify/src/labs/VColorInput/VColorInput.tsx:152]: I think unfocusing should cancel just like [VDateInput](https://play.vuetifyjs.com/#eNpVj8sKwjAQRX8lzDoPQhGkxILgXxgXMR0xENPQpN2I/26aKrS7O2ce9871DWm04hwjnyeEFlTGV/QmY6cDIWpmJsYqa2GHkI0LOP5QhX2ZZi7EKRNv7uhPGi4FkYo0kPbpemTGZjeEVJoP4xNq6JTY7v5NCty7LGQNocQmHHwoNPzAZQOLOHIpgdbTdPfSym5f0AZLBQ==)
This made me realize I need to handle the [hide-actions](https://play.vuetifyjs.com/#eNqLrlYqLkrWdywo0CsrTVWyUrIpSc0tyEksSbWLyVNQsCnTTSwoADPBnOT8vJLEzLzUIqgQWDAFqFo3M6+gtEQhJzEpNcc2RskFKKQAFopRUtCH6ddHNwAkAjHfRh/JXqVaHSVjPVM9Q2MlEMNCz9BQSSctMac4VQfFtRCxWAAjmD23) case where changes should be reflected immediately

**Review by johnleider — APPROVED** [review]
