### PR TITLE
fix(validation): respect number 0 when calculating isDirty

### LINKED ISSUE #14942: [Bug Report][3.0.0-beta.0] VTextField thinks 0 is an empty value
### Environment
**Vuetify Version:** 3.0.0-beta.0
**Vue Version:** 3.2.19
**Browsers:** Firefox 99.0
**OS:** Windows 10

### Steps to reproduce
Set value to 2, click outside the field
Set value to 0, click outside the field

### Expected Behavior
0 should show even when focus is lost since the field isn't empty

### Actual Behavior
the label hides the number

### Reproduction Link
<a href="https://codepen.io/SuperCuber2/pen/VwyxQmV" target="_blank">https://codepen.io/SuperCuber2/pen/VwyxQmV</a>

### PR DESCRIPTION
**Pull request by yuwu9145**
fixes #14942

## Description

fixes #14942

## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
<template>
  <v-app>
   <v-container>
      Note how when num=0 the number gets hidden on lose focus but when num>0 it works fine
      <v-text-field label="works" type="number" />
    </v-container> 
  </v-app> 
</template>
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

File: packages/vuetify/src/composables/validation.ts [hunk 1]
```diff
@@ -56,7 +56,7 @@ export function useValidation (
   const form = useForm()
   const internalErrorMessages = ref<string[]>([])
   const isPristine = ref(true)
-  const isDirty = computed(() => wrapInArray(model.value || []).length > 0)
```
Comment (yuwu9145) [inline packages/vuetify/src/composables/validation.ts:59]: old code seems try to convert falsy values to `[]`, however, `0` should  not be treated as falsy in this case. Here is summary of what should happen:

- for `null` & `undefined`, `wrapInArray` should return `[]` which has been implemented in `wrapInArray`
- for `0`, it should be passed as `0` and `wrapInArray` will return `[0]` as expected
- for `''` however, it should be converted to `null` ,  `wrapInArray` will return `[]` which makes `isDirty` as `false`

Therefore, in terms of `isDirty` calculation, only empty string `''` should be specifically addressed

**Review by KaelWD — APPROVED** [review]
