### PR TITLE
VSelect -  Re-evaluate selection when items changes

### LINKED ISSUE #1743: v-select default v-model not show up correctly when item get from async
### Steps to reproduce
get v-select items from async/await
### Versions

v0.15.7
### What is expected ?

v-select will show up the default value
### What is actually happening ?

the default value not display correctly
### Reproduction Link

https://codepen.io/guanxudong/pen/dVoZYB?editors=1010

### PR DESCRIPTION
**Pull request by KaelWD**
Fixes #1743 

`selectedItems` should probably be a computed property instead of data, but I don't feel like wading through that much spaghetti today.

### CODE REVIEW

File: src/components/VSelect/VSelect.js [hunk 1]
```diff
@@ -378,11 +380,12 @@ export default {
       this.isActive = true
       this.isFocused = true
 
-      if (this.$refs.input && this.isAutocomplete) {
-        this.$nextTick(() => {
-          // this.$refs.input.focus()
```
Comment (KaelWD) [inline src/components/VSelect/VSelect.js]: This wasn't doing anything so I marked it with a TODO so it's visible

File: src/components/VSelect/VSelect.js [hunk 2]
```diff
@@ -378,11 +380,12 @@ export default {
...
-        })
-      }
+      // TODO
```
Comment (johnleider) [inline src/components/VSelect/VSelect.js]: I think you can just go ahead and remove this.

Comment (KaelWD) [reply src/components/VSelect/VSelect.js]: Moved it to my other PR instead

**Comment by gygoo** [comment]
When will these changes be published? In version 1.0.17, v-select is not reactive. Does not respond to the change in the status of the selected item.

**Comment by KaelWD** [comment]
If you check the merge commit you'll notice it was released with v0.16. If you're having a different problem please open a new issue, although it may have been fixed already in the 1.1 alpha so check with that first.
