### PR TITLE
fix(helpers): coerce name value to string in groupItems

### LINKED ISSUE #12069: [Bug Report] The group function in DataTable doesn't work when some item's data is null
### Environment
**Vuetify Version:** 2.3.7
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Windows

### Steps to reproduce
Just modify the default example in the official document.
Change some item's field to undefined or null

Turns out 'undefined' works normal, 
but 'null' field will cause the components crash!

### Expected Behavior
I hope that null will work's too, because some back-end restful api will return null for you.

### Actual Behavior
Crashed

### Reproduction Link
<a href="https://codepen.io/oraant/pen/mdPELgJ" target="_blank">https://codepen.io/oraant/pen/mdPELgJ</a>

### LINKED ISSUE #12501: [Bug Report] Group by in data table does not allow null values for the group-by item property
### Environment
**Vuetify Version:** 2.3.15
**Vue Version:** 3.0.1
**Browsers:** Chrome 86.0.4240.75
**OS:** Windows 10

### Steps to reproduce
Open pen, data table does not display. 

### Expected Behavior
Databable should display, null values of the the item property should not result in error. Also no group should be created for null value

### Actual Behavior
No table is displayed at all.

### Reproduction Link
<a href="https://codepen.io/djr021320/pen/QWEdZpm" target="_blank">https://codepen.io/djr021320/pen/QWEdZpm</a>

### Other comments
Error is raised in groupItems helper function for group for items with null values as no items are added because they have value null.

### PR DESCRIPTION
**Pull request by wol-soft**
## Description
If the property which is used as groupBy contains null a TypeError is thrown (TypeError: Cannot read property 'items' of undefined) in https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/util/helpers.ts#L278 as the variable `current` is initialized with null.

Reproduction: https://codepen.io/WOL-Soft/pen/VweojBr

With this fix all items which are provided with null values or which completely miss the property used for grouping are grouped under a 'empty' group. The null group can be identified via the property `name` of the `ItemGroup` (name will be set to an empty string).

Fixes #12069
Fixes #12501 

## How Has This Been Tested?

* unit tests

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:
- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

File: packages/vuetify/src/util/helpers.ts [hunk 1]
```diff
@@ -264,14 +264,14 @@ export function groupItems<T extends any = any> (
...
+  let current
   for (var i = 0; i < items.length; i++) {
     const item = items[i]
-    const val = getObjectValueByPath(item, key)
+    const val = getObjectValueByPath(item, key, null)
     if (current !== val) {
       current = val
       groups.push({
-        name: val,
+        name: val || '',
```
Comment (KaelWD) [inline packages/vuetify/src/util/helpers.ts:274]:
```suggestion
        name: val ?? '',
```

**Comment by wol-soft** [comment]
Hi @KaelWD,

is there anything I can do to move this PR forward?

Cheers

**Comment by wol-soft** [comment]
And again the question: can I do anything to move this PR forward? Is the solution of creating an 'empty' group containing all null items not the way to go?

The PR is nearly 4 months old.

Another issue was opened which addresses the TypeError currently thrown.

Fixes #12501 

@johnleider @nekosaur

**Review by johnleider — DISMISSED** [review]

**Review by johnleider — APPROVED** [review]
