### PR TITLE
fix(VMenu): activator should not return non Element nodes

### LINKED ISSUE #13755: [Bug Report][2.5.3] v-navigation-drawer with expand-on-hover throws console errors when hovered
### Environment
**Vuetify Version:** 2.5.3
**Last working version:** 2.4.11
**Vue Version:** 2.6.11
**Browsers:** Chrome 91.0.4472.77
**OS:** Mac OS 10.14.6

### Steps to reproduce
Use `v-navigation-drawer` with `expand-on-hover` and `mini-variant`

### Expected Behavior
Navigation drawer expands and contracts

### Actual Behavior
Navigation drawer expands and contracts but throws the following console error
```
index.js:245 Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at VueComponent.checkActivatorFixed (index.js:245)
    at VueComponent.updateDimensions (index.js:338)
```
in `packages/vuetify/src/mixins/menuable/index.ts`

### Reproduction Link
<a href="https://codepen.io/kotoriii/pen/zYZWyXB" target="_blank">https://codepen.io/kotoriii/pen/zYZWyXB</a>

### Other comments
The Codepen I linked does not reproduce the issue, even though I tried using as many components as I'm currently using. It's hard to reproduce my local stack, but error is caused by these added lines in `beforeMount()` and `beforeDestroy()` in this PR's recent file changes:
https://github.com/vuetifyjs/vuetify/pull/13670/files#diff-a510753fb8a85de8db6181b6c250d80bcccbf5fa2d4a97e5660e233bfc718200R193

### PR DESCRIPTION
**Pull request by Tofandel**
## Description

Fixes #13755

## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

File: packages/vuetify/src/mixins/activatable/index.ts [hunk 1]
```diff
@@ -170,7 +170,8 @@ export default baseMixins.extend({
         activator = (e.currentTarget || e.target) as HTMLElement
       }
 
-      this.activatorElement = activator
+      // The activator should only be a valid element (Ignore comments and text nodes)
+      this.activatorElement = activator && activator.nodeType === 1 ? activator : null
```
Comment (KaelWD) [inline packages/vuetify/src/mixins/activatable/index.ts:174]:
```suggestion
      this.activatorElement = activator?.nodeType === Node.ELEMENT_NODE
```

Comment (Tofandel) [reply packages/vuetify/src/mixins/activatable/index.ts:174]: Won't this just return `true` or `false`?

Comment (KaelWD) [reply packages/vuetify/src/mixins/activatable/index.ts]: Oh yeah of course :facepalm:. You got what I meant at least lol

**Review by KaelWD — APPROVED** [review]
