### PR TITLE
fix(VDataTable): expand rows when items are plain array

### LINKED ISSUE #22080: [Bug Report][3.10.2] VDataTable expanded v-model (with return object)
### Environment
**Vuetify Version:** 3.10.2
**Vue Version:** 3.5.21
**OS:** Linux

### Steps to reproduce
1. Click on "expand all" button
2. The "expanded" model contains the items, but no rows are actually expanded in the table
3. Click on the expand button on the first row
4. All rows are now expanded and the model contains [null]
5. Click on the collapse button on the first row
6. All rows are now collapsed and the model is again empty []

### Expected Behavior
When clicking expand all button, all rows should be expanded. When clicking expand none button, all rows should be colapsed. When clicking on individual rows to expand / collapse, only those rows are expanded / collapsed

### Actual Behavior
Expand all / Expand none does nothing, although the expanded model is "correctly" filled-in / emptied.
Clicking on a single row to expand, expands all rows, while the model contains [null].
Clicking on a single expanded row to collapse, collapses all rows and empties the expanded model.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqFVLlu4zAQ/ZUBt7AD6Ii92MarGJti25RpbBe0RMFKKFIgKSWAoH/PkBStAwHSiHO8N48zQ+jUE63y9Llpkq5l5EAyw+qGU8OOZwGQdTFtGmc6J5fC0EowNYZcsKCGxoZeOQtBgMON0YIp/XQmo3Ums2yFKjbnznmmi2tZMH5gnw0VBSsQE8w5TDHTKhHL6xvLzRTWN/kRe3wI3i+KVw2twa9QM1byAyVsB2dyhL631jBAli7G4NjpvFMM3xNF1R37PpQchiy1kdmArkbAv5xX+fu9nWfOUfC/s4Fybqsj7AfWixRsogn0ljzrLVdkI36Di5bQ1bmqGgMaJ+kXXNWNVAZ6HG4JA5RK1rDBR7HxrWJdbWBcJjxZ1PbkZXtTGc4OsHmhNdtE0FHeWldYd4hWoFebnaHcOcIuD38nLfc4Vkq2JHIM02a3rrGbtGaw/Rq2/04rbC/IjcmyFbmppBjzdv7bB+i9SuAkriwyTxdHGr5h4r5/JiJLKthO3YMs/RQ88l5gXSJpWn3bWqS/9ngH/GSp3zNumAwR+Z38SfY7Yo3dY/JIopJyzaLFP8DHLl+BJE/9)

### Other comments
Changing vuetify to version 3.10.0 (or any previous) makes the demo work correctly and as expected.

### PR DESCRIPTION
**Pull request by J-Sek**
- when we add plain objects to the Set, model gets "proxied", so they change and won't match - `has()`, `delete()` do not work
- (prior to [#21128](https://github.com/vuetifyjs/vuetify/pull/21128)) only happened when using `return-object` and plain array of items

fixes #22080
reverts #21128

## Markup:

```vue
<template>
  <v-app theme="dark">
    <v-container>
      <v-data-table
        v-model:expanded="expanded1"
        :headers="headers"
        :items="items1"
        hide-default-footer
        return-object
        show-expand
      >
        <template #expanded-row="data"> {{ data.item }} </template>
      </v-data-table>
      <pre>expanded1: {{ JSON.stringify(expanded1) }}</pre>

      <v-divider />

      <v-data-table
        v-model:expanded="expanded2"
        :headers="headers"
        :items="items2"
        hide-default-footer
        return-object
        show-expand
      >
        <template #expanded-row="data"> {{ data.item }} </template>
      </v-data-table>
      <pre>expanded2: {{ JSON.stringify(expanded2) }}</pre>
    </v-container>
  </v-app>
</template>

<script setup>
  import { ref } from 'vue'
  const headers = [
    { title: 'Title', value: 'title' },
    { title: 'value', value: 'value' },
  ]

  const items1 = [
    { title: 'A', value: 1 },
    { title: 'B', value: 2 },
    { title: 'C', value: 3 },
  ]

  const items2 = ref([
    { title: 'A', value: 1 },
    { title: 'B', value: 2 },
    { title: 'C', value: 3 },
  ])

  const expanded1 = ref([items1[0]])
  const expanded2 = ref([items2.value[2]])
</script>
```

### CODE REVIEW

**Comment by KaelWD** [comment]
Adding this to #21731

#21128 was definitely incorrect, it "fixed" the problem by making return-object do nothing.

File: packages/vuetify/src/components/VDataTable/composables/expand.ts [hunk 1]
```diff
@@ -40,24 +40,23 @@ export function provideExpanded (props: ExpandProps) {
...
-    return isObject(item.value) ? item.key : item.value
-  }
-
   function expand (item: DataTableItem, value: boolean) {
     const newExpanded = new Set(expanded.value)
+    const rawValue = toRaw(item.value)
 
     if (!value) {
-      newExpanded.delete(getItemKey(item))
+      const item = [...expanded.value].find(x => toRaw(x) === rawValue)!
```
Comment (KaelWD) [inline packages/vuetify/src/components/VDataTable/composables/expand.ts:48]: Not a huge fan of this but expanded shouldn't contain too many items so it's probably ok.
