### PR TITLE
No style size on VIcon by default

### LINKED ISSUE #2845: [Bug Report] Default style on v-icon can't be overridden by CSS
### Versions and Environment
**Vuetify:** 1.0.0-alpha.3
**Vue:** 2.5.2
**Browsers:** Chrome 63.0.3239.108
**OS:** Mac OS 10.13.2

### Steps to reproduce
Visit the codesandbox link.

### Expected Behavior
The "home" icon and the "event" icon should both be 48px (set by their CSS classes). If no size property is provided to the VIcon it should not set a default, but rather use the 24px default set by the .icon CSS class. This will allow the font-size to be overridden without using !important.

### Actual Behavior
The "home" icon has a style attribute setting its size to 24px. The "event" attribute has its size attribute overridden by using a !important CSS rule.

### Reproduction Link
[https://codesandbox.io/s/01v6ooxyjl](https://codesandbox.io/s/01v6ooxyjl)

### Other comments
VIcon is adding a style: 24px attribute to icons, overriding any CSS font-size styles on the icon - including the 24px font-size defined in the .icon class.

### PR DESCRIPTION
**Pull request by mattpjohnson**
Fixes #2845

### CODE REVIEW

File: src/components/VIcon/VIcon.js [hunk 1]
```diff
@@ -44,7 +43,10 @@ export default {
       case props.xLarge: fontSize = SIZE_MAP.xLarge
         break
     }
-    data.style = { fontSize, ...data.style }
+
+    if (fontSize !== undefined) {
```
Comment (johnleider) [inline src/components/VIcon/VIcon.js]: I think it's safe to assume `if (fontSize)`

File: src/components/VIcon/VIcon.js [hunk 2]
```diff
@@ -44,7 +43,10 @@ export default {
...
+      data.style = { fontSize, ...data.style }
```
Comment (johnleider) [inline src/components/VIcon/VIcon.js]: change this to data.style.fontSize = fontSize, no reason to use spread operator here

File: src/components/VIcon/VIcon.spec.js [hunk 3]
```diff
@@ -25,10 +25,16 @@ test('VIcon.js', ({ mount, compileToFunctions }) => {
     expect(wrapper.element.classList).toContain('icon--disabled')
   })
 
+  it('should render no size by default', () => {
+    const context = functionalContext({}, 'add')
+    const wrapper = mount(VIcon, context)
+
+    expect(wrapper.element.style.fontSize).toBe('')
```
Comment (johnleider) [inline src/components/VIcon/VIcon.spec.js]: should not set font size if none provided

File: src/components/VIcon/VIcon.js (hunk 2 above)
Comment (mattpjohnson) [reply src/components/VIcon/VIcon.js]: I think the spread operator is being used in case style is not a property of data.

File: src/components/VIcon/VIcon.js (hunk 1 above)
Comment (mattpjohnson) [reply src/components/VIcon/VIcon.js]: I've updated my PR with this change.

File: src/components/VIcon/VIcon.spec.js (hunk 3 above)
Comment (mattpjohnson) [reply src/components/VIcon/VIcon.spec.js]: I've updated the spec name
