### PR TITLE
fix(VBreadcrumbs): use title as key

### LINKED ISSUE #16838: [Bug Report][3.1.7] VBreadcrumbs causes app to break when link is missing
### Environment
**Vuetify Version:** 3.1.7
**Vue Version:** 3.3.0-alpha.4
**Browsers:** Chrome 103.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. From 'Navigation issues' section, click 'Go To Demo'
2. Error!

### Expected Behavior
To display breadcrumb normally without a link

### Actual Behavior
App breaking

### Reproduction Link
[https://stackblitz.com/edit/github-12gw6x?file=pages/demo.vue](https://stackblitz.com/edit/github-12gw6x?file=pages/demo.vue)

### Other comments
I'm using nuxt 3 and came across this issue.
to solve this issue: every breadcrumb item should have link prop

### PR DESCRIPTION
**Pull request by nekosaur**
## Description

index bad

_might_ fix #16838

## Markup:

```vue

```

### CODE REVIEW

File: packages/vuetify/src/components/VBreadcrumbs/VBreadcrumbs.tsx [hunk 1]
```diff
@@ -111,12 +117,12 @@ export const VBreadcrumbs = genericComponent<new <T>() => {
...
+          { items.value.map((item, index, array) => (
             <>
               <VBreadcrumbsItem
-                key={ index }
+                key={ item.title }
                 disabled={ index >= array.length - 1 }
-                { ...(typeof item === 'string' ? { title: item } : item) }
+                { ...item }
                 v-slots={{
                   default: slots.title ? () => slots.title?.({ item, index }) : undefined,
```
Comment (KaelWD) [inline packages/vuetify/src/components/VBreadcrumbs/VBreadcrumbs.tsx:127]: Technically a breaking change, item in the slot could have been a string before but now it's `{ title: string }`

Comment (nekosaur) [reply packages/vuetify/src/components/VBreadcrumbs/VBreadcrumbs.tsx:127]: ;(

**Comment by johnleider** [comment]
Is this something we can do as part of a minor release or does it need to move to a major?

**Review by johnleider — APPROVED** [review]

**Review by johnleider — DISMISSED** [review]
