### PR TITLE
fix(VDataTable): set initial values for sort-desc and group-desc

### LINKED ISSUE #9685: [Bug Report] Data Table Initial Group-By breaks sorting if Group-Desc not specified
### Environment
**Vuetify Version:** 2.1.10
**Vue Version:** 2.6.10
**Browsers:** Chrome 79.0.3945.29
**OS:** Windows 10

### Steps to reproduce
Click *Dessert (100g serving)* header, and (optionally) then the *Calories* header.

### Expected Behavior
- The Group-By order shouldn't change & the *Dessert (100g serving)* items should be sorted descending underneath their *Category* group.
- A subsequent sort on the *Calories* header shouldn't change the order of items, because they should already be sorted on *Dessert (100g serving)*.

### Actual Behavior
- The Group-By order changes instead of the *Dessert (100g serving)* item order.
- The *Calories* sort changes the item order.

### Reproduction Link
<a href="https://codepen.io/benjaminpwarren/pen/NWWOGZp" target="_blank">https://codepen.io/benjaminpwarren/pen/NWWOGZp</a>

### Other comments
I believe this is because there's no default `group-desc` value of `false`, unlike when using `sort-by`. 

If I specify the `:group-desc="false"`, everything works as expected. Also, if I start without a `group-by` but with a `show-group-by` and then apply a group and sorting manually (clicking),  everything also works as expected.

### PR DESCRIPTION
**Pull request by nekosaur**
## Description

supplying sort-by and/or group-by values without corresponding sort-desc/group-by values could lead to issues when sorting/grouping

## Motivation and Context

closes #9685

## How Has This Been Tested?

playground, updated existing test

## Markup:

<details>

```vue
<template>
  <v-container>
    <v-data-table
      :headers="headers"
      :items="desserts"
      item-key="name"
      group-by="category"
      :sort-by="sortBy"
      show-group-by
      multi-sort
    ></v-data-table>
  </v-container>
</template>

<script>
  export default {
    data () {
      return {
        sortBy: ['category', 'name'],
        headers: [
          { text: "Category", value: "category" },
          { text: "Dessert (100g serving)", align: "left", value: "name" },
          { text: "Calories", value: "calories" },
          { text: "Fat (g)", value: "fat" },
          { text: "Carbs (g)", value: "carbs" },
          { text: "Protein (g)", value: "protein" },
          { text: "Iron (%)", value: "iron" }
        ],
        desserts: [
          {
            name: "Frozen Yogurt",
            calories: 159,
            fat: 6.0,
            carbs: 24,
            protein: 4.0,
            iron: "1%",
            category: "Ice cream"
          },
          {
            name: "Ice cream sandwich",
            calories: 237,
            fat: 9.0,
            carbs: 37,
            protein: 4.3,
            iron: "1%",
            category: "Ice cream"
          },
          {
            name: "Eclair",
            calories: 262,
            fat: 16.0,
            carbs: 23,
            protein: 6.0,
            iron: "7%",
            category: "Cookie"
          },
          {
            name: "Cupcake",
            calories: 305,
            fat: 3.7,
            carbs: 67,
            protein: 4.3,
            iron: "8%",
            category: "Pastry"
          },
          {
            name: "Gingerbread",
            calories: 356,
            fat: 16.0,
            carbs: 49,
            protein: 3.9,
            iron: "16%",
            category: "Cookie"
          },
          {
            name: "Jelly bean",
            calories: 375,
            fat: 0.0,
            carbs: 94,
            protein: 0.0,
            iron: "0%",
            category: "Candy"
          },
          {
            name: "Lollipop",
            calories: 392,
            fat: 0.2,
            carbs: 98,
            protein: 0,
            iron: "2%",
            category: "Candy"
          },
          {
            name: "Honeycomb",
            calories: 408,
            fat: 3.2,
            carbs: 87,
            protein: 6.5,
            iron: "45%",
            category: "Toffee"
          },
          {
            name: "Donut",
            calories: 452,
            fat: 25.0,
            carbs: 51,
            protein: 4.9,
            iron: "22%",
            category: "Pastry"
          },
          {
            name: "KitKat",
            calories: 518,
            fat: 26.0,
            carbs: 65,
            protein: 7,
            iron: "6%",
            category: "Candy"
          }
        ]
      };
    }
  }
</script>

```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

File: packages/vuetify/src/util/helpers.ts [hunk 1]
```diff
@@ -447,3 +447,7 @@ export function mergeDeep (
 
   return source
 }
+
+export function fillArray<T> (length: number, obj: T) {
+  return Array(length).fill(obj)
```
Comment (johnleider) [inline packages/vuetify/src/util/helpers.ts:452]: This requires a polyfill as it's not compatible with ie11 by default. Is this something we want to do? If so, we should add an alert to the doc pages. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/fill#Polyfill

Comment (nekosaur) [reply packages/vuetify/src/util/helpers.ts:452]: We already have one other instance of `Array.fill` in the code. And it looks like at least IE 11.836.18362.0 _does_ support it when checking playground.
