### PR TITLE
fix(VSwitch): render in forced-colors mode

### LINKED ISSUE #19702: [Bug Report][3.5.17] Switches disappear when in windows high contrast (forced-colors) mode (Accessibility > Contrast Themes)
### Environment
**Vuetify Version:** 3.5.17
**Vue Version:** 3.4.25
**Browsers:** Edge 124.0.0.0
**OS:** Windows 10

### Steps to reproduce
1) Enable forced-color mode within your operating system (For example, High Contrast Mode in Windows)
2) View the reproduction link

### Expected Behavior
Switches should appear

### Actual Behavior
Switches disappears

image

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrlWc1OwzAMfhXTAwOJsQsnNJC48QYcGIfQphApTaokHUKId8dN99Nubbd265aWw6bFTuN8yWfXnl9/PK38yVMc384T6t17U0OjmBNDH2cCYDofkzi2P+3Al8IQJqhaiKxQyS8IqNDZIyuxLzngRz/MvLuZl9NZrf5ixv+E+0gGlI/nhCcUJxqV0JkHnLxTjkMpcPDJAjoOKNrlGiZ5GxNr5HCrIeG6YDYMu7G7NMAErktVxAQe9KapgrLCcGPTeSGUn3pxyvoKgEsSMPGxNSMTVzyfh5TXHOUga9EsbrMCThg6j6eUJcfdNRRZthtQ94TDBaVCXaxYRNR31QXaaZAGBqf51gxNGm/OBmfPrRbZaB/6P2wbRAxsyknnQbdn7uCjae71HTBN3jkNNqes5H15bzsLpJxox9mu29xa+AtcVqKt96jecbD3gGuTyxPB6p7TO+tK3IGmZrv0QuHJaszO97DPzS/2cPDFpap0JTfjUynK9i/7vYCeJS71DmgNK0+WpDnE3aZ1SWP3dYO6jUsRB3E2wjD4oNuyoB5mZG5baffvNA5wgo4w9yo/WebN5YfQPKt2LzHpH8L6av5YOHqZRq/LwzZeOwQ6D/ck9v1j4DR4D3WP9Ri708v+tdXmG9ipJOtvTye5vjcOta9YbABtJVn7m0WxVAZ+QNEQfiFUMoIRtsxHmSviutpApD/gIZ1xNXqmnEt4kYoHF6Pr1EC2JC7m/d6IhHP79fYHBhKHdA==)

### PR DESCRIPTION
**Pull request by 06b**
## Description

fixes #19702

Before:
image
After (Example when the Night sky contrast theme is selected in windows):
image

Because native switch toggles aren't standardized yet for the web, I did my best to select what the expected system color keywords would be comparing to how the operating system changed the switches in other applications such as Windows Settings when turning on contrast themes.

## Markup:

```vue

```

### CODE REVIEW

**Comment by johnleider** [comment]
Is it possible to adjust the css selectors so that we don't use !important?

**Comment by 06b** [comment]
Yeah, it should be possible - I'll convert this pull request to a draft while refactor it.

**Comment by 06b** [comment]
All !importants have been removed, had to adjust the VSwitch to not apply the bg- classes if detects that forced-colors mode is active.

**Comment by 06b** [comment]
@johnleider I resolved the merge conflicts on Github (which merged the 'master' batch into the pull request), I then saw that on the [vuetify contributing page](https://vuetifyjs.com/en/getting-started/contributing/#choosing-a-base-branch) states "Pull requests that include unrelated commits or your local merges will be CLOSED without notice" so if this pull request is closed, I'll assume I should just do a new pull request based off latest master that way it doesn't have the merge commit included.

File: packages/vuetify/src/components/VSwitch/VSwitch.tsx [hunk 1]
```diff
@@ -79,6 +79,7 @@ export const VSwitch = genericComponent<new <T>(
     const { loaderClasses } = useLoader(props)
     const { isFocused, focus, blur } = useFocus(props)
     const control = ref<VSelectionControl>()
+    const isForcedColorsModeActive = matchMedia('(forced-colors: active)').matches
```
Comment (johnleider) [inline packages/vuetify/src/components/VSwitch/VSwitch.tsx:82]: This should check the global IN_BROWSER constant and also use window.matchMedia instead of just matchMedia.

**Review by johnleider — CHANGES_REQUESTED** [review]

File: packages/vuetify/src/components/VSwitch/VSwitch.tsx (hunk 1 above)
Comment (06b) [reply packages/vuetify/src/components/VSwitch/VSwitch.tsx]: Done

File: packages/vuetify/src/components/VSwitch/VSwitch.tsx [hunk 2]
```diff
@@ -158,7 +159,7 @@ export const VSwitch = genericComponent<new <T>(
                       <div
                         class={[
                           'v-switch__track',
-                          ...backgroundColorClasses.value,
+                          ...(!isForcedColorsModeActive ? backgroundColorClasses.value : ''),
```
Comment (johnleider) [inline packages/vuetify/src/components/VSwitch/VSwitch.tsx:162]:
```suggestion
                          !isForcedColorsModeActive ? backgroundColorClasses.value : undefined,
```

Comment (johnleider) [reply packages/vuetify/src/components/VSwitch/VSwitch.tsx:162]: I'm not sure why backgroundColorClasses is being spread here in the first place. You can adjust the logic as suggested.

**Review by johnleider — CHANGES_REQUESTED** [review]

File: packages/vuetify/src/components/VSwitch/VSwitch.tsx (hunk 2 above)
Comment (06b) [reply packages/vuetify/src/components/VSwitch/VSwitch.tsx]: Done

**Review by johnleider — APPROVED** [review]
