### PR TITLE
fix(VExpansionPanel): fix lazy animation

### LINKED ISSUE #6190: [Bug Report] Lazy ExpansionPanel not animating
### Versions and Environment
**Vuetify:** 1.4.2
**Last working version:** 1.3.7
**Vue:** 2.5.22
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 10

### Steps to reproduce
Create a ExpansionPainel with lazy ExpansionPainelContents.

### Expected Behavior
The opening animation to work initially, even with lazy content.
This used to work with v1.3.7, like in this [codepen](https://codepen.io/oliveiracdz/pen/pqmQYq) .

### Actual Behavior
The opening animation do not work.

### Reproduction Link
<a href="https://codepen.io/oliveiracdz/pen/OrYaKQ" target="_blank">https://codepen.io/oliveiracdz/pen/OrYaKQ</a>

### PR DESCRIPTION
**Pull request by sh7dm**
## Description

Fix lazy animation

## Motivation and Context

Fixes #6190 

## How Has This Been Tested?

Markup

## Markup:

<details>

```vue
<template>
  <v-app class="panes">
    <v-expansion-panel>
      <v-expansion-panel-content
        v-for="(item,i) in 5"
        :key="i"
        lazy
      >
        <div slot="header">Item</div>
        <v-card>
          <v-card-text>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</v-card-text>
        </v-card>
      </v-expansion-panel-content>
    </v-expansion-panel>
  </v-app>
</template>

<script>
  export default {
    data: () => ({})
  }
</script>
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

File: packages/vuetify/src/components/VExpansionPanel/VExpansionPanelContent.ts [hunk 1]
```diff
@@ -135,7 +135,7 @@ export default mixins<options &
       ])
     },
     toggle (active: boolean) {
```
Comment (KaelWD) [inline packages/vuetify/src/components/VExpansionPanel/VExpansionPanelContent.ts]: This type is wrong then?
