### PR TITLE
fix(VIcon): set svg dimensions in style instead of attributes

### LINKED ISSUE #12372: [Bug Report] @mdi/js icons size prop overwritten by .v-icon__svg class
### Environment
**Vuetify Version:** 2.3.13
**Vue Version:** 2.6.12
**Browsers:** Chrome 85.0.4183.121
**OS:** Mac OS 10.15.6

### Steps to reproduce
I cant reproduce, could not install @mdi/js in codepen/jsfiddle etc.
reproduce:
Follow official guide to install @mdi/js https://vuetifyjs.com/en/features/icons/#material-design-icons---js-svg
Add icont to project:
  <v-icon size="200px" left>{{ mdiPaw }}</v-icon>
Icon won't be resized and you can see .v-icon__svg is overwritting size behavior.

### Expected Behavior
Expected size to be increased

### Actual Behavior
Nothing happens, only span around is increasing its size

### Reproduction Link
<a href="https://codepen.io/albertb/pen/PozoQJj" target="_blank">https://codepen.io/albertb/pen/PozoQJj</a>

### PR DESCRIPTION
**Pull request by KaelWD**
Fixes regression from #12148 preventing size props from working

fixes #12372

## Markup:

<details>

```vue
<template>
  <v-container>
    <v-btn color="primary" icon>
      <v-icon large>{{ mdiAccountCircle }}</v-icon>
    </v-btn>

    <v-btn color="primary" icon>
      <v-icon>{{ mdiAccountCircle }}</v-icon>
    </v-btn>
  </v-container>
</template>

<script>
  import { mdiAccountCircle } from '@mdi/js'

  export default {
    data: () => ({
      mdiAccountCircle,
    }),
  }
</script>
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

### CODE REVIEW

**Comment by icleolion** [comment]
Yeah I had a shock after I updated and all the icons were huge!  Glad I saw this PR. I was about to start adjusting the size of them all again as I thought it was just a necessary consequence of the fix.

File: .gitattributes [hunk 1]
```diff
@@ -1 +1 @@
-* text=auto
+* text=auto eol=lf
```
Comment (johnleider) [inline .gitattributes:1]: This apparently was fixed:

- <https://github.com/git/git/blob/master/Documentation/RelNotes/2.10.0.txt#L248>
- <https://stackoverflow.com/questions/29435156/what-will-text-auto-eol-lf-in-gitattributes-do>

File: packages/vuetify/src/components/VIcon/VIcon.ts [hunk 2]
```diff
@@ -153,19 +153,25 @@ const VIcon = mixins(
...
           xmlns: 'http://www.w3.org/2000/svg',
           viewBox: '0 0 24 24',
-          height: fontSize || '24',
-          width: fontSize || '24',
           role: 'img',
           'aria-hidden': true,
         },
       }
 
+      const size = this.getSize()
```
Comment (johnleider) [inline packages/vuetify/src/components/VIcon/VIcon.ts:166]:
```suggestion
      const size = this.getSize()

```

**Review by johnleider — CHANGES_REQUESTED** [review]

File: .gitattributes (hunk 1 above)
Comment (KaelWD) [reply .gitattributes]: > The
> combination has been fixed to be equivalent to doing
> $ git config core.autocrlf true

Yeah that's what we want (except with `input` instead). The release notes are saying that `text=auto eol=lf` previously behaved like `text eol=lf` which marks every file as text instead of detecting text or binary.

Comment (KaelWD) [reply .gitattributes]: This commit was also supposed to be to master because I am the dumb

File: packages/vuetify/src/components/VIcon/VIcon.ts (hunk 2 above)
Comment (KaelWD) [reply packages/vuetify/src/components/VIcon/VIcon.ts:166]: Why? That's how it is everywhere else and in the original code.
