### PR TITLE
fix(VTextField): legend position not aligned with reverse prop

### LINKED ISSUE #10798: [Bug Report] VTextField Border is not aligned correctly with outlined and reverse prop in browser mozilla firefox
### Environment
**Vuetify Version:** 2.2.15
**Vue Version:** 2.6.10
**Browsers:** Mozilla Firefox
**OS:** Windows

### Steps to reproduce
create vtextfield with prop outlined and reverse. Aligned only correctly in chrome browser but in other browser ex. mozilla firefox legend not aligned correctly. like in the screenshot that I attached in comment.

### Expected Behavior
label and legend should be in right position in mozilla firefox

### Actual Behavior
only label in right position and legend still in left in mozilla firefox

### Reproduction Link
<a href="https://codepen.io/neko-chan/pen/xxGpYPm" target="_blank">https://codepen.io/neko-chan/pen/xxGpYPm</a>

### PR DESCRIPTION
**Pull request by dchinu97**
## Description
Legend position was not aligned with the reverse prop that reverses the label position. So when the value of the reverse prop is true the legend should move right
fixes #10798

## Motivation and Context
Done to Fix #10798

## How Has This Been Tested?
Visually via playground on Chrome, Edge, IE and Morzilla

## Markup:

<details>

```vue
<template>
  <v-container>
    <v-text-field label="Label" outlined reverse></v-text-field>
    <v-text-field label="Label" outlined></v-text-field>
  </v-container>
</template>

<script>
  export default {
    data: () => {
      return {}
    },
  }
</script>
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by KaelWD** [comment]
Turns out this was already fixed in #10278, the issue you commented on was missing `<v-app>`. Thanks anyway.

File: packages/vuetify/src/components/VTextField/VTextField.ts [hunk 1]
```diff
@@ -371,6 +371,9 @@ export default baseMixins.extend<options>().extend({
         style: {
           width: !this.isSingle ? convertToUnit(width) : undefined,
         },
+        attrs: {
+          align: this.reverse ? 'right' : 'left',
```
Comment (KaelWD) [inline packages/vuetify/src/components/VTextField/VTextField.ts:375]: I would've asked you to redo with CSS anyway, this attribute is deprecated.

Comment (KaelWD) [reply packages/vuetify/src/components/VTextField/VTextField.ts:375]: Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1488228

Looks like using margin instead of text-align works in firefox.

Comment (dchinu97) [reply packages/vuetify/src/components/VTextField/VTextField.ts:375]: Thanks @KaelWD , Will verify the same and update the PR

Comment (dchinu97) [reply packages/vuetify/src/components/VTextField/VTextField.ts:375]: @KaelWD As mentioned in the Mozilla patch here [https://bugzilla.mozilla.org/attachment.cgi?id=9006391&action=edit](url)

image


These changes seems to fix it.

File: packages/vuetify/src/components/VTextField/VTextField.sass [hunk 2]
```diff
@@ -433,10 +433,12 @@
 
     &.v-text-field--reverse legend
       +ltr()
-        text-align: right
+        margin-inline-start: auto
```
Comment (jacekkarczmarczyk) [inline packages/vuetify/src/components/VTextField/VTextField.sass:436]: IE doesn't support this property

Comment (dchinu97) [reply packages/vuetify/src/components/VTextField/VTextField.sass]: Thanks @jacekkarczmarczyk. Didn't knew about that, Update and tested on Chrome, Edge, IE and Firefox

**Review by KaelWD — APPROVED** [review]
