### PR TITLE
Stick to naming convetions v-header__icon

### LINKED ISSUE #4629: [Bug Report] Expansion Panel - Header Icon still "header__icon" not "v-header__icon"
### Versions and Environment
**Vuetify:** 1.1.4
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Mac OS 10.13.5

### Steps to reproduce
Look at markup. 

### Expected Behavior
I was expecting it to be v-header__icon as per the migration guide, but it was not. Not a terribly big deal but I figure you'll want to be consistent with it? 

### Actual Behavior
It is stil header__icon. 

### Reproduction Link
[https://codepen.io/anon/pen/xJVQQO?&editors=100](https://codepen.io/anon/pen/xJVQQO?&editors=100)

### PR DESCRIPTION
**Pull request by ebisbe**
## Motivation and Context

Fixes #4629 

## How Has This Been Tested?

unit
## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have created a PR in the [documentation](https://github.com/vuetifyjs/vuetifyjs.com) with the necessary changes.

### CODE REVIEW

File: src/components/VExpansionPanel/VExpansionPanelContent.ts [hunk 1]
```diff
@@ -126,7 +126,7 @@ export default mixins<options &
         attrs: { name: 'fade-transition' }
       }, [
         this.$createElement('div', {
-          staticClass: 'header__icon',
+          staticClass: 'v-header__icon',
```
Comment (KaelWD) [inline src/components/VExpansionPanel/VExpansionPanelContent.ts]: This should actually be `v-expansion-panel__header__icon`
