### PR TITLE
fix(VColorPicker): incorrect layout in RTL mode

### LINKED ISSUE #10655: [Bug Report] Color picker's sliders have wrong direction in RTL mode
### Environment
**Vuetify Version:** 2.2.14
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.116
**OS:** Windows 10

### Steps to reproduce
reverse slider's gradient color in RTL mode

### Expected Behavior
select correct color and transparency from sliders in RTL mode.

### Actual Behavior
The color and transparency slider must select the correct color like LTR mode.

### Reproduction Link
<a href="https://codepen.io/seyed_me/pen/MWwJgvm?editable=true&editors=101" target="_blank">https://codepen.io/seyed_me/pen/MWwJgvm?editable=true&editors=101</a>

### PR DESCRIPTION
**Pull request by jacekkarczmarczyk**
## Motivation and Context
fixes #10655

## How Has This Been Tested?
playground

## Markup:

<details>

```vue
<template>
  <v-container>
    <v-btn
      block
      @click="$vuetify.rtl = !$vuetify.rtl"
    >RTL {{ $vuetify.rtl }}</v-btn>
    <v-color-picker />
  </v-container>
</template>

<script>
  export default {
    created () {
      this.$vuetify.rtl = true
    },
  }
</script>
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by nekosaur** [comment]
You need to switch the gradient direction as well

File: packages/vuetify/src/components/VColorPicker/VColorPickerPreview.ts [hunk 1]
```diff
@@ -33,9 +33,9 @@ export default Vue.extend({
           max: 1,
         },
         style: {
-          backgroundImage: !this.disabled
-            ? `linear-gradient(to right, transparent, ${RGBtoCSS(this.color.rgba)})`
-            : undefined,
+          backgroundImage: this.disabled
+            ? undefined
+            : `linear-gradient(to ${this.$vuetify.rtl ? 'left' : 'right'}, transparent, ${RGBtoCSS(this.color.rgba)})`,
```
Comment (nekosaur) [inline packages/vuetify/src/components/VColorPicker/VColorPickerPreview.ts]: maybe pull this out into a computed prop `gradient`?

Comment (jacekkarczmarczyk) [reply packages/vuetify/src/components/VColorPicker/VColorPickerPreview.ts]: I was thinking about it but seemed to me as unnecessary premature optimization
