### PR TITLE
fix(VSparkline): accept numeric value for smooth

### LINKED ISSUE #19262: [Bug Report][3.5.5] VSparkline has incorrect types for properties "smooth" and "labels"
### Environment
**Vuetify Version:** 3.5.5
**Vue Version:** 3.4.14
**Browsers:** Chrome 121.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Open link, see warnings for values that have types which should be supported per docs and expected  behaviour.

### Expected Behavior
* Smooth property does not give warning if given value is of type `number`
* Labels property does not give warning if given value is of type `string[]`

### Actual Behavior
* Type warnings thrown for supported types on properties smooth and labels

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9UctugzAQ/JWtL7RSeJQAoYhU6q1/0EPIgYJpUQ22bIMqRfn3rjEVKIo47ezMeD1rny5Eycp/E8IbB0oykmvaCVZq+lr0APnolkJMcGoq3uuy7amcqYnU9Fe7TUtZDaPb8ZqyY0E69VUQ8Nc+JUr5w/A0ZJPLHUs2UPROVaE9Y+UnZQopCwylOs71N1LRal7u32YxjI2a+6sVsFWVbIUGRfVgN2k7waWGC0jawBUayTtwcHvH2AFwrtKA+eFoHI/OO2WMwweXrH5wnhaLjY2ukw2VBjs4xDtIsMamzjgJsU9vOOz/ecMdDGeqxWbgebnJvsZykxOGWRA4kw07uIO21XBTjTbVZFNNt9VsPwfD7XLffg1+CrnuyN6LvOcXYkDsxeT8B4vsskM=)

### Other comments
* Smooth
  * [Docs description mentions numbers are supported for property smooth.](https://vuetifyjs.com/en/api/v-sparkline/#props-smooth)
  * [VSpark class has types Boolean, Number and String set for property smooth](https://github.com/vuetifyjs/vuetify/blob/1ef07bd87469c970e075a3627f1035d65da7a3a3/packages/vuetify/src/components/VSparkline/VSparkline.ts#L114)
* Labels
  * [Docs description mentions type is a list of string actual type is list of SparklineItems](https://vuetifyjs.com/en/api/v-sparkline/#props-labels)
  * [VSpark class has incorrect type of list of SparklineItem](https://github.com/vuetifyjs/vuetify/blob/1ef07bd87469c970e075a3627f1035d65da7a3a3/packages/vuetify/src/components/VSparkline/VSparkline.ts#L97-L100)

### PR DESCRIPTION
**Pull request by J-Sek**
## Description

fixes #19262

## Markup:

```vue
<template>
  <v-app>
    <v-container>
      <v-sparkline :model-value="values" :smooth="4" />
      <v-sparkline :model-value="values" smooth />
      <v-sparkline :model-value="values" smooth="1" />
      <v-sparkline :model-value="values" :smooth="1" />
    </v-container>
  </v-app>
</template>

<script setup>
  const values = [80, 75, 60, 55, 65, 60, 62, 58, 55, 65, 60, 68, 62, 58, 65, 70, 65, 75, 70]
</script>
```

### CODE REVIEW

File: packages/vuetify/src/components/VSparkline/util/line.ts [hunk 1]
```diff
@@ -55,7 +55,7 @@ export const makeLineProps = propsFactory({
     default: 8,
   },
   showLabels: Boolean,
-  smooth: Boolean,
+  smooth: [Boolean, Number],
```
Comment (johnleider) [inline packages/vuetify/src/components/VSparkline/util/line.ts:58]: If we support number we'll need to support string as well.

```html
<v-sparkline smooth />
<v-sparkline smooth="5" />
<v-sparkline :smooth="5" />
```

**Review by KaelWD — APPROVED** [review]
