### PR TITLE
fix(VAutocomplete): cleared input searchterm on blur 

### LINKED ISSUE #20993: [Bug Report][3.7.12] Perfectly matching autocomplete search retained on blur
https://github.com/user-attachments/assets/81c970d1-36a0-4cc6-b11e-1bf39c2c9805

### Environment
**Vuetify Version:** 3.7.12
**Vue Version:** 3.5.13
**Browsers:** Firefox 135.0, Google Chrome, Microsoft Edge
**OS:** Windows 10

### Steps to reproduce
1. Search for a number e. g. 21.
2. Select in the dropdown the value 21.
3. Click out of the autocomplete

### Expected Behavior
The value 21 is removed as searchterm

### Actual Behavior
The value 21 (searchterm) is still visible in the autocomplete after clicking out

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVTzEOgzAM/ErkJQuFQtqhKEXiHcCQIg9IIUSQsFT9e1O3UcNyts9n+9w9YVvHorU23z1CDdLhbLVy2PSGMbmflLWUUjEuxqnJ4PqjvgrvlnEJU+gw0oxp9UB976FNu/Dv11O4tAVBx6uSZ4xXFaEgvBDe1CeIMx/SydlrN4V9kWlkcTQR/Qb6aJiE9I8skj/hlYHIr3kpIDNe6+ENLf9R7Q==)

### Other comments
If the searched value contains a letter it works

### PR DESCRIPTION
**Pull request by Arslan038**
## Description

Cleared autocomplete input on blur. Perfectly matching autocomplete search retained on blur.

Search for a number e. g. 21.
Select in the dropdown the value 21.
Click out of the autocomplete

The value 21 (searchterm) is still visible in the autocomplete after clicking out.

Now it is fixed and The value 21 is removed as searchterm.

fixes #20993 

## Markup:

```vue
<template>
  <v-app>
    <v-container>
      <v-autocomplete
        v-model="value"
        label="Autocomplete"
        :items="['21', '22', '23', '24', '29a', '30']"
        multiple
      ></v-autocomplete>
    </v-container>
  </v-app>
</template>

<script>
  import { ref } from 'vue'
  import { VAutocomplete } from '@/components'
  export default {
    setup() {
      const value = ref(null)
      return {
        value,
      }
    },
  }
</script>

```

### CODE REVIEW

**Review by johnleider — CHANGES_REQUESTED** [review]
Looks good, could you add a spec test for this?

**Review by johnleider — DISMISSED** [review]

File: packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx [hunk 1]
```diff
@@ -386,7 +386,7 @@ export const VAutocomplete = genericComponent<new <
       } else {
         if (!props.multiple && search.value == null) model.value = []
         menu.value = false
-        if (!model.value.some(({ title }) => title === search.value)) search.value = ''
+        if (props.multiple || hasSelectionSlot.value) search.value = ''
```
Comment (habibalkhabbaz) [inline packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx:389]: Looks like this change broke the search functionality. When I type anything it gets cleared immediately.

Minimal reproduction:

```
<v-autocomplete
    v-model="customer"
    v-model:search="searchCustomer"
    :items="customers"
    variant="outlined"
>
</v-autocomplete>
```

Comment (Smrtnyk) [reply packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx:389]: I have same issue and had to downgrade back to previous version

Comment (J-Sek) [reply packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx:389]: #21392 - already fixed. Will be released in v3.8.5. You can downgrade to v3.8.3 or use `patch-package` to fix current version on the fly.

Comment (habibalkhabbaz) [reply packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx:389]: Thanks @J-Sek
