### PR TITLE
fix(VDataIterator): use itemKey instead of name for select

### LINKED ISSUE #13677: [Bug Report][2.5.0] V-DataTable:  shift key logic for multiple selection doesn't work if data table has no "name" field
### Environment
**Vuetify Version:** 2.5.0
**Vue Version:** 2.6.11
**Browsers:** Firefox 88.0
**OS:** Ubuntu undefined

### Steps to reproduce
1. Click on second row
2. Press shift and click on las raw

### Expected Behavior
All 3 las rows should be selected

### Actual Behavior
First, second and last rows are selected

### Reproduction Link
<a href="https://codepen.io/florealcab/pen/abJBJWm" target="_blank">https://codepen.io/florealcab/pen/abJBJWm</a>

### Other comments
Instead of the "name" field, we should use the item-key field, which is by definition unique to each row and must exist in table data.

I have fixed that on my fork for test, I will send a PR

### PR DESCRIPTION
**Pull request by florealcab**
## Description

fixes #13677

## Motivation and Context

https://github.com/vuetifyjs/vuetify/issues/13677

## How Has This Been Tested?

There was no test for this feature (or I missed them), so I don't add unit tests. I test with my real example and it fixes the problem.

## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
<template>
   <v-app>
    <v-container>
      <v-data-table
              :headers="table_headers"
              :items="table_data"
              item-key="id"
              show-select
      ></v-data-table>
    </v-container>
  </v-app>
</template>
<script>
    module.exports = {
        data: function() {
            return {
                table_data: [
                    {
                        "id": 1,
                        "column1": "Toto",
                        "column2": "Tutu"
                    },
                    {
                        "id": 2,
                        "column1": "Toto",
                        "column2": "Tutu"
                    },
                    {
                        "id": 3,
                        "column1": "Toto",
                        "column2": "Tutu"
                    },
                    {
                        "id": 4,
                        "column1": "Toto",
                        "column2": "Tutu"
                    }
                ],
                table_headers: [
                        {align: "left", text: "Column 1", value: "column1"},
                        {align: "left", text: "Column 2", value: "column2"}
                ]
            }
        }
    }
</script>
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

File: packages/vuetify/src/components/VDataIterator/VDataIterator.ts [hunk 1]
```diff
@@ -199,7 +199,7 @@ export default mixins(
       if (value) selection[key] = item
       else delete selection[key]
 
-      const index = this.selectableItems.findIndex(x => x.name === item.name)
+      const index = this.selectableItems.findIndex(x => x[this.itemKey] === item[this.itemKey])
```
Comment (KaelWD) [inline packages/vuetify/src/components/VDataIterator/VDataIterator.ts:202]: Use `getObjectValueByPath`

Comment (florealcab) [reply packages/vuetify/src/components/VDataIterator/VDataIterator.ts]: Of course, now it's okay for that

**Review by KaelWD — APPROVED** [review]

**Review by nekosaur — APPROVED** [review]
