### PR TITLE
fix(VSelects): no closable chips when `readonly` or `disabled`

### LINKED ISSUE #22349: [Bug Report][3.10.11] closable-chips does not respect `readonly`
### Environment
**Vuetify Version:** 3.10.11
**Vue Version:** 3.5.24
**OS:** Windows 10 (current)

### Steps to reproduce
1. Have a v-autocomplete, v-select, or v-combobox with `multiple`, `chips`, and `closable-chips`.
2. Make the input readonly, either via a wrapping v-form or direct prop on the input.
3. Click the close button on the chips

### Expected Behavior
Close button on closable-chips should not deselect items on inputs or in forms that are readonly. This works correctly for disabled inputs, but not for readonly.

### Actual Behavior
Close button on chips deselects items

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrNVMtugzAQ/BXXF7dSgKBWPaQkUm/9gvaQcDBmaZAMtmwTtYry711wCI826jUXw86OhxmL9fZIrRHRq9bhoQG6oomDSkvuYLOrCUkOAde6e+0KoWrHyxrMGUJwH28OQaFMtTXAc1XL75TgrsYpoVAJHCQRci58TyY9+dLwHxttGxoEBSuVg1zvaPd857KBHR0zViUat2OkaqQrUWmMiX2pJyQhleWZhGDWiQbDkXeMwDTz2OuQfR7270T/5Zmn+Z1l5vdajt5Xj7S5pjHQXKYy9XU9Qs+4SfsWJAh33bzv34j1/n+ajlGL+ClLotH0YWmFKbUjFlzjh7CstDKOHFG9ICdSGFURhoPL/LGgrnWksp9k3TLu2RtIqciHMjK/Yw8DpQuJpC3jbEFY1i6iXXKWvoyULkd0FjzzBUtRLIm8P3RGTwv6GD6Hy4BLvefhE23reBnGMV0UXFpYTO4Zj6U/m3VY7g==)

### PR DESCRIPTION
**Pull request by Haviles04**
## Description
fixes #22349 

## Markup:

```vue
<template>
  <v-app>
    <v-container>
      <h1>v-form[readonly] v-autocomplete</h1>
      <v-form readonly>
        <v-autocomplete
          v-model="modelValue"
          :items
          chips
          closable-chips
          multiple
        />
        <v-combobox
          v-model="modelValue"
          :items
          chips
          closable-chips
          multiple
        />
        <v-select
          v-model="modelValue"
          :items
          chips
          closable-chips
          multiple
        />
      </v-form>

      <h1>v-autocomplete[readonly]</h1>
      <v-autocomplete
        v-model="modelValue"
        :items
        chips
        closable-chips
        multiple
        readonly
      />

      <h1>v-combobox[readonly]</h1>
      <v-combobox
        v-model="modelValue"
        :items
        chips
        closable-chips
        multiple
        readonly
      />

      <h1>v-select[readonly]</h1>

      <v-select
        v-model="modelValue"
        :items
        chips
        closable-chips
        multiple
        readonly
      />
    </v-container>
  </v-app>
</template>

<script setup>
  import { ref } from 'vue'

  const items = ['a', 'b', 'c', 'd']
  const modelValue = ref(['a', 'c'])
</script>


```

### CODE REVIEW

**Review by J-Sek — APPROVED** [review]
Works, very clean

**Comment by J-Sek** [comment]
What about `disabled`?

**Comment by Haviles04** [comment]
> What about `disabled`?

Disabled already works and prevents it from closing, just looks different

**Comment by J-Sek** [comment]
`disabled` still shows `x` icons that can be focused with [tab] and used with space and enter. Including `disabled` in the new code, next to `readonly` feels like a quick win.

**Comment by Haviles04** [comment]
> `disabled` still shows `x` icons that can be focused with [tab] and used with space and enter. Including `disabled` in the new code, next to `readonly` feels like a quick win.

Nice catch! updated

**Review by J-Sek — APPROVED** [review]

File: packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx [hunk 1]
```diff
@@ -598,6 +598,8 @@ export const VAutocomplete = genericComponent<new <
                     )
                     : undefined
 
+                  const allowsChanges = toRef(() => !props.readonly && !props.disabled && !form.isReadonly.value && !form.isDisabled.value)
+                  const closableChips = toRef(() => props.closableChips && allowsChanges.value)
```
Comment (KaelWD) [inline packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx]: Move these outside the render function

Comment (KaelWD) [reply packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx]: props.readonly && form.isReadonly.value is redundant, form already checks props first
